import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { requireModuleEntitlement, requireWritableTenantRole } from "@/modules/platform/module-access";

const scope=z.object({tenantId:z.string().uuid(),tenantProductId:z.string().uuid()});
async function creativeScope(context:any,data:z.infer<typeof scope>,write=false){const access=await requireModuleEntitlement(context,{...data,moduleKey:"creative.core"});if(write)requireWritableTenantRole(access.role);return access;}

export const listCreativeWorkspace=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{
 await creativeScope(context,data);const db=context.supabase as any;
 const[kits,briefs,assets]=await Promise.all([
  db.from("creative_brand_kits").select("*").eq("tenant_id",data.tenantId).eq("tenant_product_id",data.tenantProductId).order("updated_at",{ascending:false}),
  db.from("creative_briefs").select("*").eq("tenant_id",data.tenantId).eq("tenant_product_id",data.tenantProductId).order("updated_at",{ascending:false}),
  db.from("creative_assets").select("*").eq("tenant_id",data.tenantId).order("updated_at",{ascending:false}).limit(1000),
 ]);
 if(kits.error)throw new Error(kits.error.message);if(briefs.error)throw new Error(briefs.error.message);if(assets.error)throw new Error(assets.error.message);
 return{brandKits:kits.data??[],briefs:briefs.data??[],assets:assets.data??[]};
});

const kitSchema=scope.extend({id:z.string().uuid().optional(),brandKey:z.string().min(1).max(120).default("default"),name:z.string().min(1).max(200),regionKey:z.string().max(16).optional().nullable(),locale:z.string().max(20).optional().nullable(),logos:z.array(z.string().url()).max(20).default([]),colours:z.array(z.string().max(40)).max(30).default([]),fonts:z.array(z.string().max(120)).max(30).default([]),tone:z.array(z.string().max(200)).max(30).default([]),bannedTerms:z.array(z.string().max(200)).max(100).default([]),requiredDisclaimers:z.array(z.string().max(1000)).max(50).default([]),assetRefs:z.array(z.string().max(1000)).max(200).default([])});
export const saveCreativeBrandKit=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof kitSchema>)=>kitSchema.parse(input)).handler(async({context,data})=>{await creativeScope(context,data,true);const db=context.supabase as any;const values={tenant_id:data.tenantId,tenant_product_id:data.tenantProductId,brand_key:data.brandKey,name:data.name,region_key:data.regionKey??null,locale:data.locale??null,logos:data.logos,colours:data.colours,fonts:data.fonts,tone:data.tone,banned_terms:data.bannedTerms,required_disclaimers:data.requiredDisclaimers,asset_refs:data.assetRefs,revision:1};const q=data.id?db.from("creative_brand_kits").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("creative_brand_kits").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Brand kit could not be saved");return row;});

const briefSchema=scope.extend({brandKitId:z.string().uuid().optional().nullable(),campaignRef:z.string().max(200).optional().nullable(),objective:z.string().min(3).max(1000),audience:z.string().min(2).max(1000),channels:z.array(z.enum(["web","social","email","whatsapp","sms","print","video","audio","app"])).min(1),assetTypes:z.array(z.string().max(120)).min(1).max(50),message:z.string().min(1).max(5000),offer:z.string().max(2000).optional().nullable(),callToAction:z.string().max(500).optional().nullable(),dueAt:z.string().datetime().optional().nullable()});
export const createCreativeBrief=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof briefSchema>)=>briefSchema.parse(input)).handler(async({context,data})=>{await creativeScope(context,data,true);const db=context.supabase as any;const{data:row,error}=await db.from("creative_briefs").insert({tenant_id:data.tenantId,tenant_product_id:data.tenantProductId,brand_kit_id:data.brandKitId??null,campaign_ref:data.campaignRef??null,objective:data.objective,audience:data.audience,channels:data.channels,asset_types:data.assetTypes,message:data.message,offer:data.offer??null,call_to_action:data.callToAction??null,due_at:data.dueAt??null,status:"ready"}).select("*").single();if(error||!row)throw new Error(error?.message??"Creative brief could not be created");return row;});

const assetSchema=scope.extend({briefId:z.string().uuid(),type:z.enum(["copy","image","video","audio","document","web_asset"]),locale:z.string().max(20),channel:z.string().max(80),uri:z.string().url().max(2000),variantKey:z.string().max(120).optional().nullable(),modelRunId:z.string().max(200).optional().nullable(),sourceAssetRefs:z.array(z.string().max(1000)).max(100).default([]),status:z.enum(["draft","review","approved","rejected","published"]).default("review")});
export const registerCreativeAsset=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof assetSchema>)=>assetSchema.parse(input)).handler(async({context,data})=>{await creativeScope(context,data,true);const db=context.supabase as any;const{data:row,error}=await db.from("creative_assets").insert({tenant_id:data.tenantId,brief_id:data.briefId,asset_type:data.type,locale:data.locale,channel:data.channel,uri:data.uri,variant_key:data.variantKey??null,model_run_id:data.modelRunId??null,source_asset_refs:data.sourceAssetRefs,status:data.status,revision:1}).select("*").single();if(error||!row)throw new Error(error?.message??"Creative asset could not be registered");return row;});