import { JSDOM } from "jsdom";
import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import assert from "node:assert/strict";
import * as esbuild from "esbuild";

await esbuild.build({entryPoints:["../../omniqora-update/src/modules/transformation/TransformationWorkspace.tsx"],outfile:"component.mjs",bundle:true,platform:"node",format:"esm",packages:"external",loader:{".css":"empty"},jsx:"automatic"});
await esbuild.build({entryPoints:["../../omniqora-update/src/modules/transformation/transformation.server.ts"],outfile:"server-client.mjs",bundle:true,platform:"node",format:"esm"});
const server=spawn("python3",["backend.py"],{stdio:["ignore","pipe","pipe"]});
let stderr="";server.stderr.on("data",c=>stderr+=c);
try {
 await new Promise((resolve,reject)=>{server.stdout.on("data",c=>{if(String(c).includes("backend on"))resolve();});server.on("exit",code=>reject(Error(`Backend exit ${code}: ${stderr}`)));setTimeout(()=>reject(Error("Backend start timeout")),10000).unref();});
 const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost'});
 globalThis.window=dom.window;globalThis.document=dom.window.document;
 Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
 globalThis.HTMLElement=dom.window.HTMLElement;globalThis.MutationObserver=dom.window.MutationObserver;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
 const React=await import('react');
 const {render,screen,fireEvent,waitFor,cleanup}=await import('@testing-library/react');
 const {TransformationWorkspace}=await import('./component.mjs');
 const {callTransformation}=await import('./server-client.mjs');
 process.env.TRANSFORMATION_URL='http://127.0.0.1:8093';
 process.env.TRANSFORMATION_SIGNING_KEY='fictional-local-verification-only-key-123456';
 const api=(command,projectId,data={})=>callTransformation({tenant:'demo-tenant',user:'demo-owner',tenant_role:'owner'},{command,project_id:projectId,data});
 render(React.createElement(TransformationWorkspace,{api}));
 const name=await screen.findByRole('option',{name:'Northstar acquisition · fictional'});
 const project=name.value;
 fireEvent.change(screen.getByLabelText('Project',{exact:true}),{target:{value:project}});
 await screen.findByText('Readiness checks',{exact:true});
 fireEvent.click(screen.getByRole('button',{name:'Workstreams',exact:true}));
 await screen.findByText('Enterprise systems and processes',{exact:true});
 assert.equal(screen.getAllByText('blocked',{exact:true}).length,6);
 fireEvent.click(screen.getByRole('button',{name:'Evidence',exact:true}));
 fireEvent.change(screen.getByLabelText('Evidence question'),{target:{value:'What does Payroll depend on?'}});
 fireEvent.click(screen.getByRole('button',{name:'Find evidence',exact:true}));
 await screen.findByText('evidence only',{exact:true});
 assert.ok(screen.getByText(/Fictional separation architecture/));
 fireEvent.click(screen.getByRole('button',{name:'Financial',exact:true}));
 fireEvent.click(screen.getByRole('button',{name:'Calculate scenario',exact:true}));
 await screen.findByRole('columnheader',{name:'npv',exact:true});
 fireEvent.click(screen.getByRole('button',{name:'Product',exact:true}));
 await screen.findByText('426.67',{exact:true});
 assert.ok(screen.getByText('No passed UAT evidence',{exact:false}));
 fireEvent.click(screen.getByRole('button',{name:'Company planning',exact:true}));
 await screen.findByText('Company discovery to Day 1',{exact:true});
 fireEvent.click(screen.getByRole('button',{name:'Generate phased plan',exact:true}));
 await screen.findByText('Phased delivery roadmap',{exact:true});
 assert.ok(screen.getByText('GBP 154,000',{exact:true}));
 assert.ok(screen.getByText('Resolve the planning gaps',{exact:true}));
 assert.ok(screen.getByRole('button',{name:'Record independent review',exact:true}).disabled);
 fireEvent.click(screen.getByRole('button',{name:'Day 1 continuity',exact:true}));
 assert.equal(document.querySelectorAll('.oqt-plan-action').length,26);
 fireEvent.click(screen.getByRole('button',{name:/1\. Companies/}));
 assert.equal(screen.getByLabelText('Record type',{exact:true}).value,'company');
 fireEvent.change(screen.getByLabelText('Record type',{exact:true}),{target:{value:'system'}});
 fireEvent.change(screen.getByLabelText('id',{exact:true}),{target:{value:'qa-inventory-system'}});
 fireEvent.change(screen.getByLabelText('name',{exact:true}),{target:{value:'QA inventory system'}});
 fireEvent.change(screen.getByLabelText('owner',{exact:true}),{target:{value:'QA owner'}});
 fireEvent.click(screen.getByRole('button',{name:'Save system',exact:true}));
 await screen.findByRole('button',{name:/QA inventory system/});
 fireEvent.click(screen.getByRole('button',{name:'Company planning',exact:true}));
 fireEvent.click(screen.getByText(/Plan history \(/));
 fireEvent.click(screen.getAllByRole('button',{name:/northstar-plan · input version/})[0]);
 await screen.findByText('Inputs changed. Generate a fresh plan before review.',{exact:true});

 fireEvent.click(screen.getByRole('button',{name:'AI & connectors',exact:true}));
 await screen.findByText('Models, tools and specialist agents',{exact:true});
 assert.ok(screen.getByRole('button',{name:'Create agent run',exact:true}).disabled);
 fireEvent.click(screen.getByLabelText('Enable AI for this project',{exact:true}));
 fireEvent.click(screen.getByLabelText('Approve project data sharing with selected services',{exact:true}));
 fireEvent.change(screen.getByLabelText('Financial analysis model',{exact:true}),{target:{value:'contract-model'}});
 fireEvent.click(screen.getByRole('checkbox',{name:/Contract-test repository/}));
 fireEvent.click(screen.getByRole('button',{name:'Save AI controls',exact:true}));
 await waitFor(()=>assert.ok(!screen.getByRole('button',{name:'Save AI controls',exact:true}).disabled));
 fireEvent.change(screen.getByLabelText('Specialist',{exact:true}),{target:{value:'finance'}});
 fireEvent.change(screen.getByLabelText('Agent goal',{exact:true}),{target:{value:'Review our recorded finance baseline'}});
 fireEvent.click(screen.getByRole('button',{name:'Create agent run',exact:true}));
 await screen.findByText('Agent run: finance',{exact:true});
 fireEvent.click(screen.getByRole('button',{name:'Run to result',exact:true}));
 await screen.findByText('The recorded actual cost is GBP 76,000.',{exact:false});
 await waitFor(()=>assert.ok(!screen.getByRole('button',{name:'Create agent run',exact:true}).disabled));
 assert.ok(screen.getByText('obs-1 · financial_report',{exact:true}));
 assert.ok(screen.getByText('obs-2 · propose_task',{exact:true}));
 const state=await api('snapshot',project);
 assert.ok(state.actions.some(a=>a.payload.title==='Review finance baseline'&&a.status==='pending'));
 assert.ok(!state.objects.some(o=>o.kind==='task'&&o.data.title==='Review finance baseline'));
 assert.equal((await api('ai.status',project)).usage_today.model_calls,3);
 fireEvent.change(screen.getByLabelText('Connector',{exact:true}),{target:{value:'repo-demo'}});
 fireEvent.click(screen.getByRole('button',{name:'Read connector',exact:true}));
 await screen.findByLabelText('Evidence document ID',{exact:true});
 fireEvent.change(screen.getByLabelText('Evidence document ID',{exact:true}),{target:{value:'connector-evidence'}});
 fireEvent.click(screen.getByRole('button',{name:'Add reviewed snapshot to evidence',exact:true}));
 await waitFor(()=>{if(screen.queryByLabelText('Evidence document ID',{exact:true}))throw Error('Waiting for evidence import to complete');});
 assert.ok((await api('knowledge.ask',project,{question:'fictional pilot TypeScript'})).evidence.length);
 fireEvent.click(screen.getByRole('button',{name:'Create agent run',exact:true}));
 await waitFor(()=>assert.ok(!screen.getByRole('button',{name:'Cancel run',exact:true}).disabled));
 fireEvent.click(screen.getByRole('button',{name:'Cancel run',exact:true}));
 await screen.findByText('cancelled',{exact:true});

 fireEvent.click(screen.getByRole('button',{name:'Agents',exact:true}));
 fireEvent.click(screen.getByRole('button',{name:'Run readiness agent',exact:true}));
 await screen.findByText(/bounded_readiness_rules_v1/);
 const approvals=screen.getAllByRole('button',{name:'Approve',exact:true});
 fireEvent.click(approvals.find(b=>!b.disabled));
 await screen.findByRole('alert');
 assert.match(screen.getByRole('alert').textContent,/independent reviewer/);
 fireEvent.click(screen.getByRole('button',{name:'Pause all agents',exact:true}));
 await screen.findByRole('button',{name:'Resume agents',exact:true});
 assert.ok(screen.getByRole('button',{name:'Run readiness agent',exact:true}).disabled);
 cleanup();
 const result={passed:true,environment:'React DOM in jsdom against signed Node client and real Python service; model/connector contract fixtures',checks:['project load','six workstreams','GraphRAG evidence','financial scenario','RICE priority','UAT gate','company plan generation','transition cost calculation','incomplete plan review blocked','Day 1 roadmap and gates','guided company intake','stale plan history','record save','agent planning','self-approval rejection','pause control','AI disabled by default','owner route and sharing controls','model-driven multi-step run','observation citations','proposals remain pending','usage metering','connector preview and explicit evidence ingest','run cancellation'],visual_browser_verification:false,live_provider_verification:false};
 await fs.writeFile('../ui-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{server.kill('SIGTERM');}
