import { useState, type FormEvent } from 'react';
type Data=Record<string, any>;
type Props={report:Data;objects:{kind:string;id:string;revision:number;data:Data}[];role:string;busy:boolean;run:(c:string,d?:Data,refresh?:boolean)=>Promise<unknown>;openRegister:(kind:string,companyId?:string)=>void};
const nice=(s:string)=>s.replaceAll('_',' ');
const display=(v:unknown)=>v==null?'Not available':String(v);
export function BusinessPanel({report:r,objects,role,busy,run,openRegister}:Props){
 const [step,setStep]=useState('Departments');const [selected,setSelected]=useState('');const [domain,setDomain]=useState('purpose');const [editing,setEditing]=useState(false);const [answer,setAnswer]=useState('');const [owner,setOwner]=useState('');const [source,setSource]=useState('');const [status,setStatus]=useState('reported');const [sourceKind,setSourceKind]=useState('interview');
 const company=selected||r.companies?.[0]?.id||'';const covered=(r.coverage||[]).filter((c:Data)=>c.company_id===company);const q=covered.find((c:Data)=>c.domain===domain);const existing=objects.find(o=>o.kind==='discovery_answer'&&o.data.company_id===company&&o.data.domain===domain);
 const writable=['owner','analyst','reviewer'].includes(role);const financial=['owner','finance'].includes(role);
 const register=(kind:string)=>openRegister(kind,company);
 function loadAnswer(){setAnswer(existing?.data.answer||'');setOwner(existing?.data.owner||r.companies.find((c:Data)=>c.id===company)?.owner||'');setSource(existing?.data.evidence_ref||'');setStatus(existing?.data.evidence_status||'reported');setSourceKind(existing?.data.source_kind||'interview');setEditing(true);}
 async function save(e:FormEvent){e.preventDefault();const result=await run('records.save',{kind:'discovery_answer',expected_revision:existing?.revision||0,record:{id:existing?.id||crypto.randomUUID(),company_id:company,domain,question:q.question,answer,owner,evidence_ref:source,evidence_status:status,source_kind:sourceKind}});if(result)setEditing(false);}
 function exportPlan(){const blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='business360-improvement-plan.json';a.click();URL.revokeObjectURL(url);}
 function cards(rows:Data[],keys:string[]){return rows.length?<div className="oqt-table"><table><thead><tr>{keys.map(k=><th key={k}>{nice(k)}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||i}>{keys.map(k=><td key={k}>{display(row[k])}</td>)}</tr>)}</tbody></table></div>:<p className="oqt-empty">No records added yet.</p>;}
 return <div className="b360"><div className="b360-heading"><div><span className="oqt-eyebrow">BUSINESS360</span><h2>Understand the business. Build the plan.</h2><p className="oqt-muted">Start with its structure and people, then collect the evidence behind each decision.</p></div><button className="oqt-secondary" onClick={exportPlan}>Export workspace plan</button></div>
 {!r.companies.length?<section className="oqt-card"><h3>Add the business first</h3><p>Create its business record before adding departments, people and evidence.</p><button onClick={()=>register('company')}>Add business details</button></section>:<><label className="b360-company">Business<select value={company} onChange={e=>{setSelected(e.target.value);setEditing(false);}}>{r.companies.map((c:Data)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="b360-steps" role="navigation" aria-label="Business setup">{['Departments','People & stakeholders','Discovery','Performance','Improvement plan'].map((s,i)=><button className={step===s?'selected':'oqt-secondary'} key={s} onClick={()=>{setStep(s);setEditing(false);}}><span>{String(i+1).padStart(2,'0')}</span>{s}</button>)}</div>
 {step==='Departments'&&<section className="oqt-card"><h3>Departments and responsibilities</h3><p>Define each department’s purpose and accountable owner.</p>{cards(r.departments.filter((d:Data)=>d.company_id===company),['name','purpose','owner'])}<button disabled={!writable} onClick={()=>register('department')}>Add department</button><button className="oqt-secondary" onClick={()=>setStep('People & stakeholders')}>Continue to people</button></section>}
 {step==='People & stakeholders'&&<><section className="oqt-card"><h3>People and reporting lines</h3>{cards(r.people.filter((d:Data)=>d.company_id===company),['name','department_id','job_title','reports_to','employment_type'])}<button disabled={!writable} onClick={()=>register('person')}>Add person</button>{financial&&<button className="oqt-secondary" onClick={()=>register('person_private')}>Restricted pay & benefits</button>}<p className="oqt-muted">Directory records do not grant login access. Owners manage project access separately.</p></section><section className="oqt-card"><h3>Customers, suppliers and other stakeholders</h3>{cards(r.stakeholders.filter((d:Data)=>d.company_id===company),['name','party','organisation','interest','owner'])}<button disabled={!writable} onClick={()=>register('stakeholder')}>Add stakeholder</button><button className="oqt-secondary" onClick={()=>setStep('Discovery')}>Continue to discovery</button></section></>}
 {step==='Discovery'&&<div className="oqt-columns"><section className="oqt-card"><h3>Discovery coverage</h3><div className="b360-coverage">{covered.map((c:Data)=><button key={c.domain} className={'b360-domain '+(c.domain===domain?'current':'')} onClick={()=>{setDomain(c.domain);setEditing(false);}}><span>{nice(c.domain)}</span><small>{nice(c.status)}</small></button>)}</div></section><section className="oqt-card"><span className="oqt-pill">{q?.status}</span><h3 className="b360-question">{q?.question}</h3>{editing?<form onSubmit={save}><label>Answer<textarea required value={answer} onChange={e=>setAnswer(e.target.value)}/></label><label>Accountable owner<input required value={owner} onChange={e=>setOwner(e.target.value)}/></label><label>Evidence reference<input required value={source} placeholder="Document reference, interview date or inspection record" onChange={e=>setSource(e.target.value)}/></label><div className="oqt-fields"><label>Source<select value={sourceKind} onChange={e=>setSourceKind(e.target.value)}>{['interview','document','inspection','system'].map(s=><option key={s}>{s}</option>)}</select></label><label>Evidence status<select value={status} onChange={e=>setStatus(e.target.value)}>{['reported','verified','disputed','unknown'].map(s=><option key={s} disabled={s==='verified'&&!['owner','reviewer'].includes(role)}>{s}</option>)}</select></label></div><button disabled={busy}>Save answer</button><button type="button" className="oqt-secondary" onClick={()=>setEditing(false)}>Cancel</button></form>:<><p className="b360-answer">{existing?.data.answer||'Capture an answer and supporting evidence to begin.'}</p>{existing&&<p className="oqt-muted">{existing.data.owner} · {existing.data.evidence_ref}</p>}<button disabled={busy||!writable} onClick={loadAnswer}>{existing?'Update answer':'Record answer'}</button></>}</section></div>}
 {step==='Performance'&&<><div className="oqt-inline"><button disabled={!financial} onClick={()=>register('business_financials')}>Add financial baseline</button><button className="oqt-secondary" disabled={!financial} onClick={()=>register('receivable')}>Add receivable</button><button className="oqt-secondary" onClick={()=>register('business_process')}>Map a process</button></div>{r.metrics.filter((m:Data)=>m.company_id===company).map((m:Data)=><section className="oqt-card b360-metric" key={m.id}><h3>{m.period_start} — {m.period_end} · {m.currency}</h3><div className="oqt-kpis">{[['Gross margin',m.gross_margin_percent,'%'],['Operating margin',m.operating_margin_percent,'%'],['Collection days',m.dso_days,'days'],['Acquisition cost',m.cac,m.currency]].map(([name,value,unit])=><div key={name}><span>{name}</span><strong>{value==null?'—':value}</strong><small>{value==null?'Missing inputs':unit}</small></div>)}</div>{cards([m],['inventory_days','dpo_days','cash_conversion_days','lead_conversion_percent','missed_call_percent'])}<p className="oqt-muted">{m.basis}</p></section>)}{!r.metrics.some((m:Data)=>m.company_id===company)&&<p className="oqt-empty">Add a baseline to calculate margins, collection days, customer acquisition cost and conversion.</p>}<section className="oqt-card"><h3>Collections across this workspace</h3><strong className="b360-total">{r.collections.overdue_total} {r.currency}</strong><p>{r.collections.overdue_count} overdue invoices · {r.collections.eligible_draft_count} draft candidates for collection review</p><p className="oqt-muted">{r.collections.basis} Recovrable is not connected.</p></section></>}
 {step==='Improvement plan'&&<><div className="oqt-inline"><button disabled={!writable} onClick={()=>register('stakeholder_issue')}>Record a bottleneck</button><button className="oqt-secondary" disabled={!writable} onClick={()=>register('improvement')}>Model an improvement</button></div><section className="oqt-card"><h3>Opportunities and estimates</h3><p className="oqt-muted">{r.benefit_basis}</p>{cards(r.opportunities.filter((x:Data)=>x.company_id===company),['name','benefit_type','amount','frequency','first_year_net','overlap'])}</section><section className="oqt-card"><h3>Proposed actions across this workspace</h3><p className="oqt-muted">Generated from recorded gaps, issues and opportunities. Owners and dates require review.</p>{r.actions.map((a:Data)=><details key={a.id} className="oqt-plan-action"><summary><b>{a.title}</b><span> · {a.phase} · {a.due_date}</span></summary><p>Owner: {a.owner}</p><p>{a.acceptance}</p><p className="oqt-muted">Sources: {a.source_ids.join(', ')}</p></details>)}</section></>}
 </> }</div>;
}
