export const recordTemplates: Record<string, Record<string, unknown>> = {
  department: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "name": "", "purpose": ""},
  person: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "name": "", "department_id": "", "job_title": "", "reports_to": "", "email": "", "employment_type": "employee"},
  person_private: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "person_id": "", "annual_salary": "", "annual_benefits": "", "currency": "GBP"},
  stakeholder: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "name": "", "party": "customer", "organisation": "", "interest": "", "email": ""},
  discovery_answer: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "domain": "purpose", "question": "", "answer": "", "source_kind": "interview", "evidence_status": "reported"},
  business_process: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "name": "", "trigger": "", "steps": [""], "outcome": "", "bottleneck": "", "cycle_minutes": "", "waiting_minutes": ""},
  stakeholder_issue: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "name": "", "party": "customer", "domain": "processes", "problem": "", "impact": "", "recommendation": "", "severity": "medium", "status": "open"},
  business_financials: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "period_start": "", "period_end": "", "currency": "GBP", "revenue": "", "cogs": "", "opex": "", "average_receivables": "", "credit_sales": "", "average_inventory": "", "average_payables": "", "credit_purchases": "", "marketing_cost": "", "new_customers": "", "leads": "", "won_leads": "", "calls": "", "missed_calls": "", "cash": ""},
  improvement: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "name": "", "benefit_type": "cost_saving", "amount": "", "frequency": "monthly", "implementation_cost": "", "recurring_cost": "", "overlap_group": "", "assumptions": "", "action": "", "target_date": ""},
  receivable: {"id": "", "company_id": "", "owner": "", "evidence_ref": "", "customer_ref": "", "invoice_ref": "", "currency": "GBP", "outstanding": "", "due_date": "", "disputed": false, "collection_hold": false, "last_verified": ""},

  company: { id: "", name: "", company_role: "operating", sector: "", countries: [""], sites: [""], owner: "", description: "", evidence_ref: "" },
  planning_scope: { id: "", name: "", deal_type: "carve_out", company_ids: [""], target_company_id: "", asset_ids: [""], workforce_ids: [""], business_service_ids: [""], cost_item_ids: [""], owner: "", start_date: "", day_one_date: "", horizon_days: 100, constraints: "", requirements_ref: "", inventory_complete: false, workforce_complete: false, costs_complete: false, transition_budget: "" },
  business_service: { id: "", name: "", company_id: "", owner: "", criticality: "high", day_one_required: true, acceptance_criteria: "", evidence_ref: "" },
  asset: { id: "", name: "", company_id: "", asset_type: "technology", quantity: 1, owner: "", criticality: "high", day_one_required: true, disposition: "unassessed", target_company_id: "", transferability: "unknown", workstream_id: "enterprise", system_id: "", evidence_ref: "" },
  workforce: { id: "", name: "", company_id: "", owner: "", headcount: 0, fte: "0", skills: [""], key_dependencies: "", target_company_id: "", transition_approach: "", evidence_ref: "" },
  cost_item: { id: "", name: "", company_id: "", cost_key: "", cost_state: "current", cost_category: "technology", amount: "", currency: "GBP", frequency: "monthly", duration_months: "", owner: "", basis: "estimated", asset_id: "", workforce_id: "", fx_rate: "", fx_as_of: "", fx_source: "", evidence_ref: "" },
  objective: { id: "", name: "", company_id: "", owner: "", metric: "", baseline: "", target: "", unit: "", direction: "decrease", moscow: "must", target_date: "", evidence_ref: "" },
  asset_dependency: { id: "", source: "", target: "", reviewed: false, evidence_ref: "" },
  delivery_mandate: { id: "", name: "", company_id: "", owner: "", delivery_model: "sub_contract", client: "", prime_adviser: "", delivery_partner: "", branding: "white_label", display_brand: "", workstream_ids: ["enterprise", "identity", "cloud", "security", "integration", "data"], decision_rights: "", reporting_cadence: "", acceptance_criteria: "", commercial_ref: "" },
  tdd_finding: { id: "", name: "", company_id: "", owner: "", severity: "high", finding_status: "open", business_impact: "", recommendation: "", cost_item_ids: [""], evidence_ref: "" },
  tsa_obligation: { id: "", name: "", company_id: "", owner: "", tsa_id: "", provider_company_id: "", recipient_company_id: "", asset_ids: [""], service_scope: "", service_levels: "", charging_basis: "", responsibilities: "", exit_roadmap: "", consent_status: "draft", evidence_ref: "" },
  decision: { id: "", name: "", company_id: "", owner: "", decision_date: "", decision_status: "proposed", rationale: "", alternatives: "", evidence_ref: "" },
  workstream: { id: "enterprise", name: "", owner: "", scope: "", platforms: "" },
  checkpoint: { id: "", workstream_id: "enterprise", title: "", phase: "discovery", owner: "", status: "pending", blocking: true, evidence_ref: "", exception_reason: "" },
  migration_wave: { id: "", name: "", workstream_id: "enterprise", owner: "", system_ids: [""], scheduled_date: "", status: "planned", freeze_ref: "", rollback_ref: "", evidence_ref: "" },
  security_mapping: { id: "", framework: "", edition: "", control_ref: "", scope: "", owner: "", applicability: "under_review", status: "gap", evidence_ref: "", reviewed_on: "", exception_reason: "" },
  interface: { id: "", name: "", owner: "", producer: "", consumer: "", contract_ref: "", auth_scope: "", status: "planned", test_evidence_ref: "", rollback_ref: "" },
  data_asset: { id: "", name: "", owner: "", source_system: "", target_system: "", classification: "internal", lineage_ref: "", quality_rule: "", status: "planned", evidence_ref: "" },
  spec: { id: "", title: "", type: "prd", owner: "", problem: "", requirements: "", acceptance_criteria: "", success_metrics: "", research_ids: [""], status: "draft", evidence_ref: "" },
  sprint: { id: "", title: "", owner: "", goal: "", start_date: "", end_date: "", capacity_points: 0, status: "planned" },
  system: { id: "", name: "", owner: "", criticality: "high", status: "active", evidence_ref: "", reviewed: false },
  dependency: { id: "", source: "", target: "", evidence_ref: "", reviewed: false },
  task: { id: "", title: "", owner: "", status: "todo", critical: false, due_date: "", evidence_ref: "" },
  risk: { id: "", title: "", owner: "", severity: "high", status: "open", mitigation: "", evidence_ref: "" },
  control: { id: "", title: "", owner: "", status: "pending", evidence_ref: "" },
  tsa: { id: "", name: "", supplier: "", owner: "", exit_date: "", monthly_cost: "0", currency: "GBP", status: "active", exit_conditions: "", evidence_ref: "" },
  runbook: { id: "", title: "", owner: "", steps: [""], rollback: "", status: "draft", evidence_ref: "" },
  engagement: { id: "", name: "", client: "", adviser: "", delivery_lead: "", branding: "direct", display_brand: "", deal_type: "carve_out", scope: "", start_date: "", target_date: "" },
  deliverable: { id: "", title: "", owner: "", status: "planned", acceptance_criteria: "", due_date: "", evidence_ref: "" },
  integration: { id: "", name: "", owner: "", status: "planned", permissions: "", evidence_ref: "" },
  research: { id: "", title: "", method: "interview", segment: "", finding: "", jtbd: "", source_ref: "", observed_on: "", reviewed: false },
  opportunity: { id: "", title: "", owner: "", reach: "0", reach_period: "", reach_population: "", impact: "1", confidence_percent: "50", effort_person_months: "1", moscow: "should", jtbd: "", evidence_ref: "", status: "discovery", target_release: "" },
  story: { id: "", title: "", owner: "", opportunity_id: "", sprint: "", status: "backlog", acceptance_criteria: "", estimate_points: 0 },
  uat: { id: "", title: "", story_id: "", tester: "", status: "pending", blocking: true, tested_on: "", evidence_ref: "" },
  release: { id: "", title: "", owner: "", target_date: "", story_ids: [""], status: "planned", changelog_ref: "", rollback_ref: "", gtm_ref: "" },
  gtm: { id: "", title: "", owner: "", audience: "", positioning: "", channels: "", success_metric: "", status: "draft", launch_date: "" },
  competitor: { id: "", name: "", proposition: "", strengths: "", gaps: "", source_ref: "", checked_on: "" },
  adoption: { id: "", cohort: "", period_start: "", period_end: "", eligible_users: 0, activated_users: 0, retained_users: 0, feature_users: 0, source_ref: "" },
};

export const choices: Record<string, string[]> = {
  domain: ["purpose", "customers", "revenue", "processes", "people", "assets", "technology", "costs", "collections", "suppliers", "compliance", "goals"],
  employment_type: ["employee", "contractor", "adviser"],
  party: ["customer", "supplier", "staff", "management", "investor", "adviser", "regulator"],
  source_kind: ["interview", "document", "inspection", "system"],
  evidence_status: ["reported", "verified", "disputed", "unknown"],
  benefit_type: ["cost_saving", "incremental_contribution", "cash_recovery", "working_capital", "capacity_hours"],

  company_role: ["buyer", "seller", "target", "newco", "merged", "operating", "group"], asset_type: ["technology", "property", "equipment", "inventory", "ip", "data", "contract", "licence", "brand", "network", "other"],
  disposition: ["retain", "migrate", "consolidate", "replace", "separate", "retire", "shared", "unassessed"], transferability: ["unknown", "confirmed", "restricted"],
  cost_state: ["current", "transition", "target"], cost_category: ["technology", "people", "property", "operations", "supplier", "tsa", "other"], frequency: ["daily", "weekly", "monthly", "quarterly", "annual", "one_off"], basis: ["confirmed", "estimated"], direction: ["increase", "decrease", "maintain"],
  delivery_model: ["sub_contract", "direct_advisory"], finding_status: ["open", "mitigating", "closed"], consent_status: ["draft", "negotiating", "confirmed"], decision_status: ["proposed", "accepted", "rejected", "superseded"],
  workstream_id: ["enterprise", "identity", "cloud", "security", "integration", "data"], phase: ["discovery", "build", "rehearsal", "cutover", "handover"], applicability: ["under_review", "applicable", "not_applicable"],
  type: ["prd", "technical", "design"],
  criticality: ["low", "medium", "high", "critical"], severity: ["low", "medium", "high", "critical"],
  currency: ["GBP", "EUR", "USD", "AED", "PKR"], branding: ["direct", "white_label", "co_branded"],
  deal_type: ["acquisition", "carve_out", "merger", "modernisation"],
  moscow: ["must", "should", "could", "wont_now"], method: ["interview", "survey", "observation", "support", "analytics", "desk_research"],
};
export const statuses: Record<string, string[]> = {
  stakeholder_issue: ["open", "mitigating", "closed"],
  checkpoint: ["pending", "passed", "failed", "not_applicable"], migration_wave: ["planned", "rehearsing", "ready", "completed", "rolled_back"], security_mapping: ["gap", "in_progress", "evidenced", "assessed"], interface: ["planned", "building", "tested", "accepted", "retired"], data_asset: ["planned", "building", "tested", "accepted", "retired"],
  spec: ["draft", "review", "approved"], sprint: ["planned", "active", "closed"],
  system: ["active", "planned", "retiring", "retired"], task: ["todo", "doing", "blocked", "done"], risk: ["open", "mitigating", "closed"],
  control: ["pending", "failed", "passed"], tsa: ["active", "exit_pending", "exited"], runbook: ["draft", "tested", "approved"],
  deliverable: ["planned", "draft", "review", "accepted"], integration: ["planned", "configuring", "validated", "disabled"],
  opportunity: ["discovery", "planned", "building", "measuring", "done"], story: ["backlog", "ready", "in_progress", "review", "done"],
  uat: ["pending", "passed", "failed", "blocked"], release: ["planned", "testing", "review", "released"], gtm: ["draft", "review", "approved", "launched"],
};
