'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {UserRoundCheck,PhoneForwarded,Loader2} from 'lucide-react';
import {callerPhone} from '@/lib/phone';
import {date} from './console';
type R=Record<string,any>;
async function customerRequest(body:R,signal?:AbortSignal){const response=await fetch('/api/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal});const data=await response.json() as R;if(!response.ok)throw Error(data.error||'Customer lookup failed.');return data;}
export function FollowUp({history,preferredId,onChoose,disabled}:{history:R;preferredId?:string;onChoose?:(id:string)=>void;disabled?:boolean}){const last=history.lastHuman;return <div className="customer-history"><strong>Customer context</strong><p className="muted text-sm">{history.historyScope}</p>{last&&<div className="customer-followup"><PhoneForwarded size={18}/><div><strong>Previously spoke with {last.name}</strong><p>{last.handoff_note||last.summary}</p><small className="muted">{date(last.created_at)} · {last.stillOnTeam?'Availability has not been checked':'No longer in this workspace’s active team'}</small>{onChoose&&last.stillOnTeam&&<Button type="button" size="sm" variant={preferredId===last.id?'default':'outline'} disabled={disabled} onClick={()=>onChoose(preferredId===last.id?'':last.id)}>{preferredId===last.id?'Same person requested · clear':'Customer requests the same person'}</Button>}<p className="muted text-sm">A preference for follow-up. Live transfer, staff presence and callback scheduling are coming soon.</p></div></div>}{!last&&<p className="muted">No previous human conversation has been recorded for this customer.</p>}{history.items.length>0&&<details><summary>Recent requests ({history.items.length})</summary>{history.items.map((r:R)=><div className="customer-past" key={r.id}><small>{date(r.created_at)} · {r.kind} · {r.status}</small><p>{r.summary}</p>{r.source_ref&&<small>Source reference: {r.source_ref}</small>}</div>)}</details>}</div>}
export function CallerLookup({form,onSelect,onPreferred,disabled}:{form:R;onSelect:(customer:R)=>void;onPreferred:(id:string)=>void;disabled:boolean}){
 const [result,setResult]=useState<R|null>(null),[history,setHistory]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);const scope=useRef(''),requests=useRef<AbortController[]>([]);const key=form.productId+'|'+form.callerNumber+'|'+form.requestKey;scope.current=key;
 useEffect(()=>{setResult(null);setHistory(null);setError('');setBusy(false);const controller=new AbortController();requests.current.push(controller);const timer=setTimeout(()=>{if(!form.productId)return;setBusy(true);customerRequest({action:'lookup',productId:form.productId,phone:form.callerNumber},controller.signal).then(data=>{if(!controller.signal.aborted)setResult(data)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setBusy(false)})},350);return()=>{clearTimeout(timer);requests.current.forEach(c=>c.abort());requests.current=[]}},[key,revision]);
 useEffect(()=>{setHistory(null);if(!form.customerId)return;const controller=new AbortController();requests.current.push(controller);customerRequest({action:'history',productId:form.productId,customerId:form.customerId},controller.signal).then(data=>{if(!controller.signal.aborted)setHistory(data)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[key,form.customerId,revision]);
 const save=async()=>{const original=key,controller=new AbortController();requests.current.push(controller);setBusy(true);setError('');try{const r=await customerRequest({action:'save',productId:form.productId,name:form.customer,phone:form.callerNumber,externalRef:'manual:'+form.customerKey},controller.signal);if(original===scope.current&&!controller.signal.aborted){onSelect(r.customer);setRevision(v=>v+1)}}catch(e:any){if(original===scope.current&&e.name!=='AbortError')setError(e.message)}finally{if(original===scope.current&&!controller.signal.aborted)setBusy(false)}};
 const parsed=callerPhone(form.callerNumber);return <div className="caller-lookup"><div className="flex gap-2 items-center"><UserRoundCheck size={18}/><strong>Recognise the customer</strong>{busy&&<Loader2 size={15} className="spin"/>}</div><p className="muted text-sm">Matches are limited to this company and product. Confirm who is calling; a number match does not verify identity.</p>{error&&<p role="alert" className="notice warning compact">{error}</p>}{result?.status==='withheld'&&<p>No caller number is available. Ask for their details.</p>}{result?.status==='invalid'&&<p>Enter the international number with country code, for example +44 20 7946 0123. Local numbers and extensions need clarification.</p>}{result?.status==='unknown'&&<p>No saved customer matches this number. You can save a profile after confirming their details.</p>}{result?.status==='ambiguous'&&<p className="notice warning compact">Shared number: more than one customer matches. Ask who is calling before selecting a profile.{result.more?' More than 20 profiles match; use the source customer reference to disambiguate.':''}</p>}{result?.matches?.map((c:R)=><div className="customer-match" key={c.id}><div><strong>{c.name}</strong><small>{c.phone} · {c.external_ref}</small></div><Button type="button" size="sm" variant={form.customerId===c.id?'default':'outline'} disabled={disabled||busy} onClick={()=>onSelect(c)}>{form.customerId===c.id?'Selected':'Confirm this customer'}</Button></div>)}{!form.customerId&&parsed.state==='number'&&<Button type="button" variant="outline" size="sm" disabled={disabled||busy||!form.customer?.trim()||!form.productId} onClick={save}>Save entered name as a new customer</Button>}{form.customerId&&<p className="muted text-sm">This request will be linked to the selected customer when saved.</p>}{history&&history.customer.id===form.customerId&&<FollowUp history={history} preferredId={form.preferredHandlerId} onChoose={onPreferred} disabled={disabled}/>}</div>
}
export function CustomerContext({productId,customerId}:{productId:string;customerId:string}){const [data,setData]=useState<R|null>(null),[error,setError]=useState('');useEffect(()=>{setData(null);setError('');const c=new AbortController();customerRequest({action:'history',productId,customerId},c.signal).then(r=>{if(!c.signal.aborted)setData(r)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[productId,customerId]);return error?<p className="notice warning compact">{error}</p>:data?<FollowUp history={data}/>:<p className="muted">Loading linked customer context…</p>}
