'use client';
import {DictationButton} from './speech-input';
import {useState,useEffect,useCallback,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';
import {Skeleton} from '@/components/ui/skeleton';
import {Sunrise,Plus,ArrowRight,CalendarDays,CheckCircle2,Clock,MessageCircle,Flag,AlertCircle,RefreshCw,Check,ChevronRight,Copy,Trash2,ClipboardList,Sparkles,PhoneIncoming} from 'lucide-react';
import {toast} from 'sonner';
import {useConsole,Field,Choice,Tag,Modal,Head,Empty,request,parse,copy} from './console';
import {localDay,offsetDay} from '@/lib/day';
type R=Record<string,any>;
const helpKinds=[{value:'breakdown',label:'Break this task into steps'},{value:'draft',label:'Prepare a message or document'},{value:'unblock',label:'Help me resolve a blocker'}];
function localInput(value:string){const d=new Date(value);return localDay(d,Intl.DateTimeFormat().resolvedOptions().timeZone)+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function dayLabel(value:string){return new Date(value+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}
export function MyDay(){
 const {data:workspaceData,mutate,busy,canWrite,setView,newRun,setRunId,setConfirm}=useConsole();
 const [day,setDay]=useState(''),[zone,setZone]=useState('Europe/London'),[data,setData]=useState<R|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[item,setItem]=useState<R|null>(null),[meeting,setMeeting]=useState<R|null>(null),[checkIn,setCheckIn]=useState(false),[checkStep,setCheckStep]=useState(0),[plan,setPlan]=useState<R>({goals:'',issues:'',review_note:'',help:[],revision:0}),[helpId,setHelpId]=useState(''),[helpKind,setHelpKind]=useState('breakdown'),[stepTitle,setStepTitle]=useState(''),[wrap,setWrap]=useState(false),[draft,setDraft]=useState<R|null>(null);
 const lastToday=useRef('');
 const seq=useRef(0),dirty=useRef(false),dateRef=useRef({day:'',zone:'Europe/London'});dateRef.current={day,zone};
 useEffect(()=>{const z=Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/London';setZone(z);lastToday.current=localDay(new Date(),z);setDay(lastToday.current)},[]);
 const load=useCallback(async()=>{if(!day)return;const n=++seq.current;try{const d=await request('/api/day?date='+day+'&timezone='+encodeURIComponent(zone),undefined,'GET');if(n!==seq.current)return;setData(d);setError('');if(!dirty.current)setPlan({...d.plan,help:parse(d.plan.help_item_ids,[])})}catch(e:any){if(n===seq.current)setError(e.message)}finally{if(n===seq.current)setLoading(false)}},[day,zone,workspaceData.workspace.id]);
 useEffect(()=>{setLoading(true);setData(null);dirty.current=false;setItem(null);setMeeting(null);setHelpId('');setCheckIn(false);setWrap(false);setDraft(null);void load();return()=>{seq.current++}},[load]);
 useEffect(()=>{const onFocus=()=>void load();window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus)},[load]);
 useEffect(()=>{const h=setInterval(()=>{const current=dateRef.current;const today=localDay(new Date(),current.zone);if(lastToday.current&&today!==lastToday.current&&current.day===lastToday.current&&!dirty.current)setDay(today);lastToday.current=today},60000);return()=>clearInterval(h)},[]);
 const act=async(b:R)=>{const r=await mutate(b,'/api/day');if(r)await load();return r};
 const savePlan=async()=>{const r=await act({action:'save_plan',day,timezone:zone,goals:plan.goals,issues:plan.issues,reviewNote:plan.review_note,helpItemIds:plan.help,revision:plan.revision});if(r){dirty.current=false;await load();toast.success('Your day plan is saved')}return r};
 const newItem=(prefill:R={})=>setItem({title:'',notes:'',productId:'',day,dueDate:'',priority:'normal',blocker:'',...prefill});
 const editItem=(i:R)=>setItem({id:i.id,title:i.title,notes:i.notes,productId:i.product_id||'',day:i.scheduled_date,dueDate:i.due_date||'',priority:i.priority,blocker:i.blocker,revision:i.revision,source_task_id:i.source_task_id});
 const editMeeting=(m?:R)=>{const browserZone=Intl.DateTimeFormat().resolvedOptions().timeZone;setMeeting(m?{id:m.id,title:m.title,productId:m.product_id||'',starts:localInput(m.starts_at),duration:m.duration,timezone:browserZone,attendees:m.attendees,status:m.status,notes:m.notes,revision:m.revision}:{title:'',productId:'',starts:day+'T09:00',duration:30,timezone:browserZone,attendees:'',status:'unconfirmed',notes:''})};
 const setStatus=(i:R,status:string)=>{const run=()=>act({action:'item_status',id:i.id,revision:i.revision,status,completeSource:!!i.source_task_id});if(i.source_task_id&&status==='completed')setConfirm({title:'Complete this workspace task?',description:'This will complete the linked task in the shared Task inbox as well as your day plan.',label:'Complete task',run});else void run()};
 const askAgent=(i:R)=>{setHelpId('');newRun({productId:i.product_id||undefined,templateId:helpKind==='draft'?'documents':'coordination',kind:workspaceData.provider.connected?'live':'sample',title:'Daily guide: '+i.title,input:'Help me '+(helpKind==='draft'?'prepare a draft for':helpKind==='unblock'?'resolve the blocker on':'break down and complete')+' this task.\nTask: '+i.title+'\nNotes: '+i.notes+'\nDue date: '+(i.due_date||'Not set')+'\nRecorded blocker: '+(i.blocker||'None')+'\nCurrent steps: '+JSON.stringify(parse(i.steps,[]))+'\nUse the available evidence, ask about missing facts, and suggest a practical next step. Do not claim a message was sent or that the task is complete.'})};
 if(!day||loading)return <div className="day-loading"><Skeleton className="h-40 rounded-xl"/><Skeleton className="h-80 rounded-xl"/></div>;
 if(error||!data)return <section className="panel"><Empty icon={AlertCircle} title="Your daily briefing could not load" description={error||'Please try again.'}><Button onClick={()=>load()}>Try again</Button></Empty></section>;
 const o=data.overview,help=data.items.find((i:R)=>i.id===helpId),firstName=workspaceData.user.name.includes('@')?'there':workspaceData.user.name.split(' ')[0],isToday=day===localDay(new Date(),zone),hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'numeric',hourCycle:'h23'}).format(new Date())),greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';
 const productOptions=[{value:'none',label:'General task'},...workspaceData.products.map((p:R)=>({value:p.id,label:p.name}))];
 const taskCard=(i:R)=><div className={'day-task '+(i.status==='blocked'?'is-blocked':'')} key={i.id}><div className="day-task-main"><Button variant="ghost" size="icon" aria-label={'Complete '+i.title} disabled={busy||!canWrite||i.status==='completed'} onClick={()=>setStatus(i,'completed')}><CheckCircle2 size={21} className={i.status==='completed'?'text-emerald-600':''}/></Button><div className="flex-1 min-w-0"><button className="day-task-title" onClick={()=>{setHelpId(i.id);setStepTitle('')}}>{i.title}</button><div className="day-task-meta">{i.product_name&&<span>{i.product_name}</span>}{i.due_date&&<span className={i.due_date<day&&i.status!=='completed'?'overdue-text':''}>Due {i.due_date}</span>}{i.scheduled_date<day&&i.status!=='completed'&&<Tag>Carried forward</Tag>}{i.source_task_id&&<Tag>Linked task</Tag>}{i.priority==='high'&&<Tag tone="amber">High priority</Tag>}{i.status==='blocked'&&<Tag tone="red">Blocked</Tag>}{plan.help.includes(i.id)&&<Tag>Help requested</Tag>}</div>{i.status==='blocked'&&i.blocker&&<p className="day-blocker">{i.blocker}</p>}</div><Button variant="outline" size="sm" onClick={()=>{setHelpId(i.id);setHelpKind(i.status==='blocked'?'unblock':'breakdown')}}><MessageCircle size={15}/>Help me</Button></div></div>;
 const meetingCard=(m:R)=><div className="day-meeting" key={m.id}><div className="meeting-time">{new Date(m.starts_at).toLocaleTimeString('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit'})}<small>{localDay(m.starts_at,zone)===day?m.duration+' min':localDay(m.starts_at,zone)}</small></div><div className="flex-1 min-w-0"><button className="day-task-title" onClick={()=>editMeeting(m)}>{m.title}</button><p>{m.attendees||'No participants recorded'}</p><Tag tone={m.status==='confirmed'?'green':m.status==='unconfirmed'?'amber':''}>{m.status==='unconfirmed'?'Awaiting confirmation':m.status}</Tag></div>{m.status==='unconfirmed'&&canWrite&&<Button variant="ghost" size="sm" onClick={()=>setDraft({title:'Meeting confirmation draft',text:'Hello'+(m.attendees?' '+m.attendees:'')+',\n\nPlease confirm whether you can attend '+m.title+' on '+new Date(m.starts_at).toLocaleString('en-GB',{timeZone:zone})+' ('+zone+').\n\n'+(m.notes?'Agenda: '+m.notes+'\n\n':'')+'Please let me know if another time would work better. Thank you.',meeting:m})}>Follow up</Button>}</div>;
 return <div className="day-view"><div className="day-toolbar"><div className="flex items-center gap-2"><CalendarDays size={17}/><Input aria-label="Day to review" type="date" value={day} disabled={busy||dirty.current} onChange={e=>e.target.value&&setDay(e.target.value)}/><Button variant="ghost" size="sm" disabled={busy||dirty.current} onClick={()=>setDay(localDay(new Date(),zone))}>Today</Button></div><div className="day-zone"><Choice value={zone} disabled={busy||dirty.current} onChange={setZone} options={[...new Set([zone,'Europe/London','Europe/Berlin','Asia/Karachi','America/New_York','Asia/Dubai','UTC'])]}/></div><Button variant="ghost" size="icon" aria-label="Refresh daily briefing" onClick={()=>load()}><RefreshCw size={16}/></Button></div>
 {dirty.current&&<div className="notice compact"><p>You have unsaved check-in changes. Save them in your check-in, or discard them to load the latest saved plan.</p><Button variant="outline" size="sm" onClick={()=>{dirty.current=false;setPlan({...data.plan,help:parse(data.plan.help_item_ids,[])})}}>Discard changes</Button></div>}
 <section className="day-welcome"><div className="day-welcome-icon"><Sunrise size={28}/></div><div className="flex-1"><p className="eyebrow">{dayLabel(day)}</p><h2>{isToday?greeting+', '+firstName:'Your plan for the day'}.</h2><p>{o.active.length?'You have '+o.active.length+' open '+(o.active.length===1?'task':'tasks')+' in your plan'+(o.overdue.length?', including '+o.overdue.length+' overdue':'')+'.':'There are no outstanding tasks in your personal plan yet.'} {o.todayMeetings.length?o.todayMeetings.length+' recorded '+(o.todayMeetings.length===1?'meeting':'meetings')+' today.':'No meetings recorded for this day.'}</p><p className="day-welcome-question">How can I help you move things forward today?</p></div><Button onClick={()=>{setCheckIn(true);setCheckStep(0)}} disabled={!canWrite||busy}>{data.plan.revision?'Update my check-in':'Let’s plan my day'}<ArrowRight size={16}/></Button></section>
 <div className="day-stats">{[[o.active.length,'Tasks in your plan',ClipboardList],[o.overdue.length,'Overdue',Clock],[o.unconfirmed.length,'Meetings to confirm',CalendarDays],[o.completed.length,'Completed today',CheckCircle2]].map(([value,label,Icon]:any)=><div key={label}><Icon size={19}/><strong>{value}</strong><span>{label}</span></div>)}</div>
 <div className="day-columns"><div className="day-primary"><section className="panel"><Head title="Your next steps"><Button variant="outline" size="sm" disabled={!canWrite||busy} onClick={()=>newItem()}><Plus size={15}/>Add a task</Button></Head>{o.active.length?o.active.map(taskCard):<Empty icon={ClipboardList} title="What would you like to get done?" description="Add a task or choose an outstanding workspace task below. Your unfinished work will carry forward."/>}</section>
 {o.upcoming.length>0&&<details className="panel day-completed"><summary><CalendarDays size={17}/>{o.upcoming.length} planned for later</summary>{o.upcoming.map((i:R)=><div key={i.id}><p className="day-section-note">Planned for {i.scheduled_date}</p>{taskCard(i)}</div>)}</details>}
 {o.completed.length>0&&<details className="panel day-completed"><summary><CheckCircle2 size={17}/>{o.completed.length} completed today</summary>{o.completed.map(taskCard)}</details>}
 <section className="panel"><Head title="Outstanding workspace tasks"><Tag>{data.workspaceCounts.tasks} open</Tag></Head><p className="day-section-note">Shared company work. Choose what belongs in your day; these tasks are not assumed to be assigned to you.</p>{data.availableTasks.length?data.availableTasks.slice(0,10).map((t:R)=><div className="record-row" key={t.id}><div className="record-text"><strong>{t.title}</strong><small>{t.product_name} · {t.assignee||'No named assignee'}</small></div><Button size="sm" variant="outline" disabled={!canWrite||busy} onClick={()=>act({action:'import_task',taskId:t.id,day})}><Plus size={14}/>Add to my day</Button></div>):<p className="day-section-note">No additional live tasks are available to add. Sample tasks are excluded from this briefing.</p>}{data.availableTasks.length>10&&<Button variant="ghost" className="m-3" onClick={()=>setView('Task inbox')}>View more in Task inbox</Button>}</section>
 {data.workspaceCounts.approvals>0&&<button className="day-alert" onClick={()=>setView('Approvals')}><Flag size={21}/><span><strong>{data.workspaceCounts.approvals} company actions need approval</strong><small>Review proposals so work can continue.</small></span><ChevronRight size={18}/></button>}
 {data.reception?.pending>0&&<button className="day-alert" onClick={()=>setView('Receptionist')}><PhoneIncoming size={21}/><span><strong>{data.reception.pending} reception items need attention</strong><small>{data.reception.bookings} bookings awaiting confirmation · {data.reception.orders} orders awaiting handoff</small></span><ChevronRight size={18}/></button>}
 </div><aside className="day-secondary"><section className="panel"><Head title="Today’s check-in"/><div className="panel-body">{plan.goals?<><p className="day-small-label">What matters today</p><p className="day-note">{plan.goals}</p></>:<p className="day-note muted">What else do you plan for the day?</p>}{plan.issues&&<><p className="day-small-label">Issues you mentioned</p><p className="day-note">{plan.issues}</p></>}<Button variant="outline" className="w-full mt-3" disabled={!canWrite||busy} onClick={()=>{setCheckIn(true);setCheckStep(2)}}><MessageCircle size={16}/>Any tasks you need help with?</Button></div></section>
 <section className="panel"><Head title="Meetings"><Button variant="ghost" size="icon" aria-label="Add a meeting" disabled={!canWrite||busy} onClick={()=>editMeeting()}><Plus size={17}/></Button></Head>{o.todayMeetings.length?o.todayMeetings.map(meetingCard):<p className="day-section-note">No meetings recorded for this day.</p>}<p className="day-section-note day-source-note">Manually recorded meetings. Calendar and live RSVP connections are not connected.</p></section>
 {o.unconfirmed.filter((m:R)=>localDay(m.starts_at,zone)!==day).length>0&&<section className="panel"><Head title="Still awaiting confirmation"/>{o.unconfirmed.filter((m:R)=>localDay(m.starts_at,zone)!==day).map(meetingCard)}<p className="day-section-note">Recorded meetings from the last 30 days and next 7 days.</p></section>}
 {data.history.length>0&&<section className="panel"><Head title="From your last check-in"/><div className="panel-body"><Tag>{data.history[0].day}</Tag><p className="day-note mt-3">{data.history[0].review_note||data.history[0].goals||'No priorities recorded.'}</p>{data.history[0].issues&&<p className="day-note muted">Previously recorded issue: {data.history[0].issues}</p>}<button className="text-link" disabled={dirty.current} onClick={()=>setDay(data.history[0].day)}>Review that day <ArrowRight size={14}/></button></div></section>}
 <section className="day-wrap"><h3>Before you finish</h3><p>What did you complete, and what needs attention next?</p><Button variant="outline" disabled={!canWrite||busy} onClick={()=>setWrap(true)}>Wrap up my day</Button></section></aside></div>
 <p className="day-footnote">Your check-ins, manual tasks and recorded meetings are personal within this company. Shared task changes and submitted agent runs are visible to authorised workspace members. Briefing updates when you open or refresh My day.{(data.limits.items||data.limits.meetings)&&' The loaded history limit was reached; older records may not be included.'}</p>
 <Modal title="Let’s plan your day" description={['What else do you plan for the day?','Any issues or blockers I should know about?','Which tasks would you like help with?'][checkStep]} open={checkIn} onClose={()=>setCheckIn(false)}><div className="day-check-progress"><Progress value={(checkStep+1)/3*100}/><span>Step {checkStep+1} of 3</span></div>{checkStep===0&&<Field label="What would make today a good day?"><Textarea rows={5} value={plan.goals} onChange={e=>{dirty.current=true;setPlan({...plan,goals:e.target.value})}} placeholder="Your priorities, extra work or anything you want to make time for."/><DictationButton label="daily priorities" value={plan.goals} maxLength={4000} disabled={busy||!canWrite} onInsert={value=>{dirty.current=true;setPlan({...plan,goals:value})}}/></Field>}{checkStep===1&&<Field label="What might get in the way?"><Textarea rows={5} value={plan.issues} onChange={e=>{dirty.current=true;setPlan({...plan,issues:e.target.value})}} placeholder="Waiting for a reply, missing information, time pressure, or another issue."/><DictationButton label="daily issues" value={plan.issues} maxLength={4000} disabled={busy||!canWrite} onInsert={value=>{dirty.current=true;setPlan({...plan,issues:value})}}/></Field>}{checkStep===2&&<div className="form-stack">{o.active.length?<div className="day-help-select">{o.active.map((i:R)=><label className="check-row" key={i.id}><Checkbox checked={plan.help.includes(i.id)} onCheckedChange={v=>{dirty.current=true;setPlan({...plan,help:v?[...plan.help,i.id]:plan.help.filter((x:string)=>x!==i.id)})}}/><span>{i.title}</span></label>)}</div>:<p className="muted">Save your check-in, then add your first task. You can ask for help from any task.</p>}<p className="day-note muted">I can guide the next step, help you prepare a draft, or help you work through a blocker. Choose a task to begin.</p></div>}<div className="form-footer">{checkStep>0&&<Button variant="outline" onClick={()=>setCheckStep(checkStep-1)}>Back</Button>}{checkStep<2?<Button onClick={()=>setCheckStep(checkStep+1)}>Continue <ArrowRight size={15}/></Button>:<Button disabled={busy} onClick={async()=>{const chosen=plan.help[0];if(await savePlan()){setCheckIn(false);if(chosen)setHelpId(chosen)}}}>Save my plan <Check size={15}/></Button>}</div></Modal>
 <Modal title={item?.id?'Update your task':'Add a task to your day'} description="Set a priority, a planned day and an optional deadline." open={item} onClose={()=>setItem(null)}>{item&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await act({action:'save_item',...item}))setItem(null)}}><Field label="Task"><Input required maxLength={180} value={item.title} onChange={e=>setItem({...item,title:e.target.value})}/></Field><Field label="Product"><Choice value={item.productId||'none'} disabled={!!item.source_task_id} onChange={(v:string)=>setItem({...item,productId:v==='none'?'':v})} options={productOptions}/></Field><Field label="Notes"><Textarea rows={3} value={item.notes} onChange={e=>setItem({...item,notes:e.target.value})}/><DictationButton label="task notes" value={item.notes} maxLength={4000} disabled={busy||!canWrite} onInsert={value=>{setItem({...item,notes:value})}}/></Field><div className="two-grid"><Field label="Planned day"><Input type="date" required value={item.day} onChange={e=>setItem({...item,day:e.target.value})}/></Field><Field label="Due date (optional)"><Input type="date" value={item.dueDate} onChange={e=>setItem({...item,dueDate:e.target.value})}/></Field></div><Field label="Priority"><Choice value={item.priority} onChange={(v:string)=>setItem({...item,priority:v})} options={[{value:'high',label:'High'},{value:'normal',label:'Normal'},{value:'low',label:'Low'}]}/></Field><Field label="Anything blocking this task?"><Textarea value={item.blocker} onChange={e=>setItem({...item,blocker:e.target.value})} placeholder="Leave blank if you can get started."/><DictationButton label="task blocker" value={item.blocker} maxLength={2000} disabled={busy||!canWrite} onInsert={value=>{setItem({...item,blocker:value})}}/></Field><Button disabled={busy}>Save task</Button></form>}</Modal>
 <Modal title={meeting?.id?'Update meeting':'Record a meeting'} description="Record the details and confirmation status. This does not send an invitation or reserve a booking." open={meeting} onClose={()=>setMeeting(null)}>{meeting&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await act({action:'save_meeting',...meeting,startsAt:new Date(meeting.starts).toISOString(),duration:Number(meeting.duration)}))setMeeting(null)}}><Field label="Meeting title"><Input required value={meeting.title} onChange={e=>setMeeting({...meeting,title:e.target.value})}/></Field><Field label="Product"><Choice value={meeting.productId||'none'} onChange={(v:string)=>setMeeting({...meeting,productId:v==='none'?'':v})} options={productOptions}/></Field><Field label={'Date and time · '+meeting.timezone}><Input type="datetime-local" required value={meeting.starts} onChange={e=>setMeeting({...meeting,starts:e.target.value})}/></Field><Field label="Duration (minutes)"><Input type="number" required min={5} max={720} value={meeting.duration} onChange={e=>setMeeting({...meeting,duration:e.target.value})}/></Field><Field label="Participants"><Input value={meeting.attendees} onChange={e=>setMeeting({...meeting,attendees:e.target.value})} placeholder="Names or email addresses"/></Field><Field label="Confirmation status" hint="Confirmed means you have independently received confirmation."><Choice value={meeting.status} onChange={(v:string)=>setMeeting({...meeting,status:v})} options={[{value:'unconfirmed',label:'Awaiting confirmation'},{value:'confirmed',label:'Confirmation received'},{value:'completed',label:'Meeting completed'},{value:'cancelled',label:'Cancelled'}]}/></Field><Field label="Agenda and notes"><Textarea value={meeting.notes} onChange={e=>setMeeting({...meeting,notes:e.target.value})}/><DictationButton label="meeting notes" value={meeting.notes} maxLength={4000} disabled={busy||!canWrite} onInsert={value=>{setMeeting({...meeting,notes:value})}}/></Field><div className="form-footer">{meeting.id&&<Button variant="outline" type="button" disabled={busy} onClick={()=>setConfirm({title:'Remove this recorded meeting?',description:'This only removes your personal record. No calendar invitation is cancelled.',danger:true,label:'Remove',run:async()=>{if(await act({action:'delete_meeting',id:meeting.id,revision:meeting.revision}))setMeeting(null)}})}>Remove</Button>}<Button disabled={busy||!canWrite}>Save meeting</Button></div></form>}</Modal>
 <Sheet open={!!help} onOpenChange={v=>!v&&setHelpId('')}><SheetContent className="run-sheet w-full sm:max-w-[620px] overflow-y-auto"><SheetHeader><SheetTitle>How can I help with this?</SheetTitle><SheetDescription>{help?.title||'Task guidance'}</SheetDescription></SheetHeader>{help&&<div className="sheet-body"><p className="prose-text">{help.notes||'Start by recording what you need to achieve.'}</p>{help.blocker&&<div className="notice warning compact"><AlertCircle size={18}/><span>Recorded blocker: {help.blocker}</span></div>}<div><h3 className="detail-title">Let’s work through the next steps</h3><p className="muted text-sm mb-4">Editable starting checklist. Tick a step when you have completed it.</p><div className="day-step-list">{parse(help.steps,[]).map((s:R,index:number)=><label className="check-row" key={s.id}><Checkbox checked={s.done} disabled={!canWrite||busy} onCheckedChange={v=>act({action:'save_steps',id:help.id,revision:help.revision,steps:parse(help.steps,[]).map((x:R,n:number)=>n===index?{...x,done:!!v}:x)})}/><span className={s.done?'line-through muted':''}>{s.title}</span></label>)}</div>{canWrite&&<form className="flex gap-2 mt-4" onSubmit={async e=>{e.preventDefault();if(await act({action:'save_steps',id:help.id,revision:help.revision,steps:[...parse(help.steps,[]),{title:stepTitle,done:false}]}))setStepTitle('')}}><Input aria-label="Add a step" value={stepTitle} maxLength={300} onChange={e=>setStepTitle(e.target.value)} placeholder="Add a specific next step"/><Button variant="outline" disabled={busy||!stepTitle.trim()||parse(help.steps,[]).length>=20}><Plus size={16}/></Button></form>}</div><section className="day-agent-help"><h3>Need more help?</h3><Choice value={helpKind} onChange={setHelpKind} options={helpKinds}/><p>Open an agent task with this task’s details. Submitted runs are shared with authorised workspace members.</p>{!workspaceData.provider.connected&&<p className="day-provider-note">Live AI is not connected. The checklist works now; an agent run would be a labelled scripted sample.</p>}<Button disabled={!canWrite||busy||!workspaceData.products.some((p:R)=>p.enabled)} onClick={()=>askAgent(help)}><Sparkles size={16}/>{workspaceData.provider.connected?'Ask the AI agent':'Preview sample agent flow'}</Button></section><div className="flex flex-wrap gap-2">{canWrite&&<><Button variant="outline" onClick={()=>{setHelpId('');editItem(help)}}>Edit task or blocker</Button><Button disabled={busy||help.status==='completed'||help.source_status==='completed'} onClick={()=>setStatus(help,'completed')}><Check size={16}/>Complete task</Button><Button variant="ghost" onClick={()=>setConfirm({title:'Remove this task from your plan?',description:'The linked workspace task, if any, will be kept.',danger:true,label:'Remove from my plan',run:async()=>{if(await act({action:'delete_item',id:help.id,revision:help.revision}))setHelpId('')}})}><Trash2 size={15}/>Remove</Button></>}</div></div>}</SheetContent></Sheet>
 <Modal title="Wrap up your day" description="Record what went well and anything that needs attention next. Unfinished tasks carry forward automatically." open={wrap} onClose={()=>setWrap(false)}><Field label="Your end-of-day notes"><Textarea rows={5} value={plan.review_note} onChange={e=>{dirty.current=true;setPlan({...plan,review_note:e.target.value})}} placeholder="Completed work, decisions, follow-ups and tomorrow’s priorities."/><DictationButton label="day review" value={plan.review_note} maxLength={4000} disabled={busy||!canWrite} onInsert={value=>{dirty.current=true;setPlan({...plan,review_note:value})}}/></Field><Button disabled={busy} onClick={async()=>{if(await savePlan())setWrap(false)}}>Save my day’s review</Button></Modal>
 <Modal title={draft?.title||'Follow-up draft'} description="Review and copy this message. It has not been sent." open={draft} onClose={()=>setDraft(null)}><Textarea rows={9} value={draft?.text||''} onChange={e=>setDraft({...draft,text:e.target.value})}/><div className="form-footer"><Button variant="outline" onClick={()=>copy(draft?.text||'')}><Copy size={15}/>Copy draft</Button><Button disabled={!canWrite||busy} onClick={()=>{const m=draft?.meeting;setDraft(null);newItem({title:'Confirm: '+m.title,notes:draft?.text,productId:m.product_id||'',priority:'high'})}}>Add follow-up task</Button></div></Modal>
 </div>
}
