'use client';
import {createContext,useContext,useEffect,useRef,useState,ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Mic,Square,Upload,Loader2,Check,Trash2,AlertCircle} from 'lucide-react';
import {speechLanguages,browserDictation,appendTranscript,MAX_AUDIO_BYTES,MAX_TRANSCRIPT_CHARS,audioFileType} from '@/lib/speech';
type Target={label:string;insert:(text:string)=>void;max:number};
const SpeechContext=createContext<((target:Target)=>(()=>void)|undefined)|null>(null);
export function DictationButton({label,value,onInsert,maxLength=MAX_TRANSCRIPT_CHARS,disabled=false}:{label:string;value:string;onInsert:(value:string)=>void;maxLength?:number;disabled?:boolean}){const open=useContext(SpeechContext),latest=useRef({value,onInsert});latest.current={value,onInsert};const release=useRef<(()=>void)|undefined>(undefined);useEffect(()=>()=>release.current?.(),[]);return <Button type="button" variant="ghost" size="sm" className="dictation-button" disabled={disabled||!open} aria-label={'Dictate '+label} onClick={e=>{e.preventDefault();e.stopPropagation();release.current=open?.({label,max:maxLength,insert:text=>latest.current.onInsert(appendTranscript(latest.current.value,text,maxLength))})}}><Mic size={14}/>Dictate</Button>}
export function SpeechProvider({children,workspaceId,scopeKey,canWrite,cloudAvailable}:{children:ReactNode;workspaceId?:string;scopeKey?:string;canWrite:boolean;cloudAvailable:boolean}){
 const [target,setTarget]=useState<Target|null>(null),[language,setLanguage]=useState('en-GB'),[transcript,setTranscript]=useState(''),[interim,setInterim]=useState(''),[state,setState]=useState<'starting'|'listening'|'stopping'|'idle'>('idle'),[error,setError]=useState(''),[supported,setSupported]=useState(false),[mode,setMode]=useState<'microphone'|'upload'>('microphone'),[file,setFile]=useState<File|null>(null),[uploading,setUploading]=useState(false),[service,setService]=useState<any>(null);
 const listener=useRef<ReturnType<typeof browserDictation>|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),upload=useRef<AbortController|null>(null),generation=useRef(0),currentTarget=useRef(target);currentTarget.current=target;
 const stopResources=()=>{generation.current++;listener.current?.abort();listener.current=null;if(timer.current)clearTimeout(timer.current);timer.current=null;upload.current?.abort();upload.current=null};
 const close=()=>{stopResources();setTarget(null);setState('idle');setTranscript('');setInterim('');setFile(null);setUploading(false);setError('');setService(null)};
 useEffect(()=>{setSupported(!!((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition));return()=>stopResources()},[]);
 useEffect(()=>{close()},[workspaceId,scopeKey,canWrite]);
 useEffect(()=>{if(!target)return;const controller=new AbortController();fetch('/api/speech',{signal:controller.signal}).then(async r=>{if(r.ok){const data=await r.json();if(!controller.signal.aborted)setService(data)}}).catch(()=>{});return()=>controller.abort()},[!!target,workspaceId]);
 useEffect(()=>{if(!target)return;const onHide=()=>{if(document.hidden){listener.current?.stop();if(timer.current)clearTimeout(timer.current)}};document.addEventListener('visibilitychange',onHide);return()=>document.removeEventListener('visibilitychange',onHide)},[!!target]);
 const open=(next:Target)=>{if(!canWrite)return;stopResources();setTranscript('');setInterim('');setError('');setFile(null);setState('idle');setUploading(false);setTarget(next);currentTarget.current=next;setMode(supported?'microphone':'upload');return()=>{if(currentTarget.current===next)close()}};
 const start=()=>{if(!canWrite||!target)return;stopResources();const seq=generation.current,Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition){setSupported(false);setError('Browser dictation is unavailable. You can use your device keyboard microphone or upload audio when transcription is connected.');return}const base=transcript.trim();setError('');setInterim('');listener.current=browserDictation(Recognition,language,{text:(final,partial)=>{if(seq!==generation.current)return;const text=[base,final].filter(Boolean).join('\n');if(text.length>MAX_TRANSCRIPT_CHARS){listener.current?.stop();setError('The transcript reached its length limit. Review the text already captured.');return}setTranscript(text);setInterim(partial)},state:s=>{if(seq!==generation.current)return;setState(s);if(s==='idle'){setInterim('');if(timer.current)clearTimeout(timer.current)}},error:message=>{if(seq===generation.current)setError(message)}});listener.current.start();timer.current=setTimeout(()=>{listener.current?.stop()},90000)};
 const transcribe=async()=>{if(!file||!canWrite||!target)return;setError('');stopResources();const seq=generation.current,controller=new AbortController();upload.current=controller;setUploading(true);try{if(file.size>MAX_AUDIO_BYTES||file.size===0||!audioFileType(file.name,file.type))throw Error('Choose a supported, non-empty audio file of up to 2 MB.');const body=new FormData();body.set('audio',file);body.set('language',language);const response=await fetch('/api/speech',{method:'POST',body,signal:controller.signal});const data=await response.json() as any;if(!response.ok)throw Error(data.error||'Transcription failed.');if(seq===generation.current)setTranscript(data.text)}catch(e:any){if(seq===generation.current&&e.name!=='AbortError')setError(e.message)}finally{if(seq===generation.current)setUploading(false)}};
 const active=state!=='idle',connected=service?.connected??cloudAvailable;
 return <SpeechContext.Provider value={open}>{children}<Dialog open={!!target} onOpenChange={value=>!value&&close()}><DialogContent className="speech-dialog max-h-[90vh] overflow-y-auto sm:max-w-[620px]"><DialogHeader><DialogTitle>Dictate {target?.label||'text'}</DialogTitle><DialogDescription>Speak or transcribe an audio file, then review the words before adding them. Nothing is submitted automatically.</DialogDescription></DialogHeader><div className="speech-mode"><Button type="button" variant={mode==='microphone'?'default':'outline'} size="sm" disabled={active||uploading} onClick={()=>setMode('microphone')}><Mic size={15}/>Microphone</Button><Button type="button" variant={mode==='upload'?'default':'outline'} size="sm" disabled={active||uploading} onClick={()=>setMode('upload')}><Upload size={15}/>Audio file</Button></div><label className="field"><span>Spoken language</span><select className="speech-language" value={language} disabled={active||uploading} onChange={e=>setLanguage(e.target.value)}>{speechLanguages.map(l=><option key={l.value} value={l.value}>{l.label}</option>)}</select><small className="muted">Availability and accuracy depend on the speech service and language.</small></label>
 {mode==='microphone'?<div className="speech-capture"><p className="speech-privacy">Your browser may send audio to its speech service. Omniqora does not store microphone audio. Listening starts only when you press Start.</p>{supported?<div className="flex gap-3 items-center"><Button type="button" disabled={uploading||!canWrite||state==='stopping'} onClick={()=>active?listener.current?.stop():start()}>{active?<Square size={16}/>:<Mic size={16}/>} {state==='starting'?'Cancel start':state==='listening'?'Stop listening':state==='stopping'?'Finishing…':'Start listening'}</Button><span role="status" aria-live="polite" className={active?'speech-listening':'muted'}>{state==='listening'?'Listening · maximum 90 seconds':state==='starting'?'Waiting for microphone permission':state==='stopping'?'Finishing transcript':'Microphone is off'}</span></div>:<p className="notice warning compact">This browser does not expose speech recognition. Use your phone’s keyboard microphone in the text field, open the site in a supported browser, or use audio-file transcription when connected.</p>}{interim&&<p className="speech-interim" aria-live="polite">Hearing: {interim}</p>}</div>:<div className="speech-capture"><p className="speech-privacy">Audio-file transcription sends your selected recording to OpenAI. Only upload audio you are authorised to use. Omniqora does not retain the audio or save this transcript until you insert and save it.</p>{connected?<><Input type="file" aria-label="Choose audio file" accept=".mp3,.mp4,.m4a,.mpeg,.mpga,.wav,.webm" disabled={uploading} onChange={e=>{setFile(e.target.files?.[0]||null);setError('')}}/><p className="muted text-sm">Up to 2 MB. MP3, MP4/M4A, MPEG, WAV or WebM. {service?.used!==undefined?`${service.used} of ${service.limit} monthly transcription requests used.`:''}</p><Button type="button" disabled={!file||uploading||!canWrite} onClick={transcribe}>{uploading?<Loader2 size={16} className="spin"/>:<Upload size={16}/>} {uploading?'Transcribing…':'Transcribe selected audio'}</Button></>:<p className="notice warning compact">Audio-file transcription is not connected. An owner must configure the OpenAI service. Browser dictation and your device’s keyboard microphone can be used without that connection.</p>}</div>}
 {error&&<div className="notice warning compact" role="alert"><AlertCircle size={17}/>{error}</div>}<label className="field"><span>Review transcript</span><Textarea rows={7} dir="auto" value={transcript} maxLength={MAX_TRANSCRIPT_CHARS} disabled={active||uploading} onChange={e=>setTranscript(e.target.value)} placeholder="Your words appear here. Check names, amounts, dates and quantities before inserting."/></label><p className="muted text-sm">{transcript.length.toLocaleString()} characters · inserted text is appended to your existing {target?.label.toLowerCase()||'text'}.</p><div className="form-footer"><Button type="button" variant="ghost" disabled={active||uploading||!transcript} onClick={()=>setTranscript('')}><Trash2 size={14}/>Clear</Button><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="button" disabled={active||uploading||!transcript.trim()||!canWrite} onClick={()=>{try{currentTarget.current?.insert(transcript);close()}catch(e:any){setError(e.message)}}}><Check size={16}/>Insert reviewed text</Button></div></DialogContent></Dialog></SpeechContext.Provider>
}
