import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const load=async path=>import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64'));
const {appendTranscript,recognitionText,browserDictation,audioFileType}=await load('lib/speech.ts');
const {callerPhone}=await load('lib/phone.ts');
const result=(text,isFinal)=>Object.assign([{transcript:text}],{isFinal});
test('recognition uses complete snapshots without duplicating final words or inserting interim words',()=>{const first=[result('Book a table',true),result('for',false)];assert.deepEqual(recognitionText(first),{final:'Book a table',interim:'for'});const next=[...first.slice(0,1),result('for four',true)];assert.deepEqual(recognitionText(next),{final:'Book a table for four',interim:''});assert.deepEqual(recognitionText(next),recognitionText(next));});
test('reviewed transcript appends safely and rejects overflow without truncation',()=>{assert.equal(appendTranscript('Existing note  ',' New words '),'Existing note\nNew words');assert.equal(appendTranscript('','اردو النص'),'اردو النص');assert.throws(()=>appendTranscript('12345','67890',10),/too long/);});
test('dictation stops on cancellation and ignores late recognition callbacks',()=>{let instance;class Recognition{constructor(){instance=this}start(){this.onstart()}stop(){this.onend()}abort(){this.aborted=true}}
 const states=[],texts=[];const session=browserDictation(Recognition,'ur-PK',{state:s=>states.push(s),text:(...v)=>texts.push(v),error:()=>assert.fail()});session.start();assert.equal(instance.lang,'ur-PK');assert.deepEqual(states,['starting','listening']);instance.onresult({results:[result('Hello',true)]});const late=instance.onresult;session.abort();late({results:[result('Stale content',true)]});assert.equal(instance.aborted,true);assert.equal(texts.length,1);assert.equal(instance.onresult,null);});
test('permission failures and start exceptions return to an idle state without automatic retries',()=>{let instance,starts=0;class Recognition{constructor(){instance=this}start(){starts++}abort(){}stop(){}}const states=[],errors=[];const session=browserDictation(Recognition,'en-GB',{state:s=>states.push(s),text:()=>assert.fail(),error:e=>errors.push(e)});session.start();instance.onerror({error:'not-allowed'});session.start();assert.equal(starts,1);assert.equal(states.at(-1),'idle');assert.match(errors[0],/denied/);class Broken extends Recognition{start(){throw Error('no microphone')}}const broken=browserDictation(Broken,'en-GB',{state:s=>states.push(s),text:()=>{},error:e=>errors.push(e)});broken.start();assert.equal(states.at(-1),'idle');assert.match(errors[1],/could not start/);});
test('audio uploads reject mismatched formats and accept documented browser audio types',()=>{assert(audioFileType('voice.webm','audio/webm;codecs=opus'));assert(audioFileType('VOICE.M4A','audio/mp4'));assert(!audioFileType('voice.html','audio/mpeg'));assert(!audioFileType('voice.mp3','text/html'));assert(!audioFileType('voice.ogg','audio/ogg'));});
test('caller numbers normalise international formatting without guessing local countries or extensions',()=>{assert.deepEqual(callerPhone('0044 20 7946 0123'),{state:'number',number:'+442079460123'});assert.equal(callerPhone('+44 (20) 7946-0123').number,'+442079460123');for(const v of ['',null,'anonymous','WITHHELD','private'])assert.equal(callerPhone(v).state,'withheld');for(const v of ['02079460123','+44 20 7946 0123 ext 8','+0012345','+123','+1;DROP TABLE','+442079460123,+33123456789'])assert.equal(callerPhone(v).state,'invalid');assert.notEqual(callerPhone('+442079460123').number,callerPhone('+492079460123').number);});

test('a delayed microphone permission event cannot restart listening after cancellation',()=>{let instance;class Recognition{constructor(){instance=this}start(){}stop(){}abort(){this.aborted=true}}const states=[];const session=browserDictation(Recognition,'en-GB',{state:s=>states.push(s),text:()=>assert.fail(),error:()=>{}});session.start();session.stop();instance.onstart();assert.deepEqual(states,['starting','stopping','idle']);assert.equal(instance.aborted,true);session.abort()});
