import {test,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import ts from 'typescript';
const root=process.cwd();
const moduleURL=(path,replacements=[])=>{let source=readFileSync(resolve(root,path),'utf8');for(const [a,b] of replacements)source=source.replaceAll(a,b).replaceAll(a.replaceAll("'",'"'),b);const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return 'data:text/javascript;base64,'+Buffer.from(js).toString('base64')};
const catalog=moduleURL('lib/catalog.ts'),policyURL=moduleURL('lib/policy.ts'),approval=moduleURL('lib/approval.ts');
const serverURL=moduleURL('lib/server.ts',[
["import {env} from 'cloudflare:workers';","const env=globalThis.testContext.env;"],
["import {cookies} from 'next/headers';","const cookies=async()=>({get:()=>({value:globalThis.testContext.cookie})});"],
["import {getChatGPTUser} from '@/app/chatgpt-auth';","const getChatGPTUser=async()=>globalThis.testContext.user;"],
["from './catalog'","from '"+catalog+"'"],["from './policy'","from '"+policyURL+"'"],["from './approval'","from '"+approval+"'"]]);
globalThis.testContext={env:{},user:null,cookie:''};
const server=await import(serverURL),policy=await import(policyURL),analytics=await import(moduleURL('lib/analytics.ts'));
const runnerURL=moduleURL('lib/runner.ts',[["import {env} from 'cloudflare:workers';","const env=globalThis.testContext.env;"],["from 'zod'","from '"+import.meta.resolve('zod')+"'"],["from './catalog'","from '"+catalog+"'"],["from './policy'","from '"+policyURL+"'"],["from './server'","from '"+serverURL+"'"]]);
const runner=await import(runnerURL);
const outbox=await import(moduleURL('app/api/integrations/tasks/route.ts',[["from '@/lib/server'","from '"+serverURL+"'"]]));
const journey=await import(moduleURL('app/api/journeys/route.ts',[["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/policy'","from '"+policyURL+"'"],["from '@/lib/journey-steps'","from '"+moduleURL('lib/journey-steps.ts')+"'"]]));
const dayURL=moduleURL('lib/day.ts'),analyticsURL=moduleURL('lib/analytics.ts');
const planningURL=moduleURL('lib/planning.ts',[["from './analytics'","from '"+analyticsURL+"'"],["from './day'","from '"+dayURL+"'"]]);
const phoneURL=moduleURL('lib/phone.ts'),speechURL=moduleURL('lib/speech.ts');
const customersURL=moduleURL('lib/customers.ts',[["from './server'","from '"+serverURL+"'"],["from './phone'","from '"+phoneURL+"'"],["from './policy'","from '"+policyURL+"'"]]);
const customers=await import(customersURL);
const receptionURL=moduleURL('lib/reception.ts',[["from './phone'","from '"+phoneURL+"'"],["from './customers'","from '"+customersURL+"'"],["from './server'","from '"+serverURL+"'"],["from './policy'","from '"+policyURL+"'"]]);
const dayFns=await import(dayURL),planning=await import(planningURL),reception=await import(receptionURL);
const dayApi=await import(moduleURL('app/api/day/route.ts',[["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/policy'","from '"+policyURL+"'"],["from '@/lib/day'","from '"+dayURL+"'"]]));
const receptionApi=await import(moduleURL('app/api/reception/route.ts',[["import {env} from 'cloudflare:workers';","const env=globalThis.testContext.env;"],["from '@/lib/reception-status'","from '"+moduleURL('lib/reception-status.ts')+"'"],["from '@/lib/customers'","from '"+customersURL+"'"],["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/policy'","from '"+policyURL+"'"],["from '@/lib/reception'","from '"+receptionURL+"'"]]));
const receptionConnector=await import(moduleURL('app/api/integrations/reception/route.ts',[["from '@/lib/customers'","from '"+customersURL+"'"],["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/reception'","from '"+receptionURL+"'"]]));
const planningApi=await import(moduleURL('app/api/planning/route.ts',[["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/policy'","from '"+policyURL+"'"],["from '@/lib/planning'","from '"+planningURL+"'"]]));
const customerApi=await import(moduleURL('app/api/customers/route.ts',[["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/customers'","from '"+customersURL+"'"]]));
const customerConnector=await import(moduleURL('app/api/integrations/customers/route.ts',[["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/customers'","from '"+customersURL+"'"],["from '@/lib/reception'","from '"+receptionURL+"'"]]));
const speechApi=await import(moduleURL('app/api/speech/route.ts',[["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/speech'","from '"+speechURL+"'"],["import {env} from 'cloudflare:workers';","const env=globalThis.testContext.env;"]]));
const apiRequest=(body,path='/api/day',headers={})=>new Request('https://example.com'+path,{method:'POST',headers:{'Content-Type':'application/json',origin:'https://example.com',...headers},body:JSON.stringify(body)});
const dayRequest=()=>new Request('https://example.com/api/day?date=2026-09-15&timezone=Europe%2FLondon');
const personalTask=(extra={})=>({action:'save_item',title:'Review the work',productId:'p1',day:'2026-09-15',dueDate:'2026-09-15',priority:'normal',notes:'Private notes',blocker:'',...extra});
const enableReception=()=>receptionApi.POST(apiRequest({action:'settings',productId:'p1',enabled:true,instructions:'Capture the request.',escalation:'Duty manager',revision:0},'/api/reception'));
let sqlite;
function insert(table,row){const keys=Object.keys(row);sqlite.prepare('INSERT INTO '+table+'('+keys.join(',')+') VALUES('+keys.map(()=>'?').join(',')+')').run(...keys.map(k=>row[k]));}
function count(table,where='1=1'){return sqlite.prepare('SELECT COUNT(*) n FROM '+table+' WHERE '+where).get().n;}
function fixtureProduct(id,w){insert('products',{id,workspace_id:w,slug:id,name:id,sector:'Test',description:'Test product',color:'#123456',template_id:'intake',created_at:'2026-09-15'});}
beforeEach(()=>{sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
 function prepared(sql,args=[]){return {bind(...values){return prepared(sql,values)},async all(){return {results:sqlite.prepare(sql).all(...args)}},async first(){return sqlite.prepare(sql).get(...args)||null},async run(){return this._run()},_run(){const result=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(result.changes)}}}}}
 globalThis.testContext.env.DB={prepare:prepared,async batch(statements){sqlite.exec('BEGIN');try{const result=statements.map(s=>s._run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};delete globalThis.testContext.env.OPENAI_API_KEY;delete globalThis.testContext.env.OPENAI_TRANSCRIBE_MODEL;delete globalThis.testContext.env.SPEECH_MONTHLY_LIMIT;
 globalThis.testContext.user={userId:'owner1',email:'owner@example.com',displayName:'Owner'};globalThis.testContext.cookie='w1';
 insert('workspaces',{id:'w1',owner_id:'owner1',name:'Company One',created_at:'2026-09-15'});insert('workspaces',{id:'w2',owner_id:'owner2',name:'Company Two',created_at:'2026-09-15'});fixtureProduct('p1','w1');fixtureProduct('p2','w2');
});
afterEach(()=>sqlite.close());
test('daily dates respect local midnight and reject impossible dates and zones',()=>{assert.equal(dayFns.validDay('2026-02-30'),false);assert.equal(dayFns.validDay('2024-02-29'),true);assert.equal(dayFns.validZone('Invented/Zone'),false);assert.equal(dayFns.localDay('2026-09-14T23:30:00Z','Europe/London'),'2026-09-15');assert.equal(dayFns.offsetDay('2026-03-01',-1),'2026-02-28');});
test('daily overview carries work forward, ranks overdue tasks and follows source completion',()=>{const item={created_at:'2026-09-10',updated_at:'2026-09-15T10:00:00Z',status:'planned',scheduled_date:'2026-09-14',priority:'normal'};const overview=dayFns.dayOverview([{...item,id:'ordinary'},{...item,id:'late',due_date:'2026-09-14'},{...item,id:'done',source_status:'completed',source_updated_at:'2026-09-14T23:30:00Z'},{...item,id:'future',scheduled_date:'2026-09-20'}],[{id:'meeting',starts_at:'2026-09-14T23:30:00Z',status:'unconfirmed'}],'2026-09-15','Europe/London');assert.deepEqual(overview.active.map(r=>r.id),['late','ordinary']);assert.equal(overview.completed[0].id,'done');assert.equal(overview.upcoming[0].id,'future');assert.equal(overview.unconfirmed.length,1);assert.equal(overview.todayMeetings.length,1);});
test('personal plans are isolated between users inside the same company',async()=>{const a=await dayApi.POST(apiRequest(personalTask()));assert.equal(a.status,200);const {id}=await a.json();let response=await dayApi.POST(apiRequest({action:'save_plan',day:'2026-09-15',timezone:'Europe/London',revision:0,goals:'Private priority',helpItemIds:[id]}));assert.equal(response.status,200);insert('members',{id:'m3',workspace_id:'w1',user_id:'coworker',email:'coworker@example.com',role:'operator',created_at:'2026-09-15'});globalThis.testContext.user={userId:'coworker',email:'coworker@example.com',displayName:'Coworker'};const data=await (await dayApi.GET(dayRequest())).json();assert.equal(data.items.length,0);assert.equal(data.plan.revision,0);response=await dayApi.POST(apiRequest({action:'item_status',id,revision:1,status:'completed'}));assert.equal(response.status,404);response=await dayApi.POST(apiRequest({action:'save_plan',day:'2026-09-15',timezone:'Europe/London',revision:0,helpItemIds:[id]}));assert.equal(response.status,404);assert.equal(count('day_items',"status='planned'"),1);});
test('daily plan and task updates reject stale revisions and cross-company product IDs',async()=>{assert.equal((await dayApi.POST(apiRequest(personalTask({productId:'p2'})))).status,404);const plan={action:'save_plan',day:'2026-09-15',timezone:'Europe/London',revision:0,goals:'First plan'};assert.equal((await dayApi.POST(apiRequest(plan))).status,200);assert.equal((await dayApi.POST(apiRequest({...plan,goals:'Stale plan'}))).status,409);assert.equal(sqlite.prepare('SELECT goals FROM daily_plans').get().goals,'First plan');const {id}=await (await dayApi.POST(apiRequest(personalTask()))).json();assert.equal((await dayApi.POST(apiRequest({action:'item_status',id,revision:1,status:'in_progress'}))).status,200);assert.equal((await dayApi.POST(apiRequest({action:'item_status',id,revision:1,status:'completed'}))).status,409);assert.equal(sqlite.prepare('SELECT status FROM day_items').get().status,'in_progress');});
test('only open live tasks can be imported and linked completion is atomic under races',async()=>{const r=await userRun();await runner.executeRun('w1','owner',r.id);for(const a of sqlite.prepare('SELECT * FROM actions').all())await server.decide('w1','owner',a.id,'approved','');const tasks=sqlite.prepare('SELECT * FROM tasks').all(),source=tasks.find(t=>t.status==='open'),draft=tasks.find(t=>t.status==='draft');const importBody={action:'import_task',day:'2026-09-15',taskId:source.id};assert.equal((await dayApi.POST(apiRequest(importBody))).status,404);sqlite.prepare("UPDATE runs SET kind='live' WHERE id=?").run(r.id);assert.equal((await dayApi.POST(apiRequest({...importBody,taskId:draft.id}))).status,404);const one=await (await dayApi.POST(apiRequest(importBody))).json(),two=await (await dayApi.POST(apiRequest(importBody))).json();assert.equal(one.id,two.id);assert.equal(count('day_items'),1);const update={action:'item_status',id:one.id,revision:1,status:'completed',completeSource:true};const responses=await Promise.all([dayApi.POST(apiRequest(update)),dayApi.POST(apiRequest(update))]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);assert.equal(sqlite.prepare('SELECT status FROM tasks WHERE id=?').get(source.id).status,'completed');assert.equal(count('audit',"event='day.task_status'"),1);});
test('linked task completion rolls back the personal status if shared storage fails',async()=>{const r=await userRun();await runner.executeRun('w1','owner',r.id);const action=sqlite.prepare("SELECT * FROM actions WHERE type='internal_task'").get();await server.decide('w1','owner',action.id,'approved','');sqlite.prepare("UPDATE runs SET kind='live' WHERE id=?").run(r.id);const source=sqlite.prepare('SELECT * FROM tasks').get();const {id}=await (await dayApi.POST(apiRequest({action:'import_task',day:'2026-09-15',taskId:source.id}))).json();sqlite.exec("CREATE TRIGGER fail_completion BEFORE UPDATE ON tasks BEGIN SELECT RAISE(ABORT,'forced completion failure'); END");const response=await dayApi.POST(apiRequest({action:'item_status',id,revision:1,status:'completed',completeSource:true}));assert.equal(response.status,500);assert.equal(sqlite.prepare('SELECT status FROM day_items').get().status,'planned');assert.equal(count('audit',"event='day.task_status'"),0);});
test('recorded meetings persist confirmation state without a calendar connection',async()=>{const body={action:'save_meeting',productId:'p1',title:'Planning review',startsAt:'2026-09-15T09:00:00Z',timezone:'Europe/London',duration:30,attendees:'Team',status:'unconfirmed',notes:'Review goals'};let response=await dayApi.POST(apiRequest(body));assert.equal(response.status,200);const {id}=await response.json();let data=await (await dayApi.GET(dayRequest())).json();assert.equal(data.overview.unconfirmed.length,1);assert.equal(data.calendarConnected,false);response=await dayApi.POST(apiRequest({...body,id,revision:1,status:'confirmed'}));assert.equal(response.status,200);data=await (await dayApi.GET(dayRequest())).json();assert.equal(data.overview.unconfirmed.length,0);assert.equal(data.overview.todayMeetings[0].status,'confirmed');});
test('reception intake is disabled by default and retry keys do not duplicate requests',async()=>{const b={kind:'order',channel:'phone',customer:'Customer',contact:'',summary:'Two meals for collection.'};await assert.rejects(()=>reception.receiveReception('w1','p1',b,'key','owner'),e=>e.status===409);assert.equal((await enableReception()).status,200);const a=await reception.receiveReception('w1','p1',b,'key','owner'),again=await reception.receiveReception('w1','p1',b,'key','owner');assert.equal(a.id,again.id);assert.equal(count('reception_items'),1);await assert.rejects(()=>reception.receiveReception('w1','p1',{...b,summary:'Different order'},'key','owner'),e=>e.status===409);assert.equal((await (await dayApi.GET(dayRequest())).json()).reception.orders,1);});
test('online orders queue without a model and require verified source and KDS receipts',async()=>{await enableReception();const r=await reception.receiveReception('w1','p1',{kind:'order',channel:'online',customer:'Customer',summary:'Order request',contact:''},'online1','source',true);assert.equal(r.status,'queued');assert.equal(count('runs'),0);await assert.rejects(()=>reception.advanceReception('w1','p1',{id:r.id,status:'accepted',sourceRef:'order1'},'operator'),e=>e.status===403);await assert.rejects(()=>reception.advanceReception('w1','p1',{id:r.id,status:'accepted',sourceRef:'order1',receipt:{accepted:true}},'app',true),e=>e.status===400);const accepted={id:r.id,status:'accepted',sourceRef:'order1',receipt:{accepted:true,priceValidated:true,availabilityValidated:true,paymentState:'paid'}};assert.equal((await reception.advanceReception('w1','p1',accepted,'app',true)).status,'accepted');assert.equal((await reception.advanceReception('w1','p1',accepted,'app',true)).revision,2);await assert.rejects(()=>reception.advanceReception('w1','p1',{id:r.id,status:'delivered',sourceRef:'wrong',receipt:{kdsAcknowledged:true}},'app',true),e=>e.status===409);assert.equal((await reception.advanceReception('w1','p1',{id:r.id,status:'delivered',sourceRef:'order1',receipt:{kdsAcknowledged:true}},'app',true)).status,'delivered');assert.equal((await (await dayApi.GET(dayRequest())).json()).reception.orders,0);});
test('booking confirmation requires a reserved slot and cross-product receipts are refused',async()=>{await enableReception();const r=await reception.receiveReception('w1','p1',{kind:'booking',channel:'online',customer:'Customer',summary:'Friday table',contact:''},'b1','app',true);await assert.rejects(()=>reception.advanceReception('w2','p2',{id:r.id,status:'confirmed',sourceRef:'b1',receipt:{slotReserved:true}},'other',true),e=>e.status===404);await assert.rejects(()=>reception.advanceReception('w1','p1',{id:r.id,status:'confirmed',sourceRef:'b1'},'app',true),e=>e.status===400);assert.equal((await reception.advanceReception('w1','p1',{id:r.id,status:'confirmed',sourceRef:'b1',receipt:{slotReserved:true}},'app',true)).status,'confirmed');});
test('reception connector scopes product and rejects stale signed-in events',async()=>{await enableReception();const token=server.randomToken();insert('integrations',{id:'rec-key',workspace_id:'w1',product_id:'p1',name:'Order app',token_hash:await server.tokenHash(token),created_at:'2026-09-15'});const body={action:'receive',kind:'order',channel:'online',customer:'Customer',summary:'New order',contact:'',productId:'p2'};let headers={authorization:'Bearer '+token,'idempotency-key':'evt-1','x-event-timestamp':'1'};assert.equal((await receptionConnector.POST(apiRequest(body,'/api/integrations/reception',headers))).status,401);headers['x-event-timestamp']=String(Date.now());const result=await receptionConnector.POST(apiRequest(body,'/api/integrations/reception',headers));assert.equal(result.status,202);assert.equal((await result.json()).item.product_id,'p1');const out=await (await receptionConnector.GET(new Request('https://example.com/api/integrations/reception',{headers}))).json();assert.equal(out.items.length,1);assert.equal((await receptionConnector.GET(new Request('https://example.com/api/integrations/reception'))).status,401);});
test('planning CSV rejects invalid values, duplicate keys and ambiguous balance periods',()=>{const t=planning.csvTemplate('financials');assert.throws(()=>planning.parsePlanning('financials',t+'2026-09-01,2026-09-30,London,GBP,100,Cash,asset,100.00'));assert.throws(()=>planning.parsePlanning('financials',t+'2026-09-01,2026-09-30,London,GBP,100,Sales,revenue,10.999'));const line='2026-09-01,2026-09-30,London,GBP,100,Sales,revenue,-10.25\n';assert.equal(planning.parsePlanning('financials',t+line)[0].data.amount,-1025);assert.throws(()=>planning.parsePlanning('financials',t+line+line));assert.throws(()=>planning.parsePlanning('cashflow',planning.csvTemplate('cashflow')+'2026-02-30,London,GBP,R1,in,sales,10,expected'));});
test('P&L preserves missing costs and separates balance snapshots and currencies',()=>{const base={period_start:'2026-09-01',period_end:'2026-09-30',location:'London',currency:'GBP'};const entries=planning.pnlCategories.map(category=>({...base,category,amount:category==='revenue'?100000:1000}));const balance=planning.balanceCategories.map(category=>({...base,period_start:'2026-09-30',category,amount:{asset:50000,liability:20000,equity:30000}[category]}));const out=planning.accountSummary([...entries,...balance,...balance.map(r=>({...r,period_start:'2026-08-31',period_end:'2026-08-31',amount:999999})),{...entries[0],currency:'USD',amount:999999}],'2026-09-01','2026-09-30','GBP');assert.equal(out.net,94000);assert.equal(out.balanceDifference,0);assert.equal(out.totals.asset,50000);assert.equal(planning.accountSummary(entries.filter(r=>r.category!=='tax'),'2026-09-01','2026-09-30','GBP').net,null);});
test('weekday forecast abstains on gaps and backtests against held-out dates',()=>{const asOf='2026-09-15',sales=Array.from({length:56},(_,i)=>({date:dayFns.offsetDay(asOf,-56+i),location:'London',gross:10000,refunds:0}));const output=planning.salesForecast(sales,asOf,7,20);assert.equal(output.ready,true);assert.equal(output.total,84000);assert.equal(output.mae,0);assert.equal(output.lower,71400);assert.equal(planning.salesForecast(sales.slice(0,-1),asOf,7).ready,false);assert.equal(planning.salesForecast([...sales,{date:'2026-09-14',location:'Leeds',gross:10000,refunds:0}],asOf,7).ready,false);assert.equal(planning.salesForecast(sales.slice(-28),asOf,7).mae,null);});
test('cash projection excludes paid rows, delays receipts and exposes temporary shortfalls',()=>{const rows=[{due_date:'2026-09-14',direction:'out',amount:12000,status:'expected'},{due_date:'2026-09-16',direction:'in',amount:10000,status:'expected'},{due_date:'2026-09-15',direction:'in',amount:999999,status:'paid'}];const p=planning.cashProjection(rows,'2026-09-15',7,10000,2);assert.equal(p.lowest,-2000);assert.equal(p.firstShortfall,'2026-09-15');assert.equal(p.closing,8000);assert.equal(p.points.find(r=>r.date==='2026-09-18').incoming,10000);assert.equal(p.overdue,1);});
test('inventory uses one snapshot, FEFO, independent units and explicit missing costs',()=>{const lot={as_of:'2026-09-15',location:'London',sku:'A',item_name:'Food',unit:'kg',on_order:0,avg_daily_usage:2,lead_days:3,safety_stock:5,currency:'GBP',unit_cost:100};const stock=[{...lot,lot:'early',on_hand:10,expiry_date:'2026-09-15'},{...lot,lot:'later',on_hand:4,expiry_date:'2026-09-16',unit_cost:null},{...lot,lot:'expired',on_hand:20,expiry_date:'2026-09-14'},{...lot,as_of:'2026-09-01',lot:'old',on_hand:500,expiry_date:''}];const [p]=planning.inventoryPlan(stock,'2026-09-15');assert.equal(p.onHand,14);assert.equal(p.expired,20);assert.equal(p.reorder,0);assert.equal(p.daysCover,7);assert.equal(p.lots.find(r=>r.lot==='early').atRisk,8);assert.equal(p.lots.find(r=>r.lot==='later').atRisk,2);assert.equal(p.lots.find(r=>r.lot==='later').riskValue,null);const bad=planning.inventoryPlan([...stock,{...lot,lot:'conflict',on_hand:2,expiry_date:'',avg_daily_usage:5}],'2026-09-15')[0];assert.equal(bad.consistent,false);assert.equal(bad.reorder,null);});
test('workforce handles overnight coverage and flags skills without employment decisions',()=>{const out=planning.workforcePlan([{date:'2026-09-15',location:'London',team:'Night',start:'22:00',end:'06:00',required_staff:3,scheduled_staff:2,required_skills:'First aid;Manager',confirmed_skills:'first aid',status:'draft'}],'2026-09-15',7);assert.equal(out[0].duration,8);assert.equal(out[0].gap,-1);assert.equal(out[0].scheduledHours,16);assert.deepEqual(out[0].missingSkills,['manager']);const compliance=planning.compliancePlan([{due_date:'2026-09-14',status:'open'},{due_date:'2026-09-10',status:'complete',evidence_ref:''}],'2026-09-15');assert.deepEqual(compliance.map(r=>r.flag),['Evidence missing','Overdue']);});
test('planning imports upsert without duplicates and people records are admin-only',async()=>{const financial=planning.csvTemplate('financials')+'2026-09-01,2026-09-30,London,GBP,100,Sales,revenue,100.00';const body={action:'import',productId:'p1',kind:'financials',csv:financial};assert.equal((await planningApi.POST(apiRequest(body,'/api/planning'))).status,200);assert.equal((await planningApi.POST(apiRequest({...body,csv:financial.replace('100.00','200.00')},'/api/planning'))).status,200);assert.equal(count('planning_records'),1);assert.equal(JSON.parse(sqlite.prepare('SELECT data FROM planning_records').get().data).amount,20000);const shifts=planning.csvTemplate('shifts')+'2026-09-15,London,Kitchen,09:00,17:00,3,2,Names,manager,manager,draft';assert.equal((await planningApi.POST(apiRequest({action:'import',productId:'p1',kind:'shifts',csv:shifts},'/api/planning'))).status,200);insert('members',{id:'op',workspace_id:'w1',user_id:'operator',email:'op@example.com',role:'operator',created_at:'2026-09-15'});globalThis.testContext.user={userId:'operator',email:'op@example.com',displayName:'Operator'};const view=await (await planningApi.GET(new Request('https://example.com/api/planning?productId=p1'))).json();assert.equal(view.peopleAccess,false);assert.equal(view.records.length,1);assert.equal((await planningApi.POST(apiRequest({action:'import',productId:'p1',kind:'shifts',csv:shifts},'/api/planning'))).status,403);assert.equal((await planningApi.GET(new Request('https://example.com/api/planning?productId=p2'))).status,404);});
test('viewers cannot write day, reception or planning data',async()=>{insert('members',{id:'v',workspace_id:'w1',user_id:'viewer',email:'v@example.com',role:'viewer',created_at:'2026-09-15'});globalThis.testContext.user={userId:'viewer',email:'v@example.com',displayName:'Viewer'};assert.equal((await dayApi.POST(apiRequest(personalTask()))).status,403);assert.equal((await receptionApi.POST(apiRequest({action:'receive',productId:'p1'},'/api/reception'))).status,403);assert.equal((await planningApi.POST(apiRequest({action:'import',productId:'p1'},'/api/planning'))).status,403);});
const userRun=async(extra={})=>server.createRun({id:'w1',paused:0},'owner@example.com',{productId:'p1',kind:'sample',input:'Review the onboarding checklist.',...extra});
test('approval policy limits automatic work and isolates samples',()=>{assert.equal(policy.actionStatus('automatic','internal_task','live'),'approved');assert.equal(policy.actionStatus('automatic','draft','live'),'pending');assert.equal(policy.actionStatus('automatic','internal_task','sample'),'pending');assert.equal(policy.actionStatus('assist','internal_task','live'),'draft');});
test('source verification rejects empty and invented quotes',()=>{assert.deepEqual(policy.validateSourceQuotes([{source:'brief',quote:''},{source:'brief',quote:'real text'},{source:'brief',quote:'invented'}],{brief:'This is real text.'}).map(x=>x.verified),[false,true,false]);});
test('EPOS values use cents; incomplete costs remain unknown; bad rows fail',()=>{const values=analytics.parseSales('date,location,currency,gross_sales,refunds,orders,cost_of_goods,labour_cost\n2026-09-14,"London, Central",GBP,10.10,0.10,2,3.00,2.00');assert.equal(values[0].gross,1010);assert.equal(analytics.summarizeSales(values).contribution,500);assert.equal(analytics.summarizeSales([{...values[0],cogs:null}]).contribution,null);assert.throws(()=>analytics.parseSales(analytics.salesTemplate.replace('1200.00','1.999')));assert.throws(()=>analytics.parseSales(analytics.salesTemplate.replace('2026-09-14','2026-02-30')));assert.throws(()=>analytics.parseSales(analytics.salesTemplate+analytics.salesTemplate.split('\n')[1]));});
test('forged workspace cookie cannot grant company access',async()=>{globalThis.testContext.cookie='w2';const {w,accessible}=await server.workspace();assert.equal(w.id,'w1');assert.equal(accessible.length,1);});
test('viewer cannot perform operator or admin actions',()=>assert.throws(()=>server.requireRole({role:'viewer'},['owner','admin','operator']),e=>e.status===403));
test('cross-company products and evidence cannot be attached to a run',async()=>{await assert.rejects(()=>userRun({productId:'p2'}),e=>e.status===404);insert('documents',{id:'foreign',workspace_id:'w2',product_id:'p2',name:'Private',object_key:'secret',mime:'text/plain',size:10,created_at:'2026-09-15'});await assert.rejects(()=>userRun({documentIds:['foreign']}),e=>e.status===403);assert.equal(count('runs'),0);});
test('same event key creates only one run',async()=>{const a=await userRun({idempotencyKey:'same-event'}),b=await userRun({idempotencyKey:'same-event'});assert.equal(a.id,b.id);assert.equal(count('runs'),1);});
test('sample workflow requires review, creates tasks once and completes the run',async()=>{const r=await userRun();const result=await runner.executeRun('w1','owner',r.id);assert.equal(result.status,'awaiting_approval');assert.equal(count('tasks'),0);const actions=sqlite.prepare('SELECT * FROM actions').all();await server.decide('w1','owner',actions[0].id,'approved','Reviewed');assert.equal(count('tasks'),1);await assert.rejects(()=>server.decide('w1','owner',actions[0].id,'approved','Again'),e=>e.status===409);await server.decide('w1','owner',actions[1].id,'approved','Reviewed');assert.equal(count('tasks'),2);assert.equal(sqlite.prepare('SELECT status FROM runs WHERE id=?').get(r.id).status,'completed');assert.equal(count('usage'),0);});
test('approval and task delivery roll back together if task creation fails',async()=>{const r=await userRun();await runner.executeRun('w1','owner',r.id);const a=sqlite.prepare('SELECT * FROM actions LIMIT 1').get();sqlite.exec("CREATE TRIGGER fail_task BEFORE INSERT ON tasks BEGIN SELECT RAISE(ABORT,'forced storage failure'); END");await assert.rejects(()=>server.decide('w1','owner',a.id,'approved',''));assert.equal(sqlite.prepare('SELECT status FROM actions WHERE id=?').get(a.id).status,'pending');assert.equal(count('audit',"event='action.approved'"),0);assert.equal(count('tasks'),0);});
test('competing approvals create one task and one decision record',async()=>{const r=await userRun();await runner.executeRun('w1','owner',r.id);const a=sqlite.prepare('SELECT * FROM actions LIMIT 1').get();const results=await Promise.allSettled([server.decide('w1','first',a.id,'approved',''),server.decide('w1','second',a.id,'approved','')]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(count('tasks'),1);assert.equal(count('audit',"event='action.approved'"),1);});
test('paused workspace refuses approval and other tenants cannot approve',async()=>{const r=await userRun();await runner.executeRun('w1','owner',r.id);const a=sqlite.prepare('SELECT * FROM actions LIMIT 1').get();await assert.rejects(()=>server.decide('w2','other',a.id,'approved',''),e=>e.status===404);sqlite.exec("UPDATE workspaces SET paused=1 WHERE id='w1'");await assert.rejects(()=>server.decide('w1','owner',a.id,'approved',''),e=>e.status===409);assert.equal(count('tasks'),0);await server.decide('w1','owner',a.id,'rejected','Paused');});
test('live runs require provider configuration',async()=>{await assert.rejects(()=>userRun({kind:'live'}),e=>e.status===409);});
test('outbox excludes samples and drafts, scopes product and verifies acknowledgements',async()=>{const r=await userRun();await runner.executeRun('w1','owner',r.id);for(const a of sqlite.prepare('SELECT * FROM actions').all())await server.decide('w1','owner',a.id,'approved','');const token=server.randomToken();insert('integrations',{id:'i1',workspace_id:'w1',product_id:'p1',name:'Test key',token_hash:await server.tokenHash(token),created_at:'2026-09-15'});const headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};assert.deepEqual((await (await outbox.GET(new Request('https://example.com/api/integrations/tasks',{headers}))).json()).tasks,[]);sqlite.prepare("UPDATE runs SET kind='live' WHERE id=?").run(r.id);sqlite.exec("UPDATE tasks SET status='open'");const tasks=(await (await outbox.GET(new Request('https://example.com/api/integrations/tasks',{headers}))).json()).tasks;assert.equal(tasks.length,1);const response=await outbox.POST(new Request('https://example.com/api/integrations/tasks',{method:'POST',headers,body:JSON.stringify({id:tasks[0].id,status:'completed'})}));assert.equal(response.status,200);assert.equal((await (await outbox.GET(new Request('https://example.com/api/integrations/tasks',{headers}))).json()).tasks.length,0);});
test('journey cannot advance before review and task completion',async()=>{insert('journeys',{id:'j1',workspace_id:'w1',product_id:'p1',title:'Onboarding',goal:'Gather client information',kind:'sample',status:'active',created_at:'2026-09-15',updated_at:'2026-09-15'});const req=b=>new Request('https://example.com/api/journeys',{method:'POST',headers:{'Content-Type':'application/json',origin:'https://example.com'},body:JSON.stringify(b)});let response=await journey.POST(req({action:'complete_step',id:'j1',outcome:'Reviewed the information.'}));assert.equal(response.status,409);response=await journey.POST(req({action:'run_step',id:'j1',context:'Client needs a checklist.'}));const {run}=await response.json();await runner.executeRun('w1','owner',run.id);for(const a of sqlite.prepare('SELECT * FROM actions').all())await server.decide('w1','owner',a.id,'approved','');response=await journey.POST(req({action:'complete_step',id:'j1',outcome:'Reviewed the information.'}));assert.equal(response.status,409);sqlite.exec("UPDATE tasks SET status='completed'");response=await journey.POST(req({action:'complete_step',id:'j1',outcome:'Reviewed the information and completed both tasks.'}));assert.equal(response.status,200);assert.equal(sqlite.prepare("SELECT current_step FROM journeys WHERE id='j1'").get().current_step,1);});

test('live tool loop records usage and creates only permitted automatic tasks',async()=>{globalThis.testContext.env.OPENAI_API_KEY='test-key-not-real';sqlite.exec("UPDATE products SET mode='automatic' WHERE id='p1'");const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);calls++;const fn=calls===1?'read_evidence':calls===2?'list_open_tasks':calls===3?'propose_internal_task':null;return Response.json({status:'completed',usage:{input_tokens:10,output_tokens:5},output:fn?[{type:'function_call',call_id:'call-'+calls,name:fn,arguments:fn==='propose_internal_task'?JSON.stringify({title:'Review intake',body:'Check the supplied onboarding checklist.',assignee:'Owner'}):'{}'}]:[{type:'message',content:[{type:'output_text',text:JSON.stringify({summary:'Review needed.',findings:[{title:'Checklist',detail:'The brief asks for a review.',source:'Task brief',quote:'onboarding checklist'}],questions:[]})}]}]})};try{const r=await userRun({kind:'live'});const result=await runner.executeRun('w1','owner',r.id);assert.equal(calls,4);assert.equal(result.status,'completed');assert.equal(count('tasks'),1);assert.equal(count('actions',"status='approved'"),1);const usage=sqlite.prepare('SELECT * FROM usage').get();assert.equal(usage.reserved,1);assert.equal(usage.input_tokens,40);assert.equal(usage.output_tokens,20);assert.equal(JSON.parse(result.output).findings[0].verified,true);}finally{globalThis.fetch=original;}});

const networkURL=moduleURL('lib/portfolio-network.ts',[["from './portfolio-products'","from '"+moduleURL('lib/portfolio-products.ts')+"'"]]);
const opportunities=await import(moduleURL('app/api/integrations/opportunities/route.ts',[["from '@/lib/server'","from '"+serverURL+"'"],["from '@/lib/portfolio-network'","from '"+networkURL+"'"]]));
test('opportunity API requires authentication and takes source from the integration, not the request',async()=>{
  const path='https://example.com/api/integrations/opportunities?country=GB&source=insure360';
  assert.equal((await opportunities.GET(new Request(path))).status,401);
  sqlite.exec("UPDATE products SET slug='haccora' WHERE id='p1'");
  const token=server.randomToken();insert('integrations',{id:'i1',workspace_id:'w1',product_id:'p1',name:'Test key',token_hash:await server.tokenHash(token),created_at:'2026-09-15'});
  const headers={Authorization:'Bearer '+token};
  const response=await opportunities.GET(new Request(path,{headers}));assert.equal(response.status,200);
  const body=await response.json();assert.equal(body.source,'haccora');assert(body.offers.length>0);assert(!JSON.stringify(body).includes('owner@example.com'));
  assert.equal((await opportunities.GET(new Request(path+'&placement=checkout',{headers}))).status,400);
  sqlite.exec("UPDATE workspaces SET paused=1 WHERE id='w1'");assert.equal((await opportunities.GET(new Request(path,{headers}))).status,409);
});

const audioRequest=(file=new File(['RIFF test audio'],'note.wav',{type:'audio/wav'}),language='en-GB')=>{const form=new FormData();form.set('audio',file);form.set('language',language);return new Request('https://example.com/api/speech',{method:'POST',headers:{origin:'https://example.com'},body:form})};
test('speech provider status is truthful and unconfigured transcription makes no network request',async()=>{assert.equal((await (await speechApi.GET()).json()).connected,false);const original=globalThis.fetch;globalThis.fetch=()=>assert.fail('Unconfigured speech must not call a provider');try{assert.equal((await speechApi.POST(audioRequest())).status,409);assert.equal(count('speech_usage'),0)}finally{globalThis.fetch=original}});
test('speech rejects unauthorised viewers, paused workspaces and malformed files before provider use',async()=>{globalThis.testContext.env.OPENAI_API_KEY='test-key-not-real';assert.equal((await speechApi.POST(audioRequest(new File(['bad'],'note.html',{type:'text/html'})))).status,400);assert.equal((await speechApi.POST(audioRequest(undefined,'invented'))).status,400);assert.equal((await speechApi.POST(new Request('https://example.com/api/speech',{method:'POST',headers:{origin:'https://example.com','Content-Type':'multipart/form-data; boundary=test'},body:new Uint8Array(2*1024*1024+20000)}))).status,413);assert.equal(count('speech_usage'),0);sqlite.exec("UPDATE workspaces SET paused=1 WHERE id='w1'");assert.equal((await speechApi.POST(audioRequest())).status,409);sqlite.exec("UPDATE workspaces SET paused=0 WHERE id='w1'");insert('members',{id:'viewer-speech',workspace_id:'w1',user_id:'viewer',email:'v@example.com',role:'viewer',created_at:'2026-09-15'});globalThis.testContext.user={userId:'viewer',email:'v@example.com'};assert.equal((await speechApi.POST(audioRequest())).status,403);assert.equal(count('speech_usage'),0)});
test('speech uses server credentials, bounded monthly reservations and never persists the transcript or audio',async()=>{globalThis.testContext.env.OPENAI_API_KEY='test-key-not-real';globalThis.testContext.env.SPEECH_MONTHLY_LIMIT='1';const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/audio/transcriptions');assert.equal(options.headers.Authorization,'Bearer test-key-not-real');assert.equal(options.body.get('model'),'gpt-transcribe');assert.equal(options.body.get('languages[]'),'en');assert.equal(options.body.get('file').name,'recording.wav');return Response.json({text:'Confidential meeting transcript'})};try{const results=await Promise.all([speechApi.POST(audioRequest()),speechApi.POST(audioRequest())]);assert.deepEqual(results.map(r=>r.status).sort(),[200,429]);const data=await results.find(r=>r.status===200).json();assert.equal(data.text,'Confidential meeting transcript');assert.equal(data.audioRetained,false);assert.equal(calls,1);assert.equal(sqlite.prepare('SELECT requests FROM speech_usage').get().requests,1);assert.equal(count('documents'),0);assert.equal(count('runs'),0);assert.equal(count('audit'),0);const tables=sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table'").all();for(const {name} of tables)assert(!JSON.stringify(sqlite.prepare('SELECT * FROM '+name).all()).includes('Confidential meeting transcript'))}finally{globalThis.fetch=original}});
test('speech provider failure consumes one attempt, hides provider details and is not retried',async()=>{globalThis.testContext.env.OPENAI_API_KEY='test-key-not-real';const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({error:'secret upstream data'},{status:401})};try{const response=await speechApi.POST(audioRequest());assert.equal(response.status,503);assert(!(await response.text()).includes('secret upstream'));assert.equal(calls,1);assert.equal(sqlite.prepare('SELECT requests FROM speech_usage').get().requests,1)}finally{globalThis.fetch=original}});
const customer=(extra={})=>({name:'Alex Customer',phone:'+44 20 7946 0123',externalRef:'crm-1',...extra});
test('customer number matching is exact, scoped, handles shared and withheld numbers, and never verifies identity',async()=>{const a=await customers.saveCustomer('w1','p1',customer(),'owner');await customers.saveCustomer('w2','p2',customer({name:'Other company secret'}),'other');const found=await customers.lookupCustomer('w1','p1','0044 20 7946 0123');assert.equal(found.status,'matched');assert.equal(found.matches[0].id,a.id);assert.equal(found.identityVerified,false);assert(!JSON.stringify(found).includes('Other company'));assert.equal((await customers.lookupCustomer('w1','p1','private')).status,'withheld');assert.equal((await customers.lookupCustomer('w1','p1','02079460123')).status,'invalid');assert.equal((await customers.lookupCustomer('w1','p1','+442079460124')).status,'unknown');await customers.saveCustomer('w1','p1',customer({name:'Family member',externalRef:'crm-2'}),'owner');assert.equal((await customers.lookupCustomer('w1','p1',customer().phone)).status,'ambiguous');await assert.rejects(()=>customers.lookupCustomer('w1','p2',customer().phone),e=>e.status===404)});
test('customer creation is retry safe and conflicting updates require a current revision',async()=>{const a=await customers.saveCustomer('w1','p1',customer(),'owner'),b=await customers.saveCustomer('w1','p1',customer(),'owner');assert.equal(a.id,b.id);assert.equal(count('reception_customers'),1);await assert.rejects(()=>customers.saveCustomer('w1','p1',customer({name:'Changed'}),'owner'),e=>e.status===409);const changed=await customers.saveCustomer('w1','p1',customer({name:'Changed',revision:1}),'owner');assert.equal(changed.revision,2);await assert.rejects(()=>customers.saveCustomer('w1','p1',customer({name:'Stale',revision:1}),'owner'),e=>e.status===409);assert.equal(count('audit',"event='customer.created'"),1);assert.equal(count('audit',"event='customer.updated'"),1)});
test('reception links confirmed customers and keeps human context and same-person preference without transferring calls',async()=>{await enableReception();insert('members',{id:'sarah',workspace_id:'w1',user_id:'sarah-id',email:'sarah@example.com',role:'operator',created_at:'2026-09-15'});const c=await customers.saveCustomer('w1','p1',customer(),'owner');const base={kind:'message',channel:'phone',customer:c.name,callerNumber:c.phone,summary:'Following up on a booking',customerId:c.id};await assert.rejects(()=>reception.receiveReception('w1','p1',base,'a','owner'),e=>e.status===400);const first=await reception.receiveReception('w1','p1',{...base,customerConfirmed:true,humanHandlerId:'sarah-id',handoffNote:'Agreed to check the Friday slot.'},'a','owner');assert.equal(first.human_handler_name,'sarah@example.com');const context=await customers.customerHistory('w1','p1',c.id);assert.equal(context.lastHuman.id,'sarah-id');assert.equal(context.lastHuman.available,null);assert.equal(context.items.length,1);const follow=await reception.receiveReception('w1','p1',{...base,customerConfirmed:true,preferredHandlerId:'sarah-id'},'b','owner');assert.equal(follow.status,'new');assert.equal(follow.preferred_handler_id,'sarah-id');assert.equal((await customers.customerHistory('w1','p1',c.id)).lastHuman.id,'sarah-id');sqlite.exec("DELETE FROM members WHERE user_id='sarah-id'");assert.equal((await customers.customerHistory('w1','p1',c.id)).lastHuman.stillOnTeam,false);await assert.rejects(()=>reception.receiveReception('w1','p1',{...base,customerConfirmed:true,preferredHandlerId:'sarah-id'},'c','owner'),e=>e.status===400);assert.equal(count('runs'),0)});
test('customer linkage rejects foreign profiles, mismatched numbers and invalid handlers',async()=>{await enableReception();const c=await customers.saveCustomer('w2','p2',customer(),'other'),own=await customers.saveCustomer('w1','p1',customer(),'owner');const base={kind:'message',channel:'phone',customer:own.name,summary:'Follow up',customerConfirmed:true};await assert.rejects(()=>reception.receiveReception('w1','p1',{...base,customerId:c.id},'foreign','owner'),e=>e.status===404);await assert.rejects(()=>reception.receiveReception('w1','p1',{...base,customerId:own.id,callerNumber:'+442079460124'},'wrong','owner'),e=>e.status===409);await assert.rejects(()=>reception.receiveReception('w1','p1',{...base,humanHandlerId:'foreign-agent'},'wrong-handler','owner'),e=>e.status===400);await assert.rejects(()=>customers.customerHistory('w1','p1',c.id),e=>e.status===404);assert.equal(count('reception_items'),0)});
test('customer API rejects viewer lookup and connector ignores forged workspace and product claims',async()=>{await enableReception();await customers.saveCustomer('w1','p1',customer(),'owner');await customers.saveCustomer('w2','p2',customer({name:'Foreign secret'}),'owner');const token=server.randomToken();insert('integrations',{id:'customer-key',workspace_id:'w1',product_id:'p1',name:'Reception adapter',token_hash:await server.tokenHash(token),created_at:'2026-09-15'});const headers={authorization:'Bearer '+token};const body={action:'lookup',productId:'p2',workspaceId:'w2',phone:customer().phone};const response=await customerConnector.POST(apiRequest(body,'/api/integrations/customers',headers));assert.equal(response.status,200);assert(!(await response.text()).includes('Foreign secret'));assert.equal((await customerConnector.POST(apiRequest(body,'/api/integrations/customers'))).status,401);assert.equal((await customerConnector.POST(apiRequest({action:'save',...customer({externalRef:'new'})},'/api/integrations/customers',headers))).status,401);insert('members',{id:'viewer-customer',workspace_id:'w1',user_id:'viewer',email:'v@example.com',role:'viewer',created_at:'2026-09-15'});globalThis.testContext.user={userId:'viewer',email:'v@example.com'};assert.equal((await customerApi.POST(apiRequest({...body,productId:'p1'},'/api/customers'))).status,403)});
test('reception paging reaches older requests, scopes counts and rejects malformed cursors',async()=>{for(let n=0;n<121;n++)insert('reception_items',{id:'r'+String(n).padStart(3,'0'),workspace_id:'w1',product_id:'p1',kind:'message',channel:'phone',customer:'Customer',summary:'Request '+n,status:n===0?'handled':'new',external_key:'page-'+n,created_at:'2026-09-15T10:00:00.000Z',updated_at:'2026-09-15T10:00:00.000Z'});insert('reception_items',{id:'foreign-request',workspace_id:'w2',product_id:'p2',kind:'message',channel:'phone',customer:'Foreign',summary:'Private',status:'new',external_key:'page',created_at:'2026-09-15T10:00:00.000Z',updated_at:'2026-09-15T10:00:00.000Z'});const first=await (await receptionApi.GET(new Request('https://example.com/api/reception?productId=p1&filter=all'))).json();assert.equal(first.items.length,100);assert.equal(first.filteredCount,121);assert.equal(first.counts.pending,120);assert.equal(first.connections.liveCalls.state,'coming_soon');const second=await (await receptionApi.GET(new Request('https://example.com/api/reception?productId=p1&filter=all&before='+encodeURIComponent(first.nextCursor)))).json();assert.equal(second.items.length,21);assert.equal(second.nextCursor,null);assert.equal(new Set([...first.items,...second.items].map(r=>r.id)).size,121);assert.equal((await receptionApi.GET(new Request('https://example.com/api/reception?before=wrong'))).status,400);assert.equal((await receptionApi.GET(new Request('https://example.com/api/reception?productId=p2'))).status,404)});
test('late order acceptance after KDS delivery is idempotent and connection status reflects receipts only',async()=>{await enableReception();const r=await reception.receiveReception('w1','p1',{kind:'order',channel:'online',customer:'Customer',summary:'One meal'},'late-order','app',true);const accepted={id:r.id,status:'accepted',sourceRef:'order-1',receipt:{accepted:true,priceValidated:true,availabilityValidated:true,paymentState:'paid'}};await reception.advanceReception('w1','p1',accepted,'app',true);await reception.advanceReception('w1','p1',{id:r.id,status:'delivered',sourceRef:'order-1',receipt:{kdsAcknowledged:true}},'app',true);const late=await reception.advanceReception('w1','p1',accepted,'app',true);assert.equal(late.status,'delivered');assert.equal(late.revision,3);assert.equal(count('audit',"event='reception.accepted'"),1);const data=await (await receptionApi.GET()).json();assert.equal(data.connections.orders.state,'receipt_recorded');assert.equal(data.connections.kds.state,'receipt_recorded');assert.equal(data.connections.bookings.state,'awaiting_receipt');assert.equal(data.connections.liveCalls.state,'coming_soon');await assert.rejects(()=>reception.advanceReception('w1','p1',{...accepted,receipt:{...accepted.receipt,paymentState:'pay_later_authorized'}},'app',true),e=>e.status===409)});
