import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
const db=new PGlite();const migrations=new URL("../../supabase/migrations/",import.meta.url);
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;GRANT USAGE ON SCHEMA auth TO authenticated;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid $$;CREATE PUBLICATION supabase_realtime;`);
for(const name of (await readdir(migrations)).filter(x=>x.endsWith(".sql")).sort()){const sql=await readFile(new URL(name,migrations),"utf8");if(name.startsWith("20260816120554"))for(const id of ["18bafcd5-3e4c-4044-bb63-10325a0b7209","e66c0525-1787-4250-be26-79f849624521","890c71b1-cf6e-4b68-a56e-dd6050372481","97319fe5-82fd-44cd-b27d-6ae314ee368b"])await db.query("INSERT INTO auth.users(id,email) VALUES($1,$2)",[id,"fixture@example.invalid"]);await db.exec(sql);}
const admin="33333333-aaaa-4aaa-8aaa-333333333333",stranger="44444444-bbbb-4bbb-8bbb-444444444444";for(const id of[admin,stranger])await db.query("INSERT INTO auth.users(id,email) VALUES($1,$2)",[id,id+"@example.invalid"]);await db.query("INSERT INTO public.platform_admins(user_id) VALUES($1)",[admin]);
async function asUser(user,fn){await db.exec("BEGIN;SET LOCAL ROLE authenticated;");await db.query("SELECT set_config('request.jwt.claim.sub',$1,true)",[user]);try{const v=await fn();await db.exec("COMMIT");return v;}catch(e){await db.exec("ROLLBACK");throw e;}}
async function asService(fn){await db.exec("BEGIN;SET LOCAL ROLE service_role;");await db.query("SELECT set_config('request.jwt.claim.role','service_role',true)");try{const v=await fn();await db.exec("COMMIT");return v;}catch(e){await db.exec("ROLLBACK");throw e;}}
const pilot=await asUser(admin,async()=> (await db.query("SELECT public.platform_bootstrap_dishbee_pilot() AS result")).rows[0].result);const md=pilot.tenants.find(x=>x.tenantSlug==="mealdeck");assert(md?.tenantId);
const loc=(await asUser(admin,()=>db.query("INSERT INTO public.inventory_stock_locations(tenant_id,product_key,name,location_kind) VALUES($1,'mealdeck','Main Kitchen','kitchen') RETURNING id",[md.tenantId]))).rows[0].id;
async function stock(name,ref,qty){const item=(await asUser(admin,()=>db.query("INSERT INTO public.inventory_items(tenant_id,product_key,external_ref,name,track_stock) VALUES($1,'mealdeck',$2,$3,true) RETURNING id",[md.tenantId,ref,name]))).rows[0].id;await asUser(admin,()=>db.query("SELECT public.inventory_record_movement($1,$2,$3,'receipt',$4,$5,NULL,NULL)",[md.tenantId,item,loc,qty,"open:"+ref]));return item;}
const item1=await stock("Paratha","paratha",20),item2=await stock("French Taco","taco",20);
const v1=(await asUser(admin,()=>db.query("INSERT INTO public.marketplace_vendors(tenant_id,product_key,name,vendor_key,commission_bps) VALUES($1,'mealdeck','Paratique','paratique',1000) RETURNING id",[md.tenantId]))).rows[0].id;
const v2=(await asUser(admin,()=>db.query("INSERT INTO public.marketplace_vendors(tenant_id,product_key,name,vendor_key,commission_bps) VALUES($1,'mealdeck','Taconelle','taconelle',1500) RETURNING id",[md.tenantId]))).rows[0].id;
const l1=(await asUser(admin,()=>db.query("INSERT INTO public.marketplace_listings(tenant_id,product_key,vendor_id,inventory_item_id,stock_location_id,title,price_minor,currency,inventory_tracked,status) VALUES($1,'mealdeck',$2,$3,$4,'Chicken Paratha',699,'GBP',true,'active') RETURNING id",[md.tenantId,v1,item1,loc]))).rows[0].id;
const l2=(await asUser(admin,()=>db.query("INSERT INTO public.marketplace_listings(tenant_id,product_key,vendor_id,inventory_item_id,stock_location_id,title,price_minor,currency,inventory_tracked,status) VALUES($1,'mealdeck',$2,$3,$4,'French Taco',899,'GBP',true,'active') RETURNING id",[md.tenantId,v2,item2,loc]))).rows[0].id;
const oid=await asUser(admin,async()=> (await db.query("SELECT public.marketplace_create_order($1,'mealdeck','crm:test',$2::jsonb,'basket-0001','{}'::jsonb) AS id",[md.tenantId,JSON.stringify([{listingId:l1,quantity:2},{listingId:l2,quantity:1}])])).rows[0].id);assert(oid);
const order=await asUser(admin,()=>db.query("SELECT status,total_minor FROM public.marketplace_orders WHERE id=$1",[oid]));assert.deepEqual(order.rows[0],{status:"pending_payment",total_minor:2297});
const settlements=await asUser(admin,()=>db.query("SELECT vendor_id,gross_minor,commission_minor,net_minor FROM public.marketplace_vendor_settlements WHERE order_id=$1 ORDER BY gross_minor",[oid]));assert.equal(settlements.rows.length,2);assert(settlements.rows.some(r=>r.vendor_id===v1&&r.gross_minor===1398&&r.commission_minor===140&&r.net_minor===1258));assert(settlements.rows.some(r=>r.vendor_id===v2&&r.gross_minor===899&&r.commission_minor===135&&r.net_minor===764));
const bal=await asUser(admin,()=>db.query("SELECT item_id,reserved FROM public.inventory_stock_balances WHERE stock_location_id=$1 ORDER BY item_id",[loc]));assert.equal(bal.rows.reduce((n,r)=>n+Number(r.reserved),0),3);
const svc=(await asUser(admin,()=>db.query("INSERT INTO public.booking_services(tenant_id,product_key,name,duration_minutes,capacity,active) VALUES($1,'mealdeck','Collection Slot',15,5,true) RETURNING id",[md.tenantId]))).rows[0].id;
const bid=await asUser(admin,async()=> (await db.query("SELECT public.booking_create($1,'mealdeck',$2,NULL,'crm:test',now()+interval '1 hour',now()+interval '75 minutes','Europe/London',2,'web','booking-0001') AS id",[md.tenantId,svc])).rows[0].id);assert(bid);
const prog=(await asUser(admin,()=>db.query("INSERT INTO public.loyalty_programmes(tenant_id,product_key,name,loyalty_currency) VALUES($1,'mealdeck','Zoryn Rewards','points') RETURNING id",[md.tenantId]))).rows[0].id;
await asService(()=>db.query("SELECT public.loyalty_apply($1,$2,'crm:test','earn',100,'earn-0001','order')",[md.tenantId,prog]));await asService(()=>db.query("SELECT public.loyalty_apply($1,$2,'crm:test','redeem',30,'redeem-0001','reward')",[md.tenantId,prog]));
const loyalty=await asUser(admin,()=>db.query("SELECT balance,lifetime_earned,lifetime_redeemed FROM public.loyalty_accounts WHERE programme_id=$1",[prog]));
assert.equal(Number(loyalty.rows[0].balance),70);
assert.equal(Number(loyalty.rows[0].lifetime_earned),100);
assert.equal(Number(loyalty.rows[0].lifetime_redeemed),30);
const hidden=await asUser(stranger,()=>db.query("SELECT * FROM public.marketplace_orders WHERE tenant_id=$1",[md.tenantId]));assert.equal(hidden.rows.length,0);
await db.close();console.log("MealDeck multi-vendor cart, inventory, booking and loyalty verified");
