import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
const db=new PGlite();const migrations=new URL("../../supabase/migrations/",import.meta.url);
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;GRANT USAGE ON SCHEMA auth TO authenticated;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid $$;CREATE PUBLICATION supabase_realtime;`);
for(const name of (await readdir(migrations)).filter(x=>x.endsWith(".sql")).sort()){const sql=await readFile(new URL(name,migrations),"utf8");if(name.startsWith("20260816120554"))for(const id of ["18bafcd5-3e4c-4044-bb63-10325a0b7209","e66c0525-1787-4250-be26-79f849624521","890c71b1-cf6e-4b68-a56e-dd6050372481","97319fe5-82fd-44cd-b27d-6ae314ee368b"])await db.query("INSERT INTO auth.users(id,email) VALUES($1,$2)",[id,"fixture@example.invalid"]);await db.exec(sql);}
const admin="55555555-aaaa-4aaa-8aaa-555555555555";await db.query("INSERT INTO auth.users(id,email) VALUES($1,$2)",[admin,admin+"@example.invalid"]);await db.query("INSERT INTO public.platform_admins(user_id) VALUES($1)",[admin]);
async function asUser(fn){await db.exec("BEGIN;SET LOCAL ROLE authenticated;");await db.query("SELECT set_config('request.jwt.claim.sub',$1,true)",[admin]);try{const v=await fn();await db.exec("COMMIT");return v;}catch(e){await db.exec("ROLLBACK");throw e;}}
const pilot=await asUser(async()=> (await db.query("SELECT public.platform_bootstrap_dishbee_pilot() AS result")).rows[0].result);const md=pilot.tenants.find(x=>x.tenantSlug==="mealdeck");assert(md?.tenantId);
const person=(await asUser(()=>db.query("INSERT INTO public.crm_people(tenant_id,display_name,external_ref,lifecycle_stage) VALUES($1,'Growth Customer','customer-1','customer') RETURNING id",[md.tenantId]))).rows[0].id;
await asUser(()=>db.query("INSERT INTO public.marketplace_orders(tenant_id,product_key,buyer_ref,status,currency,total_minor,idempotency_key,created_at) VALUES($1,'mealdeck',$2,'completed','GBP',2500,'g-order-1',now()-interval '10 days'),($1,'mealdeck',$2,'completed','GBP',3500,'g-order-2',now()-interval '2 days')",[md.tenantId,"customer-1"]));
const count=await asUser(async()=> (await db.query("SELECT public.growth_recompute_customer_metrics($1) AS n",[md.tenantId])).rows[0].n);assert(count>=1);
const metric=await asUser(()=>db.query("SELECT orders_count,revenue_minor,rfm_segment,ltv_minor,churn_risk FROM public.growth_customer_metrics WHERE tenant_id=$1 AND person_id=$2",[md.tenantId,person]));assert.equal(metric.rows[0].orders_count,2);assert.equal(metric.rows[0].revenue_minor,6000);assert.equal(metric.rows[0].ltv_minor,6000);assert(["recent","loyal","champion"].includes(metric.rows[0].rfm_segment));
const seg=(await asUser(()=>db.query("INSERT INTO public.growth_segments(tenant_id,name,segment_key,rules) VALUES($1,'Recent customers','recent-customers','{}') RETURNING id",[md.tenantId]))).rows[0].id;
const camp=(await asUser(()=>db.query("INSERT INTO public.marketing_campaigns(tenant_id,product_key,name,channel,segment_id,status) VALUES($1,'mealdeck','Weekend Offer','whatsapp',$2,'draft') RETURNING id",[md.tenantId,seg]))).rows[0].id;assert(camp);
const journey=(await asUser(()=>db.query("INSERT INTO public.customer_journeys(tenant_id,product_key,name,trigger_event,status,definition) VALUES($1,'mealdeck','Post-order','marketplace.order.completed','active','{\"nodes\":[{\"id\":\"start\"}],\"edges\":[]}'::jsonb) RETURNING id",[md.tenantId]))).rows[0].id;assert(journey);
const survey=(await asUser(()=>db.query("INSERT INTO public.feedback_surveys(tenant_id,product_key,name,survey_type,trigger_event,status) VALUES($1,'mealdeck','Post-order NPS','nps','marketplace.order.completed','active') RETURNING id",[md.tenantId]))).rows[0].id;
await asUser(()=>db.query("INSERT INTO public.feedback_responses(tenant_id,survey_id,person_id,score,comment,sentiment) VALUES($1,$2,$3,10,'Great','positive'),($1,$2,$3,5,'Late','negative')",[md.tenantId,survey,person]));
const resp=await asUser(()=>db.query("SELECT count(*)::int AS n FROM public.feedback_responses WHERE survey_id=$1",[survey]));assert.equal(resp.rows[0].n,2);
const impl=await db.query("SELECT service_key,implementation_status FROM public.service_catalogue WHERE service_key IN('omniqora.journeys','omniqora.rfm','omniqora.sales','omniqora.feedback','omniqora.campaigns')");assert(impl.rows.every(r=>r.implementation_status==="built_main"));
await db.close();console.log("Growth RFM campaigns journeys sales/feedback foundations verified");