import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
const db=new PGlite();const migrations=new URL("../../supabase/migrations/",import.meta.url);
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;GRANT USAGE ON SCHEMA auth TO authenticated;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid $$;CREATE PUBLICATION supabase_realtime;`);
for(const name of (await readdir(migrations)).filter(x=>x.endsWith(".sql")).sort()){const sql=await readFile(new URL(name,migrations),"utf8");if(name.startsWith("20260816120554"))for(const id of ["18bafcd5-3e4c-4044-bb63-10325a0b7209","e66c0525-1787-4250-be26-79f849624521","890c71b1-cf6e-4b68-a56e-dd6050372481","97319fe5-82fd-44cd-b27d-6ae314ee368b"])await db.query("INSERT INTO auth.users(id,email) VALUES($1,$2)",[id,"fixture@example.invalid"]);await db.exec(sql);}
const admin="66666666-aaaa-4aaa-8aaa-666666666666",stranger="77777777-bbbb-4bbb-8bbb-777777777777";for(const id of[admin,stranger])await db.query("INSERT INTO auth.users(id,email) VALUES($1,$2)",[id,id+"@example.invalid"]);await db.query("INSERT INTO public.platform_admins(user_id) VALUES($1)",[admin]);
async function asUser(user,fn){await db.exec("BEGIN;SET LOCAL ROLE authenticated;");await db.query("SELECT set_config('request.jwt.claim.sub',$1,true)",[user]);try{const v=await fn();await db.exec("COMMIT");return v;}catch(e){await db.exec("ROLLBACK");throw e;}}
async function asService(fn){await db.exec("BEGIN;SET LOCAL ROLE service_role;");await db.query("SELECT set_config('request.jwt.claim.role','service_role',true)");try{const v=await fn();await db.exec("COMMIT");return v;}catch(e){await db.exec("ROLLBACK");throw e;}}
const pilot=await asUser(admin,async()=> (await db.query("SELECT public.platform_bootstrap_dishbee_pilot() AS result")).rows[0].result);const md=pilot.tenants.find(x=>x.tenantSlug==="mealdeck");assert(md?.tenantId);
const person=(await asUser(admin,()=>db.query("INSERT INTO public.crm_people(tenant_id,display_name,lifecycle_stage) VALUES($1,'Utility Customer','customer') RETURNING id",[md.tenantId]))).rows[0].id;
const workflow=(await asUser(admin,()=>db.query("INSERT INTO public.automation_workflows(tenant_id,product_key,name,trigger_event,status,definition,created_by) VALUES($1,'mealdeck','Order follow-up','marketplace.order.completed','active','{\"nodes\":[],\"edges\":[]}'::jsonb,$2) RETURNING id",[md.tenantId,admin]))).rows[0].id;
const event=(await asService(()=>db.query("INSERT INTO public.platform_events(tenant_id,product_key,event_type,idempotency_key,payload) VALUES($1,'mealdeck','marketplace.order.completed','utility-event-0001','{\"orderId\":\"o1\"}'::jsonb) RETURNING id",[md.tenantId]))).rows[0].id;
const enqueued=await asService(async()=> (await db.query("SELECT public.automation_enqueue_for_event($1) AS n",[event])).rows[0].n);assert.equal(enqueued,1);
const run=await asUser(admin,()=>db.query("SELECT workflow_id,status FROM public.automation_runs WHERE tenant_id=$1",[md.tenantId]));assert.deepEqual(run.rows[0],{workflow_id:workflow,status:"queued"});
await asUser(admin,()=>db.query("INSERT INTO public.notification_preferences(tenant_id,person_id,channel,purpose,enabled) VALUES($1,$2,'whatsapp','marketing',false)",[md.tenantId,person]));
const nid=await asService(async()=> (await db.query("SELECT public.notification_enqueue($1,'mealdeck',$2,'whatsapp','marketing','offer','{}'::jsonb,'{}'::jsonb,'notify-0001') AS id",[md.tenantId,person])).rows[0].id);assert(nid);
const notif=await asUser(admin,()=>db.query("SELECT status FROM public.notification_outbox WHERE id=$1",[nid]));assert.equal(notif.rows[0].status,"suppressed");
await asUser(admin,()=>db.query("INSERT INTO public.search_documents(tenant_id,product_key,entity_type,entity_id,title,body,keywords) VALUES($1,'mealdeck','order','order-1','MealDeck order 1','Chicken paratha and taco order',ARRAY['food','order'])",[md.tenantId]));
const found=await asUser(admin,()=>db.query("SELECT * FROM public.search_tenant($1,'paratha',10)",[md.tenantId]));assert.equal(found.rows.length,1);assert.equal(found.rows[0].entity_id,"order-1");
const hidden=await asUser(stranger,()=>db.query("SELECT * FROM public.search_tenant($1,'paratha',10)",[md.tenantId]));assert.equal(hidden.rows.length,0);
const ticket=(await asUser(admin,()=>db.query("INSERT INTO public.support_tickets(tenant_id,product_key,person_id,subject,priority,status) VALUES($1,'mealdeck',$2,'Delivery query','normal','open') RETURNING id",[md.tenantId,person]))).rows[0].id;assert(ticket);
const doc=(await asUser(admin,()=>db.query("INSERT INTO public.document_records(tenant_id,product_key,document_type,title,created_by) VALUES($1,'mealdeck','pod','POD evidence',$2) RETURNING id",[md.tenantId,admin]))).rows[0].id;await asUser(admin,()=>db.query("INSERT INTO public.document_versions(document_id,tenant_id,version,storage_ref,mime_type,created_by) VALUES($1,$2,1,'s3://evidence/pod.pdf','application/pdf',$3)",[doc,md.tenantId,admin]));
const form=(await asUser(admin,()=>db.query("INSERT INTO public.form_definitions(tenant_id,product_key,form_key,name,status,schema) VALUES($1,'mealdeck','delivery-issue','Delivery issue','active','{\"fields\":[]}'::jsonb) RETURNING id",[md.tenantId]))).rows[0].id;assert(form);
const impl=await db.query("SELECT implementation_status FROM public.service_catalogue WHERE service_key IN('omniqora.automation','omniqora.documents','omniqora.forms','omniqora.search','omniqora.support','omniqora.notifications')");assert(impl.rows.every(r=>r.implementation_status==="built_main"));
await db.close();console.log("Platform utilities automation notification search support documents/forms verified");