import assert from 'node:assert/strict';
const {chromium}=await import(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright/index.mjs' : 'playwright');
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4178');
await page.getByRole('heading',{name:'Needs your attention'}).waitFor();
await page.screenshot({path:'/tmp/practice-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Work',exact:true}).click();
await page.getByLabel('Search jobs').fill('Aster');
assert.equal(await page.getByRole('button').filter({hasText:'Aster Trading Ltd'}).count(),1);
await page.getByRole('button',{name:'Table',exact:true}).click();
await page.getByRole('button',{name:'Aster Trading Ltd Accounts preparation'}).click();
await page.getByRole('heading',{name:'Job phases'}).waitFor();
await page.getByRole('button',{name:'Complete',exact:true}).first().click();
assert.equal(await page.evaluate(()=>window.__lastCommand.operation),'phase.complete');
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Services',exact:true}).click();
await page.getByRole('button',{name:'Create / update template'}).click();
await page.getByLabel('Start from an industry pack').selectOption('compliance');
assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Compliance assessment');
await page.getByRole('button',{name:'Save',exact:true}).click();
await page.waitForFunction(()=>window.__lastCommand?.operation==='service.save');
assert.equal(await page.evaluate(()=>window.__lastCommand.service.phases.length),4);
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Work',exact:true}).click();
await page.screenshot({path:'/tmp/practice-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true,'No page-wide horizontal overflow');
assert.deepEqual(errors,[]);
console.log('PASS: desktop/mobile workspace, search, table, job panel, phase action, service template form');
await browser.close();
