"use client";

import { useMemo, useState } from "react";
import { Activity, AppWindow, Bot, Boxes, BrainCircuit, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Cpu, Database, FileCheck2, Gauge, GitBranch, History, KeyRound, LockKeyhole, Menu, Network, Play, Plus, RefreshCcw, Route, Search, ShieldCheck, Sparkles, TriangleAlert, Users, Webhook, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type AppRecord = { name: string; sector: string; agents: number; events: string; health: number; status: "Live" | "Simulation" | "Attention" };
const applications: AppRecord[] = [
  { name: "Dishbee", sector: "Hospitality", agents: 8, events: "12.4k", health: 99, status: "Live" },
  { name: "Haccora", sector: "Food compliance", agents: 6, events: "4.8k", health: 98, status: "Live" },
  { name: "Cirqiva", sector: "Waste & circular economy", agents: 5, events: "2.1k", health: 96, status: "Simulation" },
  { name: "Premisora", sector: "Construction", agents: 7, events: "1.8k", health: 97, status: "Simulation" },
  { name: "DOMUREVA", sector: "Property restoration", agents: 6, events: "1.2k", health: 94, status: "Attention" },
  { name: "Dokuvera", sector: "Document control", agents: 4, events: "8.7k", health: 99, status: "Live" },
  { name: "Zoryn Pay", sector: "Payments", agents: 4, events: "6.3k", health: 98, status: "Simulation" },
];
const approvals = [
  { title: "Increase Chicken Tikka Wrap price by £0.40", app: "Dishbee · Café 1 Luton", risk: "Financial", age: "8 min", owner: "Operations" },
  { title: "Issue refrigeration corrective action", app: "Haccora · Futures House", risk: "Compliance", age: "21 min", owner: "Site manager" },
  { title: "Approve drawing revision A-204 Rev C", app: "Premisora · Project Alder", risk: "Technical", age: "44 min", owner: "Project lead" },
  { title: "Send organic-waste collection amendment", app: "Cirqiva · Café 1 St Albans", risk: "Operational", age: "1 hr", owner: "Operations" },
];
const engines = [
  { name: "Hospitality Intelligence", products: "Dishbee, Café 1, Haccora", workflows: 24, accuracy: 96, color: "#7c5cff" },
  { name: "Construction Intelligence", products: "Premisora, DOMUREVA, Craftvaro", workflows: 18, accuracy: 93, color: "#22b8a7" },
  { name: "Waste Intelligence", products: "Cirqiva, Haccora, Dishbee", workflows: 12, accuracy: 95, color: "#e7a53d" },
  { name: "Compliance Intelligence", products: "Regulos, Dokuvera, Haccora", workflows: 21, accuracy: 97, color: "#4b8ef1" },
  { name: "Sales & Call Centre", products: "All client workspaces", workflows: 28, accuracy: 96, color: "#ef6f91" },
  { name: "Finance Intelligence", products: "Omniqora, TaxLounge, client accounts", workflows: 19, accuracy: 98, color: "#36a269" },
  { name: "Education Intelligence", products: "UniPathways, GradLume, TrainDirekt", workflows: 16, accuracy: 95, color: "#8a68d8" },
  { name: "Retail Intelligence", products: "Kalëthon, Meyzaar, Sofellea", workflows: 20, accuracy: 94, color: "#e28b38" },
];
const agents = [
  ["Supervisor Agent", "Quality and routing", "All products", "2,184 runs", "98.2%"], ["Reception Agent", "Voice and messaging", "All clients", "4,921 runs", "96.9%"],
  ["Customer Service Agent", "Resolution", "All clients", "3,842 runs", "97.1%"], ["Booking Agent", "Appointments", "9 products", "1,784 runs", "98.0%"],
  ["Sales Qualifier", "Lead qualification", "All products", "2,421 runs", "95.8%"], ["Proposal Agent", "Sales documents", "12 products", "1,109 runs", "96.4%"],
  ["Campaign Agent", "Marketing", "All products", "1,842 runs", "95.9%"], ["Content Agent", "Multilingual content", "All products", "3,407 runs", "97.5%"],
  ["Bookkeeping Agent", "Transaction review", "Client finance", "2,206 runs", "98.4%"], ["Management Accounts Agent", "Financial reporting", "Client finance", "684 runs", "98.1%"],
  ["Credit Control Agent", "Receivables", "Client finance", "911 runs", "97.2%"], ["Operations Agent", "Tasks and exceptions", "All products", "1,842 runs", "96.8%"],
  ["Document Agent", "Extraction", "11 products", "3,407 runs", "98.1%"], ["Compliance Agent", "Risk", "8 products", "921 runs", "97.4%"],
  ["Forecasting Agent", "Prediction", "6 products", "688 runs", "93.9%"], ["Design Change Agent", "Construction", "2 products", "143 runs", "94.6%"],
  ["Waste Optimisation Agent", "Circular economy", "3 products", "209 runs", "95.2%"], ["Report Publisher", "Approved delivery", "All clients", "1,288 runs", "99.1%"],
];
const workflows = [
  { name: "Daily hospitality briefing", trigger: "Schedule · 06:30", engine: "Hospitality", steps: 7, status: "Active", last: "Today 06:30" },
  { name: "Failed food-safety check", trigger: "haccora.check.failed", engine: "Compliance", steps: 6, status: "Active", last: "18 min ago" },
  { name: "Food-waste variance", trigger: "dishbee.shift.closed", engine: "Waste", steps: 8, status: "Simulation", last: "Yesterday" },
  { name: "Drawing revision impact", trigger: "dokuvera.revision.created", engine: "Construction", steps: 9, status: "Simulation", last: "2 hrs ago" },
  { name: "Grant evidence gap", trigger: "domureva.claim.updated", engine: "Compliance", steps: 5, status: "Active", last: "3 hrs ago" },
];
const connections = [
  { app: "Dishbee", mode: "API + webhooks", endpoint: "/v1/events/dishbee", events: 12, state: "Healthy", delivery: "99.98%" },
  { app: "Haccora", mode: "Signed webhooks", endpoint: "/v1/events/haccora", events: 9, state: "Healthy", delivery: "99.96%" },
  { app: "Cirqiva", mode: "Bridge", endpoint: "/v1/events/cirqiva", events: 7, state: "Testing", delivery: "100%" },
  { app: "Premisora", mode: "API + bridge", endpoint: "/v1/events/premisora", events: 11, state: "Testing", delivery: "99.91%" },
  { app: "DOMUREVA", mode: "Signed webhooks", endpoint: "/v1/events/domureva", events: 8, state: "Attention", delivery: "98.72%" },
];
const team = [
  ["Amer Saleem", "Portfolio owner", "All products", "Full control"], ["Compliance Lead", "Compliance administrator", "Haccora, Regulos, Cirqiva", "Review + approve"],
  ["Operations Manager", "Operations", "Dishbee, Café 1", "Review + operate"], ["Project Lead", "Construction", "Premisora, DOMUREVA", "Review + approve"], ["Auditor", "Read only", "All products", "View audit"],
];
const recentRuns = [
  { id:"RUN-8421", workflow:"Daily hospitality briefing", app:"Dishbee", status:"Waiting approval", duration:"1.8s", cost:"£0.00", time:"2 min ago" },
  { id:"RUN-8420", workflow:"Failed food-safety check", app:"Haccora", status:"Completed", duration:"0.9s", cost:"£0.00", time:"18 min ago" },
  { id:"RUN-8419", workflow:"Drawing revision impact", app:"Premisora", status:"Waiting approval", duration:"2.3s", cost:"£0.00", time:"42 min ago" },
  { id:"RUN-8418", workflow:"Food-waste variance", app:"Cirqiva", status:"Completed", duration:"1.4s", cost:"£0.00", time:"1 hr ago" },
];
const providers = [
  { name:"OpenAI Primary", role:"Complex reasoning and planning", state:"Ready to connect", routing:"High-risk analysis" },
  { name:"OpenAI Review", role:"Independent answer review", state:"Ready to connect", routing:"Quality gate" },
  { name:"Gemini Fast", role:"Document and data extraction", state:"Ready to connect", routing:"High-volume tasks" },
  { name:"Gemini Review", role:"Cross-provider verification", state:"Ready to connect", routing:"Disagreement check" },
];
const deadLetters = [
  { id:"DL-019", app:"DOMUREVA", event:"domureva.claim.updated", stage:"Validation", reason:"Evidence reference missing", attempts:0, age:"12 min" },
  { id:"DL-018", app:"Cirqiva", event:"cirqiva.collection.completed", stage:"Enrichment", reason:"Waste code not recognised", attempts:1, age:"38 min" },
  { id:"DL-017", app:"Dishbee", event:"dishbee.shift.closed", stage:"Delivery", reason:"Site callback timed out", attempts:2, age:"2 hr" },
];
const auditEntries = [
  ["11:42", "Amer Saleem", "workflow.simulated", "Daily hospitality briefing", "Success"],
  ["11:31", "Operations Manager", "approval.decided", "Café 1 price recommendation", "Approved"],
  ["10:58", "Project Lead", "workflow.versioned", "Drawing revision impact v4", "Success"],
  ["10:44", "System", "dead_letter.created", "DL-019", "Review"],
  ["09:16", "Compliance Lead", "connection.tested", "Haccora", "Healthy"],
];
const readiness = [
  { app:"Dishbee", passed:6, total:6, state:"Ready" },{ app:"Haccora", passed:6, total:6, state:"Ready" },{ app:"Cirqiva", passed:5, total:6, state:"Review" },{ app:"Premisora", passed:4, total:6, state:"Review" },{ app:"DOMUREVA", passed:3, total:6, state:"Blocked" },
];
const portfolioScale = [
  { product:"Dishbee", tenants:"42 businesses", region:"UK", boundary:"Strict", policies:"Hospitality + payments" },
  { product:"Haccora", tenants:"318 sites", region:"UK / DE", boundary:"Strict", policies:"Food safety + compliance" },
  { product:"Cirqiva", tenants:"27 operators", region:"UK", boundary:"Strict", policies:"Waste duty of care" },
  { product:"Premisora", tenants:"14 projects", region:"UK / DE", boundary:"Project", policies:"Construction change" },
  { product:"DOMUREVA", tenants:"11 councils", region:"UK", boundary:"Authority", policies:"Grant evidence" },
];
const schedules = [["Executive hospitality briefing","Daily · 06:30","Europe/London","Active"],["Food-safety exception digest","Every 2 hours","Europe/London","Active"],["Waste diversion report","Monday · 07:00","Europe/London","Simulation"],["Construction portfolio review","Friday · 15:00","Europe/Berlin","Simulation"]];
const policyPacks = [["Hospitality Core","12 controls","Dishbee, Café 1"],["Food Safety Core","18 controls","Haccora"],["Waste Duty of Care","14 controls","Cirqiva"],["Construction Change","16 controls","Premisora, DOMUREVA"],["Payment Recommendation Safety","21 controls","Zoryn Pay"]];
const commercialPlans = [{name:"Intelligence Essentials",price:"From £49/mo",for:"Single-site SMEs",features:"2 workflows · 1,000 runs · approvals"},{name:"Industry Pro",price:"From £149/mo",for:"Multi-site businesses",features:"Industry pack · 10 workflows · analytics"},{name:"Portfolio",price:"Custom",for:"Groups and platforms",features:"Multi-tenant · API · governance · SLA"},{name:"White Label",price:"Custom + usage",for:"SaaS operators",features:"Own brand/domain · embedded UI · metering"}];

function Status({ value }: { value: AppRecord["status"] }) {
  const style = value === "Live" ? "bg-emerald-500/12 text-emerald-300 border-emerald-400/20" : value === "Attention" ? "bg-amber-500/12 text-amber-300 border-amber-400/20" : "bg-violet-500/12 text-violet-300 border-violet-400/20";
  return <Badge variant="outline" className={style}>{value}</Badge>;
}
function Metric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof Activity }) {
  return <Card className="metric-card"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="eyebrow">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight text-white">{value}</p></div><div className="icon-well"><Icon size={18} /></div></div><p className="mt-4 text-sm text-slate-400">{note}</p></CardContent></Card>;
}

export default function Home() {
  const [query, setQuery] = useState(""); const [mobileOpen, setMobileOpen] = useState(false); const [resolved, setResolved] = useState<string[]>([]); const [view, setView] = useState("overview"); const [briefingRun,setBriefingRun]=useState<"idle"|"running"|"ready">("idle");
  const filtered = useMemo(() => applications.filter(a => `${a.name} ${a.sector}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const navigation = [["Overview", Gauge, "overview"], ["Applications", AppWindow, "applications"], ["Agent workforce", Bot, "agents"], ["Industry engines", Boxes, "engines"], ["Workflows", GitBranch, "workflows"], ["Workflow builder", Plus, "builder"], ["Run history", History, "runs"], ["Operations", Activity, "operations"], ["Portfolio scale", Boxes, "scale"], ["Commercial", CircleDollarSign, "commercial"], ["AI providers", Cpu, "providers"], ["Approvals", FileCheck2, "approvals"], ["Connections", Network, "connections"], ["Audit", Database, "audit"], ["Access", ShieldCheck, "access"]] as const;
  const Sidebar = () => <aside className="sidebar-shell"><div className="brand-lockup"><div className="brand-mark"><BrainCircuit size={22}/></div><div><p className="brand-name">Omniqora Control</p><p className="brand-sub">by iTechLounge</p></div></div><nav className="mt-8 space-y-1">{navigation.map(([label, Icon, target]) => <button key={label} onClick={()=>{setView(target);setMobileOpen(false)}} className={`nav-item ${view === target ? "nav-active" : ""}`}><Icon size={17}/><span>{label}</span>{label === "Approvals" && <span className="nav-count">{approvals.length-resolved.length}</span>}</button>)}</nav><div className="sidebar-footer"><div className="flex items-center gap-3"><div className="avatar">AS</div><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-100">Amer Saleem</p><p className="text-xs text-slate-500">Portfolio owner</p></div></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-emerald-400/15 bg-emerald-400/5 px-3 py-2 text-xs text-emerald-300"><ShieldCheck size={14}/>Internal · protected</div></div></aside>;
  return <div className="app-shell"><div className="hidden lg:block"><Sidebar/></div>{mobileOpen && <div className="mobile-layer"><button aria-label="Close navigation" className="mobile-scrim" onClick={() => setMobileOpen(false)}/><div className="mobile-panel"><button className="mobile-close" onClick={() => setMobileOpen(false)}><X size={20}/></button><Sidebar/></div></div>}
    <main className="main-canvas"><header className="topbar"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(true)}><Menu/></Button><div><h1>Portfolio intelligence</h1><p>One view across your applications, agents and decisions.</p></div></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-lg border border-emerald-400/20 bg-emerald-400/5 px-3 py-2 text-sm text-emerald-300 sm:flex"><span className="pulse-dot"/>Systems healthy</div><Button className="run-button" disabled={briefingRun==="running"} onClick={()=>{setBriefingRun("running");setTimeout(()=>setBriefingRun("ready"),850)}}><Play size={15}/>{briefingRun==="running"?"Running…":briefingRun==="ready"?"Briefing ready":"Run briefing"}</Button></div></header>
      <section className="content-wrap"><div className="briefing-card"><div className="briefing-glow"/><div className="relative flex flex-col justify-between gap-5 md:flex-row md:items-center"><div className="flex items-start gap-4"><div className="spark-box"><Sparkles size={22}/></div><div><div className="flex flex-wrap items-center gap-2"><h2>{briefingRun==="ready"?"Fresh executive briefing":"Monday executive briefing"}</h2><Badge className="border-0 bg-white/10 text-slate-200">Simulation mode</Badge></div><p className="mt-2 max-w-3xl text-slate-300">Three items need attention: a DOMUREVA evidence gap, a Café 1 margin recommendation and an overdue Premisora design approval. No critical security events detected.</p></div></div><Button variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10" onClick={()=>setView("runs")}>Open briefing<ChevronRight size={15}/></Button></div></div>
        <div className="metrics-grid"><Metric label="Connected products" value="19" note="7 active in this release" icon={AppWindow}/><Metric label="Agent runs · 30d" value="7,210" note="96.4% accepted by reviewers" icon={Bot}/><Metric label="Pending approvals" value="4" note="Oldest waiting 1 hour" icon={Clock3}/><Metric label="Estimated AI cost" value="£286" note="32% below monthly budget" icon={CircleDollarSign}/></div>
        <Tabs value={view} onValueChange={setView} className="mt-7"><TabsList className="tabs-bar"><TabsTrigger value="overview">Command view</TabsTrigger><TabsTrigger value="workflows">Workflows</TabsTrigger><TabsTrigger value="connections">Connections</TabsTrigger><TabsTrigger value="access">Access</TabsTrigger></TabsList>
          <TabsContent value="overview" className="mt-5 space-y-5"><div className="grid gap-5 xl:grid-cols-[1.35fr_.85fr]"><Card className="panel"><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Industry layer</p><CardTitle>Intelligence engines</CardTitle></div><Button variant="ghost" size="sm" className="text-slate-300">View registry<ChevronRight size={14}/></Button></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{engines.map(e => <div key={e.name} className="engine-card"><div className="engine-line" style={{background:e.color}}/><div className="flex items-start justify-between gap-2"><div><h3>{e.name}</h3><p>{e.products}</p></div><span className="accuracy">{e.accuracy}%</span></div><div className="mt-5 flex items-center justify-between text-xs text-slate-500"><span>{e.workflows} workflows</span><span>Accuracy</span></div><Progress value={e.accuracy} className="mt-2 h-1.5 bg-slate-800"/></div>)}</CardContent></Card>
            <Card className="panel"><CardHeader><div className="flex items-center justify-between"><div><p className="eyebrow">Decision control</p><CardTitle>Approval queue</CardTitle></div><span className="queue-number">{approvals.length-resolved.length}</span></div></CardHeader><CardContent className="space-y-2">{approvals.filter(a=>!resolved.includes(a.title)).slice(0,3).map(a=><Dialog key={a.title}><DialogTrigger asChild><button className="approval-row"><div className="approval-icon"><TriangleAlert size={16}/></div><div className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-medium text-slate-100">{a.title}</p><p className="mt-1 text-xs text-slate-500">{a.app} · {a.age}</p></div><ChevronRight size={15} className="text-slate-600"/></button></DialogTrigger><DialogContent className="border-slate-700 bg-[#101625] text-white"><DialogHeader><DialogTitle>{a.title}</DialogTitle><DialogDescription className="text-slate-400">{a.app}. This simulated recommendation requires {a.owner.toLowerCase()} approval before any external action.</DialogDescription></DialogHeader><div className="rounded-xl border border-slate-700 bg-slate-900/60 p-4 text-sm text-slate-300"><p><strong className="text-white">Risk class:</strong> {a.risk}</p><p className="mt-2"><strong className="text-white">Safeguard:</strong> AI can prepare this action but cannot execute it without an authorised reviewer.</p></div><div className="flex justify-end gap-2"><Button variant="outline" className="border-slate-600 bg-transparent">Hold</Button><Button onClick={()=>setResolved(v=>[...v,a.title])} className="bg-violet-500 hover:bg-violet-400">Approve simulation</Button></div></DialogContent></Dialog>)}{approvals.length===resolved.length&&<div className="empty-state"><CheckCircle2/><p>All simulated decisions reviewed.</p></div>}</CardContent></Card></div>
            <Card className="panel"><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Live operations</p><CardTitle>Application health</CardTitle></div><div className="relative w-64 max-w-[45vw]"><Search className="absolute left-3 top-2.5 text-slate-500" size={16}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find application" className="border-slate-700 bg-slate-900 pl-9 text-slate-100"/></div></CardHeader><CardContent><AppTable rows={filtered}/></CardContent></Card></TabsContent>
          <TabsContent value="applications" className="mt-5"><Card className="panel"><CardHeader><p className="eyebrow">Registry</p><CardTitle>Connected applications</CardTitle></CardHeader><CardContent><AppTable rows={filtered}/></CardContent></Card></TabsContent>
          <TabsContent value="agents" className="mt-5"><Card className="panel"><CardHeader><p className="eyebrow">Reusable workforce</p><CardTitle>Agent registry</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Agent</TableHead><TableHead>Specialism</TableHead><TableHead>Coverage</TableHead><TableHead>Runs</TableHead><TableHead>Accepted</TableHead></TableRow></TableHeader><TableBody>{agents.map(a=><TableRow key={a[0]}><TableCell className="font-medium text-white">{a[0]}</TableCell>{a.slice(1).map((v,i)=><TableCell key={i}>{v}</TableCell>)}</TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
          <TabsContent value="engines" className="mt-5"><Card className="panel"><CardHeader><p className="eyebrow">Industry modules</p><CardTitle>Intelligence engine registry</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{engines.map(e=><div key={e.name} className="engine-card"><div className="engine-line" style={{background:e.color}}/><h3>{e.name}</h3><p>{e.products}</p><div className="mt-5 flex justify-between text-sm text-slate-400"><span>{e.workflows} workflows</span><span>{e.accuracy}% accepted</span></div></div>)}</CardContent></Card></TabsContent>
          <TabsContent value="workflows" className="mt-5"><Card className="panel"><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Automation</p><CardTitle>Workflow control</CardTitle></div><Button onClick={()=>setView("builder")}><Plus size={15}/>New workflow</Button></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Workflow</TableHead><TableHead>Trigger</TableHead><TableHead>Engine</TableHead><TableHead>Steps</TableHead><TableHead>Last run</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{workflows.map(w=><TableRow key={w.name}><TableCell className="font-medium text-white">{w.name}</TableCell><TableCell className="font-mono text-xs">{w.trigger}</TableCell><TableCell>{w.engine}</TableCell><TableCell>{w.steps}</TableCell><TableCell>{w.last}</TableCell><TableCell><Badge variant="outline" className={w.status==="Active"?"border-emerald-400/20 text-emerald-300":"border-violet-400/20 text-violet-300"}>{w.status}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
          <TabsContent value="builder" className="mt-5"><div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><Card className="panel"><CardHeader><p className="eyebrow">Workflow definition</p><CardTitle>New cross-SaaS workflow</CardTitle></CardHeader><CardContent className="space-y-4"><label className="builder-field"><span>Name</span><Input defaultValue="Daily portfolio exceptions"/></label><label className="builder-field"><span>Application</span><select defaultValue="dishbee"><option value="dishbee">Dishbee</option><option value="haccora">Haccora</option><option value="cirqiva">Cirqiva</option><option value="premisora">Premisora</option></select></label><label className="builder-field"><span>Trigger event</span><Input defaultValue="dishbee.shift.closed" className="font-mono"/></label><label className="builder-field"><span>Risk class</span><select defaultValue="medium"><option>low</option><option>medium</option><option>high</option></select></label><div className="rounded-xl border border-emerald-400/15 bg-emerald-400/5 p-3 text-sm text-emerald-300"><CheckCircle2 size={16} className="mb-2"/>Valid structure · approval policy satisfied</div><div className="flex gap-2"><Button variant="outline" className="border-slate-600 bg-transparent">Save draft</Button><Button onClick={()=>setView("runs")}><Play size={15}/>Simulate</Button></div></CardContent></Card><Card className="panel"><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Execution canvas</p><CardTitle>Five controlled steps</CardTitle></div><Badge variant="outline" className="border-violet-400/20 text-violet-300">Version 1 draft</Badge></CardHeader><CardContent><div className="workflow-canvas">{[["01","Validate event","Check contract, signature and required fields","validate"],["02","Enrich context","Load approved product metrics and policies","enrich"],["03","Reason","Analyse exceptions using the routed intelligence provider","reason"],["04","Human approval","Hold recommendations for an authorised reviewer","approve"],["05","Notify","Return the approved result to the source SaaS","notify"]].map((s,i)=><div className="workflow-node" key={s[0]}><div className="node-number">{s[0]}</div><div className="flex-1"><div className="flex items-center justify-between gap-3"><h3>{s[1]}</h3><code>{s[3]}</code></div><p>{s[2]}</p></div>{i<4&&<div className="node-line"/>}</div>)}</div></CardContent></Card></div></TabsContent>
          <TabsContent value="runs" className="mt-5"><Card className="panel"><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Execution ledger</p><CardTitle>Workflow run history</CardTitle></div><Badge variant="outline" className="border-violet-400/20 text-violet-300">Simulation · £0 cost</Badge></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Run</TableHead><TableHead>Workflow</TableHead><TableHead>Application</TableHead><TableHead>Status</TableHead><TableHead>Duration</TableHead><TableHead>Cost</TableHead><TableHead>Started</TableHead></TableRow></TableHeader><TableBody>{recentRuns.map(r=><TableRow key={r.id}><TableCell className="font-mono text-xs text-violet-300">{r.id}</TableCell><TableCell className="font-medium text-white">{r.workflow}</TableCell><TableCell>{r.app}</TableCell><TableCell><Badge variant="outline" className={r.status==="Completed"?"border-emerald-400/20 text-emerald-300":"border-amber-400/20 text-amber-300"}>{r.status}</Badge></TableCell><TableCell>{r.duration}</TableCell><TableCell>{r.cost}</TableCell><TableCell>{r.time}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
          <TabsContent value="providers" className="mt-5"><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card className="panel"><CardHeader><p className="eyebrow">Provider-neutral routing</p><CardTitle>AI provider gateway</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{providers.map(p=><div className="provider-card" key={p.name}><div className="flex items-start justify-between"><div className="provider-logo"><Cpu size={18}/></div><Badge variant="outline" className="border-slate-600 text-slate-300">{p.state}</Badge></div><h3>{p.name}</h3><p>{p.role}</p><div className="provider-route"><Route size={14}/>{p.routing}</div></div>)}</CardContent></Card><Card className="panel"><CardHeader><p className="eyebrow">Quality controls</p><CardTitle>Routing policy</CardTitle></CardHeader><CardContent className="space-y-3"><Policy icon={Route} title="Task-aware routing" text="Send each job to the best model for cost, speed and risk."/><Policy icon={ShieldCheck} title="Independent review" text="High-risk recommendations require a second model and a person."/><Policy icon={CircleDollarSign} title="Budget protection" text="Per-app limits and automatic fallback prevent overspend."/><Policy icon={Database} title="Simulation first" text="All four routes are testable before credentials are connected."/></CardContent></Card></div></TabsContent>
          <TabsContent value="operations" className="mt-5 space-y-5"><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Card className="panel"><CardHeader><p className="eyebrow">Recovery queue</p><CardTitle>Dead-letter events</CardTitle></CardHeader><CardContent className="space-y-3">{deadLetters.map(d=><div className="dead-letter" key={d.id}><div className="approval-icon"><TriangleAlert size={16}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="font-mono text-xs text-violet-300">{d.id}</span><span className="text-sm font-medium text-white">{d.app}</span><Badge variant="outline" className="border-amber-400/20 text-amber-300">{d.stage}</Badge></div><p className="mt-1 truncate text-xs text-slate-500">{d.event} · {d.reason}</p></div><div className="hidden text-right sm:block"><p className="text-xs text-slate-400">{d.age}</p><p className="text-xs text-slate-600">{d.attempts} replays</p></div><Button size="sm" variant="outline" className="border-slate-600 bg-transparent"><RefreshCcw size={14}/>Replay</Button></div>)}</CardContent></Card><Card className="panel"><CardHeader><p className="eyebrow">Promotion gates</p><CardTitle>Application readiness</CardTitle></CardHeader><CardContent className="space-y-4">{readiness.map(r=><div key={r.app}><div className="mb-2 flex items-center justify-between text-sm"><span className="text-slate-200">{r.app}</span><span className={r.state==="Ready"?"text-emerald-300":r.state==="Blocked"?"text-amber-300":"text-violet-300"}>{r.passed}/{r.total} · {r.state}</span></div><Progress value={r.passed/r.total*100} className="h-1.5 bg-slate-800"/></div>)}</CardContent></Card></div><div className="grid gap-4 md:grid-cols-3"><Metric label="Delivery success" value="99.94%" note="30-day signed-event delivery" icon={Webhook}/><Metric label="Dead letters" value="3" note="None are security failures" icon={TriangleAlert}/><Metric label="Budget used" value="£0.00" note="Simulation mode remains active" icon={CircleDollarSign}/></div></TabsContent>
          <TabsContent value="connections" className="mt-5"><div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card className="panel"><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Bridges and webhooks</p><CardTitle>Application connections</CardTitle></div><Button><Plus size={15}/>Register app</Button></CardHeader><CardContent className="space-y-3">{connections.map(c=><div className="connection-row" key={c.app}><div className="connection-icon"><Webhook size={18}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-medium text-white">{c.app}</p><Badge variant="outline" className={c.state==="Healthy"?"border-emerald-400/20 text-emerald-300":c.state==="Attention"?"border-amber-400/20 text-amber-300":"border-violet-400/20 text-violet-300"}>{c.state}</Badge></div><p className="mt-1 truncate font-mono text-xs text-slate-500">{c.endpoint}</p></div><div className="hidden text-right sm:block"><p className="text-sm text-slate-300">{c.delivery}</p><p className="text-xs text-slate-500">delivery · {c.events} events</p></div><Button variant="ghost" size="icon"><ChevronRight size={16}/></Button></div>)}</CardContent></Card><Card className="panel"><CardHeader><p className="eyebrow">Security standard</p><CardTitle>Bridge policy</CardTitle></CardHeader><CardContent className="space-y-3"><Policy icon={KeyRound} title="HMAC signatures" text="Every inbound event is signed and timestamped."/><Policy icon={RefreshCcw} title="Safe retries" text="Idempotency keys prevent duplicate actions."/><Policy icon={Route} title="Least privilege" text="Each app can call only approved workflows."/><Policy icon={Database} title="Data boundaries" text="Source records remain inside their product."/></CardContent></Card></div></TabsContent>
          <TabsContent value="approvals" className="mt-5"><Card className="panel"><CardHeader><p className="eyebrow">Human oversight</p><CardTitle>Approval centre</CardTitle></CardHeader><CardContent className="grid gap-3">{approvals.map(a=><div key={a.title} className="full-approval"><div className="flex items-center gap-3"><div className="approval-icon"><FileCheck2 size={16}/></div><div><p className="font-medium text-white">{a.title}</p><p className="mt-1 text-sm text-slate-500">{a.app} · owner: {a.owner}</p></div></div><div className="flex items-center gap-3"><Badge variant="outline" className="border-slate-600 text-slate-300">{a.risk}</Badge>{resolved.includes(a.title)?<span className="flex items-center gap-1 text-sm text-emerald-300"><CheckCircle2 size={15}/>Reviewed</span>:<Button size="sm" onClick={()=>setResolved(v=>[...v,a.title])}>Review</Button>}</div></div>)}</CardContent></Card></TabsContent>
          <TabsContent value="audit" className="mt-5"><Card className="panel"><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Immutable activity trail</p><CardTitle>Audit and governance</CardTitle></div><Button variant="outline" className="border-slate-600 bg-transparent">Export evidence</Button></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Actor</TableHead><TableHead>Action</TableHead><TableHead>Resource</TableHead><TableHead>Outcome</TableHead></TableRow></TableHeader><TableBody>{auditEntries.map(row=><TableRow key={row.join("-")}>{row.map((v,i)=><TableCell key={v} className={i===2?"font-mono text-xs text-violet-300":i===3?"font-medium text-white":""}>{v}</TableCell>)}</TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
          <TabsContent value="scale" className="mt-5 space-y-5"><div className="scale-hero"><div><p className="eyebrow">Shared intelligence · isolated data</p><h2>One control plane, every SaaS</h2><p>Reusable workflows, schedules, callbacks and policies—with each product and customer kept inside its own boundary.</p></div><div className="scale-score"><span>397</span><small>isolated tenants</small></div></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="panel"><CardHeader><p className="eyebrow">Tenant registry</p><CardTitle>Portfolio data boundaries</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Product</TableHead><TableHead>Tenants</TableHead><TableHead>Region</TableHead><TableHead>Boundary</TableHead><TableHead>Policy</TableHead></TableRow></TableHeader><TableBody>{portfolioScale.map(r=><TableRow key={r.product}><TableCell className="font-medium text-white">{r.product}</TableCell><TableCell>{r.tenants}</TableCell><TableCell>{r.region}</TableCell><TableCell><Badge variant="outline" className="border-emerald-400/20 text-emerald-300">{r.boundary}</Badge></TableCell><TableCell>{r.policies}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card className="panel"><CardHeader><p className="eyebrow">Outbound bridge</p><CardTitle>Secure callback delivery</CardTitle></CardHeader><CardContent className="space-y-3"><Policy icon={LockKeyhole} title="HTTPS allowlist" text="Callbacks can reach only approved product domains."/><Policy icon={KeyRound} title="Signed results" text="Each response has its own timestamp, secret and idempotency key."/><Policy icon={RefreshCcw} title="Delivery recovery" text="Retry queues isolate failures without repeating business actions."/><Policy icon={ShieldCheck} title="Tenant scope" text="Every callback carries only the originating tenant's result."/></CardContent></Card></div><div className="grid gap-5 xl:grid-cols-2"><Card className="panel"><CardHeader><p className="eyebrow">Scheduled intelligence</p><CardTitle>Portfolio schedules</CardTitle></CardHeader><CardContent className="space-y-2">{schedules.map(s=><div className="schedule-row" key={s[0]}><Clock3 size={16}/><div className="flex-1"><p>{s[0]}</p><span>{s[1]} · {s[2]}</span></div><Badge variant="outline" className={s[3]==="Active"?"border-emerald-400/20 text-emerald-300":"border-violet-400/20 text-violet-300"}>{s[3]}</Badge></div>)}</CardContent></Card><Card className="panel"><CardHeader><p className="eyebrow">Reusable governance</p><CardTitle>Industry policy packs</CardTitle></CardHeader><CardContent className="space-y-2">{policyPacks.map(p=><div className="schedule-row" key={p[0]}><ShieldCheck size={16}/><div className="flex-1"><p>{p[0]}</p><span>{p[2]}</span></div><span className="text-xs text-slate-400">{p[1]}</span></div>)}</CardContent></Card></div></TabsContent>
          <TabsContent value="commercial" className="mt-5 space-y-5"><div className="commercial-hero"><Badge className="border-0 bg-white/10 text-white">Omniqora Intelligence</Badge><h2>Turn the internal intelligence layer into a client add-on.</h2><p>Sell an industry-specific AI operations module inside each iTechLounge SaaS—or offer it directly to outside businesses—with central control, separate subscriptions and strict tenant isolation.</p><div className="mt-5 flex flex-wrap gap-2"><Button>Onboard client</Button><Button variant="outline" className="border-white/20 bg-white/5">Create industry pack</Button></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{commercialPlans.map(p=><Card className="plan-card" key={p.name}><CardHeader><p className="eyebrow">{p.for}</p><CardTitle>{p.name}</CardTitle></CardHeader><CardContent><p className="plan-price">{p.price}</p><p className="plan-features">{p.features}</p><Button variant="outline" className="mt-5 w-full border-slate-600 bg-transparent">Configure</Button></CardContent></Card>)}</div><div className="grid gap-5 xl:grid-cols-3"><Card className="panel"><CardHeader><CardTitle>Embedded add-on</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-slate-400">Dishbee, Haccora, Cirqiva and every other SaaS shows its own branded intelligence area. Clients never need to enter the internal control plane.</p></CardContent></Card><Card className="panel"><CardHeader><CardTitle>Direct business portal</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-slate-400">Outside businesses can buy an Omniqora industry pack with their own workspace, users, workflows, approvals and reports.</p></CardContent></Card><Card className="panel"><CardHeader><CardTitle>White-label option</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-slate-400">Larger clients can use their own logo, accent colour, support address and domain while iTechLounge operates the shared engine.</p></CardContent></Card></div></TabsContent>
          <TabsContent value="access" className="mt-5"><div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card className="panel"><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Internal access</p><CardTitle>Roles and permissions</CardTitle></div><Button><Users size={15}/>Invite member</Button></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Member</TableHead><TableHead>Role</TableHead><TableHead>Scope</TableHead><TableHead>Permission</TableHead></TableRow></TableHeader><TableBody>{team.map(r=><TableRow key={r[0]}>{r.map((v,i)=><TableCell key={v} className={i===0?"font-medium text-white":""}>{v}</TableCell>)}</TableRow>)}</TableBody></Table></CardContent></Card><Card className="panel"><CardHeader><p className="eyebrow">Protection</p><CardTitle>Access safeguards</CardTitle></CardHeader><CardContent className="space-y-3"><Policy icon={LockKeyhole} title="Internal only" text="Access is restricted to approved team members."/><Policy icon={ShieldCheck} title="Two-person controls" text="High-risk actions require a second approver."/><Policy icon={Activity} title="Complete audit" text="Every view, decision and change is attributed."/></CardContent></Card></div></TabsContent>
        </Tabs></section></main></div>;
}
function Policy({icon:Icon,title,text}:{icon:typeof Activity;title:string;text:string}) { return <div className="policy-row"><div className="policy-icon"><Icon size={16}/></div><div><p className="text-sm font-medium text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>; }
function AppTable({ rows }: { rows: AppRecord[] }) { return <Table><TableHeader><TableRow><TableHead>Application</TableHead><TableHead>Industry</TableHead><TableHead>Agents</TableHead><TableHead>Events · 30d</TableHead><TableHead>Health</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{rows.map(a=><TableRow key={a.name}><TableCell><div className="flex items-center gap-3"><div className="app-initial">{a.name.slice(0,2).toUpperCase()}</div><span className="font-medium text-white">{a.name}</span></div></TableCell><TableCell>{a.sector}</TableCell><TableCell>{a.agents}</TableCell><TableCell>{a.events}</TableCell><TableCell><div className="flex items-center gap-2"><Progress value={a.health} className="h-1.5 w-16 bg-slate-800"/><span>{a.health}%</span></div></TableCell><TableCell><Status value={a.status}/></TableCell></TableRow>)}</TableBody></Table>; }
