import { useEffect,useState,useCallback, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import { TransformationWorkspace } from '../../../src/modules/transformation/TransformationWorkspace';
import './standalone.css';
type User={id:string;tenant:string;email:string;csrf:string;enabled:boolean};
function App(){
 const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);
 async function me(){const r=await fetch('/api/me',{credentials:'same-origin'});if(r.ok)setUser(await r.json());else if(r.status!==401)throw Error('Unable to check your session');}
 useEffect(()=>{me().catch(e=>setError(String(e.message))).finally(()=>setLoading(false));},[]);
 async function login(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{const r=await fetch('/api/login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw Error(data.error);setPassword('');await me();}catch(e){setError(e instanceof Error?e.message:'Sign-in failed');}finally{setBusy(false);}}
 const api=useCallback(async(command:string,projectId?:string,data:Record<string,unknown>={})=>{const r=await fetch('/api/rpc',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':user?.csrf||''},body:JSON.stringify({command,project_id:projectId,data})});const value=await r.json();if(!r.ok){if(r.status===401)setUser(null);throw Error(value.error||'Request failed');}return value;},[user]);
 async function logout(){try{const r=await fetch('/api/logout',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':user?.csrf||''},body:'{}'});if(!r.ok)throw Error('Unable to sign out');setUser(null);}catch(e){setError(String(e));}}
 if(loading)return <main className="auth"><p role="status">Opening your workspace…</p></main>;
 if(!user)return <main className="auth"><div className="auth-story"><span className="auth-mark">B360</span><h1>Understand the whole business.</h1><p>Discover its people and processes. Connect the evidence. Build a practical plan for what comes next.</p><ol><li>Business & departments</li><li>People & stakeholders</li><li>Discovery & assessment</li><li>Improvement & transaction plans</li></ol></div><section className="auth-card"><span className="auth-kicker">BUSINESS360</span><h2>Welcome back</h2><p>Sign in to your organisation’s workspace.</p><form onSubmit={login}><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="auth-error">{error}</p>}<button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><small>Access is provided by your workspace administrator.</small></section></main>;
 return <><header className="standalone-bar"><strong>Business360 <span>by Omniqora</span></strong><div><span>{user.email}</span><button onClick={logout}>Sign out</button></div></header>{error&&<p role="alert" className="auth-error">{error}</p>}<main className="standalone-main">{user.enabled?<TransformationWorkspace key={user.tenant} api={api} standalone/>:<section className="auth-card"><h2>Workspace activation required</h2><p>Your administrator needs to enable Business360 for this organisation.</p></section>}</main></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
