import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
const uuid=z.string().uuid();
const scope=z.object({tenantId:uuid,productKey:z.string().min(2).max(80)});
export const getCommerceWorkspace=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.infer<typeof scope>)=>scope.parse(i)).handler(async({context,data})=>{const db=context.supabase as any;const rs=await Promise.all([
 db.from("marketplace_vendors").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("name"),
 db.from("marketplace_listings").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("title"),
 db.from("marketplace_orders").select("*,items:marketplace_order_items(*),settlements:marketplace_vendor_settlements(*)").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("created_at",{ascending:false}).limit(100),
 db.from("inventory_items").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("name"),
 db.from("inventory_stock_locations").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("name"),
 db.from("booking_services").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("name"),
 db.from("loyalty_programmes").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("name"),
 db.from("payment_intents").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("created_at",{ascending:false}).limit(100)
 ]);for(const r of rs)if(r.error)throw new Error(r.error.message);return{vendors:rs[0].data??[],listings:rs[1].data??[],orders:rs[2].data??[],items:rs[3].data??[],stockLocations:rs[4].data??[],bookingServices:rs[5].data??[],loyaltyProgrammes:rs[6].data??[],payments:rs[7].data??[]};});
const vendor=scope.extend({name:z.string().trim().min(1).max(160),vendorKey:z.string().regex(/^[a-z0-9-]{1,100}$/),brandId:uuid.nullish(),commissionBps:z.number().int().min(0).max(10000).default(0)});
export const createMarketplaceVendor=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof vendor>)=>vendor.parse(i)).handler(async({context,data})=>{const{data:row,error}=await(context.supabase as any).from("marketplace_vendors").insert({tenant_id:data.tenantId,product_key:data.productKey,name:data.name,vendor_key:data.vendorKey,brand_id:data.brandId??null,commission_bps:data.commissionBps}).select("*").single();if(error)throw new Error(error.message);return row;});
const stock=scope.extend({name:z.string().min(1).max(160),locationName:z.string().min(1).max(160),externalRef:z.string().min(1).max(160),sku:z.string().max(100).nullish(),quantity:z.number().nonnegative()});
export const createStockItem=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof stock>)=>stock.parse(i)).handler(async({context,data})=>{const db=context.supabase as any;let loc=await db.from("inventory_stock_locations").select("id").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).eq("name",data.locationName).maybeSingle();if(loc.error)throw new Error(loc.error.message);if(!loc.data){loc=await db.from("inventory_stock_locations").insert({tenant_id:data.tenantId,product_key:data.productKey,name:data.locationName,location_kind:"kitchen"}).select("id").single();if(loc.error)throw new Error(loc.error.message);}
 const item=await db.from("inventory_items").insert({tenant_id:data.tenantId,product_key:data.productKey,external_ref:data.externalRef,sku:data.sku??null,name:data.name,track_stock:true}).select("*").single();if(item.error)throw new Error(item.error.message);
 const mv=await db.rpc("inventory_record_movement",{_tenant:data.tenantId,_item:item.data.id,_location:loc.data.id,_type:"receipt",_quantity:data.quantity,_source_ref:"opening:"+item.data.id,_unit_cost:null,_currency:null});if(mv.error)throw new Error(mv.error.message);return{item:item.data,stockLocationId:loc.data.id};});
const listing=scope.extend({vendorId:uuid,inventoryItemId:uuid.nullish(),stockLocationId:uuid.nullish(),title:z.string().min(1).max(200),externalRef:z.string().max(160).nullish(),priceMinor:z.number().int().min(0),currency:z.string().regex(/^[A-Z]{3}$/).default("GBP"),trackInventory:z.boolean().default(false)});
export const createMarketplaceListing=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof listing>)=>listing.parse(i)).handler(async({context,data})=>{const{data:row,error}=await(context.supabase as any).from("marketplace_listings").insert({tenant_id:data.tenantId,product_key:data.productKey,vendor_id:data.vendorId,inventory_item_id:data.inventoryItemId??null,stock_location_id:data.stockLocationId??null,title:data.title,external_ref:data.externalRef??null,price_minor:data.priceMinor,currency:data.currency,inventory_tracked:data.trackInventory,status:"active"}).select("*").single();if(error)throw new Error(error.message);return row;});
const order=scope.extend({buyerRef:z.string().min(1).max(200),items:z.array(z.object({listingId:uuid,quantity:z.number().positive()})).min(1),idempotencyKey:z.string().min(8).max(160)});
export const createMarketplaceOrder=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof order>)=>order.parse(i)).handler(async({context,data})=>{const r=await(context.supabase as any).rpc("marketplace_create_order",{_tenant:data.tenantId,_product:data.productKey,_buyer:data.buyerRef,_items:data.items,_idempotency:data.idempotencyKey,_metadata:{}});if(r.error)throw new Error(r.error.message);return{orderId:r.data as string};});
const programme=scope.extend({name:z.string().min(1).max(160),loyaltyCurrency:z.enum(["points","stamps","credit"]).default("points")});
export const createLoyaltyProgramme=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof programme>)=>programme.parse(i)).handler(async({context,data})=>{const{data:row,error}=await(context.supabase as any).from("loyalty_programmes").insert({tenant_id:data.tenantId,product_key:data.productKey,name:data.name,loyalty_currency:data.loyaltyCurrency}).select("*").single();if(error)throw new Error(error.message);return row;});
