import {workspace,requireRole,sameOrigin,readBody,rows,one,stmt,db,auditStmt,product,now,id,fail,apiError} from '@/lib/server';
import {parsePlanning,planKinds} from '@/lib/planning';
import {boundedText} from '@/lib/policy';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const {w}=await workspace();const pid=new URL(req.url).searchParams.get('productId');if(!pid)fail('Choose a product.');await product(w.id,pid);const admin=['owner','admin'].includes(w.role);const [records,scenarios,sales]=await Promise.all([rows("SELECT * FROM planning_records WHERE workspace_id=? AND product_id=? AND (?=1 OR kind NOT IN ('shifts','compliance')) ORDER BY kind,record_key LIMIT 10001",w.id,pid,admin?1:0),rows('SELECT * FROM planning_scenarios WHERE workspace_id=? AND product_id=? ORDER BY updated_at DESC LIMIT 50',w.id,pid),rows('SELECT * FROM sales WHERE workspace_id=? AND product_id=? ORDER BY date DESC LIMIT 10001',w.id,pid)]);return Response.json({records:records.slice(0,10000).map(r=>({...r,data:JSON.parse(r.data)})),scenarios,sales:sales.slice(0,10000),peopleAccess:admin,truncated:records.length>10000||sales.length>10000},{headers:{'Cache-Control':'no-store'}});}catch(e){return apiError(e);}}
export async function POST(req:Request){try{sameOrigin(req);const {w,user}=await workspace();requireRole(w,['owner','admin','operator']);const b=await readBody(req,250000);const p=await product(w.id,b.productId);if(b.action==='import'){if(!planKinds.includes(b.kind)||typeof b.csv!=='string')fail('Choose a dataset and add CSV data.');if(['shifts','compliance'].includes(b.kind))requireRole(w,['owner','admin']);let parsed;try{parsed=parsePlanning(b.kind,b.csv)}catch(e:any){fail(e.message)}const t=now();await db().batch([...parsed.map(r=>stmt('INSERT INTO planning_records(id,workspace_id,product_id,kind,record_key,data,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(workspace_id,product_id,kind,record_key) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at',id(),w.id,p.id,b.kind,r.key,JSON.stringify(r.data),t)),auditStmt(w.id,user.email,'planning.imported',parsed.length+' '+b.kind+' records imported',p.id)]);return Response.json({count:parsed.length});}
 if(b.action==='delete_record'){const r=await one('SELECT * FROM planning_records WHERE id=? AND workspace_id=? AND product_id=?',b.id,w.id,p.id);if(!r)fail('Record not found.',404);if(['shifts','compliance'].includes(r.kind))requireRole(w,['owner','admin']);const result=await stmt('DELETE FROM planning_records WHERE id=? AND workspace_id=? AND product_id=? AND updated_at=?',b.id,w.id,p.id,b.updatedAt).run();if(!result.meta.changes)fail('This record changed. Refresh and review it.',409);return Response.json({ok:true});}
 if(b.action==='save_scenario'){const name=boundedText(b.name,100);if(!name)fail('Name the scenario.');const a=b.assumptions;if(!a||typeof a!=='object'||!Number.isInteger(a.horizon)||a.horizon<7||a.horizon>90||!Number.isFinite(a.demand)||a.demand< -90||a.demand>200||!Number.isInteger(a.delay)||a.delay<0||a.delay>90||!Number.isSafeInteger(a.opening)||Math.abs(a.opening)>1e11||!['GBP','EUR','USD','AED'].includes(a.currency)||typeof a.location!=='string'||a.location.length>100)fail('Use valid scenario assumptions.');const clean=JSON.stringify({horizon:a.horizon,demand:a.demand,delay:a.delay,opening:a.opening,currency:a.currency,location:a.location});if(b.id){const result=await stmt('UPDATE planning_scenarios SET name=?,assumptions=?,revision=revision+1,updated_at=? WHERE id=? AND workspace_id=? AND product_id=? AND revision=?',name,clean,now(),b.id,w.id,p.id,b.revision).run();if(!result.meta.changes)fail('This scenario changed. Reload it before saving.',409);return Response.json({ok:true});}const sid=id();await stmt('INSERT INTO planning_scenarios(id,workspace_id,product_id,name,assumptions,updated_at) VALUES(?,?,?,?,?,?)',sid,w.id,p.id,name,clean,now()).run();return Response.json({id:sid});}
 fail('Unknown planning action.');}catch(e){return apiError(e);}}
