import {env} from 'cloudflare:workers';
import {bootstrap,workspace,sameOrigin,readBody,importPortfolio,product,one,rows,stmt,db,auditStmt,auditLog,now,id,fail,apiError,createRun,decide,randomToken,tokenHash,requireRole} from '@/lib/server';
import {getTemplate} from '@/lib/catalog';
import {boundedText,MODES} from '@/lib/policy';
import {executeRun} from '@/lib/runner';
export const dynamic='force-dynamic';
export async function GET(){try{return Response.json(await bootstrap(),{headers:{'Cache-Control':'no-store'}});}catch(e){return apiError(e);}}
export async function POST(req:Request){try{sameOrigin(req);const {w,user}=await workspace();const b=await readBody(req);const actor=user.email;
const adminActions=['import_portfolio','save_product','save_settings','create_integration','revoke_integration','invite_member','remove_member'];
if(adminActions.includes(b.action))requireRole(w,['owner','admin']);
if(!['switch_workspace','create_workspace'].includes(b.action))requireRole(w,['owner','admin','operator']);
switch(b.action){
 case 'create_workspace':{const name=boundedText(b.name,100);if(!name)fail('Enter a company name.');const count=await one('SELECT COUNT(*) AS n FROM workspaces WHERE owner_id=?',user.userId);if(count&&count.n>=100)fail('The company workspace limit has been reached.',409);const wid=id();await db().batch([stmt('INSERT INTO workspaces(id,owner_id,name,kind,created_at) VALUES(?,?,?,?,?)',wid,user.userId,name,b.kind==='client'?'client':'internal',now()),stmt('INSERT INTO members(id,workspace_id,user_id,email,role,created_at) VALUES(?,?,?,?,?,?)',id(),wid,user.userId,user.email,'owner',now()),auditStmt(wid,actor,'workspace.created',name,wid)]);return Response.json({ok:true},{headers:{'Set-Cookie':'lai_workspace='+wid+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=31536000'}});}
 case 'switch_workspace':{const target=await one('SELECT w.id FROM workspaces w LEFT JOIN members m ON m.workspace_id=w.id AND m.user_id=? WHERE w.id=? AND (w.owner_id=? OR m.user_id=?)',user.userId,b.id,user.userId,user.userId);if(!target)fail('Company workspace not found.',404);return Response.json({ok:true},{headers:{'Set-Cookie':'lai_workspace='+target.id+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=31536000'}});}
 case 'invite_member':{const email=boundedText(b.email,200).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!['admin','operator','viewer'].includes(b.role))fail('Enter a valid email and role.');const token=randomToken();await db().batch([stmt('INSERT INTO invitations(id,workspace_id,email,role,token_hash,expires_at,created_at) VALUES(?,?,?,?,?,?,?)',id(),w.id,email,b.role,await tokenHash(token),new Date(Date.now()+7*86400000).toISOString(),now()),auditStmt(w.id,actor,'member.invited',email)]);return Response.json({token});}
 case 'remove_member':{const member=await one('SELECT * FROM members WHERE id=? AND workspace_id=?',b.id,w.id);if(!member||member.role==='owner'||member.user_id===user.userId)fail('This member cannot be removed.');await db().batch([stmt('DELETE FROM members WHERE id=? AND workspace_id=?',b.id,w.id),auditStmt(w.id,actor,'member.removed',member.email,b.id)]);return Response.json({ok:true});}
 case 'import_portfolio':await importPortfolio(w.id,actor);return Response.json({ok:true});
 case 'save_product':{const name=boundedText(b.name,80),description=boundedText(b.description,1000),sector=boundedText(b.sector,80)||'Other';if(!name)fail('Enter a product name.');if(!getTemplate(b.templateId))fail('Choose an agent template.');if(!MODES.includes(b.mode))fail('Choose a valid agent mode.');if(b.id){await product(w.id,b.id);await db().batch([stmt('UPDATE products SET name=?,description=?,sector=?,template_id=?,mode=?,enabled=?,instructions=?,scope=? WHERE id=? AND workspace_id=?',name,description,sector,b.templateId,b.mode,b.enabled?1:0,boundedText(b.instructions,4000),b.scope==='review'?'review':'confirmed',b.id,w.id),auditStmt(w.id,actor,'product.updated',name,b.id)]);}else{const pid=id();await db().batch([stmt('INSERT INTO products(id,workspace_id,slug,name,sector,description,color,scope,template_id,mode,enabled,instructions,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',pid,w.id,name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+pid.slice(0,5),name,sector,description,'#5265b9','confirmed',b.templateId,b.mode,1,boundedText(b.instructions,4000),now()),auditStmt(w.id,actor,'product.created',name,pid)]);}return Response.json({ok:true});}
 case 'create_run':{const run=await createRun(w,actor,b);return Response.json({run});}
 case 'execute_run':return Response.json({run:await executeRun(w.id,actor,b.id)});
 case 'cancel_run':{const r=await one('SELECT * FROM runs WHERE id=? AND workspace_id=?',b.id,w.id);if(!r)fail('Run not found.',404);if(!['queued','failed'].includes(r.status))fail('Only queued or failed runs can be cancelled.',409);await db().batch([stmt("UPDATE runs SET status='cancelled',updated_at=? WHERE id=? AND workspace_id=? AND status IN ('queued','failed')",now(),b.id,w.id),auditStmt(w.id,actor,'run.cancelled',r.title,b.id)]);return Response.json({ok:true});}
 case 'recover_run':{const cutoff=new Date(Date.now()-5*60*1000).toISOString();const result=await stmt("UPDATE runs SET status='failed',error='Run interrupted. Review and retry.',updated_at=? WHERE id=? AND workspace_id=? AND status='running' AND updated_at<?",now(),b.id,w.id,cutoff).run();if(!result.meta.changes)fail('Only a run with no activity for five minutes can be recovered.',409);await auditLog(w.id,actor,'run.recovered','Interrupted run made available for retry',b.id);return Response.json({ok:true});}
 case 'decide':await decide(w.id,actor,b.id,b.decision,b.note||'');return Response.json({ok:true});
 case 'task_status':{if(!['open','completed','draft'].includes(b.status))fail('Invalid task status.');const t=await one('SELECT * FROM tasks WHERE id=? AND workspace_id=?',b.id,w.id);if(!t)fail('Task not found.',404);await db().batch([stmt('UPDATE tasks SET status=?,updated_at=? WHERE id=? AND workspace_id=?',b.status,now(),b.id,w.id),auditStmt(w.id,actor,'task.'+b.status,t.title,b.id)]);return Response.json({ok:true});}
 case 'save_settings':{const name=boundedText(b.name,100);const limit=Number(b.runLimit);if(!name||!Number.isInteger(limit)||limit<1||limit>10000)fail('Enter a workspace name and a monthly run limit from 1 to 10,000.');const plan=['pilot','core','operations','enterprise'].includes(b.plan)?b.plan:'pilot';const price=Number(b.monthlyPrice||0);if(!Number.isInteger(price)||price<0||price>100000000)fail('Invalid monthly subscription amount.');const currency=['GBP','EUR','USD','AED'].includes(b.currency)?b.currency:'GBP';await db().batch([stmt('UPDATE workspaces SET name=?,paused=?,run_limit=?,plan=?,monthly_price=?,currency=? WHERE id=?',name,b.paused?1:0,limit,plan,price,currency,w.id),auditStmt(w.id,actor,'workspace.updated',b.paused?'Workspace paused':'Workspace settings saved',w.id)]);return Response.json({ok:true});}
 case 'create_integration':{const p=await product(w.id,b.productId);const token=randomToken(),hash=await tokenHash(token),iid=id();await db().batch([stmt('DELETE FROM integrations WHERE workspace_id=? AND product_id=?',w.id,p.id),stmt('INSERT INTO integrations(id,workspace_id,product_id,name,token_hash,created_at) VALUES(?,?,?,?,?,?)',iid,w.id,p.id,p.name+' API',hash,now()),auditStmt(w.id,actor,'integration.key_created','Created or rotated '+p.name+' integration key',iid)]);return Response.json({token,id:iid});}
 case 'revoke_integration':{const i=await one('SELECT * FROM integrations WHERE id=? AND workspace_id=?',b.id,w.id);if(!i)fail('Integration not found.',404);await db().batch([stmt('DELETE FROM integrations WHERE id=? AND workspace_id=?',b.id,w.id),auditStmt(w.id,actor,'integration.revoked',i.name,b.id)]);return Response.json({ok:true});}
 default:fail('Unknown action.');
}}catch(e){return apiError(e);}}
