import { z } from "zod";
import { authoriseServiceScope,parseServiceAuthorization,verifyServiceSecret,type ServiceCredentialRecord } from "@/modules/platform/service-identity";
const base=z.object({tenantId:z.string().uuid(),productKey:z.string().min(2),agentId:z.string().uuid()});
const schema=z.discriminatedUnion("operation",[
 base.extend({operation:z.literal("jobs.list")}),
 base.extend({operation:z.literal("position.update"),jobId:z.string().uuid().nullish(),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),accuracyMetres:z.number().nonnegative().nullish(),speedKph:z.number().nonnegative().nullish(),headingDegrees:z.number().min(0).max(359.999).nullish(),observedAt:z.string().datetime()}),
 base.extend({operation:z.literal("job.status"),jobId:z.string().uuid(),status:z.enum(["accepted","en_route","arrived","in_progress","collected","en_route_dropoff","arrived_dropoff","completed","failed"])})
]);
function reply(b:unknown,s=200){return Response.json(b,{status:s,headers:{"cache-control":"no-store"}})}
async function auth(req:Request){const{keyId,secret}=parseServiceAuthorization(req.headers.get("authorization"));const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const db=supabaseAdmin as any;const{data:r}=await db.from("platform_service_credentials").select("*").eq("key_id",keyId).maybeSingle();if(!r||!verifyServiceSecret(secret,r.secret_hash))throw new Error("Service credential refused");const scopes=z.array(z.object({tenantId:z.string().uuid(),productKey:z.string(),brandIds:z.array(z.string()).optional(),locationIds:z.array(z.string()).optional(),capabilities:z.array(z.string())})).parse(r.scopes);return{db,credential:{id:r.id,keyId:r.key_id,secretHash:r.secret_hash,status:r.status,expiresAt:r.expires_at,scopes} as ServiceCredentialRecord};}
export async function serveAgent(request:Request){try{const input=schema.parse(await request.json());const{db,credential}=await auth(request);const cap=input.operation==="jobs.list"?"agent.jobs.read":input.operation==="position.update"?"agent.location.write":"agent.jobs.write";authoriseServiceScope(credential,{tenantId:input.tenantId,productKey:input.productKey,capability:cap});const ar=await db.from("dispatch_agents").select("id").eq("id",input.agentId).eq("tenant_id",input.tenantId).eq("product_key",input.productKey).maybeSingle();if(ar.error||!ar.data)throw new Error("Agent scope refused");
 if(input.operation==="jobs.list"){const{data,error}=await db.from("dispatch_jobs").select("*,stops:dispatch_job_stops(*)").eq("tenant_id",input.tenantId).eq("product_key",input.productKey).eq("assigned_agent_id",input.agentId).not("status","in","(completed,failed,cancelled)").order("scheduled_at");if(error)throw new Error(error.message);return reply({jobs:data??[]});}
 if(input.operation==="position.update"){const{error}=await db.from("dispatch_agent_positions").insert({tenant_id:input.tenantId,product_key:input.productKey,agent_id:input.agentId,job_id:input.jobId??null,latitude:input.latitude,longitude:input.longitude,accuracy_metres:input.accuracyMetres??null,speed_kph:input.speedKph??null,heading_degrees:input.headingDegrees??null,observed_at:input.observedAt});if(error)throw new Error(error.message);if(input.jobId)await db.from("tracking_snapshots").upsert({tenant_id:input.tenantId,subject_type:"dispatch_job",subject_id:input.jobId,status:"en_route",latitude:input.latitude,longitude:input.longitude,heading:input.headingDegrees??null,revision:Date.now(),updated_at:new Date().toISOString()},{onConflict:"tenant_id,subject_type,subject_id"});return reply({ok:true});}
 const{error}=await db.rpc("dispatch_update_status",{_job:input.jobId,_status:input.status});if(error)throw new Error(error.message);await db.from("tracking_snapshots").upsert({tenant_id:input.tenantId,subject_type:"dispatch_job",subject_id:input.jobId,status:input.status,revision:Date.now(),updated_at:new Date().toISOString()},{onConflict:"tenant_id,subject_type,subject_id"});return reply({ok:true});
 }catch(e){if(e instanceof z.ZodError)return reply({error:"Invalid agent contract"},422);const m=e instanceof Error?e.message:"Agent request refused";return reply({error:m},/credential|scope/i.test(m)?403:503)}}
