import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { createHash } from "node:crypto";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
const uuid=z.string().uuid();
export const listDispatch=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{tenantId:string})=>z.object({tenantId:uuid}).parse(i)).handler(async({context,data})=>{const db=context.supabase as any;const[jobs,agents,vehicles]=await Promise.all([db.from("dispatch_jobs").select("*,stops:dispatch_job_stops(*)").eq("tenant_id",data.tenantId).order("created_at",{ascending:false}).limit(200),db.from("dispatch_agents").select("*").eq("tenant_id",data.tenantId).order("name"),db.from("dispatch_vehicles").select("*").eq("tenant_id",data.tenantId).order("registration")]);for(const r of[jobs,agents,vehicles])if(r.error)throw new Error(r.error.message);return{jobs:jobs.data??[],agents:agents.data??[],vehicles:vehicles.data??[]};});
const create=z.object({tenantId:uuid,productKey:z.string(),locationId:uuid.nullish(),jobType:z.string().min(1),priority:z.enum(["low","normal","high","urgent"]).default("normal"),externalRef:z.string().max(200).nullish(),stops:z.array(z.object({kind:z.enum(["pickup","dropoff","service","return"]),lat:z.number(),lng:z.number(),address:z.string().optional(),contactName:z.string().optional(),contactPhone:z.string().optional(),instructions:z.string().optional()})).min(1)});
export const createDispatchJob=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof create>)=>create.parse(i)).handler(async({context,data})=>{const r=await(context.supabase as any).rpc("dispatch_create_job",{_tenant:data.tenantId,_product:data.productKey,_location:data.locationId??null,_job_type:data.jobType,_priority:data.priority,_external_ref:data.externalRef??null,_metadata:{},_stops:data.stops});if(r.error)throw new Error(r.error.message);return{jobId:r.data as string};});
export const createTrackingToken=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{tenantId:string;subjectType:string;subjectId:string;hours?:number})=>z.object({tenantId:uuid,subjectType:z.string().min(1).max(80),subjectId:z.string().min(1).max(200),hours:z.number().int().min(1).max(168).default(24)}).parse(i)).handler(async({context,data})=>{const db=context.supabase as any;const token=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,"0")).join("");const hash=createHash("sha256").update(token).digest("hex");const exp=new Date(Date.now()+data.hours*3600000).toISOString();const{error}=await db.from("public_tracking_tokens").insert({tenant_id:data.tenantId,subject_type:data.subjectType,subject_id:data.subjectId,token_hash:hash,expires_at:exp});if(error)throw new Error(error.message);return{token,expiresAt:exp};});
