import {env} from 'cloudflare:workers';
import {workspace,requireRole,sameOrigin,one,stmt,db,id,fail,apiError} from '@/lib/server';
import {MAX_AUDIO_BYTES,MAX_TRANSCRIPT_CHARS,audioFileType,speechLanguages} from '@/lib/speech';
export const dynamic='force-dynamic';
function settings(){const n=Number(env.SPEECH_MONTHLY_LIMIT||100);return {limit:Number.isInteger(n)&&n>=0&&n<=10000?n:100,model:env.OPENAI_TRANSCRIBE_MODEL||'gpt-transcribe'};}
export async function GET(){try{const {w}=await workspace(),month=new Date().toISOString().slice(0,7),s=settings();const usage=await one('SELECT requests FROM speech_usage WHERE workspace_id=? AND month=?',w.id,month);return Response.json({connected:!!env.OPENAI_API_KEY,model:s.model,limit:s.limit,used:usage?.requests||0,month,maxBytes:MAX_AUDIO_BYTES,audioRetained:false},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return apiError(e);}}
async function boundedForm(req:Request){const maximum=MAX_AUDIO_BYTES+16384;if(Number(req.headers.get('content-length')||0)>maximum)fail('Use an audio file of up to 2 MB.',413);if(!req.headers.get('content-type')?.startsWith('multipart/form-data;'))fail('Upload audio using the file form.');if(!req.body)fail('Choose an audio file.');const reader=req.body.getReader(),chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maximum){await reader.cancel();fail('Use an audio file of up to 2 MB.',413)}chunks.push(value)}const bytes=new Uint8Array(size);let pos=0;for(const chunk of chunks){bytes.set(chunk,pos);pos+=chunk.length}try{return await new Response(bytes,{headers:{'Content-Type':req.headers.get('content-type')!}}).formData()}catch{fail('The audio upload could not be read.');}}
export async function POST(req:Request){try{sameOrigin(req);const {w}=await workspace();requireRole(w,['owner','admin','operator']);if(w.paused)fail('Speech transcription is paused for this workspace.',409);if(!env.OPENAI_API_KEY)fail('Audio-file transcription is not connected. Use browser dictation or ask the owner to configure the OpenAI service.',409);const s=settings();if(!['gpt-transcribe','gpt-4o-mini-transcribe','gpt-4o-transcribe','whisper-1'].includes(s.model))fail('The configured transcription model is unsupported. Ask the owner to check the service settings.',409);
 const form=await boundedForm(req),file=form.get('audio'),language=String(form.get('language')||'en-GB');if(!file||typeof file==='string'||!file.size||file.size>MAX_AUDIO_BYTES||!audioFileType(file.name,file.type))fail('Choose a supported, non-empty audio file of up to 2 MB.');if(!speechLanguages.some(l=>l.value===language))fail('Choose a supported spoken language.');
 const month=new Date().toISOString().slice(0,7);const reserved=await db().batch([stmt('INSERT OR IGNORE INTO speech_usage(id,workspace_id,month) VALUES(?,?,?)',id(),w.id,month),stmt('UPDATE speech_usage SET requests=requests+1,bytes=bytes+? WHERE workspace_id=? AND month=? AND requests<?',file.size,w.id,month,s.limit)]);if(!reserved[1].meta.changes)fail('This company has reached its monthly audio transcription allowance.',429);
 const payload=new FormData();payload.set('file',file,'recording.'+file.name.toLowerCase().split('.').pop());payload.set('model',s.model);payload.set(s.model==='gpt-transcribe'?'languages[]':'language',language.split('-')[0]);let response:Response;try{response=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:'Bearer '+env.OPENAI_API_KEY},body:payload,signal:AbortSignal.timeout(45000)})}catch{fail('The transcription service did not respond. No automatic retry was made. Try again when the connection is available.',502)}
 if(!response.ok){if(response.status===429)fail('The transcription provider is busy or its allowance is exhausted. Ask the owner to check the service.',503);if(response.status===401||response.status===403)fail('The transcription provider rejected this connection. Ask the owner to check the key and model access.',503);fail('The recording could not be transcribed. Check that it contains readable audio and try again.',502)}let result:any;try{result=await response.json()}catch{fail('The transcription provider returned an unreadable response.',502)}if(typeof result.text!=='string'||!result.text.trim())fail('No transcript was returned. Try a recording with clearer speech.',422);if(result.text.length>MAX_TRANSCRIPT_CHARS)fail('The recording is too long for this form. Use a shorter audio clip.',413);return Response.json({text:result.text,model:s.model,audioRetained:false},{headers:{'Cache-Control':'private, no-store'}});
 }catch(e){return apiError(e);}}
