import { ArrowUpRight, AudioLines, Workflow, BrainCircuit, BookOpen, ChartNoAxesCombined, ShieldCheck, Network, MessagesSquare, Compass, Layers3, Check, Building2 } from 'lucide-react';
import './omniqora-website.css';
import PlatformCatalogue from './PlatformCatalogue';
import EcosystemCatalogue from './EcosystemCatalogue';

const services = [
 {id:'connect',family:'Omniqora Connect',icon:MessagesSquare,title:'Every conversation, with context.',text:'Bring enquiries, customer history and follow-ups into a clear, coordinated service experience.',features:['WhatsApp, social messaging, SMS, email and web chat','CRM, customer records, leads and cases','Aida reply assistance, summaries and translation','SLA management, campaigns and team handoffs'],outcome:'Help the right person respond with the right information.'},
 {id:'voice',family:'Omniqora Voice',icon:AudioLines,title:'A better first response.',text:'Plan voice and reception services around the way your customers contact you and your team works.',features:['AI-assisted reception and enquiry intake','Call routing and human handoff journeys','Booking, order and callback workflows','Call outcomes and service reporting'],outcome:'Reduce avoidable missed enquiries and make follow-ups clearer.',note:'Live telephony and transfers require agreed provider integration.'},
 {id:'flow',family:'Omniqora Flow',icon:Workflow,title:'Less chasing. Clearer progress.',text:'Turn repeatable work into guided steps, with clear responsibilities, approvals and useful reminders.',features:['No-code workflow configuration','Tasks, checklists and approval stages','Department and system handoffs','Daily priorities and exception review'],outcome:'Give work a clear next step and an accountable owner.'},
 {id:'agents',family:'Omniqora Agents',icon:BrainCircuit,title:'AI that helps your team move.',text:'Use specialist assistants to research, prepare, analyse and propose work within an agreed scope.',features:['Sales, service and operational assistants','Research and document-based drafting','Specialist finance and delivery analysis','Human review for consequential actions'],outcome:'Free people to focus on judgement, customers and delivery.'},
 {id:'knowledge',family:'Knowledge & document intelligence',icon:BookOpen,title:'Make business knowledge useful.',text:'Help people find relevant answers across approved business information, with supporting sources close at hand.',features:['Document and policy discovery','Source-linked answers and summaries','Connected business context','Evidence gaps and review workflows'],outcome:'Spend less time searching and more time making informed decisions.'},
 {id:'business360',family:'Omniqora Business360',icon:ChartNoAxesCombined,title:'See the business. Find the opportunities.',text:'Build a structured view of a business or department, then identify what could improve performance.',features:['People, departments, assets and processes','Costs, revenue, margins and cash-flow inputs','Sales, marketing, collections and bottlenecks','Prioritised improvement plans and KPI review'],outcome:'Turn scattered information into a practical, measurable plan.'},
 {id:'transformation',family:'Transformation & transaction planning',icon:Network,title:'Make complex change manageable.',text:'Bring the business, technology and delivery work together for acquisitions, mergers, carve-outs and modernisation.',features:['Current-state and target-state planning','Dependencies, risks and transition costs','Day-1 readiness and 100-day plans','Transition services and accountable workstreams'],outcome:'Give leaders a clearer view of what needs to happen, when and why.'},
 {id:'governance',family:'AI governance, risk & compliance',icon:ShieldCheck,title:'Move forward with oversight.',text:'Structure AI adoption and evidence review so that decisions, responsibilities and unresolved questions stay visible.',features:['AI use-case and adoption registers','Policies, reviews and decision records','Risk, control and evidence mapping','Approval history and progress reporting'],outcome:'Support accountable adoption and better-informed oversight.',note:'Tools support professional review; they do not certify compliance.'},
 {id:'procurement-readiness',family:'Procurement & partner readiness',icon:ShieldCheck,title:'Be prepared for your next contract.',text:'Organise the evidence needed for government procurement, Aramco supply-chain opportunities and investment-bank supplier assessments.',features:['Priority Aramco CCC+ assessment preparation','UK government and US federal readiness packs','Bank supplier due diligence and evidence review','Scoped supplier dossiers, gaps and renewal tracking'],outcome:'Show what your company holds, what it covers and what still needs work.',note:'Readiness support does not issue certificates or guarantee buyer approval. CCC+ requires an Aramco-authorised audit firm.'},
 {id:'revenue',family:'Commerce, revenue & collections',icon:Building2,title:'Connect the work to the cash.',text:'Coordinate customer journeys, commercial operations and payment follow-ups across the tools in your business.',features:['CRM, order and fulfilment coordination','Payment-link and status journeys','Debtor review and collection case preparation','Supplier, stock and operational insights'],outcome:'Identify friction between winning business, delivering it and getting paid.',note:'Payment and collection services depend on authorised provider connections.'},
 {id:'product',family:'Product & decision intelligence',icon:Compass,title:'Build on what you learn.',text:'Connect research, business priorities and delivery evidence to make product and operational decisions clearer.',features:['Discovery, requirements and prioritisation','Roadmaps, acceptance checks and delivery review','Decision journals and reviewed lessons','Adoption, outcomes and benefit tracking'],outcome:'Make the next investment in your business better informed.'},
 {id:'exchange',family:'Omniqora Exchange',icon:Layers3,title:'Bring the right services together.',text:'Extend a platform with relevant services and connections, shaped around the customer journey.',features:['Partner and ecosystem connections','Relevant service discovery and referrals','Embedded tools and branded experiences','Integration planning across business platforms'],outcome:'Add useful capabilities without making customers start again.'},
];
const observations=[
 {tag:'CUSTOMER EXPERIENCE',title:'A missed enquiry is an operational signal.',text:'The useful question is not only how many calls were missed. It is what happened next: who followed up, whether the customer was recognised, and where the handoff broke down.'},
 {tag:'BUSINESS PERFORMANCE',title:'Revenue and cash tell different stories.',text:'A growing sales figure can sit alongside slow invoicing, disputed balances and rising costs. An improvement plan needs to connect the customer journey to delivery, invoicing and collection.'},
 {tag:'BUSINESS CHANGE',title:'Day 1 starts well before Day 1.',text:'A department may look independent on an organisation chart while sharing systems, contracts, people and data. Those dependencies need to be understood before separation or integration.'},
 {tag:'PRACTICAL AI',title:'Start with one useful outcome.',text:'A clear problem, a known owner and a measurable result make a stronger starting point than a long list of AI features. Expand when the evidence supports it.'},
];
export default function OmniqoraWebsite(){return <div className="oq-web" lang="en" dir="ltr">
 <a className="oq-skip" href="#main">Skip to content</a>
 <header className="oq-nav"><a className="oq-logo" href="#top" aria-label="Omniqora home"><img src="/brand/omniqora-mark.svg" width="44" height="44" alt=""/><span>Omniqora</span></a><nav aria-label="Website navigation"><a href="#platform">Platform features</a><a href="#services">Services & add-ons</a><a href="/#pricing">Pricing</a><a href="#ecosystem">Ecosystem</a><a href="#observations">Observations</a><a href="/auth">Sign in</a><a className="oq-nav-contact" href="#contact">Let’s talk <ArrowUpRight size={17}/></a></nav></header>
 <main id="main"><section id="top" className="oq-hero"><div className="oq-hero-copy"><p className="oq-eyebrow">CONNECTED BUSINESS INTELLIGENCE</p><h1>Your business,<br/><span>working as one.</span></h1><p className="oq-lead">Connect your customers, people, knowledge and operations. Use intelligence to see what matters—and turn it into useful action.</p><div className="oq-actions"><a className="oq-button" href="#services">Explore our services <ArrowUpRight size={19}/></a><a className="oq-text-link" href="#contact">Discuss your business</a></div><p className="oq-hero-foot">Standalone solutions · SaaS add-ons · Managed delivery</p></div><div className="oq-hero-panel"><div className="oq-core"><img src="/brand/omniqora-mark.svg" alt="Omniqora connected intelligence mark" width="150" height="150"/><span>ONE CONNECTED VIEW</span></div><div className="oq-journey"><div><span className="oq-step">01</span><div><b>Understand</b><p>The business, its people and its purpose.</p></div></div><div><span className="oq-step">02</span><div><b>Improve</b><p>The journeys, decisions and work that matter.</p></div></div><div><span className="oq-step">03</span><div><b>Move forward</b><p>With a clear plan and accountable delivery.</p></div></div></div></div></section>
 <section className="oq-intro"><p className="oq-eyebrow">INTELLIGENCE WITH A BUSINESS PURPOSE</p><h2>More connected.<br/>More capable.</h2><div><p>Great businesses are built on people, relationships and decisions. Omniqora brings practical intelligence to the work between them.</p><p>Bring WhatsApp, customer conversations, CRM, cases, campaigns and workflows together. Extend that foundation with Business360, knowledge intelligence and transformation services.</p><div className="oq-intro-links"><a className="oq-text-link" href="#platform">Explore platform features <ArrowUpRight size={16}/></a><a className="oq-text-link" href="#ways">Ways to work with us <ArrowUpRight size={16}/></a></div></div></section>
 <PlatformCatalogue />
 <section className="oq-services oq-section" id="services"><div className="oq-section-heading"><div><p className="oq-eyebrow">OUR SERVICES</p><h2>Built around the way<br/>your business works.</h2></div><p>From the first customer conversation to the next stage of business growth.</p></div><div className="oq-service-grid">{services.map(({id,family,icon:Icon,title,text,features,outcome,note},index)=><article className={'oq-service '+(id==='business360'?'oq-featured-service':'')} key={id} id={id}><div className="oq-service-top"><Icon size={27}/><span>{String(index+1).padStart(2,'0')}</span></div><p className="oq-family">{family}</p><h3>{title}</h3><p className="oq-service-description">{text}</p><ul>{features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul><p className="oq-outcome">{outcome}</p>{note&&<p className="oq-service-note">{note}</p>}</article>)}<article className="oq-service oq-start"><p className="oq-eyebrow">NOT SURE WHERE TO START?</p><h3>Start with<br/>your business.</h3><p>Tell us where the friction is. We can help define the right starting point and a realistic path forward.</p><a className="oq-button" href="#contact">Talk through your needs <ArrowUpRight size={18}/></a></article></div><p className="oq-availability">Services are scoped to your requirements. Module availability, integrations and delivery stages are confirmed before an engagement begins.</p></section>
 <EcosystemCatalogue />
 <section className="oq-ways oq-section" id="ways"><div className="oq-section-heading"><div><p className="oq-eyebrow">FLEXIBLE BY DESIGN</p><h2>One capability.<br/>Or a connected whole.</h2></div><p>Use a focused service, or bring selected capabilities together with Omniqora One.</p></div><div className="oq-ways-grid"><article><span>01 / STANDALONE</span><h3>A focused service.</h3><p>Choose a dedicated solution for a specific team, business problem or improvement programme.</p><b>For businesses with a clear starting point.</b></article><article><span>02 / ADD-ON</span><h3>More from your platform.</h3><p>Add relevant Omniqora intelligence and workflows to our SaaS products and apps, with a connected customer experience.</p><b>For customers already using our ecosystem.</b></article><article><span>03 / MANAGED DELIVERY</span><h3>A partner for the change.</h3><p>Combine discovery, planning, implementation and ongoing improvement in an agreed delivery engagement.</p><b>For broader or more complex requirements.</b></article></div><div className="oq-scope-note"><ShieldCheck size={24}/><p>Scope, fees, permissions and third-party connections are agreed around the selected service. You stay in control of the decisions that matter.</p></div></section>
 <section className="oq-business-banner oq-section"><p className="oq-eyebrow">BUSINESS360</p><div><h2>First, understand<br/>the whole picture.</h2><p>Begin with the business and its departments. Map the people and stakeholders. Gather the documents, questions and observations that explain how things really work. Then build the plan.</p></div><ol><li>Business & departments</li><li>People & stakeholders</li><li>Evidence & performance</li><li>Priorities & action</li></ol><p className="oq-business-detail">Reviews can cover workforce and roles, software and phone systems, equipment and other assets, supplier costs, marketing, sales, customer experience and working capital. Short-, medium- and long-term goals keep the recommendations connected to your priorities.</p><a className="oq-text-link" href="#contact">Explore a business or department review <ArrowUpRight size={18}/></a></section>
 <section className="oq-section oq-observations" id="observations"><div className="oq-section-heading"><div><p className="oq-eyebrow">OBSERVATIONS</p><h2>A useful perspective<br/>on the everyday.</h2></div><p>Practical ideas for better-connected businesses.</p></div><div className="oq-observation-grid">{observations.map(o=><article key={o.title}><p className="oq-eyebrow">{o.tag}</p><h3>{o.title}</h3><p>{o.text}</p></article>)}</div></section>
 <section className="oq-about oq-section"><div><p className="oq-eyebrow">PART OF ITECHLOUNGE</p><h2>Business understanding.<br/>Thoughtful technology.</h2></div><div><p>Omniqora brings together specialist services for communication, intelligence, operations and business change.</p><p>Behind it is iTechLounge’s focus on practical software, connected systems and ongoing improvement. Our conversations start with your goals, not a technical specification.</p><a className="oq-text-link" href="https://itechlounge.co.uk" target="_blank" rel="noreferrer">About iTechLounge <ArrowUpRight size={18}/></a></div></section>
 <section className="oq-contact oq-section" id="contact"><p className="oq-eyebrow">LET’S START WITH WHAT MATTERS</p><h2>What would you like<br/>your business to do better?</h2><p>Tell us about your business, the team involved and the outcome you want. We’ll help you shape the next step.</p><a className="oq-button oq-button-light" href="mailto:hello@itechlounge.co.uk?subject=Omniqora%20enquiry">Discuss your requirements <ArrowUpRight size={19}/></a><a className="oq-email" href="mailto:hello@itechlounge.co.uk">hello@itechlounge.co.uk</a></section></main>
 <footer className="oq-footer"><a className="oq-logo" href="#top"><img src="/brand/omniqora-mark.svg" width="35" height="35" alt=""/><span>Omniqora</span></a><p>Your business, working as one.</p><div><a href="/datenschutz">Privacy</a><a href="/agb">Terms</a><span>© 2026 iTechLounge</span></div></footer></div>}
