import { createFileRoute,Link } from "@tanstack/react-router";
import { useEffect,useMemo,useState } from "react";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AppShell,StatusBadge } from "@/components/app/shell";
import { Card,CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { useTenant } from "@/hooks/useTenant";
import { getTenantControlPlane } from "@/lib/control-plane.functions";
import { getPracticeWorkspace,grantPracticePortalUser,mutatePracticeWorkspace } from "@/modules/practice/functions";
import { PRACTICE_PACKS } from "@/modules/practice/contracts";
import { BriefcaseBusiness,CalendarClock,ClipboardList,FileCheck2,Plus,Users } from "lucide-react";
import { toast } from "sonner";

export const Route=createFileRoute("/_authenticated/app/practice")({component:PracticeWorkspace,head:()=>({meta:[{title:"Practice Operations — Omniqora"},{name:"robots",content:"noindex"}]})});

function PracticeWorkspace(){
 const current=useTenant(),tenantId=current.tenantId??"";const tenantFn=useServerFn(getTenantControlPlane);
 const workspaceFn=useServerFn(getPracticeWorkspace),mutate=useServerFn(mutatePracticeWorkspace),grant=useServerFn(grantPracticePortalUser);const qc=useQueryClient();
 const tenant=useQuery({queryKey:["practice-tenant",tenantId],enabled:!!tenantId,queryFn:()=>tenantFn({data:{tenantId}}),retry:false});
 const products=(tenant.data?.products??[]).filter((p:any)=>!["cancelled","failed"].includes(p.status));
 const[productKey,setProductKey]=useState("");
 useEffect(()=>{if(products.length&&!products.some((p:any)=>p.product_key===productKey))setProductKey(products[0].product_key);},[products,productKey]);
 const ws=useQuery({queryKey:["practice",tenantId,productKey],enabled:!!tenantId&&!!productKey,queryFn:()=>workspaceFn({data:{tenantId,productKey}}),retry:false});
 const data=ws.data as any;const clients=data?.clients??[],services=data?.services??[],jobs=data?.jobs??[],phases=data?.phases??[],requests=data?.requests??[],time=data?.time??[],proposals=data?.proposals??[];
 const[busy,setBusy]=useState("");const[client,setClient]=useState({name:"",crmCompanyId:"",billingEmail:""});
 const[job,setJob]=useState({clientId:"",serviceId:"",periodKey:new Date().toISOString().slice(0,7),internalDue:"",externalDue:""});
 const[request,setRequest]=useState({jobId:"",title:"",dueAt:""});
 const[proposal,setProposal]=useState({clientId:"",serviceId:"",units:"1",catchup:"0",terms:"Services as agreed.",expiresAt:""});
 const[portal,setPortal]=useState({clientId:"",userId:"",role:"client_viewer"});
 const activeJobs=jobs.filter((j:any)=>!["completed","cancelled"].includes(j.status));
 const totalMinutes=time.reduce((s:number,t:any)=>s+Number(t.minutes??0),0);
 const quoted=proposals.filter((p:any)=>p.status!=="draft").reduce((s:number,p:any)=>s+Number(p.total_minor??0),0);

 async function refresh(){await qc.invalidateQueries({queryKey:["practice",tenantId,productKey]});}
 async function run(key:string,fn:()=>Promise<unknown>){try{setBusy(key);await fn();toast.success("Practice workspace updated");await refresh();}catch(e){toast.error(e instanceof Error?e.message:String(e));}finally{setBusy("");}}
 const command=(command:any)=>mutate({data:{tenantId,productKey,command}});

 if(current.loading)return <AppShell title="Practice Operations"><State text="Loading workspace…"/></AppShell>;
 return <AppShell title="Practice Operations" subtitle="Shared service-delivery workspace for accountancy, legal, compliance and other professional SaaS products."
  actions={<Button variant="outline" asChild><Link to="/client-portal">Client portal</Link></Button>}>
  <div className="space-y-6">
   <Card><CardContent className="p-5"><label className="text-xs font-medium text-muted-foreground">Product workspace</label><select className="mt-1 h-10 w-full max-w-md rounded-md border bg-background px-3 text-sm" value={productKey} onChange={e=>setProductKey(e.target.value)}>{products.map((p:any)=><option key={p.product_key} value={p.product_key}>{p.product_key} · {p.status}</option>)}</select></CardContent></Card>
   {ws.error?<State destructive text={ws.error instanceof Error?ws.error.message:"Practice unavailable"}/>:<>
   <div className="grid gap-4 md:grid-cols-4"><Metric icon={Users} label="Clients" value={clients.length}/><Metric icon={BriefcaseBusiness} label="Open jobs" value={activeJobs.length}/><Metric icon={CalendarClock} label="Time recorded" value={Math.round(totalMinutes/60*10)/10+"h"}/><Metric icon={FileCheck2} label="Issued/accepted value" value={money(quoted,proposals.find((p:any)=>p.status!=="draft")?.currency??"GBP")}/></div>
   <div className="grid gap-6 xl:grid-cols-[360px_1fr]">
    <div className="space-y-6">
     <Card><CardContent className="p-5"><h3 className="font-semibold">New client</h3><div className="mt-3 space-y-3"><Input placeholder="Client name" value={client.name} onChange={e=>setClient(v=>({...v,name:e.target.value}))}/><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={client.crmCompanyId} onChange={e=>setClient(v=>({...v,crmCompanyId:e.target.value}))}><option value="">No CRM company link</option>{(data?.crmCompanies??[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Input placeholder="Billing email" type="email" value={client.billingEmail} onChange={e=>setClient(v=>({...v,billingEmail:e.target.value}))}/><Button disabled={!client.name||busy==="client"} onClick={()=>run("client",async()=>{await command({operation:"client.save",client:{displayName:client.name,crmCompanyId:client.crmCompanyId||null,billingEmail:client.billingEmail||null,status:"active",metadata:{}}});setClient({name:"",crmCompanyId:"",billingEmail:""});})}><Plus className="mr-2 h-4 w-4"/>Create client</Button></div></CardContent></Card>
     <Card><CardContent className="p-5"><h3 className="font-semibold">Starter service packs</h3><p className="mt-1 text-xs text-muted-foreground">Templates only. They do not determine statutory obligations or prices.</p><div className="mt-3 space-y-2">{PRACTICE_PACKS.map(pack=><Button className="w-full justify-between" variant="outline" key={pack.key} disabled={busy==="pack"} onClick={()=>run("pack",()=>command({operation:"service.save",service:pack}))}><span>{pack.name}</span><span className="text-xs text-muted-foreground">{pack.recurrence}</span></Button>)}</div></CardContent></Card>
    </div>
    <div className="space-y-6">
     <Card><CardContent className="p-0"><Header title="Today / work board" subtitle="Internal target dates and client-facing deadlines stay separate."/><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-surface-2 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Client</th><th className="px-4 py-3">Service</th><th className="px-4 py-3">Period</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">External due</th><th className="px-4 py-3">Progress</th></tr></thead><tbody className="divide-y">{activeJobs.map((j:any)=>{const ps=phases.filter((p:any)=>p.engagement_id===j.id);const done=ps.filter((p:any)=>p.completed_at).length;return <tr key={j.id}><td className="px-4 py-3">{clients.find((c:any)=>c.id===j.client_id)?.display_name??"—"}</td><td className="px-4 py-3">{j.service_key}</td><td className="px-4 py-3">{j.period_key}</td><td className="px-4 py-3"><StatusBadge status={j.status}/></td><td className="px-4 py-3">{j.external_due_at?new Date(j.external_due_at).toLocaleDateString():"—"}</td><td className="px-4 py-3">{done}/{ps.length}</td></tr>})}{!activeJobs.length&&<tr><td colSpan={6} className="px-4 py-8 text-center text-muted-foreground">No open jobs.</td></tr>}</tbody></table></div></CardContent></Card>
     <div className="grid gap-4 lg:grid-cols-2">
      <Card><CardContent className="p-5"><h3 className="font-semibold">Create job</h3><div className="mt-3 space-y-3"><Select value={job.clientId} set={v=>setJob(x=>({...x,clientId:v}))} label="Client" options={clients.map((c:any)=>[c.id,c.display_name])}/><Select value={job.serviceId} set={v=>setJob(x=>({...x,serviceId:v}))} label="Service" options={services.map((s:any)=>[s.id,s.name])}/><Input placeholder="Period e.g. 2026 or 2026-10" value={job.periodKey} onChange={e=>setJob(v=>({...v,periodKey:e.target.value}))}/><Input type="datetime-local" value={job.internalDue} onChange={e=>setJob(v=>({...v,internalDue:e.target.value}))}/><Input type="datetime-local" value={job.externalDue} onChange={e=>setJob(v=>({...v,externalDue:e.target.value}))}/><Button disabled={!job.clientId||!job.serviceId||!job.periodKey||busy==="job"} onClick={()=>run("job",()=>command({operation:"job.create",clientId:job.clientId,serviceId:job.serviceId,periodKey:job.periodKey,internalDue:iso(job.internalDue),externalDue:iso(job.externalDue)}))}>Create job</Button></div></CardContent></Card>
      <Card><CardContent className="p-5"><h3 className="font-semibold">Information request</h3><div className="mt-3 space-y-3"><Select value={request.jobId} set={v=>setRequest(x=>({...x,jobId:v}))} label="Job" options={activeJobs.map((j:any)=>[j.id,(clients.find((c:any)=>c.id===j.client_id)?.display_name??"Client")+" · "+j.period_key])}/><Input placeholder="What do you need from the client?" value={request.title} onChange={e=>setRequest(v=>({...v,title:e.target.value}))}/><Input type="datetime-local" value={request.dueAt} onChange={e=>setRequest(v=>({...v,dueAt:e.target.value}))}/><Button disabled={!request.jobId||!request.title||busy==="request"} onClick={()=>run("request",()=>command({operation:"request.create",jobId:request.jobId,title:request.title,dueAt:iso(request.dueAt),chaseEnabled:true}))}>Create request</Button></div></CardContent></Card>
     </div>
     <div className="grid gap-4 lg:grid-cols-2">
      <Card><CardContent className="p-5"><h3 className="font-semibold">Proposal</h3><div className="mt-3 space-y-3"><Select value={proposal.clientId} set={v=>setProposal(x=>({...x,clientId:v}))} label="Client" options={clients.map((c:any)=>[c.id,c.display_name])}/><Select value={proposal.serviceId} set={v=>setProposal(x=>({...x,serviceId:v}))} label="Service" options={services.map((s:any)=>[s.id,s.name])}/><Input type="number" min="0" value={proposal.units} onChange={e=>setProposal(v=>({...v,units:e.target.value}))}/><Input type="number" min="0" placeholder="Catch-up fee minor units" value={proposal.catchup} onChange={e=>setProposal(v=>({...v,catchup:e.target.value}))}/><Input placeholder="Terms" value={proposal.terms} onChange={e=>setProposal(v=>({...v,terms:e.target.value}))}/><Input type="datetime-local" value={proposal.expiresAt} onChange={e=>setProposal(v=>({...v,expiresAt:e.target.value}))}/><Button disabled={!proposal.clientId||!proposal.serviceId||!proposal.expiresAt||busy==="proposal"} onClick={()=>run("proposal",()=>command({operation:"proposal.create",clientId:proposal.clientId,serviceId:proposal.serviceId,units:Number(proposal.units),catchupMinor:Number(proposal.catchup),terms:proposal.terms,expiresAt:iso(proposal.expiresAt)!}))}>Create proposal</Button></div></CardContent></Card>
      <Card><CardContent className="p-5"><h3 className="font-semibold">Client portal access</h3><div className="mt-3 space-y-3"><Select value={portal.clientId} set={v=>setPortal(x=>({...x,clientId:v}))} label="Client" options={clients.map((c:any)=>[c.id,c.display_name])}/><Input placeholder="Existing user UUID" value={portal.userId} onChange={e=>setPortal(v=>({...v,userId:e.target.value}))}/><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={portal.role} onChange={e=>setPortal(v=>({...v,role:e.target.value}))}><option value="client_viewer">Client viewer</option><option value="client_owner">Client owner</option></select><Button disabled={!portal.clientId||!portal.userId||busy==="portal"} onClick={()=>run("portal",()=>grant({data:{tenantId,productKey,clientId:portal.clientId,userId:portal.userId,role:portal.role as any}}))}>Grant portal access</Button></div></CardContent></Card>
     </div>
     <Card><CardContent className="p-0"><Header title="Requests & proposals" subtitle="Client responses and proposal decisions are auditable; provider e-signature/payment remain separate integrations."/><div className="grid gap-0 lg:grid-cols-2"><div className="border-r"><div className="divide-y">{requests.slice(0,20).map((r:any)=><div className="p-4" key={r.id}><div className="flex justify-between gap-2"><b>{r.title}</b><StatusBadge status={r.status}/></div><p className="mt-1 text-xs text-muted-foreground">{r.due_at?new Date(r.due_at).toLocaleString():"No due date"} · chase {r.chase_enabled?"on":"off"}</p></div>)}</div></div><div><div className="divide-y">{proposals.slice(0,20).map((p:any)=><div className="p-4" key={p.id}><div className="flex justify-between gap-2"><b>{money(p.total_minor/100,p.currency)}</b><StatusBadge status={p.status}/></div><p className="mt-1 text-xs text-muted-foreground">Expires {new Date(p.expires_at).toLocaleString()}</p>{p.status==="draft"&&<Button className="mt-2" size="sm" variant="outline" onClick={()=>run("issue",()=>command({operation:"proposal.issue",proposalId:p.id}))}>Issue</Button>}</div>)}</div></div></div></CardContent></Card>
    </div>
   </div></>}
  </div>
 </AppShell>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string|number}){return <Card><CardContent className="p-5"><div className="flex justify-between text-xs uppercase text-muted-foreground"><span>{label}</span><Icon className="h-4 w-4"/></div><div className="mt-2 font-display text-xl font-semibold">{value}</div></CardContent></Card>;}
function Header({title,subtitle}:{title:string;subtitle:string}){return <div className="border-b px-5 py-4"><h3 className="font-semibold">{title}</h3><p className="text-xs text-muted-foreground">{subtitle}</p></div>;}
function State({text,destructive=false}:{text:string;destructive?:boolean}){return <Card><CardContent className={"p-6 text-sm "+(destructive?"text-destructive":"text-muted-foreground")}>{text}</CardContent></Card>;}
function Select({value,set,label,options}:{value:string;set:(v:string)=>void;label:string;options:Array<[string,string]>}){return <select aria-label={label} className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={value} onChange={e=>set(e.target.value)}><option value="">{label}</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>;}
function iso(value:string){return value?new Date(value).toISOString():null;}
function money(value:number,currency:string){try{return new Intl.NumberFormat(undefined,{style:"currency",currency}).format(value);}catch{return currency+" "+value.toFixed(2);}}
