import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { AppShell,StatusBadge } from "@/components/app/shell";
import { Card,CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { useTenant } from "@/hooks/useTenant";
import { getTenantControlPlane } from "@/lib/control-plane.functions";
import { createLoyaltyProgramme,createMarketplaceListing,createMarketplaceOrder,createMarketplaceVendor,createStockItem,getCommerceWorkspace } from "@/modules/commerce/functions";
import { Boxes,RefreshCw,ShoppingCart,Store } from "lucide-react";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/app/commerce")({component:Commerce,head:()=>({meta:[{title:"Commerce & Marketplace — Omniqora"},{name:"robots",content:"noindex"}]})});
function Commerce(){
 const t=useTenant();const tenantId=t.tenantId??"";const tenantFn=useServerFn(getTenantControlPlane),getFn=useServerFn(getCommerceWorkspace),vendorFn=useServerFn(createMarketplaceVendor),stockFn=useServerFn(createStockItem),listingFn=useServerFn(createMarketplaceListing),orderFn=useServerFn(createMarketplaceOrder),loyaltyFn=useServerFn(createLoyaltyProgramme);
 const td=useQuery({queryKey:["commerce-tenant",tenantId],queryFn:()=>tenantFn({data:{tenantId}}),enabled:!!tenantId,retry:false});const[productKey,setProductKey]=useState("mealdeck");
 const data=useQuery({queryKey:["commerce",tenantId,productKey],queryFn:()=>getFn({data:{tenantId,productKey}}),enabled:!!tenantId&&!!productKey,retry:false});
 const[vName,setVName]=useState(""),[vKey,setVKey]=useState(""),[stockName,setStockName]=useState(""),[stockQty,setStockQty]=useState("10"),[listingTitle,setListingTitle]=useState(""),[listingPrice,setListingPrice]=useState(""),[selectedVendor,setSelectedVendor]=useState(""),[selectedItem,setSelectedItem]=useState(""),[selectedListing,setSelectedListing]=useState("");
 const products=(td.data?.products??[]).filter(p=>!["failed","cancelled"].includes(p.status));const d=data.data;
 async function run(fn:()=>Promise<unknown>,m:string){try{await fn();toast.success(m);await data.refetch();}catch(e){toast.error(e instanceof Error?e.message:String(e));}}
 return <AppShell title="Syndriva Commerce" subtitle="Marketplace, inventory, bookings, payments and Zoryn Rewards shared across entitled SaaS products." actions={<Button variant="outline" size="sm" onClick={()=>data.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>}>
  <div className="grid gap-4 md:grid-cols-4"><Metric label="Vendors" value={d?.vendors?.length??0}/><Metric label="Listings" value={d?.listings?.length??0}/><Metric label="Orders" value={d?.orders?.length??0}/><Metric label="Payments" value={d?.payments?.length??0}/></div>
  <Card className="mt-6"><CardContent className="p-5"><label className="text-xs text-muted-foreground">Tenant product</label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={productKey} onChange={e=>setProductKey(e.target.value)}>{products.map(p=><option key={p.product_key}>{p.product_key}</option>)}</select></CardContent></Card>
  <div className="mt-6 grid gap-6 xl:grid-cols-3">
   <Card><CardContent className="p-5"><Store className="h-4 w-4"/><h2 className="mt-2 font-semibold">Vendor / brand</h2><Input className="mt-3" placeholder="Vendor name" value={vName} onChange={e=>{setVName(e.target.value);if(!vKey)setVKey(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""));}}/><Input className="mt-2" placeholder="vendor-key" value={vKey} onChange={e=>setVKey(e.target.value)}/><Button className="mt-3" disabled={!vName||!vKey} onClick={()=>run(async()=>{await vendorFn({data:{tenantId,productKey,name:vName,vendorKey:vKey,brandId:null,commissionBps:0}});setVName("");setVKey("");},"Vendor created")}>Create vendor</Button></CardContent></Card>
   <Card><CardContent className="p-5"><Boxes className="h-4 w-4"/><h2 className="mt-2 font-semibold">Stock item</h2><Input className="mt-3" placeholder="Item name" value={stockName} onChange={e=>setStockName(e.target.value)}/><Input className="mt-2" type="number" min="0" value={stockQty} onChange={e=>setStockQty(e.target.value)}/><Button className="mt-3" disabled={!stockName} onClick={()=>run(async()=>{await stockFn({data:{tenantId,productKey,name:stockName,locationName:"Main Kitchen",externalRef:"item-"+crypto.randomUUID(),sku:null,quantity:Number(stockQty)}});setStockName("");},"Stock item created")}>Add stock</Button></CardContent></Card>
   <Card><CardContent className="p-5"><ShoppingCart className="h-4 w-4"/><h2 className="mt-2 font-semibold">Listing</h2><select className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={selectedVendor} onChange={e=>setSelectedVendor(e.target.value)}><option value="">Choose vendor</option>{(d?.vendors??[]).map((v:any)=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={selectedItem} onChange={e=>setSelectedItem(e.target.value)}><option value="">No stock link</option>{(d?.items??[]).map((i:any)=><option key={i.id} value={i.id}>{i.name}</option>)}</select><Input className="mt-2" placeholder="Listing title" value={listingTitle} onChange={e=>setListingTitle(e.target.value)}/><Input className="mt-2" type="number" step=".01" placeholder="Price £" value={listingPrice} onChange={e=>setListingPrice(e.target.value)}/><Button className="mt-3" disabled={!selectedVendor||!listingTitle||!listingPrice} onClick={()=>run(async()=>{const item=(d?.items??[]).find((i:any)=>i.id===selectedItem);const loc=item?(d?.stockLocations??[])[0]:null;await listingFn({data:{tenantId,productKey,vendorId:selectedVendor,inventoryItemId:item?.id??null,stockLocationId:loc?.id??null,title:listingTitle,externalRef:null,priceMinor:Math.round(Number(listingPrice)*100),currency:"GBP",trackInventory:!!item}});setListingTitle("");setListingPrice("");},"Listing created")}>Create listing</Button></CardContent></Card>
  </div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[360px_1fr]"><Card><CardContent className="p-5"><h2 className="font-semibold">Test single-cart order</h2><select className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={selectedListing} onChange={e=>setSelectedListing(e.target.value)}><option value="">Choose listing</option>{(d?.listings??[]).map((l:any)=><option key={l.id} value={l.id}>{l.title}</option>)}</select><Button className="mt-3" disabled={!selectedListing} onClick={()=>run(()=>orderFn({data:{tenantId,productKey,buyerRef:"crm:test-customer",items:[{listingId:selectedListing,quantity:1}],idempotencyKey:"order-"+crypto.randomUUID()}}),"Order created")}>Create order</Button><Button className="mt-2" variant="outline" onClick={()=>run(()=>loyaltyFn({data:{tenantId,productKey,name:"Zoryn Rewards",loyaltyCurrency:"points"}}),"Loyalty programme created")}>Enable Zoryn Rewards</Button></CardContent></Card>
   <Card><CardContent className="p-0"><div className="border-b p-5"><h2 className="font-semibold">Orders & vendor splits</h2></div><div className="divide-y">{(d?.orders??[]).map((o:any)=><div key={o.id} className="p-4"><div className="flex justify-between"><div><b>{o.buyer_ref}</b><p className="text-xs text-muted-foreground">{o.id}</p></div><div className="flex gap-2"><Badge variant="outline">{money(o.total_minor,o.currency)}</Badge><StatusBadge status={o.status}/></div></div><div className="mt-2 flex flex-wrap gap-2">{(o.settlements??[]).map((s:any)=><Badge key={s.id} variant="secondary">vendor {s.vendor_id.slice(0,8)} · net {money(s.net_minor,s.currency)}</Badge>)}</div></div>)}{!(d?.orders??[]).length&&<p className="p-5 text-sm text-muted-foreground">No orders yet.</p>}</div></CardContent></Card>
  </div>
 </AppShell>
}
function Metric({label,value}:{label:string;value:number}){return <Card><CardContent className="p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 font-display text-2xl font-semibold">{value}</p></CardContent></Card>}
function money(minor:number,currency:string){return new Intl.NumberFormat("en-GB",{style:"currency",currency:currency||"GBP"}).format(Number(minor||0)/100)}
