import {createFileRoute} from "@tanstack/react-router";
import {useQuery} from "@tanstack/react-query";
import {useServerFn} from "@tanstack/react-start";
import {useEffect,useMemo,useState} from "react";
import {AppShell,StatusBadge} from "@/components/app/shell";
import {Card,CardContent} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";
import {useTenant} from "@/hooks/useTenant";
import {getTenantControlPlane} from "@/lib/control-plane.functions";
import {createAutomotiveAppraisal,createBidModel,getAutomotiveWorkspace,queueAutomotiveIntelligence,recordAutomotiveValuation,saveAutomotiveVehicle,upsertAuctionLot} from "@/modules/automotive/functions";
import {BrainCircuit,Gauge,RefreshCw,ShieldCheck,Truck} from "lucide-react";
import {toast} from "sonner";

export const Route=createFileRoute("/_authenticated/app/automotive")({component:Automotive,head:()=>({meta:[{title:"Automotive Intelligence — Omniqora"},{name:"robots",content:"noindex"}]})});

function Automotive(){
 const t=useTenant(),tenantId=t.tenantId??"";const tenantFn=useServerFn(getTenantControlPlane),getFn=useServerFn(getAutomotiveWorkspace),
 vehicleFn=useServerFn(saveAutomotiveVehicle),appraisalFn=useServerFn(createAutomotiveAppraisal),aiFn=useServerFn(queueAutomotiveIntelligence),
 valuationFn=useServerFn(recordAutomotiveValuation),lotFn=useServerFn(upsertAuctionLot),bidFn=useServerFn(createBidModel);
 const tenant=useQuery({queryKey:["auto-tenant",tenantId],queryFn:()=>tenantFn({data:{tenantId}}),enabled:!!tenantId,retry:false});
 const automotiveProducts=useMemo(()=>{const allowed=new Set(["zivvo","autohashi","sparesgrid"]);const rows=(tenant.data?.products??[]).map((p:any)=>p.product_key).filter((p:string)=>allowed.has(p));return rows.length?rows:(tenant.data?.products??[]).map((p:any)=>p.product_key)},[tenant.data]);
 const[productKey,setProductKey]=useState("");useEffect(()=>{if(!productKey&&automotiveProducts[0])setProductKey(automotiveProducts[0])},[productKey,automotiveProducts.join("|")]);
 const q=useQuery({queryKey:["automotive",tenantId,productKey],queryFn:()=>getFn({data:{tenantId,productKey}}),enabled:!!tenantId&&!!productKey,retry:false});
 const[make,setMake]=useState(""),[model,setModel]=useState(""),[vin,setVin]=useState(""),[vrm,setVrm]=useState(""),[origin,setOrigin]=useState<"uk"|"japan"|"other">("uk");
 const[lotRef,setLotRef]=useState(""),[targetRetail,setTargetRetail]=useState("");
 async function run(fn:()=>Promise<any>,msg:string){try{const r=await fn();toast.success(msg);await q.refetch();return r}catch(e){toast.error(e instanceof Error?e.message:String(e))}}
 const vehicles=q.data?.vehicles??[],selected=vehicles[0];
 return <AppShell title="Automotive Intelligence" subtitle="Shared vehicle identity, evidence, appraisals, AI findings, valuations, JDM auction economics, parts fitment and compliance for Zivvo, Autohashi and SparesGrid."
 actions={<Button variant="outline" size="sm" onClick={()=>q.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>}>
  <Card><CardContent className="p-5"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={productKey} onChange={e=>setProductKey(e.target.value)}>{automotiveProducts.map((p:string)=><option key={p}>{p}</option>)}</select></CardContent></Card>
  <div className="mt-6 grid gap-4 md:grid-cols-4"><Metric icon={Truck} label="Vehicles" value={vehicles.length}/><Metric icon={BrainCircuit} label="AI findings" value={q.data?.findings?.length??0}/><Metric icon={Gauge} label="Valuations" value={q.data?.valuations?.length??0}/><Metric icon={ShieldCheck} label="Compliance checks" value={q.data?.compliance?.length??0}/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-2">
   <Card><CardContent className="p-5"><h2 className="font-semibold">Vehicle identity / passport source</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><Input placeholder="Make" value={make} onChange={e=>setMake(e.target.value)}/><Input placeholder="Model" value={model} onChange={e=>setModel(e.target.value)}/><Input placeholder="VIN / chassis" value={vin} onChange={e=>setVin(e.target.value)}/><Input placeholder="VRM (UK)" value={vrm} onChange={e=>setVrm(e.target.value)}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={origin} onChange={e=>setOrigin(e.target.value as any)}>{["uk","japan","other"].map(x=><option key={x}>{x}</option>)}</select></div><Button className="mt-3" disabled={!make||!model||(!vin&&!vrm)} onClick={()=>run(()=>vehicleFn({data:{tenantId,productKey,vehicleId:null,origin,vrm:vrm||null,vin:vin||null,chassisNumber:null,modelCode:null,make,model,derivative:null,firstRegistrationDate:null,specification:{},provenance:{source:"operator"}}}),"Vehicle saved")}>Add vehicle</Button>
    <div className="mt-4 space-y-2">{vehicles.slice(0,8).map((v:any)=><div key={v.id} className="flex items-center justify-between rounded-lg bg-muted p-3 text-sm"><div><b>{v.make} {v.model}</b><p className="text-xs text-muted-foreground">{v.vin||v.vrm||v.chassis_number} · {v.origin}</p></div><StatusBadge status={v.status}/></div>)}</div></CardContent></Card>
   <Card><CardContent className="p-5"><h2 className="font-semibold">Evidence & AI appraisal</h2><p className="mt-1 text-xs text-muted-foreground">Fresh-capture workflow explicitly keeps geolocation off. AI findings are proposed and reviewable, not auto-approved.</p><Button className="mt-4" disabled={!selected} onClick={()=>run(()=>appraisalFn({data:{tenantId,productKey,vehicleId:selected.id,requestedItems:["front","rear","left","right","interior","odometer","documents"],expiresAt:null,allowLibraryUpload:false}}),"Fresh appraisal requested")}>Request appraisal</Button><Button className="ml-2 mt-4" variant="outline" disabled={!selected} onClick={()=>run(()=>aiFn({data:{tenantId,productKey,vehicleId:selected.id,appraisalId:null,goal:"Assess condition, provenance gaps and valuation factors from reviewed evidence.",evidenceIds:[]}}),"Automotive AI queued")}>Queue AI assessment</Button><div className="mt-4 flex flex-wrap gap-2">{(q.data?.appraisals??[]).slice(0,10).map((a:any)=><Badge key={a.id} variant="outline">{a.status}</Badge>)}</div></CardContent></Card>
   <Card><CardContent className="p-5"><h2 className="font-semibold">Valuation</h2><Input className="mt-3" type="number" placeholder="Retail value minor units (e.g. 1250000)" value={targetRetail} onChange={e=>setTargetRetail(e.target.value)}/><Button className="mt-3" disabled={!selected||!targetRetail} onClick={()=>run(()=>valuationFn({data:{tenantId,productKey,vehicleId:selected.id,valuationType:"retail",currency:"GBP",amountMinor:Number(targetRetail),lowMinor:null,highMinor:null,source:"operator_review",comparableRefs:[],assumptions:{},confidence:null}}),"Valuation recorded")}>Record reviewed valuation</Button><div className="mt-4 space-y-2">{(q.data?.valuations??[]).slice(0,8).map((v:any)=><div key={v.id} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span>{v.valuation_type}</span><b>{v.currency} {(Number(v.amount_minor)/100).toLocaleString()}</b></div>)}</div></CardContent></Card>
   <Card><CardContent className="p-5"><h2 className="font-semibold">JDM auction / max bid</h2><Input className="mt-3" placeholder="External lot ID" value={lotRef} onChange={e=>setLotRef(e.target.value)}/><Button className="mt-3" disabled={!lotRef} onClick={async()=>{const lot=await run(()=>lotFn({data:{tenantId,productKey,vehicleId:selected?.id??null,providerKey:null,externalLotId:lotRef,auctionHouse:null,auctionAt:null,grade:null,odometerKm:null,startingPriceMinor:null,currentPriceMinor:null,currency:"GBP",auctionSheet:{},images:[]}}),"Auction lot saved");if(lot&&targetRetail)await run(()=>bidFn({data:{tenantId,productKey,auctionLotId:lot.id,destinationCountry:"GB",currency:"GBP",auctionFeesMinor:0,inlandTransportMinor:0,freightMinor:0,insuranceMinor:0,dutyMinor:0,taxMinor:0,registrationMinor:0,otherMinor:0,targetMarginMinor:0,targetRetailMinor:Number(targetRetail),fxRate:null,fxSource:null,fxAsOf:null,assumptions:{incompleteCosts:true}}}),"Draft max-bid model created")}}>Create lot / draft bid model</Button><p className="mt-2 text-xs text-muted-foreground">A zero-cost placeholder produces a draft only; shipping, duty, FX, tax, registration and margin must be completed before approval.</p></CardContent></Card>
  </div>
 </AppShell>
}
function Metric({icon:Icon,label,value}:{icon:typeof Truck;label:string;value:number}){return <Card><CardContent className="p-5"><div className="flex items-center justify-between text-xs uppercase tracking-wide text-muted-foreground"><span>{label}</span><Icon className="h-4 w-4"/></div><div className="mt-2 font-display text-2xl font-semibold">{value}</div></CardContent></Card>}
