import {createFileRoute,Link} from "@tanstack/react-router";
import {useQuery} from "@tanstack/react-query";
import {useServerFn} from "@tanstack/react-start";
import {useEffect,useState} from "react";
import {AppShell,StatusBadge} from "@/components/app/shell";
import {Card,CardContent} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Badge} from "@/components/ui/badge";
import {useTenant} from "@/hooks/useTenant";
import {getTenantControlPlane} from "@/lib/control-plane.functions";
import {completePracticePhase,createManagedPracticeEngagement,createPracticeDocumentRequest,createPracticeProposal,createPracticeSignatureRequest,createPracticeSubmission,getPracticeDeliveryWorkspace,issuePracticeProposal,recordPracticeTime,savePracticeRecurringWork,savePracticeTemplate} from "@/modules/practice-delivery/functions";
import {BriefcaseBusiness,Clock3,FileSignature,RefreshCw,Repeat2} from "lucide-react";
import {toast} from "sonner";

export const Route=createFileRoute("/_authenticated/app/practice")({component:PracticeWorkspace,head:()=>({meta:[{title:"Practice Operations — Omniqora"},{name:"robots",content:"noindex"}]})});

function PracticeWorkspace(){
 const t=useTenant(),tenantId=t.tenantId??"";const tenantFn=useServerFn(getTenantControlPlane),getFn=useServerFn(getPracticeDeliveryWorkspace),
 templateFn=useServerFn(savePracticeTemplate),jobFn=useServerFn(createManagedPracticeEngagement),requestFn=useServerFn(createPracticeDocumentRequest),
 timeFn=useServerFn(recordPracticeTime),proposalFn=useServerFn(createPracticeProposal),issueFn=useServerFn(issuePracticeProposal),
 signatureFn=useServerFn(createPracticeSignatureRequest),submissionFn=useServerFn(createPracticeSubmission),recurringFn=useServerFn(savePracticeRecurringWork),
 phaseFn=useServerFn(completePracticePhase);
 const tenant=useQuery({queryKey:["practice-tenant",tenantId],queryFn:()=>tenantFn({data:{tenantId}}),enabled:!!tenantId,retry:false});
 const products=(tenant.data?.products??[]).map((p:any)=>p.product_key);const[productKey,setProductKey]=useState("");
 useEffect(()=>{if(!productKey&&products[0])setProductKey(products[0]);},[productKey,products.join("|")]);
 const q=useQuery({queryKey:["practice-delivery",tenantId,productKey],queryFn:()=>getFn({data:{tenantId,productKey}}),enabled:!!tenantId&&!!productKey,retry:false});
 const[templateKey,setTemplateKey]=useState("annual-accounts"),[templateName,setTemplateName]=useState("Annual Accounts"),[fee,setFee]=useState("0");
 const[periodKey,setPeriodKey]=useState(String(new Date().getUTCFullYear())),[requestTitle,setRequestTitle]=useState("Bank statements and records");
 const[minutes,setMinutes]=useState("30"),[proposalRef,setProposalRef]=useState("PROP-"+Date.now());
 async function run(fn:()=>Promise<unknown>,msg:string){try{await fn();toast.success(msg);await q.refetch();}catch(e){toast.error(e instanceof Error?e.message:String(e));}}
 const client=(q.data?.clients??[])[0],template=(q.data?.templates??[])[0],engagement=(q.data?.engagements??[])[0],proposal=(q.data?.proposals??[])[0];
 const phases=(q.data?.phases??[]).filter((p:any)=>p.engagement_id===engagement?.id);
 return <AppShell title="Practice Operations" subtitle="Client delivery, recurring work, requests, time/WIP, proposals, e-sign tracking and authority submissions."
 actions={<><Button size="sm" variant="outline" onClick={()=>q.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button><Button size="sm" variant="outline" asChild><Link to="/practice-portal">Client portal</Link></Button></>}>
  <Card><CardContent className="p-5"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={productKey} onChange={e=>setProductKey(e.target.value)}>{products.map((p:string)=><option key={p}>{p}</option>)}</select></CardContent></Card>
  <div className="mt-6 grid gap-4 md:grid-cols-5"><Metric icon={BriefcaseBusiness} label="Clients" value={q.data?.clients?.length??0}/><Metric icon={Repeat2} label="Jobs" value={q.data?.engagements?.length??0}/><Metric icon={Clock3} label="Time entries" value={q.data?.time?.length??0}/><Metric icon={FileSignature} label="Proposals" value={q.data?.proposals?.length??0}/><Metric icon={FileSignature} label="Submissions" value={q.data?.submissions?.length??0}/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-2">
   <Card><CardContent className="p-5"><h2 className="font-semibold">Service template</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><Input value={templateKey} onChange={e=>setTemplateKey(e.target.value)}/><Input value={templateName} onChange={e=>setTemplateName(e.target.value)}/></div><Input className="mt-2" type="number" value={fee} onChange={e=>setFee(e.target.value)}/><Button className="mt-3" onClick={()=>run(()=>templateFn({data:{tenantId,productKey,templateKey,name:templateName,serviceFamily:"accounting",currency:"GBP",baseFeeMinor:Number(fee)||0,unitFeeMinor:0,recurrence:"annual",phases:[{title:"Collect records",budgetMinutes:60},{title:"Prepare",budgetMinutes:240},{title:"Review",budgetMinutes:60},{title:"Submit/complete",budgetMinutes:30}],terms:"Subject to engagement terms"}}),"Template saved")}>Save template</Button></CardContent></Card>
   <Card><CardContent className="p-5"><h2 className="font-semibold">Create managed job</h2><Input className="mt-3" value={periodKey} onChange={e=>setPeriodKey(e.target.value)}/><Button className="mt-3" disabled={!client||!template} onClick={()=>run(()=>jobFn({data:{tenantId,productKey,clientId:client.id,templateId:template.id,periodKey,periodStart:null,periodEnd:null,internalDueAt:null,externalDueAt:null,ownerUserId:null}}),"Managed engagement created")}>Create for first client/template</Button><div className="mt-4 space-y-2">{(q.data?.engagements??[]).slice(0,8).map((x:any)=><div key={x.id} className="flex justify-between rounded-lg border p-3 text-sm"><div><b>{x.engagement_type}</b><p className="text-xs text-muted-foreground">{x.period_key||"Ad hoc"} · v{x.work_version}</p></div><StatusBadge status={x.status}/></div>)}</div></CardContent></Card>
   <Card><CardContent className="p-5"><h2 className="font-semibold">Client request & phases</h2><Input className="mt-3" value={requestTitle} onChange={e=>setRequestTitle(e.target.value)}/><Button className="mt-3" disabled={!client||!engagement} onClick={()=>run(()=>requestFn({data:{tenantId,productKey,clientId:client.id,engagementId:engagement.id,requestKey:"records-"+Date.now(),title:requestTitle,description:null,dueAt:null}}),"Client document request created")}>Request records</Button><div className="mt-4 space-y-2">{phases.map((p:any)=><div key={p.id} className="flex justify-between rounded-lg bg-muted p-3 text-sm"><span>{p.position+1}. {p.title}</span>{p.status==="open"?<Button size="sm" variant="outline" onClick={()=>run(()=>phaseFn({data:{tenantId,phaseId:p.id,expectedVersion:engagement.work_version}}),"Phase completed")}>Complete</Button>:<StatusBadge status={p.status}/>}</div>)}</div></CardContent></Card>
   <Card><CardContent className="p-5"><h2 className="font-semibold">Time / WIP</h2><Input className="mt-3" type="number" value={minutes} onChange={e=>setMinutes(e.target.value)}/><Button className="mt-3" disabled={!engagement} onClick={()=>run(()=>timeFn({data:{tenantId,productKey,engagementId:engagement.id,workDate:new Date().toISOString().slice(0,10),minutes:Number(minutes)||1,costRateMinor:3000,chargeRateMinor:7500,description:"Practice work",billable:true}}),"Time recorded")}>Record time</Button><p className="mt-3 text-xs text-muted-foreground">WIP/cost/charge reporting is operational only; it does not recognise accounting revenue.</p></CardContent></Card>
   <Card><CardContent className="p-5"><h2 className="font-semibold">Proposal & e-sign</h2><Input className="mt-3" value={proposalRef} onChange={e=>setProposalRef(e.target.value)}/><div className="mt-3 flex flex-wrap gap-2"><Button disabled={!client||!template} onClick={()=>run(()=>proposalFn({data:{tenantId,productKey,clientId:client.id,engagementId:engagement?.id??null,templateId:template.id,proposalRef,totalMinor:Number(fee)||0,currency:"GBP",terms:"Practice engagement proposal",validUntil:new Date(Date.now()+30*86400000).toISOString(),serviceSnapshot:{templateKey:template.template_key,version:template.version},feeSnapshot:[]}}),"Proposal created")}>Create</Button>{proposal?.status!=="issued"&&proposal&&<Button variant="outline" onClick={()=>run(()=>issueFn({data:{tenantId,proposalId:proposal.id}}),"Proposal issued")}>Issue</Button>}{proposal?.status==="issued"&&client&&<Button variant="outline" onClick={()=>run(()=>signatureFn({data:{tenantId,productKey,clientId:client.id,proposalId:proposal.id,documentId:null,signerRef:"client-owner",signerName:client.display_name,signerEmail:null,providerKey:null}}),"Signature request approved for connector")}>Prepare signature</Button>}</div><p className="mt-3 text-xs text-muted-foreground">Issued/approved is internal. Only a provider callback can mark an e-sign request signed.</p></CardContent></Card>
   <Card><CardContent className="p-5"><h2 className="font-semibold">Authority submission</h2><Button className="mt-3" disabled={!client} onClick={()=>run(()=>submissionFn({data:{tenantId,productKey,clientId:client.id,engagementId:engagement?.id??null,deadlineId:null,submissionType:"generic-filing",authority:"Configured authority",providerKey:null,payloadRef:null}}),"Submission sent to review")}>Prepare submission</Button><div className="mt-4 flex flex-wrap gap-2">{(q.data?.submissions??[]).slice(0,8).map((x:any)=><Badge key={x.id} variant="outline">{x.submission_type} · {x.status}</Badge>)}</div><p className="mt-3 text-xs text-muted-foreground">Only connector/provider evidence can move approved work to submitted/accepted/rejected.</p></CardContent></Card>
  </div>
 </AppShell>
}
function Metric({icon:Icon,label,value}:{icon:typeof BriefcaseBusiness;label:string;value:number}){return <Card><CardContent className="p-5"><div className="flex items-center justify-between text-xs uppercase tracking-wide text-muted-foreground"><span>{label}</span><Icon className="h-4 w-4"/></div><div className="mt-2 font-display text-2xl font-semibold">{value}</div></CardContent></Card>}
