import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useMemo,useState } from "react";
import { AppShell,StatusBadge } from "@/components/app/shell";
import { Card,CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { useTenant } from "@/hooks/useTenant";
import { getPortfolioControlPlane } from "@/modules/control-plane/control-plane.functions";
import { bootstrapDishbeeMigrationTargets,getMigrationFactoryAsset,mapMigrationTarget,markMigrationCutoverReady,recordRepoAudit,recordShadowCheck,refreshMigrationTarget,saveCutoverPlan,saveMigrationAdapter } from "@/modules/migration-factory/functions";
import { CheckCircle2,RefreshCw,ShieldAlert } from "lucide-react";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/app/migration-factory")({component:MigrationFactory,head:()=>({meta:[{title:"Migration Factory — Omniqora"},{name:"robots",content:"noindex"}]})});
function MigrationFactory(){
 const t=useTenant();const tenantId=t.tenantId??"";const portfolioFn=useServerFn(getPortfolioControlPlane),detailFn=useServerFn(getMigrationFactoryAsset),targetFn=useServerFn(mapMigrationTarget),dishbeeBootstrapFn=useServerFn(bootstrapDishbeeMigrationTargets),refreshFn=useServerFn(refreshMigrationTarget),auditFn=useServerFn(recordRepoAudit),adapterFn=useServerFn(saveMigrationAdapter),checkFn=useServerFn(recordShadowCheck),planFn=useServerFn(saveCutoverPlan),readyFn=useServerFn(markMigrationCutoverReady);
 const portfolio=useQuery({queryKey:["migration-portfolio",tenantId],queryFn:()=>portfolioFn({data:{tenantId}}),enabled:!!tenantId,retry:false});
 const dishbee=useMemo(()=>portfolio.data?.assets?.find((a:any)=>a.name.toLowerCase().includes("dishbee"))??null,[portfolio.data]);
 const[assetId,setAssetId]=useState("");
 const effectiveAsset=assetId||dishbee?.id||portfolio.data?.assets?.[0]?.id||"";
 const detail=useQuery({queryKey:["migration-asset",effectiveAsset],queryFn:()=>detailFn({data:{assetId:effectiveAsset}}),enabled:!!effectiveAsset,retry:false});
 const[sourceWorkspace,setSourceWorkspace]=useState(""),[targetTenant,setTargetTenant]=useState(""),[cafe1LutonWorkspace,setCafe1LutonWorkspace]=useState(""),[cafe1StAlbansWorkspace,setCafe1StAlbansWorkspace]=useState(""),[mealDeckWorkspace,setMealDeckWorkspace]=useState(""),[adapterKey,setAdapterKey]=useState("dishbee-v2"),[rollback,setRollback]=useState("Restore source routing and disable Omniqora cutover flags.");
 const evaluation=detail.data?.evaluation as any;const assets=portfolio.data?.assets??[];
 async function run(fn:()=>Promise<unknown>,msg:string){try{await fn();toast.success(msg);await detail.refetch();}catch(e){toast.error(e instanceof Error?e.message:String(e));}}
 return <AppShell title="Automated Migration Factory" subtitle="Audit → map targets → adapter → shadow parity → approved cutover. No registry row counts as migrated by itself." actions={<Button variant="outline" size="sm" onClick={()=>Promise.all([portfolio.refetch(),detail.refetch()])}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>}>
  <Card><CardContent className="p-5"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={effectiveAsset} onChange={e=>setAssetId(e.target.value)}>{assets.map((a:any)=><option key={a.id} value={a.id}>{a.name} · {a.migration_stage}</option>)}</select></CardContent></Card>
  {detail.data&&<>
   <div className="mt-6 grid gap-4 md:grid-cols-4"><Metric label="Repo audits" value={detail.data.audits.length}/><Metric label="Required targets" value={evaluation?.requiredTargets??0}/><Metric label="Ready targets" value={evaluation?.readyTargets??0}/><Metric label="Shadow passes" value={evaluation?.passedShadowChecks??0}/></div>
   <Card className="mt-6"><CardContent className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{detail.data.asset.name}</h2><p className="text-xs text-muted-foreground">{detail.data.asset.repository_url||"No repository URL"}</p></div>{evaluation?.ready?<Badge className="gap-1" variant="outline"><CheckCircle2 className="h-3 w-3"/>Cutover gates pass</Badge>:<Badge className="gap-1" variant="destructive"><ShieldAlert className="h-3 w-3"/>Blocked</Badge>}</div><div className="mt-3 flex flex-wrap gap-2">{(evaluation?.blockers??[]).map((b:string)=><Badge key={b} variant="destructive">{b}</Badge>)}{(evaluation?.warnings??[]).map((w:string)=><Badge key={w} variant="outline">{w}</Badge>)}</div></CardContent></Card>
   <div className="mt-6 grid gap-6 xl:grid-cols-2">
    <Card><CardContent className="p-5"><h2 className="font-semibold">1. Repository audit</h2><Button className="mt-3" onClick={()=>run(()=>auditFn({data:{tenantId,assetId:effectiveAsset,repositoryUrl:detail.data.asset.repository_url,commitSha:null,status:"passed",stack:{},capabilities:[],risks:[],evidence:{manual:true}}}),"Audit evidence recorded")}>Record passed audit</Button></CardContent></Card>
    <Card><CardContent className="p-5"><h2 className="font-semibold">2. Map operational targets</h2>{detail.data.asset.name.toLowerCase().includes("dishbee")?<div className="mt-3 space-y-2"><p className="text-xs text-muted-foreground">Paste the three local Dishbee tenant/workspace IDs. Omniqora resolves the matching Cafe 1 Luton, Cafe 1 St Albans and MealDeck tenants automatically inside this organisation.</p><Input value={cafe1LutonWorkspace} onChange={e=>setCafe1LutonWorkspace(e.target.value)} placeholder="Cafe 1 Luton · Dishbee workspace UUID"/><Input value={cafe1StAlbansWorkspace} onChange={e=>setCafe1StAlbansWorkspace(e.target.value)} placeholder="Cafe 1 St Albans · Dishbee workspace UUID"/><Input value={mealDeckWorkspace} onChange={e=>setMealDeckWorkspace(e.target.value)} placeholder="MealDeck · Dishbee workspace UUID"/><Button className="mt-2" disabled={!cafe1LutonWorkspace||!cafe1StAlbansWorkspace||!mealDeckWorkspace} onClick={()=>run(()=>dishbeeBootstrapFn({data:{assetId:effectiveAsset,cafe1LutonWorkspace,cafe1StAlbansWorkspace,mealDeckWorkspace}}),"All three Dishbee targets mapped")}>Bootstrap Dishbee targets</Button></div>:<div className="mt-3 space-y-2"><Input value={targetTenant} onChange={e=>setTargetTenant(e.target.value)} placeholder="Target tenant UUID"/><Input value={sourceWorkspace} onChange={e=>setSourceWorkspace(e.target.value)} placeholder="Source workspace ID"/><Button disabled={!targetTenant} onClick={()=>run(()=>targetFn({data:{assetId:effectiveAsset,targetTenantId:targetTenant,productKey:detail.data.asset.canonical_product_key||"dishbee",sourceWorkspaceId:sourceWorkspace||null,required:true}}),"Migration target mapped")}>Map target</Button></div>}</CardContent></Card>
    <Card><CardContent className="p-5"><h2 className="font-semibold">3. Verified adapter</h2><Input className="mt-3" value={adapterKey} onChange={e=>setAdapterKey(e.target.value)}/><Textarea className="mt-2" value={rollback} onChange={e=>setRollback(e.target.value)}/><Button className="mt-3" onClick={()=>run(()=>adapterFn({data:{tenantId,assetId:effectiveAsset,adapterKey,direction:"bidirectional",contract:{},mapping:{},idempotencyStrategy:"source event id + target tenant",rollbackStrategy:rollback,status:"verified"}}),"Adapter verified")}>Save verified adapter</Button></CardContent></Card>
    <Card><CardContent className="p-5"><h2 className="font-semibold">4. Shadow parity</h2><select id="shadowTarget" className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Whole asset</option>{detail.data.targets.map((x:any)=><option key={x.id} value={x.id}>{x.target_tenant?.name||x.target_tenant_id}</option>)}</select><Button className="mt-3" onClick={()=>{const el=document.getElementById("shadowTarget") as HTMLSelectElement|null;run(()=>checkFn({data:{tenantId,assetId:effectiveAsset,targetId:el?.value||null,checkKey:"manual-parity-"+Date.now(),checkType:"manual",status:"passed",sourceValue:null,targetValue:null,evidence:{operator:true}}}),"Shadow check passed")}}>Record parity pass</Button></CardContent></Card>
    <Card><CardContent className="p-5"><h2 className="font-semibold">5. Approved rollback/cutover plan</h2><Textarea className="mt-3" value={rollback} onChange={e=>setRollback(e.target.value)}/><Button className="mt-3" onClick={()=>run(()=>planFn({data:{tenantId,assetId:effectiveAsset,rollbackStrategy:rollback,changeWindow:null,freezeStrategy:"Short source write freeze during final delta",dnsStrategy:"No DNS change until smoke tests pass",communicationPlan:"Notify operators before cutover",smokeTests:["auth","orders","payments","KDS"],approve:true}}),"Cutover plan approved")}>Approve plan</Button></CardContent></Card>
    <Card><CardContent className="p-5"><h2 className="font-semibold">6. Required target checks</h2><div className="mt-3 space-y-2">{detail.data.targets.map((x:any)=><div key={x.id} className="flex items-center justify-between rounded border p-3 text-sm"><div><b>{x.target_tenant?.name||x.target_tenant_id}</b><p className="text-xs text-muted-foreground">{x.target_product_key} · {x.source_workspace_id||"workspace not set"}</p>{x.target_product_key==="dishbee"?<p className="mt-1 text-xs text-muted-foreground">Source runtime: {x.config?.lastSourceRuntime?.ready===true?"ready":x.config?.lastSourceRuntime?.dishbeeTenantId?"blocked":"not reported"}</p>:null}</div><div className="flex items-center gap-2"><StatusBadge status={x.status}/><Button size="sm" variant="outline" onClick={()=>run(()=>refreshFn({data:{targetId:x.id}}),"Target rechecked")}>Check</Button></div></div>)}</div><Button className="mt-4 w-full" disabled={!evaluation?.ready} onClick={()=>run(()=>readyFn({data:{assetId:effectiveAsset}}),"Asset marked cutover ready")}>Mark cutover ready</Button></CardContent></Card>
   </div>
  </>}
 </AppShell>
}
function Metric({label,value}:{label:string;value:number}){return <Card><CardContent className="p-5"><p className="text-xs uppercase text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></CardContent></Card>}
