import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const receptionCustomers=sqliteTable('reception_customers',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),externalRef:text('external_ref').notNull(),name:text('name').notNull(),phone:text('phone').notNull(),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('customer_source_ref').on(t.workspaceId,t.productId,t.externalRef),index('customer_phone_lookup').on(t.workspaceId,t.productId,t.phone)]);
export const speechUsage=sqliteTable('speech_usage',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),month:text('month').notNull(),requests:integer('requests').notNull().default(0),bytes:integer('bytes').notNull().default(0)},t=>[uniqueIndex('speech_workspace_month').on(t.workspaceId,t.month)]);
export const receptionItems=sqliteTable('reception_items',{id:text('id').primaryKey(),customerId:text('customer_id'),callerNumber:text('caller_number'),humanHandlerId:text('human_handler_id'),humanHandlerName:text('human_handler_name'),handoffNote:text('handoff_note').notNull().default(''),preferredHandlerId:text('preferred_handler_id'),preferredHandlerName:text('preferred_handler_name'),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),kind:text('kind').notNull(),channel:text('channel').notNull(),customer:text('customer').notNull(),contact:text('contact').notNull().default(''),summary:text('summary').notNull(),status:text('status').notNull().default('new'),externalKey:text('external_key').notNull(),sourceRef:text('source_ref'),receipt:text('receipt').notNull().default('{}'),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('reception_event').on(t.workspaceId,t.productId,t.externalKey),index('reception_status').on(t.workspaceId,t.status)]);
export const receptionSettings=sqliteTable('reception_settings',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),enabled:integer('enabled').notNull().default(0),instructions:text('instructions').notNull().default(''),escalation:text('escalation').notNull().default(''),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('reception_product').on(t.workspaceId,t.productId)]);
export const planningRecords=sqliteTable('planning_records',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),kind:text('kind').notNull(),recordKey:text('record_key').notNull(),data:text('data').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('planning_record').on(t.workspaceId,t.productId,t.kind,t.recordKey),index('planning_product').on(t.workspaceId,t.productId,t.kind)]);
export const planningScenarios=sqliteTable('planning_scenarios',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),name:text('name').notNull(),assumptions:text('assumptions').notNull(),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[index('scenarios_product').on(t.workspaceId,t.productId)]);
export const workspaces=sqliteTable('workspaces',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),name:text('name').notNull(),paused:integer('paused').notNull().default(0),runLimit:integer('run_limit').notNull().default(100),kind:text('kind').notNull().default('internal'),plan:text('plan').notNull().default('pilot'),monthlyPrice:integer('monthly_price').notNull().default(0),currency:text('currency').notNull().default('GBP'),createdAt:text('created_at').notNull()},t=>[index('workspace_owner_lookup').on(t.ownerId)]);
export const products=sqliteTable('products',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),slug:text('slug').notNull(),name:text('name').notNull(),sector:text('sector').notNull(),description:text('description').notNull(),color:text('color').notNull(),scope:text('scope').notNull().default('confirmed'),templateId:text('template_id').notNull(),mode:text('mode').notNull().default('approve'),enabled:integer('enabled').notNull().default(1),instructions:text('instructions').notNull().default(''),createdAt:text('created_at').notNull()},t=>[uniqueIndex('product_workspace_slug').on(t.workspaceId,t.slug)]);
export const runs=sqliteTable('runs',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),templateId:text('template_id').notNull(),title:text('title').notNull(),input:text('input').notNull(),kind:text('kind').notNull(),mode:text('mode').notNull(),status:text('status').notNull(),output:text('output'),error:text('error'),documentIds:text('document_ids').notNull().default('[]'),inputTokens:integer('input_tokens').notNull().default(0),outputTokens:integer('output_tokens').notNull().default(0),idempotencyKey:text('idempotency_key').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('runs_workspace_time').on(t.workspaceId,t.createdAt),uniqueIndex('run_idempotency').on(t.workspaceId,t.idempotencyKey)]);
export const actions=sqliteTable('actions',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),runId:text('run_id').notNull(),productId:text('product_id').notNull(),type:text('type').notNull(),title:text('title').notNull(),body:text('body').notNull(),assignee:text('assignee').notNull(),status:text('status').notNull(),decisionNote:text('decision_note'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('actions_workspace_status').on(t.workspaceId,t.status)]);
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),runId:text('run_id').notNull(),actionId:text('action_id').notNull(),title:text('title').notNull(),body:text('body').notNull(),assignee:text('assignee').notNull(),status:text('status').notNull().default('open'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('task_action').on(t.actionId),index('tasks_workspace_status').on(t.workspaceId,t.status)]);
export const documents=sqliteTable('documents',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),name:text('name').notNull(),key:text('object_key').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()},t=>[index('documents_workspace_product').on(t.workspaceId,t.productId)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),actor:text('actor').notNull(),event:text('event').notNull(),detail:text('detail').notNull(),resourceId:text('resource_id'),createdAt:text('created_at').notNull()},t=>[index('audit_workspace_time').on(t.workspaceId,t.createdAt)]);
export const integrations=sqliteTable('integrations',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),name:text('name').notNull(),tokenHash:text('token_hash').notNull(),lastSeen:text('last_seen'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('integration_token').on(t.tokenHash),uniqueIndex('integration_product').on(t.workspaceId,t.productId)]);
export const usage=sqliteTable('usage',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),month:text('month').notNull(),reserved:integer('reserved').notNull().default(0),inputTokens:integer('input_tokens').notNull().default(0),outputTokens:integer('output_tokens').notNull().default(0)},t=>[uniqueIndex('usage_workspace_month').on(t.workspaceId,t.month)]);

export const members=sqliteTable('members',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),userId:text('user_id').notNull(),email:text('email').notNull(),role:text('role').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('member_workspace_user').on(t.workspaceId,t.userId),index('members_user').on(t.userId)]);
export const invitations=sqliteTable('invitations',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),email:text('email').notNull(),role:text('role').notNull(),tokenHash:text('token_hash').notNull(),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('invite_token').on(t.tokenHash),index('invites_workspace').on(t.workspaceId)]);
export const sales=sqliteTable('sales',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),date:text('date').notNull(),location:text('location').notNull(),currency:text('currency').notNull(),gross:integer('gross').notNull(),refunds:integer('refunds').notNull(),orders:integer('orders').notNull(),cogs:integer('cogs'),labour:integer('labour'),source:text('source').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('sales_daily_source').on(t.workspaceId,t.productId,t.date,t.location,t.currency,t.source),index('sales_workspace_date').on(t.workspaceId,t.date)]);

export const journeys=sqliteTable('journeys',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),productId:text('product_id').notNull(),title:text('title').notNull(),goal:text('goal').notNull(),kind:text('kind').notNull(),currentStep:integer('current_step').notNull().default(0),stepRunId:text('step_run_id'),status:text('status').notNull(),history:text('history').notNull().default('[]'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('journeys_workspace').on(t.workspaceId,t.createdAt)]);

export const dailyPlans=sqliteTable('daily_plans',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),userId:text('user_id').notNull(),day:text('day').notNull(),timezone:text('timezone').notNull(),goals:text('goals').notNull().default(''),issues:text('issues').notNull().default(''),reviewNote:text('review_note').notNull().default(''),helpItemIds:text('help_item_ids').notNull().default('[]'),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('daily_plan_owner_day').on(t.workspaceId,t.userId,t.day)]);
export const dayItems=sqliteTable('day_items',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),userId:text('user_id').notNull(),productId:text('product_id'),sourceTaskId:text('source_task_id'),title:text('title').notNull(),notes:text('notes').notNull().default(''),scheduledDate:text('scheduled_date').notNull(),dueDate:text('due_date'),priority:text('priority').notNull().default('normal'),status:text('status').notNull().default('planned'),blocker:text('blocker').notNull().default(''),steps:text('steps').notNull().default('[]'),completedAt:text('completed_at'),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('day_item_owner_source').on(t.workspaceId,t.userId,t.sourceTaskId),index('day_items_owner_status').on(t.workspaceId,t.userId,t.status)]);
export const dayMeetings=sqliteTable('day_meetings',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull(),userId:text('user_id').notNull(),productId:text('product_id'),title:text('title').notNull(),startsAt:text('starts_at').notNull(),duration:integer('duration').notNull().default(30),timezone:text('timezone').notNull(),attendees:text('attendees').notNull().default(''),status:text('status').notNull().default('unconfirmed'),notes:text('notes').notNull().default(''),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('day_meetings_owner_time').on(t.workspaceId,t.userId,t.startsAt)]);
