import {receptionTeam} from '@/lib/customers';
import {env} from 'cloudflare:workers';
import {receptionConnections} from '@/lib/reception-status';
import {workspace,requireRole,sameOrigin,readBody,rows,one,stmt,db,auditStmt,product,now,id,fail,apiError} from '@/lib/server';
import {boundedText} from '@/lib/policy';
import {receiveReception,advanceReception,receptionEnabled} from '@/lib/reception';
export const dynamic='force-dynamic';
export async function GET(req?:Request){try{const {w}=await workspace();const url=new URL(req?.url||'https://app.local/api/reception'),pid=url.searchParams.get('productId')||'all',filter=url.searchParams.get('filter')||'all';if(!['all','open','order','booking','message'].includes(filter))fail('Choose a valid reception filter.');if(pid!=='all')await product(w.id,pid);const base='workspace_id=?'+(pid==='all'?'':' AND product_id=?'),args=pid==='all'?[w.id]:[w.id,pid];const filtered=base+(filter==='open'?" AND status IN ('new','queued','accepted','failed')":['order','booking','message'].includes(filter)?' AND kind=?':'');const filterArgs=['order','booking','message'].includes(filter)?[...args,filter]:args;let cursorSql='',cursorArgs:any[]=[];if(url.searchParams.has('before')){let c;try{const raw=url.searchParams.get('before')!;if(raw.length>300)throw Error();c=JSON.parse(raw);if(typeof c.createdAt!=='string'||!/^\d{4}-\d{2}-\d{2}T/.test(c.createdAt)||Number.isNaN(Date.parse(c.createdAt))||typeof c.id!=='string'||c.id.length>100||!c.id)throw Error()}catch{fail('Invalid reception page cursor.')}cursorSql=' AND (created_at<? OR (created_at=? AND id<?))';cursorArgs=[c.createdAt,c.createdAt,c.id];}
 const [page,settings,counts,matched,receipts]=await Promise.all([rows('SELECT * FROM reception_items WHERE '+filtered+cursorSql+' ORDER BY created_at DESC,id DESC LIMIT 101',...filterArgs,...cursorArgs),rows('SELECT * FROM reception_settings WHERE workspace_id=?',w.id),one("SELECT COUNT(*) AS total,SUM(status IN ('new','queued','accepted','failed')) AS pending,SUM(kind='booking' AND status IN ('new','queued','failed')) AS bookings,SUM(kind='order' AND status IN ('new','queued','accepted','failed')) AS orders FROM reception_items WHERE "+base,...args),one('SELECT COUNT(*) AS n FROM reception_items WHERE '+filtered,...filterArgs),one("SELECT SUM(kind='order' AND source_ref IS NOT NULL AND json_extract(receipt,'$.accepted')=1) AS orders,SUM(kind='booking' AND source_ref IS NOT NULL AND json_extract(receipt,'$.slotReserved')=1) AS bookings,SUM(kind='order' AND source_ref IS NOT NULL AND json_extract(receipt,'$.kdsAcknowledged')=1) AS kds,MAX(CASE WHEN kind='order' AND json_extract(receipt,'$.accepted')=1 THEN updated_at END) AS last_order,MAX(CASE WHEN kind='booking' AND json_extract(receipt,'$.slotReserved')=1 THEN updated_at END) AS last_booking,MAX(CASE WHEN kind='order' AND json_extract(receipt,'$.kdsAcknowledged')=1 THEN updated_at END) AS last_kds FROM reception_items WHERE "+base,...args)]);
 const products=await rows('SELECT id,name FROM products WHERE workspace_id=?',w.id);const items=page.slice(0,100).map(r=>({...r,product_name:products.find(p=>p.id===r.product_id)?.name||'Product'})),last=items[items.length-1];return Response.json({items,settings,team:['owner','admin','operator'].includes(w.role)?await receptionTeam(w.id):[],counts,filteredCount:matched?.n||0,nextCursor:page.length>100?JSON.stringify({createdAt:page[99].created_at,id:page[99].id}):null,connections:receptionConnections(!!env.OPENAI_API_KEY,receipts||{}),generatedAt:now(),limit:100},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return apiError(e);}}
export async function POST(req:Request){try{sameOrigin(req);const {w,user}=await workspace();requireRole(w,['owner','admin','operator']);const b=await readBody(req);const p=await product(w.id,b.productId);if(b.action==='settings'){requireRole(w,['owner','admin']);if(!Number.isInteger(b.revision)||b.revision<0)fail('Reload reception settings.');const result=await stmt('INSERT INTO reception_settings(id,workspace_id,product_id,enabled,instructions,escalation,revision,updated_at) VALUES(?,?,?,?,?,?,1,?) ON CONFLICT(workspace_id,product_id) DO UPDATE SET enabled=excluded.enabled,instructions=excluded.instructions,escalation=excluded.escalation,revision=reception_settings.revision+1,updated_at=excluded.updated_at WHERE reception_settings.revision=?',id(),w.id,p.id,b.enabled?1:0,boundedText(b.instructions,4000),boundedText(b.escalation,1000),now(),b.revision).run();if(!result.meta.changes)fail('Settings changed. Refresh and review them.',409);return Response.json({ok:true});}if(w.paused)fail('The workspace is paused.',409);if(b.action==='receive'){const key=boundedText(b.requestKey,80);if(!key)fail('A request key is required.');return Response.json({item:await receiveReception(w.id,p.id,b,'manual:'+key,user.email)});}if(b.action==='advance'){if(b.status==='queued')await receptionEnabled(w.id,p.id);return Response.json({item:await advanceReception(w.id,p.id,b,user.email)});}fail('Unknown reception action.');}catch(e){return apiError(e);}}
