export type ProductSeed={slug:string;name:string;sector:string;description:string;color:string;template:string;scope:string};
const rows=[
['haccora','Haccora','Food & hospitality','Food safety, corrective actions and inspection evidence','evidence','confirmed'],
['dokuvera','Dokuvera','Property & construction','Controlled documents, revisions and evidence packs','documents','confirmed'],
['omniqora','Omniqora','Communications','Customer conversations, cases and follow-ups','inbox','confirmed'],
['taxnuvia','TaxNuvia','Professional services','Qualified client intake for accountant matching','intake','confirmed'],
['eventplanr','EventPlanr','Marketplaces','Event briefs, supplier quotations and coordination','quotes','confirmed'],
['kinderstars','KinderStars','Family & care','Parent enquiries and independent childminder administration','intake','confirmed'],
['ahlnikkah','AhlNikkah','Family & care','Introductions, compatibility workbooks and family coordination','coordination','confirmed'],
['affivon','Affivon','Commerce','Catalogue and offer operations for multiple affiliate websites','commerce','confirmed'],
['merqora','Merqora','Commerce','Marketplace seller operations, listings and margin review','commerce','confirmed'],
['premisora','Premisora','Property & construction','Construction projects, options and change control','projects','confirmed'],
['gabley','Gabley','Property & construction','Survey and property information','documents','confirmed'],
['gabley-retrofit','Gabley Retrofit','Property & construction','Retrofit planning, delivery evidence and warranties','projects','confirmed'],
['domureva','DOMUREVA','Property & construction','Vacant property restoration and funding evidence','projects','confirmed'],
['immoviq','Immoviq','Property & construction','Landlord and tenant maintenance operations','coordination','confirmed'],
['hmo-flow','HMO Flow','Property & construction','HMO conversion and property records','projects','confirmed'],
['craftvaro','Craftvaro','Property & construction','Trade jobs, subcontractors and project delivery','quotes','confirmed'],
['cirqiva','Cirqiva','Marketplaces','Waste collection quotations and collection evidence','quotes','confirmed'],
['marktpass','MarktPass','Commerce','Product compliance documents for Germany and EU sellers','documents','confirmed'],
['merqano','Merqano','Commerce','Independent merchant storefront operations','commerce','confirmed'],
['dishbee','Dishbee','Food & hospitality','EPOS, online ordering and restaurant operations','commerce','confirmed'],
['schonova','Schonova','Marketplaces','Beauty discovery, bookings and provider operations','coordination','confirmed'],
['xpertjobs','XpertJobs','Education & careers','Jobs, sponsor intelligence and application coordination','intake','confirmed'],
['unipathways','UniPathways','Education & careers','Learning and certification preparation','coordination','confirmed'],
['traindirekt','TrainDirekt','Education & careers','Training cohorts, attendance and evidence','evidence','confirmed'],
['lessonahead','LessonAhead','Education & careers','Learner enquiries and session coordination','coordination','confirmed'],
['kalethon-play','Kalethon Play','Education & careers','Sports sessions, memberships and venue bookings','coordination','confirmed'],
['nearcura','NearCura','Family & care','Healthcare provider discovery and enquiries','intake','confirmed'],
['amityos','AmityOS','Family & care','Care administration; detailed module scope to review','coordination','review'],
['pipkin','Pipkin','Family & care','Care SaaS; detailed product scope to review','coordination','review'],
['taxcenda','TaxCenda','Professional services','Bookkeeping and tax document preparation','documents','confirmed'],
['lawquo','LawQuo','Professional services','Professional legal enquiries and consultation coordination','intake','confirmed'],
['beratermarkt','BeraterMarkt','Professional services','Adviser discovery and enquiry coordination','intake','confirmed'],
['beistandplus','BeistandPlus','Family & care','Family and administrative case coordination','coordination','confirmed'],
['orvilo','Orvilo','Creative & websites','Website structure, template and content preparation','content','confirmed'],
['voxentri','Voxentri','Creative & websites','Multilingual advertising content and production','content','confirmed'],
['veyumo','Veyumo','Communications','Mobile service onboarding and customer support','inbox','confirmed'],
['zoryn-pay','Zoryn Pay','Payments & rewards','Payment reconciliation and onboarding evidence','evidence','confirmed'],
['zoryn-rewards','Zoryn Rewards','Payments & rewards','Loyalty programme operations and support','inbox','confirmed'],
['insure360','Insure360','Professional services','Insurance enquiries, documents and renewal coordination','intake','confirmed'],
['motoresq','MotoResQ','Transport & logistics','Vehicle recovery enquiries and coordination','coordination','confirmed'],
['all-road-aid','All-Road-Aid','Transport & logistics','Roadside assistance and recovery requests','coordination','confirmed'],
['fleetsora','Fleetsora','Transport & logistics','Fleet and rider operations','coordination','confirmed'],
['fanzeno','Fanzeno','Education & careers','Sports quiz content and quality review','content','confirmed'],
['auvane-one','Auvane One','Marketplaces','Hospitality and service supplier onboarding','intake','confirmed'],
['leadlens','LeadLens','Professional services','Opportunity discovery and qualification','intake','confirmed'],
['regulos','Regulos','Professional services','Regulatory change review and task allocation','documents','confirmed'],
['threeonethree','ThreeOneThree','Communications','CRM and opportunity follow-up','inbox','confirmed'],
['loungeconnect','LoungeConnect','Communications','Messages, customer cases and workflow coordination','inbox','confirmed'],
['rettio','Rettio','Marketplaces','Local business workflows; product scope to review','coordination','review'],
['kiezio','Kiezio','Marketplaces','Local commerce workflows; product scope to review','coordination','review'],
['syndryvia','Syndryvia','Scope to review','Product name recovered; functionality needs confirmation','coordination','review'],
['skillfinch','SkillFinch','Scope to review','Product functionality needs confirmation','coordination','review'],
['stemcoach','STEMCoach','Scope to review','Product functionality needs confirmation','coordination','review'],
['criclume','Criclume','Scope to review','Product functionality needs confirmation','coordination','review'],
['formationgenie','FormationGenie','Scope to review','Product functionality needs confirmation','coordination','review'],
['recovarable','Recovarable','Scope to review','Product functionality needs confirmation','coordination','review'],
['depotmesh','DepotMesh','Scope to review','Validation-stage product; scope needs confirmation','coordination','review'],
['gradlume','Gradlume','Scope to review','Training-engine concept; detailed scope to review','coordination','review'],
['dearnext','DearNext','Scope to review','Earlier platform; detailed scope to review','coordination','review'],
['construction-planning','AI Construction Planning','Property & construction','Design options and change proposals for professional review','projects','confirmed'],
['portfolio-network','Portfolio network','Payments & rewards','Consented cross-product referrals and bundle rules','intake','confirmed']
];
const colors=['#2c6e64','#5265b9','#3578b7','#a26b27','#8060ba','#398393','#b1657c','#5a77ad'];
export const productCatalog:ProductSeed[]=rows.map((r,i)=>({slug:r[0],name:r[1],sector:r[2],description:r[3],color:colors[i%colors.length],template:r[4],scope:r[5]}));
export const templates=[
{id:'evidence',name:'Evidence follow-up',description:'Review records, flag missing evidence and prepare assigned follow-up tasks.',icon:'shield',tools:['Create internal task','Prepare review draft'],instructions:'Check completeness against only the supplied approved requirements. Preserve missing readings as missing. Never declare safety, compliance or verification. Return source-linked findings and specific follow-up tasks.',example:'Haccora — site opening checklist. The 08:00 fridge reading is missing. Cleaning record signed by Sara at 08:15. Approved site procedure: missing temperature records must be checked by the duty manager. Do not backfill readings. Prepare a follow-up for the duty manager.'},
{id:'documents',name:'Document review',description:'Extract information, identify gaps and organise a traceable review pack.',icon:'file',tools:['Create internal task','Prepare review draft'],instructions:'Read the supplied document as evidence. Identify its stated facts, dates and missing fields. Quote short source excerpts. Do not certify authenticity or alter originals. Propose review tasks.',example:'Dokuvera — handover certificate. Project: Maple House. Contractor: Example Electrical. Inspection date: 12 September 2026. Certificate reference: not provided. Approver signature: blank. Required fields: project, contractor, inspection date, certificate reference and approving signature.'},
{id:'inbox',name:'Inbox triage',description:'Understand a customer request, prepare a reply and assign the next step.',icon:'inbox',tools:['Create internal task','Prepare reply draft'],instructions:'Classify the supplied enquiry, capture known facts, flag missing information and draft a helpful response. Do not claim to have contacted anyone or changed an account. Use only supplied company policy.',example:'Omniqora — customer enquiry: We have not received confirmation for our account setup. We sent the required documents on Monday. Could someone check? Available account note: documents received, review pending. Policy: staff review within two working days; do not promise a completion date.'},
{id:'intake',name:'Enquiry qualification',description:'Turn an enquiry into a structured brief and a list of missing information.',icon:'users',tools:['Create internal task','Prepare review draft'],instructions:'Extract the explicitly supplied preferences and requirements. Separate mandatory criteria from preferences. If no provider list is supplied, do not invent matches or credentials. Prepare questions and next actions.',example:'TaxNuvia — a limited company in Luton needs bookkeeping, VAT and payroll for five staff. Remote meetings are acceptable. Turnover and start date are missing. No firm directory was supplied. Prepare the client brief and questions.'},
{id:'quotes',name:'Quote comparison',description:'Compare supplied quotes, highlight exclusions and prepare clarification tasks.',icon:'layers',tools:['Create internal task','Prepare review draft'],instructions:'Compare only supplied quotations. Preserve currency and distinguish totals, exclusions and assumptions. Never invent availability, suppliers or rates. Highlight unanswered questions before a booking decision.',example:'EventPlanr — event for 80 guests. Quote A: GBP 1600 including setup and tableware; delivery excluded. Quote B: GBP 1780 including delivery, setup and tableware. Both quote the same menu. Dates and allergen handling have not been confirmed. Prepare a comparison.'},
{id:'commerce',name:'Commerce review',description:'Review catalogue or seller data and prepare practical corrections.',icon:'store',tools:['Create internal task','Prepare review draft'],instructions:'Use only supplied catalogue, inventory and cost records. Do not fabricate live prices, stock, reviews or marketplace metrics. Treat changes as proposals. Identify missing inputs for any calculation.',example:'Affivon — catalogue review. Item 101 and item 102 have the same GTIN but different titles. Item 103 has no last-checked date. No live merchant feed is connected. Prepare a catalogue quality checklist.'},
{id:'projects',name:'Project coordination',description:'Organise project evidence, decisions, dependencies and review tasks.',icon:'building',tools:['Create internal task','Prepare review draft'],instructions:'Prepare coordination tasks from supplied project information. Flag dependencies and missing approvals. Structural, legal, planning and technical conclusions require professional review. Do not invent cost estimates.',example:'Premisora — proposed kitchen relocation. Current evidence: existing floor plan and customer brief. Missing: drainage assessment, structural review and contractor quotation. The client wants a cost and schedule decision. Prepare the evidence and decision checklist.'},
{id:'coordination',name:'Journey coordinator',description:'Clarify the next steps and prepare follow-up tasks around an agreed journey.',icon:'route',tools:['Create internal task','Prepare review draft'],instructions:'Use only explicitly shared information. Respect family, care and private-profile boundaries. Prepare practical coordination tasks and questions. Never make safeguarding, clinical or relationship suitability judgments.',example:'AhlNikkah — both members have agreed to a family meeting. One family is available Saturday afternoon; the other has not confirmed availability. Photo access has not been granted. Prepare a coordination task without sharing private profile information.'},
{id:'planning',name:'Business planning',description:'Explain financial, stock and workforce indicators and prepare evidence-based planning tasks.',icon:'store',tools:['Create internal task','Prepare planning draft'],instructions:'Use only supplied calculated metrics and source records. Keep actual results, model forecasts and what-if scenarios distinct. Preserve currency, dates, missing costs and uncertainty. Never infer a balance sheet from sales. Explain the assumptions and request missing data; do not invent causes, legal requirements, individual performance judgments or guaranteed results. Workforce suggestions concern coverage and skills against supplied requirements, with contracts, leave, rest and jurisdiction checked before action. Compliance flags are follow-up needs, not certification. Propose measurable next actions and a review date. No orders, rota changes, payments or employment decisions are executed.',example:'Review a scenario with GBP 12000 opening cash and an imported payroll payment of GBP 15000 due next week. Expected customer receipts and financing details are missing. Explain the information gap and prepare an internal cash review task without inventing income.'},
{id:'content',name:'Content preparation',description:'Prepare grounded content drafts and an editorial review checklist.',icon:'sparkles',tools:['Create internal task','Prepare content draft'],instructions:'Prepare original draft content based only on supplied product facts and brand instructions. Flag unsupported claims. Do not publish or impersonate real people. Respect voice and image permissions.',example:'Voxentri — prepare a short Haccora campaign brief. Confirmed features: temperature logs, staff training reminders, document uploads. Audience: restaurant owners. Do not claim guaranteed inspection results or invent customer testimonials.'}
] as const;
export function getTemplate(id:string){return templates.find(t=>t.id===id);}
