import {parseCSV} from './analytics';
import {validDay,offsetDay} from './day';
export type PlanRow=Record<string,any>;
export const planKinds=['financials','cashflow','inventory','shifts','compliance'] as const;
export type PlanKind=typeof planKinds[number];
export const planNames:Record<PlanKind,string>={financials:'Accounts',cashflow:'Cash commitments',inventory:'Stock and expiry',shifts:'Rota coverage',compliance:'Training and compliance'};
export const planHeaders:Record<PlanKind,string[]>={
 financials:['period_start','period_end','location','currency','account_code','account_name','category','amount'],
 cashflow:['due_date','location','currency','reference','direction','category','amount','status'],
 inventory:['as_of','location','sku','item_name','lot','unit','on_hand','on_order','avg_daily_usage','lead_days','safety_stock','expiry_date','unit_cost','currency'],
 shifts:['date','location','team','start','end','required_staff','scheduled_staff','staff_names','required_skills','confirmed_skills','status'],
 compliance:['reference','location','subject','requirement','category','due_date','owner','status','evidence_ref']
};
export const pnlCategories=['revenue','cogs','payroll','overheads','depreciation','interest','tax'];
export const balanceCategories=['asset','liability','equity'];
export function csvTemplate(kind:PlanKind){return planHeaders[kind].join(',')+'\n';}
export function parseMoney(s:string,signed=false){if(!(signed?/^-?\d+(\.\d{1,2})?$/:/^\d+(\.\d{1,2})?$/).test(s))throw Error('Use monetary amounts with at most two decimal places.');const v=Math.round(Number(s)*100);if(!Number.isSafeInteger(v)||Math.abs(v)>1e11)throw Error('Amount is too large.');return v;}
function number(s:string,max=1e7,whole=false){if(!/^\d+(\.\d{1,4})?$/.test(s))throw Error('Use a non-negative number.');const n=Number(s);if(n>max||whole&&!Number.isInteger(n))throw Error(whole?'Use a whole number within the allowed range.':'Number is too large.');return n;}
export function parsePlanning(kind:PlanKind,text:string):{key:string;data:PlanRow}[]{if(!planKinds.includes(kind))throw Error('Choose a valid dataset.');const rows=parseCSV(text.replace(/^\uFEFF/,''));if(rows.length<2||rows.length>501)throw Error('Add a header and 1 to 500 data rows.');const h=planHeaders[kind];if(rows[0].join(',')!==h.join(','))throw Error('Use the template headers in the same order.');const seen=new Set<string>();return rows.slice(1).map((cells,i)=>{try{if(cells.length!==h.length)throw Error('Expected '+h.length+' columns.');if(cells.some(c=>c.length>1000))throw Error('Keep each value below 1,000 characters.');const r:PlanRow=Object.fromEntries(h.map((key,n)=>[key,cells[n]]));const required=(...keys:string[])=>keys.forEach(k=>{if(!r[k])throw Error('Add '+k.replaceAll('_',' ')+'.')});const day=(...keys:string[])=>keys.forEach(k=>{if(!validDay(r[k]))throw Error('Use a valid YYYY-MM-DD date for '+k+'.')});const choice=(key:string,values:string[])=>{if(!values.includes(r[key]))throw Error(key+' must be one of: '+values.join(', '));};required('location');if(r.currency)choice('currency',['GBP','EUR','USD','AED']);let parts:any[]=[];
 if(kind==='financials'){required('currency','account_code','account_name');day('period_start','period_end');if(r.period_start>r.period_end)throw Error('The period end must follow its start.');choice('category',[...pnlCategories,...balanceCategories]);if(balanceCategories.includes(r.category)&&r.period_start!==r.period_end)throw Error('For balance sheet accounts, use the same as-of date in both period columns.');r.amount=parseMoney(r.amount,true);parts=[r.period_start,r.period_end,r.location,r.currency,r.account_code];}
 if(kind==='cashflow'){required('currency','reference','category');day('due_date');choice('direction',['in','out']);choice('status',['expected','paid']);r.amount=parseMoney(r.amount);parts=[r.location,r.currency,r.reference];}
 if(kind==='inventory'){required('currency','sku','item_name','lot','unit');day('as_of');if(r.expiry_date)day('expiry_date');for(const k of ['on_hand','on_order','avg_daily_usage','safety_stock'])r[k]=number(r[k]);r.lead_days=number(r.lead_days,730,true);r.unit_cost=r.unit_cost===''?null:parseMoney(r.unit_cost);parts=[r.location,r.sku,r.lot,r.as_of];}
 if(kind==='shifts'){required('team');day('date');for(const k of ['start','end'])if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(r[k]))throw Error('Use HH:MM times.');if(r.start===r.end)throw Error('A shift must have a non-zero duration.');r.required_staff=number(r.required_staff,10000,true);r.scheduled_staff=number(r.scheduled_staff,10000,true);choice('status',['draft','confirmed']);parts=[r.date,r.location,r.team,r.start,r.end];}
 if(kind==='compliance'){required('reference','subject','requirement','owner');day('due_date');choice('category',['training','staff','business']);choice('status',['open','complete']);parts=[r.location,r.reference];}
 const key=JSON.stringify(parts);if(seen.has(key))throw Error('Duplicate record in this file.');seen.add(key);return {key,data:r};}catch(e:any){throw Error('Row '+(i+2)+': '+e.message)}});}
const sum=(rows:PlanRow[],key:string)=>rows.reduce((n,r)=>n+r[key],0);
export function accountSummary(rows:PlanRow[],start:string,end:string,currency:string,location='all'){
 const selected=rows.filter(r=>r.currency===currency&&(location==='all'||r.location===location));const pnl=selected.filter(r=>pnlCategories.includes(r.category)&&r.period_start===start&&r.period_end===end);const balance=selected.filter(r=>balanceCategories.includes(r.category)&&r.period_end===end);const totals:Record<string,number|null>={};
 const pnlLocations=[...new Set(pnl.map(r=>r.location))],balanceLocations=[...new Set(balance.map(r=>r.location))];for(const c of [...pnlCategories,...balanceCategories]){const group=balanceCategories.includes(c)?balance:pnl,locations=balanceCategories.includes(c)?balanceLocations:pnlLocations;totals[c]=locations.length>0&&locations.every(l=>group.some(r=>r.location===l&&r.category===c))?sum(group.filter(r=>r.category===c),'amount'):null;}
 const full=pnlCategories.every(c=>totals[c]!==null);const net=full?totals.revenue!-pnlCategories.filter(c=>c!=='revenue').reduce((n,c)=>n+totals[c]!,0):null;
 return {pnl,balance,totals,complete:full,net,gross:totals.revenue!==null&&totals.cogs!==null?totals.revenue-totals.cogs:null,margin:net!==null&&totals.revenue?net/totals.revenue*100:null,balanceDifference:balanceCategories.every(c=>totals[c]!==null)?totals.asset!-totals.liability!-totals.equity!:null,missing:pnlCategories.filter(c=>totals[c]===null)};
}
export function salesForecast(rows:PlanRow[],asOf:string,horizon:number,change=0){
 const past=rows.filter(r=>r.date<asOf&&r.date>=offsetDay(asOf,-70));const locations=[...new Set(past.filter(r=>r.date>=offsetDay(asOf,-28)).map(r=>r.location))];const byDate=new Map<string,number>();for(const r of past)byDate.set(r.date,(byDate.get(r.date)||0)+r.gross-r.refunds);
 const covered=(date:string)=>locations.length>0&&locations.every(l=>past.some(r=>r.date===date&&r.location===l));const missing=Array.from({length:28},(_,i)=>offsetDay(asOf,-28+i)).filter(d=>!covered(d));if(missing.length)return {ready:false,missing,locations,points:[],reason:'Import a complete 28-day window for every selected location. Include zero-sales rows for closed days.'};
 const weekday=(d:string)=>new Date(d+'T12:00:00Z').getUTCDay();const baseline=(target:string,before:string)=>{const history=Array.from({length:28},(_,i)=>offsetDay(before,-28+i)).filter(d=>weekday(d)===weekday(target));return Math.max(0,history.reduce((n,d)=>n+(byDate.get(d)||0),0)/history.length)};
 const points=Array.from({length:horizon},(_,i)=>{const date=offsetDay(asOf,i),base=Math.round(baseline(date,asOf)),value=Math.round(base*(1+change/100));return {date,baseline:base,value,lower:Math.round(value*.85),upper:Math.round(value*1.15)}});
 let mae:number|null=null;const validation=Array.from({length:14},(_,i)=>offsetDay(asOf,-14+i));if(Array.from({length:42},(_,i)=>offsetDay(asOf,-42+i)).every(covered))mae=Math.round(validation.reduce((n,d)=>n+Math.abs((byDate.get(d)||0)-baseline(d,d)),0)/14);
 return {ready:true,points,total:sum(points,'value'),baselineTotal:sum(points,'baseline'),lower:sum(points,'lower'),upper:sum(points,'upper'),locations,missing:[],mae,historyStart:offsetDay(asOf,-28),historyEnd:offsetDay(asOf,-1)};
}
export function cashProjection(rows:PlanRow[],asOf:string,horizon:number,opening:number,delay=0){const end=offsetDay(asOf,horizon-1);const expected=rows.filter(r=>r.status==='expected').map<PlanRow>(r=>({...r,planned_date:offsetDay(r.due_date,r.direction==='in'?delay:0)})).map<PlanRow>(r=>({...r,planned_date:r.planned_date<asOf?asOf:r.planned_date})).filter(r=>r.planned_date<=end).sort((a,b)=>a.planned_date.localeCompare(b.planned_date));let balance=opening;const points=Array.from({length:horizon},(_,i)=>{const date=offsetDay(asOf,i),items=expected.filter(r=>r.planned_date===date),incoming=sum(items.filter(r=>r.direction==='in'),'amount'),outgoing=sum(items.filter(r=>r.direction==='out'),'amount');balance+=incoming-outgoing;return {date,incoming,outgoing,balance}});return {points,expected,closing:balance,lowest:Math.min(opening,...points.map(p=>p.balance)),firstShortfall:opening<0?asOf:points.find(p=>p.balance<0)?.date||null,incoming:sum(points,'incoming'),outgoing:sum(points,'outgoing'),overdue:rows.filter(r=>r.status==='expected'&&r.due_date<asOf).length};}
export function inventoryPlan(rows:PlanRow[],asOf:string,change=0){const candidates=rows.filter(r=>r.as_of<=asOf);const groups=new Map<string,PlanRow[]>();for(const r of candidates){const key=JSON.stringify([r.location,r.sku]);groups.set(key,[...(groups.get(key)||[]),r])}const items:PlanRow[]=[];for(const all of groups.values()){const latest=all.reduce((d,r)=>r.as_of>d?r.as_of:d,'');const lots=all.filter(r=>r.as_of===latest).sort((a,b)=>(a.expiry_date||'9999').localeCompare(b.expiry_date||'9999'));const first=lots[0],consistent=lots.every(r=>r.unit===first.unit&&r.avg_daily_usage===first.avg_daily_usage&&r.lead_days===first.lead_days&&r.safety_stock===first.safety_stock&&r.currency===first.currency);const rate=first.avg_daily_usage*(1+change/100);const usable=lots.filter(r=>!r.expiry_date||r.expiry_date>=asOf),onHand=sum(usable,'on_hand'),onOrder=sum(lots,'on_order'),expired=sum(lots.filter(r=>r.expiry_date&&r.expiry_date<asOf),'on_hand');let allocated=0;const breakdown=lots.map(r=>{const days=r.expiry_date?Math.max(0,Math.round((Date.parse(r.expiry_date)-Date.parse(asOf))/86400000)+1):null;const consumed=days===null?r.on_hand:Math.min(r.on_hand,Math.max(0,days*rate-allocated));const risk=consistent&&days!==null?Math.max(0,r.on_hand-consumed):null;allocated+=consumed;return {...r,atRisk:risk,riskValue:risk!==null&&r.unit_cost!==null?Math.round(risk*r.unit_cost):null,expired:days===0}});items.push({...first,as_of:latest,lots:breakdown,consistent,rate,onHand,onOrder,expired,daysCover:consistent&&rate>0?onHand/rate:null,reorder:consistent?Math.max(0,Math.ceil(rate*first.lead_days+first.safety_stock-onHand-onOrder)):null,atRisk:consistent?breakdown.reduce((n,r)=>n+(r.atRisk||0),0):null,stale:latest<offsetDay(asOf,-2)});}return items;}
const minutes=(s:string)=>Number(s.slice(0,2))*60+Number(s.slice(3));
export function workforcePlan(rows:PlanRow[],asOf:string,horizon:number){return rows.filter(r=>r.date>=asOf&&r.date<=offsetDay(asOf,horizon-1)).map(r=>{const duration=(minutes(r.end)-minutes(r.start)+1440)%1440/60,required=r.required_skills.split(';').map((s:string)=>s.trim().toLowerCase()).filter(Boolean),confirmed=r.confirmed_skills.split(';').map((s:string)=>s.trim().toLowerCase()).filter(Boolean);return {...r,duration,gap:r.scheduled_staff-r.required_staff,requiredHours:duration*r.required_staff,scheduledHours:duration*r.scheduled_staff,missingSkills:required.filter((s:string)=>!confirmed.includes(s))}});}
export function compliancePlan(rows:PlanRow[],asOf:string){return rows.map<PlanRow>(r=>({...r,flag:r.status==='complete'?(r.evidence_ref?'Recorded complete':'Evidence missing'):r.due_date<asOf?'Overdue':r.due_date<=offsetDay(asOf,30)?'Due within 30 days':'Upcoming'})).sort((a,b)=>a.due_date.localeCompare(b.due_date));}
