export type RolloutRecord = { id: string; source: string; name: string; kind: "Site" | "GitHub"; state: "published" | "merged" | "blocked"; audience: string; placement: string; url: string; note: string; evidence: string };
export const rolloutVerifiedAt = "2026-09-15T10:11:27.259Z";
export const portfolioRollout: RolloutRecord[] = [
  {
    "id": "omniqora-ai",
    "source": "portfolio-network",
    "name": "Omniqora Intelligence console",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Portfolio rules and rollout visibility",
    "url": "https://omniqora-ai.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90a9bfb8c8191ae65ca92ba745865"
  },
  {
    "id": "veyumo",
    "source": "veyumo",
    "name": "Veyumo",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Business page",
    "url": "https://veyumo.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90a237e3c8191a9a46e70c03f71e8"
  },
  {
    "id": "insure360",
    "source": "insure360",
    "name": "Insure360",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Owner/admin overview, team and connections",
    "url": "https://insure360.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90a2916948191baad572a07a4fc21"
  },
  {
    "id": "lessonahead",
    "source": "lessonahead",
    "name": "LessonAhead UK",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Instructor dashboard and school fleet",
    "url": "https://lessonahead-uk.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90c94ac488191a598c16146fdd8a3"
  },
  {
    "id": "premisora",
    "source": "premisora",
    "name": "Premisora",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Business and provider asset workflows",
    "url": "https://premisora-uk.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90c9b993c819181b55faa41fe5171"
  },
  {
    "id": "cirqiva",
    "source": "cirqiva",
    "name": "Cirqiva",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Provider and operator workspaces",
    "url": "https://wastora-uk.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90ca0fab08191b2508886c93d9aae"
  },
  {
    "id": "regulos2",
    "source": "regulos",
    "name": "RegulaOS",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Business document workflow using profile country",
    "url": "https://regulaos.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa912dcf1288191bdad5a329cf57463"
  },
  {
    "id": "gabley-retrofit",
    "source": "gabley-retrofit",
    "name": "Gabley Retrofit",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Professional asset workspace",
    "url": "https://gabley-retrofit.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90e1b965081918e395a62e0740311"
  },
  {
    "id": "marktpass",
    "source": "marktpass",
    "name": "MarktPass",
    "kind": "Site",
    "state": "published",
    "audience": "Public",
    "placement": "Overview, reports and team; Germany",
    "url": "https://marktpass-dashboard.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90e2fc2f4819182d9fa42a3fc31c3"
  },
  {
    "id": "affivon",
    "source": "affivon",
    "name": "Affivon",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Administrator dashboard",
    "url": "https://affiliate-commerce-os.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa90e211458819188c48c49e151dddf"
  },
  {
    "id": "sponsor-intelligence-uk",
    "source": "xpertjobs",
    "name": "Sponsor Intelligence UK",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Job seeker resources; explicit consumer relationships only",
    "url": "https://sponsor-intelligence-uk.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa914fa8a708191b207afb45eba8ee5"
  },
  {
    "id": "taxnuvia-accounts",
    "source": "taxnuvia",
    "name": "TaxNuvia Accounts UK",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Business overview",
    "url": "https://taxnuvia-accounts.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa9147023388191a63e8ea58272a8da"
  },
  {
    "id": "tenderos",
    "source": "tenderos",
    "name": "Tendryva",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Overview, team and evidence; chosen business market",
    "url": "https://tenderos.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa914ffd9208191bbc65834482a19d1"
  },
  {
    "id": "konnevia-crm",
    "source": "konnevia",
    "name": "Konnevia CRM",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Dashboard, CRM, team and integrations; chosen market",
    "url": "https://konnevia-crm.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa91504fbb88191995325a174daf8e5"
  },
  {
    "id": "commerceops",
    "source": "commerceops",
    "name": "CommerceOps",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Overview, suppliers and integrations; chosen market",
    "url": "https://commerceops.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa9150ab1248191bf287935f7b88ac8"
  },
  {
    "id": "recovra-recovery",
    "source": "recovra",
    "name": "Recovra",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Overview, team and integrations; chosen market",
    "url": "https://recovra-recovery.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa915109c948191b36ab73529c3ee79"
  },
  {
    "id": "travel-agency-os",
    "source": "travel-agency-os",
    "name": "Travel Agency OS",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Overview and suppliers; chosen market",
    "url": "https://travel-agency-os.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa91570b35481919de111080a04f514"
  },
  {
    "id": "empfangiq-dashboard",
    "source": "empfangiq",
    "name": "EmpfangIQ",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Overview, team and integrations; Germany",
    "url": "https://empfangiq-dashboard.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa91576623481918d166d9532b3d59b"
  },
  {
    "id": "loungetech-training-cloud",
    "source": "loungetech-training",
    "name": "LoungeTech Training Cloud",
    "kind": "Site",
    "state": "published",
    "audience": "Public",
    "placement": "Provider administrator overview, people and evidence; Germany",
    "url": "https://loungetech-training-cloud.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa9157c67f4819180f365c77c374ad4"
  },
  {
    "id": "loungetech-gruendung",
    "source": "loungetech-founders",
    "name": "LoungeTech Gründungsportal",
    "kind": "Site",
    "state": "published",
    "audience": "Public",
    "placement": "Founder/administrator overview and partners; Germany",
    "url": "https://loungetech-gruendung.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa91581b97c81919ea78c0be1664de8"
  },
  {
    "id": "private-lifestyle-concierge",
    "source": "auvane-one",
    "name": "Auvane One professional desk",
    "kind": "Site",
    "state": "published",
    "audience": "Private",
    "placement": "Professional workspace; chosen business market",
    "url": "https://private-lifestyle-concierge.amersaleem.chatgpt.site",
    "note": "Publication succeeded. Existing audience preserved; provider availability and paid activation remain separate.",
    "evidence": "appgdep_6aa915873f3481919c47ff4c6520f160"
  },
  {
    "id": "haccora",
    "source": "haccora",
    "name": "Haccora Germany",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Owner dashboard; Germany",
    "url": "https://github.com/asaffilate01-ship-it/haccora/pull/17",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "fe9e1e6556c38f2dc5ce62df5d4d156773027281"
  },
  {
    "id": "jobflow-tradehub",
    "source": "craftvaro",
    "name": "Craftvaro",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Trader dashboard and business performance",
    "url": "https://github.com/asaffilate01-ship-it/jobflow-tradehub/pull/8",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "ec31186766c25da59c2f3b77a360bc441c34e4c8"
  },
  {
    "id": "xpertjobs",
    "source": "xpertjobs",
    "name": "XpertJobs",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Employer overview, team and subscription",
    "url": "https://github.com/asaffilate01-ship-it/xpertjobs/pull/3",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "70833b2b7665aa827854820b999e221aa9df42b5"
  },
  {
    "id": "seamless-comms-suite",
    "source": "omniqora",
    "name": "Omniqora communications",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Owner/admin dashboard; Germany",
    "url": "https://github.com/asaffilate01-ship-it/seamless-comms-suite/pull/2",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "0d49bc85c4309c3b1160d0a10c15fe3e4aaa69c0"
  },
  {
    "id": "eventplanr2",
    "source": "eventplanr",
    "name": "EventPlanr UK",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Vendor dashboard",
    "url": "https://github.com/asaffilate01-ship-it/eventplanr2/pull/2",
    "note": "Existing secret-scan permission/configuration and tracked environment-file checks failed. Preserve runtime configuration while resolving the release gates.",
    "evidence": "29dc60c6120a0017324069b405c7bb43db0189f9"
  },
  {
    "id": "kinderstars-childcare-saas",
    "source": "kinderstars",
    "name": "KinderStars UK",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Childminder dashboard",
    "url": "https://github.com/asaffilate01-ship-it/kinderstars-childcare-saas/pull/7",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "b232afd7ba7e89af661160ad91404b156e24374c"
  },
  {
    "id": "zoryn-nexus",
    "source": "zoryn-pay",
    "name": "Zoryn Pay",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Business and merchant overview",
    "url": "https://github.com/asaffilate01-ship-it/zoryn-nexus/pull/2",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "88a6fe93b4594d9ec2bc6411dbbf382c7bd9f721"
  },
  {
    "id": "zoryn-rewards-hub",
    "source": "zoryn-rewards",
    "name": "Zoryn Rewards",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Merchant dashboard",
    "url": "https://github.com/asaffilate01-ship-it/zoryn-rewards-hub/pull/2",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "fe7e7c59c2293ee30400dd6789adfea96873e9ac"
  },
  {
    "id": "your-accountant-finder",
    "source": "taxnuvia",
    "name": "TaxNuvia accountant finder",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Dashboard link to existing service catalogue",
    "url": "https://github.com/asaffilate01-ship-it/your-accountant-finder/pull/18",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "d77a4b717b8805bdead510343fd3b370c9130d74"
  },
  {
    "id": "haccora-connect",
    "source": "haccora",
    "name": "Haccora UK",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Owner add-ons catalogue, bundles and ten contextual workflows",
    "url": "https://github.com/asaffilate01-ship-it/haccora-connect/pull/37",
    "note": "All eight source checks passed. Hosted launch still needs SUPABASE_URL, CRON_SECRET, production migrations and Edge deployment, then real role/persistence/payment acceptance through connected Lovable and Supabase.",
    "evidence": "62b0d09a59e0b2a644326c45d8f26122ab7bc5a4"
  },
  {
    "id": "leadlens-discovery",
    "source": "leadlens",
    "name": "LeadLens",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Business sales dashboard; chosen market",
    "url": "https://github.com/asaffilate01-ship-it/leadlens-discovery/pull/3",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "8d023f58ea251274ff1f6e9f2332f0ac61c14067"
  },
  {
    "id": "threeonethree",
    "source": "threeonethree",
    "name": "ThreeOneThree",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Business dashboard; chosen market",
    "url": "https://github.com/asaffilate01-ship-it/threeonethree/pull/1",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "a4c78445065b671c52bab8aba6b39cf3392654ef"
  },
  {
    "id": "all-road-aid",
    "source": "motoresq",
    "name": "MotoResQ",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Vendor documents, subscription and earnings; existing UK/UAE/DE region",
    "url": "https://github.com/asaffilate01-ship-it/all-road-aid/pull/3",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "f65457560f6ba70cf4e3d6d733db52a148592ded"
  },
  {
    "id": "zarvane",
    "source": "zarvane",
    "name": "Zarvane",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Approved trade orders; supplier self-offer suppressed",
    "url": "https://github.com/asaffilate01-ship-it/zarvane/pull/1",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "7ecc438908ff194b9316e750c573a8b5834f9c82"
  },
  {
    "id": "remix-of-property-nexus",
    "source": "gabley",
    "name": "Gabley",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Landlord/agent dashboard; UK",
    "url": "https://github.com/asaffilate01-ship-it/remix-of-property-nexus/pull/3",
    "note": "Existing npm lock mismatch, missing lock validator and check script, and disabled dependency graph block the repository gates.",
    "evidence": "43af6f03ad7c4caaa7127d8c2483193ce7d1b80d"
  },
  {
    "id": "eventplanrger",
    "source": "eventplanr",
    "name": "EventPlanr Germany",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Vendor dashboard; Germany",
    "url": "https://github.com/asaffilate01-ship-it/eventplanrger/pull/12",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "4641f0fb86cfdc00c1cf5e516f3467923c8f1299"
  },
  {
    "id": "kinderstars",
    "source": "kinderstars",
    "name": "KinderStars Germany",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Childminder dashboard; Germany",
    "url": "https://github.com/asaffilate01-ship-it/kinderstars/pull/16",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "558c45ed5fa0b06f44ab5c3799ca77fefdde4ee8"
  },
  {
    "id": "webtemplates",
    "source": "orvilo",
    "name": "Orvilo",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Business dashboard; hidden during publishing",
    "url": "https://github.com/asaffilate01-ship-it/webtemplates/pull/3",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "6972f1b8a816690cb1d9e1d5a9f0f0ff9b8edf25"
  },
  {
    "id": "remix-of-remix-of-surveycam-app",
    "source": "dokuvera",
    "name": "Dokuvera",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Admin/manager/surveyor document dashboard; existing UK/DE region",
    "url": "https://github.com/asaffilate01-ship-it/remix-of-remix-of-surveycam-app/pull/3",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "5d0f5fc0c3331989e5ac747ec9d75d7d9ba35972"
  },
  {
    "id": "ddelivery3pl",
    "source": "fleetsora",
    "name": "FleetSora",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Fleet administrator and branch administrator only; UAE scope.",
    "url": "https://github.com/asaffilate01-ship-it/ddelivery3pl/pull/1",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "40425774231399381e65e908b20023b82d2103c1"
  },
  {
    "id": "usataxlounge",
    "source": "taxcenda",
    "name": "TaxCenda",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Provider admin overview only; US scope.",
    "url": "https://github.com/asaffilate01-ship-it/usataxlounge/pull/1",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "50f83c9a311c0b8b66b119922ee496eb82884020"
  },
  {
    "id": "care-connect",
    "source": "amityos",
    "name": "AmityOS",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Active organisation owner/admin/manager finance view; no care recipient context.",
    "url": "https://github.com/asaffilate01-ship-it/care-connect/pull/1",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "a383758bc2dd58f1c87a2a5f9332b0549cc32b18"
  },
  {
    "id": "care-quest-learn",
    "source": "skillfinch",
    "name": "Skillfinch",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Owner/admin employer operations tab only, market chosen explicitly.",
    "url": "https://github.com/asaffilate01-ship-it/care-quest-learn/pull/11",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "cda36da236ec8e504513752b13bdd96ab2bd5c1e"
  },
  {
    "id": "practicecraft-hub",
    "source": "iq-practice-cloud",
    "name": "IQ Practice Cloud",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Staff with practice settings permission; accountant referral suppressed.",
    "url": "https://github.com/asaffilate01-ship-it/practicecraft-hub/pull/2",
    "note": "Typecheck, tests and build passed; existing production dependency advisories and a duplicate data_subject_requests policy block CI.",
    "evidence": "83c8b0442ee3cd3f8accc333dfef9f2b232d1494"
  },
  {
    "id": "schooldash",
    "source": "ilmvero",
    "name": "Ilmvero",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "School/campus/platform administrators only; Pakistan scope.",
    "url": "https://github.com/asaffilate01-ship-it/schooldash/pull/1",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "5bbe6d84ca717ac4bee4a986613d8730833a5d2d"
  },
  {
    "id": "autosouq",
    "source": "zivvo",
    "name": "Zivvo UK and enabled markets",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Dealer staff tab only; existing country configuration.",
    "url": "https://github.com/asaffilate01-ship-it/autosouq/pull/1",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "7e1d38808c34eb1b3d896d3d26b3042ee7c25dee"
  },
  {
    "id": "zivvo",
    "source": "zivvo",
    "name": "Zivvo Germany",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Authorised dealer staff management tab; Germany copy and market.",
    "url": "https://github.com/asaffilate01-ship-it/zivvo/pull/20",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "2d6febe34d39e97a1b23a2f2b4ef8f044cf426f6"
  },
  {
    "id": "onyn",
    "source": "onyngo",
    "name": "OnýnGo",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Verified vendor owner revenue tools; explicit business market, no customer segments shared.",
    "url": "https://github.com/asaffilate01-ship-it/onyn/pull/2",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "5bc963a1eec6be0dfa443bd18aee6068f041bc25"
  },
  {
    "id": "bidora1",
    "source": "bidlumo",
    "name": "Bidlumo",
    "kind": "GitHub",
    "state": "blocked",
    "audience": "Existing app audience",
    "placement": "Approved business sellers only on overview; no personal sellers or auction/checkout panels.",
    "url": "https://github.com/asaffilate01-ship-it/bidora1/pull/2",
    "note": "GitHub checks failed before a runner or steps were assigned; job logs were unavailable. Restore working CI and rerun before merge.",
    "evidence": "24a9e35a289e8640aea2dad26b36a64936ee4656"
  },
  {
    "id": "law-remix",
    "source": "veris-law",
    "name": "Veris Law",
    "kind": "GitHub",
    "state": "merged",
    "audience": "Existing app audience",
    "placement": "Practice administrator dashboard only; explicit business market. No case details inform recommendations.",
    "url": "https://github.com/asaffilate01-ship-it/law-remix/pull/2",
    "note": "Source merged. Hosted deployment and real account acceptance are not yet verified.",
    "evidence": "e22c9e5265078fa7b8ba2f1f60ea50f7ed13d47a"
  }
];
