import {one,stmt,db,product,id,now,fail,Row} from './server';
import {receptionTeam} from './customers';
import {callerPhone} from './phone';
import {boundedText} from './policy';
export async function receptionEnabled(w:string,p:string){const prod=await product(w,p);const settings=await one('SELECT * FROM reception_settings WHERE workspace_id=? AND product_id=?',w,p);if(!prod.enabled||!settings?.enabled)fail('Enable reception intake for this product first.',409);return settings;}
export async function receiveReception(w:string,p:string,b:Row,key:string,actor:string,fromApi=false){await receptionEnabled(w,p);if(!['message','order','booking'].includes(b.kind))fail('Choose message, order or booking.');if(!['phone','online','manual'].includes(b.channel))fail('Choose a valid reception channel.');const customer=boundedText(b.customer,120),summary=boundedText(b.summary,6000);if(!customer||!summary)fail('Add the customer name and request details.');const linked=boundedText(b.customerId,100)||null,parsed=callerPhone(b.callerNumber),number=parsed.number;if(parsed.state==='invalid')fail('Use an international caller number with country code, or leave it blank for withheld calls.');if(linked){const profile=await one('SELECT id,name,phone FROM reception_customers WHERE id=? AND workspace_id=? AND product_id=?',linked,w,p);if(!profile)fail('Customer not found.',404);if(b.customerConfirmed!==true)fail('Confirm the customer before linking their profile.');if(profile.name!==customer)fail('The customer name changed. Select the profile again.',409);if(number&&profile.phone!==number)fail('The selected customer does not match this number.',409);}const team=await receptionTeam(w),humanId=boundedText(b.humanHandlerId,100)||null,preferredId=boundedText(b.preferredHandlerId,100)||null,human=team.find(t=>t.id===humanId),preferred=team.find(t=>t.id===preferredId),handoff=boundedText(b.handoffNote,2000);if(humanId&&!human||preferredId&&!preferred)fail('Select a current team member for the handoff.');if(preferredId&&!linked)fail('Confirm the customer profile before requesting their previous contact.');const previous=await one('SELECT * FROM reception_items WHERE workspace_id=? AND product_id=? AND external_key=?',w,p,key);if(previous){if(previous.kind!==b.kind||previous.summary!==summary||previous.customer!==customer||previous.channel!==b.channel||previous.contact!==boundedText(b.contact,200)||previous.customer_id!==linked||previous.caller_number!==number||previous.human_handler_id!==humanId||previous.preferred_handler_id!==preferredId||previous.handoff_note!==handoff)fail('This event key was already used with different details.',409);return previous;}
 const rid=id(),op=id(),t=now();await db().batch([stmt("INSERT OR IGNORE INTO reception_items(id,workspace_id,product_id,kind,channel,customer,contact,summary,status,external_key,created_at,updated_at,customer_id,caller_number,human_handler_id,human_handler_name,handoff_note,preferred_handler_id,preferred_handler_name) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",rid,w,p,b.kind,b.channel,customer,boundedText(b.contact,200),summary,fromApi&&b.channel==='online'&&b.kind!=='message'?'queued':'new',key,t,t,linked,number,humanId,human?.name||null,handoff,preferredId,preferred?.name||null),stmt("INSERT INTO audit(id,workspace_id,actor,event,detail,resource_id,created_at) SELECT ?,?,?, 'reception.received',?,?,? WHERE changes()=1",op,w,actor,'Received '+b.kind+' request',rid,t)]);const saved=(await one('SELECT * FROM reception_items WHERE workspace_id=? AND product_id=? AND external_key=?',w,p,key))!;if(saved.kind!==b.kind||saved.summary!==summary||saved.customer!==customer||saved.channel!==b.channel||saved.contact!==boundedText(b.contact,200)||saved.customer_id!==linked||saved.caller_number!==number||saved.human_handler_id!==humanId||saved.preferred_handler_id!==preferredId||saved.handoff_note!==handoff)fail('This event key was already used with different details.',409);return saved;
}
export async function advanceReception(w:string,p:string,b:Row,actor:string,fromApi=false){const r=await one('SELECT * FROM reception_items WHERE id=? AND workspace_id=? AND product_id=?',b.id,w,p);if(!r)fail('Reception item not found.',404);const status=String(b.status),ref=boundedText(b.sourceRef,160),receipt=b.receipt||{};
 const permitted:Record<string,string[]>={new:['queued','handled','cancelled'],queued:['accepted','confirmed','failed','handled'],accepted:['delivered','failed'],failed:['queued','cancelled']};
 if(!fromApi&&['accepted','confirmed','delivered','failed'].includes(status))fail('This status requires an acknowledgment from the connected order or booking system.',403);
 if(status==='handled'&&r.kind!=='message')fail('Orders and bookings need confirmation from their source app.',409);
 if(status==='queued'&&r.kind==='message')fail('Resolve a message or record its follow-up before marking it handled.');
 if(status==='accepted'&&r.kind!=='order'||status==='delivered'&&r.kind!=='order'||status==='confirmed'&&r.kind!=='booking')fail('This acknowledgment does not match the request type.');
 const cleanReceipt:Row={};if(['accepted','confirmed','delivered'].includes(status)){if(!ref)fail('Include the source app order or booking reference.');if(r.source_ref&&ref!==r.source_ref)fail('The acknowledgment must use the original source reference.',409);if(status==='accepted'){if(receipt.priceValidated!==true||receipt.availabilityValidated!==true||receipt.accepted!==true||!['paid','pay_later_authorized'].includes(receipt.paymentState))fail('An accepted order requires verified prices, availability and a permitted payment state.');Object.assign(cleanReceipt,{priceValidated:true,availabilityValidated:true,accepted:true,paymentState:receipt.paymentState});}if(status==='confirmed'){if(receipt.slotReserved!==true)fail('The booking system must confirm that the slot was reserved.');cleanReceipt.slotReserved=true;}if(status==='delivered'){if(receipt.kdsAcknowledged!==true)fail('Wait for the kitchen display acknowledgment.');cleanReceipt.kdsAcknowledged=true;}}
 if(status==='failed')cleanReceipt.reason=boundedText(receipt.reason,500)||'The source system reported an exception.';
 if(fromApi&&(r.status===status||(r.status==='delivered'&&status==='accepted'))){const prior=JSON.parse(r.receipt);if(ref&&r.source_ref!==ref||Object.keys(cleanReceipt).some(k=>prior[k]!==cleanReceipt[k]))fail('This acknowledgment conflicts with the saved receipt.',409);return r;}
 if(!permitted[r.status]?.includes(status))fail('This status transition is not available. Refresh the request.',409);if(!fromApi&&b.revision!==r.revision)fail('This request changed. Refresh before saving.',409);
 const op=id(),t=now();const result=await db().batch([stmt("INSERT INTO audit(id,workspace_id,actor,event,detail,resource_id,created_at) SELECT ?,workspace_id,?,?,?,id,? FROM reception_items WHERE id=? AND workspace_id=? AND product_id=? AND revision=?",op,actor,'reception.'+status,'Reception request: '+status,t,r.id,w,p,r.revision),stmt('UPDATE reception_items SET status=?,source_ref=COALESCE(?,source_ref),receipt=?,revision=revision+1,updated_at=? WHERE id=? AND workspace_id=? AND product_id=? AND EXISTS(SELECT 1 FROM audit WHERE id=?)',status,ref||null,JSON.stringify({...JSON.parse(r.receipt),...cleanReceipt}),t,r.id,w,p,op)]);if(!result[0].meta.changes)fail('This request changed. Retry after refreshing.',409);return (await one('SELECT * FROM reception_items WHERE id=? AND workspace_id=? AND product_id=?',r.id,w,p))!;
}
