import {approvalStatements} from './approval';
import {env} from 'cloudflare:workers';
import {cookies} from 'next/headers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {productCatalog,getTemplate} from './catalog';
import {boundedText,actionStatus,currentMonth} from './policy';
export type Row=Record<string,any>;
export function db(){if(!env.DB)throw new Error('Workspace storage is unavailable. Please try again.');return env.DB;}
export async function rows(sql:string,...args:any[]):Promise<Row[]>{return (await db().prepare(sql).bind(...args).all()).results as Row[];}
export async function one(sql:string,...args:any[]):Promise<Row|null>{return await db().prepare(sql).bind(...args).first() as Row|null;}
export function stmt(sql:string,...args:any[]){return db().prepare(sql).bind(...args);}
export const now=()=>new Date().toISOString();
export const id=()=>crypto.randomUUID();
export function fail(message:string,status=400):never{throw Object.assign(new Error(message),{status});}
export async function workspace(){const user=await getChatGPTUser();if(!user)fail('Please sign in to your workspace.',401);let accessible=await rows("SELECT DISTINCT w.*,CASE WHEN w.owner_id=? THEN 'owner' ELSE m.role END AS role FROM workspaces w LEFT JOIN members m ON m.workspace_id=w.id AND m.user_id=? WHERE w.owner_id=? OR m.user_id=? ORDER BY w.created_at",user.userId,user.userId,user.userId,user.userId);if(!accessible.length){const wid='ws_'+(await tokenHash(user.userId)).slice(0,32);await db().batch([stmt('INSERT OR IGNORE INTO workspaces(id,owner_id,name,created_at) VALUES(?,?,?,?)',wid,user.userId,'iTechLounge',now()),stmt('INSERT OR IGNORE INTO members(id,workspace_id,user_id,email,role,created_at) VALUES(?,?,?,?,?,?)',id(),wid,user.userId,user.email,'owner',now())]);accessible=[{...(await one('SELECT * FROM workspaces WHERE id=?',wid)),role:'owner'}];}const selected=(await cookies()).get('lai_workspace')?.value;const w=accessible.find(x=>x.id===selected)||accessible[0];return {w,user,accessible};}
export function requireRole(w:Row,roles:string[]){if(!roles.includes(w.role))fail('Your workspace role does not allow this action.',403);}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)fail('This request origin is not allowed.',403);if(req.headers.get('sec-fetch-site')==='cross-site')fail('Cross-site request rejected.',403);}
export async function readBody(req:Request,max=100000){const length=Number(req.headers.get('content-length')||0);if(length>max)fail('Request is too large.',413);const text=await req.text();if(text.length>max)fail('Request is too large.',413);try{const value=JSON.parse(text);if(!value||typeof value!=='object'||Array.isArray(value))fail('Invalid request data.');return value;}catch{fail('Invalid request data.');}}
export function auditStmt(w:string,actor:string,event:string,detail:string,resource?:string){return stmt('INSERT INTO audit(id,workspace_id,actor,event,detail,resource_id,created_at) VALUES(?,?,?,?,?,?,?)',id(),w,actor,event,detail,resource||null,now());}
export async function auditLog(w:string,actor:string,event:string,detail:string,resource?:string){await auditStmt(w,actor,event,detail,resource).run();}
export async function product(w:string,p:string){const r=await one('SELECT * FROM products WHERE workspace_id=? AND id=?',w,p);if(!r)fail('Product not found.',404);return r;}
export async function importPortfolio(w:string,actor:string){const t=now();const statements=productCatalog.map(p=>stmt('INSERT OR IGNORE INTO products(id,workspace_id,slug,name,sector,description,color,scope,template_id,mode,enabled,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',id(),w,p.slug,p.name,p.sector,p.description,p.color,p.scope,p.template,'approve',p.scope==='confirmed'?1:0,t));await db().batch([...statements,auditStmt(w,actor,'portfolio.imported','Imported portfolio product definitions')]);}
export async function bootstrap(){const {w,user,accessible}=await workspace();const [products,runs,actions,tasks,documents,audit,integrations,usage]=await Promise.all([rows('SELECT * FROM products WHERE workspace_id=? ORDER BY created_at,name',w.id),rows('SELECT r.*,p.name AS product_name,p.color FROM runs r JOIN products p ON p.id=r.product_id WHERE r.workspace_id=? ORDER BY r.created_at DESC LIMIT 200',w.id),rows('SELECT a.*,r.kind,p.name AS product_name,p.color FROM actions a JOIN runs r ON r.id=a.run_id JOIN products p ON p.id=a.product_id WHERE a.workspace_id=? ORDER BY a.created_at DESC LIMIT 200',w.id),rows('SELECT t.*,r.kind,p.name AS product_name FROM tasks t JOIN runs r ON r.id=t.run_id JOIN products p ON p.id=t.product_id WHERE t.workspace_id=? ORDER BY t.created_at DESC LIMIT 200',w.id),rows('SELECT id,product_id,name,mime,size,created_at FROM documents WHERE workspace_id=? ORDER BY created_at DESC LIMIT 200',w.id),rows('SELECT * FROM audit WHERE workspace_id=? ORDER BY created_at DESC LIMIT 100',w.id),rows('SELECT id,product_id,name,last_seen,created_at FROM integrations WHERE workspace_id=?',w.id),one('SELECT * FROM usage WHERE workspace_id=? AND month=?',w.id,currentMonth())]);const sales=await rows('SELECT * FROM sales WHERE workspace_id=? ORDER BY date DESC LIMIT 2000',w.id);const members=await rows('SELECT id,email,role,user_id FROM members WHERE workspace_id=?',w.id);const journeys=await rows('SELECT j.*,p.name AS product_name,p.color FROM journeys j JOIN products p ON p.id=j.product_id WHERE j.workspace_id=? ORDER BY j.created_at DESC LIMIT 100',w.id);return {journeys,workspace:w,workspaces:accessible.map(x=>({id:x.id,name:x.name,kind:x.kind,plan:x.plan,role:x.role})),members,sales,user:{name:user.displayName,email:user.email},products,runs,actions,tasks,documents,audit,integrations,usage:usage||{reserved:0,input_tokens:0,output_tokens:0},provider:{connected:!!env.OPENAI_API_KEY,model:env.OPENAI_MODEL||'gpt-4.1-mini'},storage:{documents:!!env.BUCKET}};}
export async function createRun(w:Row,actor:string,b:Row){if(w.paused)fail('Automations are paused for this workspace.',409);const p=await product(w.id,b.productId);if(!p.enabled)fail('Enable this product before creating a task.',409);const template=getTemplate(b.templateId||p.template_id);if(!template)fail('Agent template not found.');const kind=b.kind==='sample'?'sample':'live';if(kind==='live'&&!env.OPENAI_API_KEY)fail('Connect the AI provider before starting a live run.',409);const title=boundedText(b.title,150)||template.name+' — '+p.name;const input=boundedText(b.input,20000);if(!input)fail('Add the information the agent should review.');const docs=Array.isArray(b.documentIds)?[...new Set(b.documentIds)].slice(0,3):[];for(const d of docs){if(!await one('SELECT id FROM documents WHERE id=? AND workspace_id=? AND product_id=?',d,w.id,p.id))fail('An evidence file is not available to this product.',403);}const key=boundedText(b.idempotencyKey,160)||id();const existing=await one('SELECT * FROM runs WHERE workspace_id=? AND idempotency_key=?',w.id,key);if(existing)return existing;const rid=id(),t=now();await db().batch([stmt('INSERT OR IGNORE INTO runs(id,workspace_id,product_id,template_id,title,input,kind,mode,status,document_ids,idempotency_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',rid,w.id,p.id,template.id,title,input,kind,p.mode,'queued',JSON.stringify(docs),key,t,t),auditStmt(w.id,actor,'run.queued',title,rid)]);return (await one('SELECT * FROM runs WHERE workspace_id=? AND idempotency_key=?',w.id,key))!;}
export async function decide(w:string,actor:string,aid:string,decision:string,note:string){
 if(!['approved','rejected'].includes(decision))fail('Invalid decision.');
 const a=await one('SELECT * FROM actions WHERE id=? AND workspace_id=?',aid,w);if(!a)fail('Action not found.',404);
 const result=await db().batch(approvalStatements(a,decision,boundedText(note,2000),actor,now(),id(),id()).map(s=>stmt(s.sql,...s.args)));
 if(!result[0].meta.changes)fail('The action was already reviewed, or the workspace or product is paused.',409);
}
export async function deliverInternalAction(a:Row){await stmt('INSERT OR IGNORE INTO tasks(id,workspace_id,product_id,run_id,action_id,title,body,assignee,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id(),a.workspace_id,a.product_id,a.run_id,a.id,a.title,a.body,a.assignee,a.type==='internal_task'?'open':'draft',now(),now()).run();}
export async function tokenHash(token:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function randomToken(){return 'lai_'+[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function connector(req:Request){const token=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(!token.startsWith('lai_'))fail('Valid integration credentials are required.',401);const i=await one('SELECT * FROM integrations WHERE token_hash=?',await tokenHash(token));if(!i)fail('Integration credentials are invalid or revoked.',401);const w=await one('SELECT * FROM workspaces WHERE id=?',i.workspace_id);if(!w||w.paused)fail('This workspace is paused.',409);const p=await product(w.id,i.product_id);if(!p.enabled)fail('This product is disabled.',409);await stmt('UPDATE integrations SET last_seen=? WHERE id=?',now(),i.id).run();return {integration:i,w};}
export function apiError(error:unknown){const e=error as Error&{status?:number};console.error('[Omniqora AI]',e.status||500,e.message);return Response.json({error:e.status?e.message:'The request could not be completed. Please try again.'},{status:e.status||500});}
