export const speechLanguages=[{value:'en-GB',label:'English (UK)'},{value:'en-US',label:'English (US)'},{value:'de-DE',label:'German'},{value:'ur-PK',label:'Urdu'},{value:'hi-IN',label:'Hindi'},{value:'ar-SA',label:'Arabic'},{value:'fr-FR',label:'French'},{value:'es-ES',label:'Spanish'}];
export const MAX_AUDIO_BYTES=2*1024*1024;
export const MAX_TRANSCRIPT_CHARS=20000;
export function appendTranscript(value:string,text:string,max=MAX_TRANSCRIPT_CHARS){const result=[value.trimEnd(),text.trim()].filter(Boolean).join(value.trim()?'\n':'');if(result.length>max)throw Error('The combined text is too long. Shorten the transcript before inserting it.');return result;}
export function recognitionText(results:ArrayLike<any>){const final:string[]=[],interim:string[]=[];for(let i=0;i<results.length;i++){const text=String(results[i]?.[0]?.transcript||'').trim();if(text)(results[i].isFinal?final:interim).push(text)}return {final:final.join(' '),interim:interim.join(' ')};}
export function speechError(code:string){const messages:Record<string,string>={'not-allowed':'Microphone access was denied. Allow microphone access in your browser settings, then try again.','service-not-allowed':'This browser does not allow its speech service here. Use your device keyboard microphone or the audio upload option.','audio-capture':'No usable microphone was found. Check that it is connected and not in use elsewhere.','network':'The browser speech service could not connect. Check your connection and try again.','no-speech':'No speech was detected. Try again and speak clearly near the microphone.','language-not-supported':'The selected language is unavailable in this browser speech service. Choose another language or use audio transcription.','aborted':'Listening stopped.'};return messages[code]||'Speech recognition stopped unexpectedly. Your confirmed transcript is still available for review.';}
export type RecognitionLike={lang:string;continuous:boolean;interimResults:boolean;maxAlternatives:number;onstart:(()=>void)|null;onend:(()=>void)|null;onerror:((e:any)=>void)|null;onresult:((e:any)=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
export function browserDictation(Recognition:new()=>RecognitionLike,language:string,callbacks:{text:(final:string,interim:string)=>void;state:(state:'starting'|'listening'|'stopping'|'idle')=>void;error:(message:string)=>void}){
 const recognition=new Recognition();let active=true,ended=false,stopping=false,stopTimer:ReturnType<typeof setTimeout>|undefined;recognition.lang=language;recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=1;
 const end=()=>{if(!active||ended)return;ended=true;clearTimeout(stopTimer);callbacks.state('idle')};
 recognition.onstart=()=>{if(active&&!ended){if(stopping){end();try{recognition.abort()}catch{}}else callbacks.state('listening')}};recognition.onresult=e=>{if(active&&!ended){const text=recognitionText(e.results);callbacks.text(text.final,text.interim)}};
 recognition.onerror=e=>{if(active&&!ended){if(e.error!=='aborted')callbacks.error(speechError(e.error));end();try{recognition.abort()}catch{}}};recognition.onend=end;
 return {start(){if(!active||ended)return;callbacks.state('starting');try{recognition.start()}catch{callbacks.error('The speech service could not start. Stop any other microphone session and try again.');end()}},stop(){if(!active||ended||stopping)return;stopping=true;callbacks.state('stopping');try{recognition.stop();stopTimer=setTimeout(()=>{if(active&&!ended){try{recognition.abort()}catch{}end()}},2000)}catch{end();try{recognition.abort()}catch{}}},abort(){active=false;ended=true;clearTimeout(stopTimer);recognition.onstart=null;recognition.onend=null;recognition.onerror=null;recognition.onresult=null;try{recognition.abort()}catch{}}};
}
export function audioFileType(name:string,type:string){const ext=name.toLowerCase().split('.').pop()||'';const formats:Record<string,string[]>={mp3:['audio/mpeg','audio/mp3'],mpeg:['audio/mpeg'],mpga:['audio/mpeg'],wav:['audio/wav','audio/x-wav','audio/wave'],webm:['audio/webm','video/webm'],m4a:['audio/mp4','audio/m4a','audio/x-m4a'],mp4:['audio/mp4','video/mp4']};return !!formats[ext]&&(!type||formats[ext].includes(type.split(';')[0].trim().toLowerCase()));}
