import {workspace,sameOrigin,readBody,requireRole,product,one,rows,stmt,db,auditStmt,now,id,fail,apiError,createRun} from '@/lib/server';
import {boundedText} from '@/lib/policy';
import {journeySteps} from '@/lib/journey-steps';
export const dynamic='force-dynamic';
export async function POST(req:Request){try{sameOrigin(req);const {w,user}=await workspace();requireRole(w,['owner','admin','operator']);const b=await readBody(req);if(b.action==='create'){const p=await product(w.id,b.productId);const title=boundedText(b.title,150),goal=boundedText(b.goal,12000);if(!title||!goal)fail('Add a journey title and the outcome you want to achieve.');const jid=id();await db().batch([stmt('INSERT INTO journeys(id,workspace_id,product_id,title,goal,kind,current_step,status,history,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?,?,?)',jid,w.id,p.id,title,goal,b.kind==='sample'?'sample':'live','active','[]',now(),now()),auditStmt(w.id,user.email,'journey.created',title,jid)]);return Response.json({id:jid});}
const j=await one('SELECT * FROM journeys WHERE id=? AND workspace_id=?',b.id,w.id);if(!j)fail('Journey not found.',404);if(j.status!=='active')fail('This journey is already completed.',409);
if(b.action==='run_step'){if(j.step_run_id){const run=await one('SELECT * FROM runs WHERE id=? AND workspace_id=?',j.step_run_id,w.id);if(run)return Response.json({run});}
const stage=journeySteps[j.current_step];if(!stage)fail('Journey stage not found.');const history=JSON.parse(j.history);const previous=history.map((x:any)=>x.stage+': '+x.outcome).join('\n');const input='Original goal:\n'+j.goal+'\n\nCurrent stage: '+stage.title+'\n'+stage.prompt+'\n\nRecorded outcomes from prior stages:\n'+(previous||'No stages completed yet.')+'\n\nAdditional information for this stage:\n'+boundedText(b.context,12000);const run=await createRun(w,user.email,{productId:j.product_id,templateId:stage.template,title:stage.title+' — '+j.title,input,kind:j.kind,documentIds:b.documentIds||[],idempotencyKey:'journey:'+j.id+':'+j.current_step});await stmt('UPDATE journeys SET step_run_id=?,updated_at=? WHERE id=? AND workspace_id=? AND current_step=?',run.id,now(),j.id,w.id,j.current_step).run();return Response.json({run});}
if(b.action==='complete_step'){if(!j.step_run_id)fail('Run and review the current step before continuing.',409);const run=await one('SELECT * FROM runs WHERE id=? AND workspace_id=?',j.step_run_id,w.id);if(run?.status!=='completed')fail('Complete the run and review all pending approvals first.',409);const pending=await one("SELECT COUNT(*) AS n FROM tasks WHERE run_id=? AND workspace_id=? AND status!='completed'",j.step_run_id,w.id);if(pending?.n)fail('Complete the tasks and review drafts from this step before continuing.',409);const outcome=boundedText(b.outcome,4000);if(outcome.length<10)fail('Record the outcome and any remaining limitations.');const history=JSON.parse(j.history);history.push({stage:journeySteps[j.current_step].title,runId:j.step_run_id,outcome,completedAt:now(),actor:user.email});const next=j.current_step+1;const changed=await stmt('UPDATE journeys SET current_step=?,step_run_id=NULL,status=?,history=?,updated_at=? WHERE id=? AND workspace_id=? AND current_step=? AND step_run_id=?',next,next>=journeySteps.length?'completed':'active',JSON.stringify(history),now(),j.id,w.id,j.current_step,j.step_run_id).run();if(!changed.meta.changes)fail('This journey changed. Refresh to continue.',409);await auditStmt(w.id,user.email,'journey.stage_completed',journeySteps[j.current_step].title,j.id).run();return Response.json({ok:true});}fail('Unknown journey action.');}catch(e){return apiError(e);}}
