import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { requireModuleEntitlement, requireWritableTenantRole } from "@/modules/platform/module-access";

const scope=z.object({tenantId:z.string().uuid(),tenantProductId:z.string().uuid()});
async function marketScope(context:any,data:z.infer<typeof scope>,write=false){const access=await requireModuleEntitlement(context,{...data,moduleKey:"marketplace.core"});if(write)requireWritableTenantRole(access.role);return access;}

export const listMarketplaceVendors=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{await marketScope(context,data);const db=context.supabase as any;const{data:rows,error}=await db.from("marketplace_vendors").select("*").eq("tenant_id",data.tenantId).order("name");if(error)throw new Error(error.message);return rows??[];});

const vendorSchema=scope.extend({id:z.string().uuid().optional(),name:z.string().trim().min(1).max(240),status:z.enum(["draft","pending_review","active","suspended","closed"]).default("draft"),countryCode:z.string().length(2),currency:z.string().regex(/^[A-Z]{3}$/),commissionProfile:z.string().max(120).optional().nullable(),payoutProfile:z.string().max(120).optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})});
export const saveMarketplaceVendor=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof vendorSchema>)=>vendorSchema.parse(input)).handler(async({context,data})=>{await marketScope(context,data,true);const db=context.supabase as any;const values={tenant_id:data.tenantId,name:data.name,status:data.status,country_code:data.countryCode,currency:data.currency,commission_profile:data.commissionProfile??null,payout_profile:data.payoutProfile??null,metadata:data.metadata};const q=data.id?db.from("marketplace_vendors").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("marketplace_vendors").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Vendor could not be saved");return row;});

export const listMarketplaceListings=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{await marketScope(context,data);const db=context.supabase as any;const{data:rows,error}=await db.from("marketplace_listings").select("*").eq("tenant_id",data.tenantId).order("updated_at",{ascending:false}).limit(1000);if(error)throw new Error(error.message);return rows??[];});

const listingSchema=scope.extend({id:z.string().uuid().optional(),vendorId:z.string().uuid(),type:z.enum(["product","service","rental","consultation","auction"]),title:z.string().trim().min(1).max(240),description:z.string().max(10000).optional().nullable(),status:z.enum(["draft","pending_review","active","paused","archived"]).default("draft"),categoryKeys:z.array(z.string().max(120)).max(50).default([]),currency:z.string().regex(/^[A-Z]{3}$/),priceMinor:z.number().int().nonnegative().optional().nullable(),attributes:z.record(z.string(),z.unknown()).default({}),inventoryTracked:z.boolean().default(false),sku:z.string().max(160).optional().nullable(),quantityOnHand:z.number().nonnegative().optional().nullable()});
export const saveMarketplaceListing=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof listingSchema>)=>listingSchema.parse(input)).handler(async({context,data})=>{await marketScope(context,data,true);const db=context.supabase as any;const values={tenant_id:data.tenantId,vendor_id:data.vendorId,listing_type:data.type,title:data.title,description:data.description??null,status:data.status,category_keys:data.categoryKeys,currency:data.currency,price_minor:data.priceMinor??null,attributes:data.attributes,inventory_tracked:data.inventoryTracked};const q=data.id?db.from("marketplace_listings").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("marketplace_listings").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Listing could not be saved");if(data.inventoryTracked){const{error:invError}=await db.from("marketplace_inventory").upsert({listing_id:row.id,tenant_id:data.tenantId,sku:data.sku??null,quantity_on_hand:data.quantityOnHand??0},{onConflict:"listing_id"});if(invError)throw new Error(invError.message);}return row;});

const orderSchema=scope.extend({buyerRef:z.string().min(1).max(200),vendorId:z.string().uuid(),items:z.array(z.object({listingId:z.string().uuid(),quantity:z.number().positive(),metadata:z.record(z.string(),z.unknown()).default({})})).min(1).max(100),metadata:z.record(z.string(),z.unknown()).default({})});
export const createMarketplaceOrder=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof orderSchema>)=>orderSchema.parse(input)).handler(async({context,data})=>{await marketScope(context,data,true);const db=context.supabase as any;const{data:id,error}=await db.rpc("create_marketplace_order",{_tenant:data.tenantId,_tenant_product:data.tenantProductId,_buyer_ref:data.buyerRef,_vendor:data.vendorId,_items:data.items,_metadata:data.metadata});if(error||!id)throw new Error(error?.message??"Order could not be created");return{id};});

export const listMarketplaceOrders=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{await marketScope(context,data);const db=context.supabase as any;const{data:orders,error}=await db.from("marketplace_orders").select("*").eq("tenant_id",data.tenantId).order("created_at",{ascending:false}).limit(500);if(error)throw new Error(error.message);const ids=(orders??[]).map((o:any)=>o.id);let items:any[]=[];if(ids.length){const res=await db.from("marketplace_order_items").select("*").eq("tenant_id",data.tenantId).in("order_id",ids);if(res.error)throw new Error(res.error.message);items=res.data??[];}return(orders??[]).map((o:any)=>({...o,items:items.filter((i:any)=>i.order_id===o.id)}));});

const transitionSchema=scope.extend({orderId:z.string().uuid(),status:z.enum(["paid","accepted","fulfilling","completed","cancelled","refunded"]),metadata:z.record(z.string(),z.unknown()).default({})});
export const transitionMarketplaceOrder=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof transitionSchema>)=>transitionSchema.parse(input)).handler(async({context,data})=>{await marketScope(context,data,true);const db=context.supabase as any;const{error}=await db.rpc("transition_marketplace_order",{_order:data.orderId,_status:data.status,_metadata:data.metadata});if(error)throw new Error(error.message);return{ok:true};});