import { z } from "zod";
import { ModuleEventProcessorRegistry, type ClaimedModuleEvent } from "./event-worker.server";
import { parseStandardEventPayload } from "./standard-events";

async function admin(){const{ supabaseAdmin }=await import("@/integrations/supabase/client.server");return supabaseAdmin as any;}
function sourceProduct(job:ClaimedModuleEvent){return String(job.event.product_key??"unknown");}
function occurred(job:ClaimedModuleEvent){return String(job.event.occurred_at??new Date().toISOString());}

async function findPerson(db:any,job:ClaimedModuleEvent,ref:string){const{data}=await db.from("crm_people").select("id,company_id").eq("tenant_id",job.tenantId).eq("source_product_key",sourceProduct(job)).eq("external_ref",ref).maybeSingle();return data??null;}
async function findCompany(db:any,job:ClaimedModuleEvent,ref:string){const{data}=await db.from("crm_companies").select("id").eq("tenant_id",job.tenantId).eq("source_product_key",sourceProduct(job)).eq("external_ref",ref).maybeSingle();return data??null;}

async function crmProcessor(job:ClaimedModuleEvent){
 const db=await admin();const type=String(job.event.event_type);const payload=parseStandardEventPayload(type,job.event.payload??{});
 if(type==="customer.created"||type==="customer.updated"){const p=payload as z.infer<typeof import("./standard-events").customerPayload>;let companyId:string|null=null;if(p.companyRef){companyId=(await findCompany(db,job,p.companyRef))?.id??null;}const existing=await findPerson(db,job,p.customerRef);const values={tenant_id:job.tenantId,company_id:companyId,display_name:p.displayName,first_name:p.firstName??null,last_name:p.lastName??null,email:p.email??null,phone_e164:p.phoneE164??null,locale:p.locale??null,lifecycle_stage:"customer",marketing_consent:p.marketingConsent,source_product_key:sourceProduct(job),external_ref:p.customerRef,metadata:p.metadata};const result=existing?await db.from("crm_people").update(values).eq("id",existing.id):await db.from("crm_people").insert(values);if(result.error)throw new Error(result.error.message);return;}
 if(type==="company.created"||type==="company.updated"){const p:any=payload;const existing=await findCompany(db,job,p.companyRef);const values={tenant_id:job.tenantId,name:p.name,legal_name:p.legalName??null,website:p.website??null,industry:p.industry??null,status:"customer",source_product_key:sourceProduct(job),external_ref:p.companyRef,metadata:p.metadata};const result=existing?await db.from("crm_companies").update(values).eq("id",existing.id):await db.from("crm_companies").insert(values);if(result.error)throw new Error(result.error.message);return;}
 if(type==="lead.created"){const p:any=payload;const person=p.customerRef?await findPerson(db,job,p.customerRef):null;const company=p.companyRef?await findCompany(db,job,p.companyRef):null;const{data:existing}=await db.from("crm_leads").select("id").eq("tenant_id",job.tenantId).eq("source_product_key",sourceProduct(job)).eq("external_ref",p.leadRef).maybeSingle();const values={tenant_id:job.tenantId,person_id:person?.id??null,company_id:company?.id??null,title:p.title,source:p.source??sourceProduct(job),status:"new",score:p.score??null,source_product_key:sourceProduct(job),external_ref:p.leadRef,metadata:p.metadata};const result=existing?await db.from("crm_leads").update(values).eq("id",existing.id):await db.from("crm_leads").insert(values);if(result.error)throw new Error(result.error.message);return;}
 if(type==="order.completed"||type==="booking.completed"){const p:any=payload;if(!p.customerRef)return;const person=await findPerson(db,job,p.customerRef);if(!person)return;const{data:existing}=await db.from("crm_activities").select("id").eq("tenant_id",job.tenantId).eq("source_product_key",sourceProduct(job)).eq("external_ref",job.event.id).maybeSingle();if(existing)return;const{error}=await db.from("crm_activities").insert({tenant_id:job.tenantId,activity_type:"system_event",summary:type==="order.completed"?"Order completed":"Booking completed",person_id:person.id,company_id:person.company_id??null,source_product_key:sourceProduct(job),external_ref:job.event.id,metadata:{eventType:type,...p},occurred_at:occurred(job)});if(error)throw new Error(error.message);}
}

async function analyticsProcessor(job:ClaimedModuleEvent){
 const db=await admin();const type=String(job.event.event_type);let metric:string|null=null;let value:number|null=null;let currency:string|null=null;const p:any=parseStandardEventPayload(type,job.event.payload??{});
 if(type==="customer.created"){metric="customers.new";value=1;}else if(type==="order.completed"){metric="revenue.gross";value=p.amounts.grossMinor;currency=p.amounts.currency;}else if(type==="marketplace.order.completed"){metric="revenue.gross";value=Number(p.totalMinor??p.amounts?.grossMinor??0);currency=p.currency??p.amounts?.currency??null;}else if(type==="dispatch.job.completed"){metric="jobs.completed";value=1;}
 if(!metric||value===null)return;const d=new Date(occurred(job));const start=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));const end=new Date(start.getTime()+86400000);const{error}=await db.from("analytics_metric_points").upsert({tenant_id:job.tenantId,product_key:sourceProduct(job),metric_key:metric,period_start:start.toISOString(),period_end:end.toISOString(),value,currency,dimensions:{sourceProduct:sourceProduct(job)},calculated_at:new Date().toISOString(),source_event_id:job.event.id},{onConflict:"tenant_id,metric_key,source_event_id"});if(error)throw new Error(error.message);
}

async function financialProcessor(job:ClaimedModuleEvent){
 const db=await admin();const type=String(job.event.event_type);const p:any=parseStandardEventPayload(type,job.event.payload??{});let kind:string|null=null;let amount:number|null=null;let currency:string|null=null;let suffix="";
 if(type==="order.completed"){kind="revenue";amount=p.amounts.grossMinor;currency=p.amounts.currency;suffix="gross";}else if(type==="marketplace.order.completed"){kind="revenue";amount=Number(p.totalMinor??p.amounts?.grossMinor??0);currency=p.currency??p.amounts?.currency??null;suffix="gross";}else if(type==="refund.completed"||type==="marketplace.refund.completed"){kind="refund";amount=Number(p.amountMinor??p.totalMinor??0);currency=p.currency??null;suffix="refund";}
 if(!kind||amount===null||!currency)return;const day=occurred(job).slice(0,10);const{error}=await db.from("financial_actuals").upsert({tenant_id:job.tenantId,product_key:sourceProduct(job),period_start:day,period_end:day,category:kind,kind,amount_minor:amount,currency,source_ref:"event:"+job.event.id+":"+suffix,source_event_id:job.event.id,observed_at:occurred(job)},{onConflict:"tenant_id,source_ref"});if(error)throw new Error(error.message);
}

export function createDefaultModuleProcessorRegistry(){return new ModuleEventProcessorRegistry().register("crm.core",crmProcessor).register("analytics.core",analyticsProcessor).register("financials.core",financialProcessor);}