import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const blueprint=z.object({regions:z.array(z.string().min(2).max(16)).min(1),locales:z.array(z.string().min(2).max(20)).min(1),modules:z.array(z.string().min(1).max(160)).max(100).default([]),roles:z.array(z.string().min(1).max(120)).max(100).default([]),navigation:z.array(z.unknown()).default([]),domainObjects:z.array(z.string().max(160)).max(200).default([]),workflows:z.array(z.string().max(160)).max(200).default([]),mobileCapabilities:z.array(z.string().max(160)).max(100).default([]),uiSchema:z.record(z.string(),z.unknown()).default({}),metadata:z.record(z.string(),z.unknown()).default({})});
const create=z.object({productKey:z.string().regex(/^[a-z0-9][a-z0-9-]{1,78}[a-z0-9]$/),name:z.string().min(2).max(160),kind:z.enum(["shared_engine","vertical_landlord","product_variant","standalone"]).default("vertical_landlord"),industry:z.string().min(2).max(160),blueprint});

export const listSaasFactoryProducts=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const db=context.supabase as any;const{data:operator}=await db.from("platform_operators").select("role,status").eq("user_id",context.userId).maybeSingle();const isAdmin=operator?.status==="active"&&["platform_owner","platform_admin"].includes(operator.role);const table=isAdmin?"platform_product_blueprints":"active_platform_product_blueprints";const{data:rows,error}=await db.from(table).select("*").order("product_key").order("version",{ascending:false});if(error)throw new Error(error.message);return rows??[];});

export const createSaasProductDraft=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof create>)=>create.parse(input)).handler(async({context,data})=>{const db=context.supabase as any;const{data:result,error}=await db.rpc("create_platform_product_draft",{_product_key:data.productKey,_name:data.name,_kind:data.kind,_industry:data.industry,_blueprint:data.blueprint});if(error||!result)throw new Error(error?.message??"Product draft could not be created");return result;});

export const publishSaasProduct=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:{productKey:string;version:number})=>z.object({productKey:z.string().min(1).max(80),version:z.number().int().positive()}).parse(input)).handler(async({context,data})=>{const db=context.supabase as any;const{error}=await db.rpc("publish_platform_product_blueprint",{_product_key:data.productKey,_version:data.version});if(error)throw new Error(error.message);return{ok:true};});