import {workspace,sameOrigin,readBody,requireRole,product,one,rows,stmt,db,auditStmt,now,id,fail,apiError} from '@/lib/server';
import {boundedText} from '@/lib/policy';
import {validDay,validZone,localDay,offsetDay,dayOverview,startingSteps} from '@/lib/day';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const {w,user}=await workspace();const url=new URL(req.url);const timezone=url.searchParams.get('timezone')||'Europe/London';if(!validZone(timezone))fail('Choose a valid time zone.');const date=url.searchParams.get('date')||localDay(new Date(),timezone);if(!validDay(date))fail('Choose a valid date.');
 const [plan,history,items,meetings,availableTasks,counts,reception]=await Promise.all([
 one('SELECT * FROM daily_plans WHERE workspace_id=? AND user_id=? AND day=?',w.id,user.userId,date),
 rows('SELECT day,goals,issues,review_note FROM daily_plans WHERE workspace_id=? AND user_id=? AND day<? ORDER BY day DESC LIMIT 5',w.id,user.userId,date),
 rows("SELECT i.*,p.name AS product_name,t.status AS source_status,t.updated_at AS source_updated_at FROM day_items i LEFT JOIN products p ON p.id=i.product_id AND p.workspace_id=i.workspace_id LEFT JOIN tasks t ON t.id=i.source_task_id AND t.workspace_id=i.workspace_id WHERE i.workspace_id=? AND i.user_id=? AND (i.status!='completed' OR i.updated_at>=?) ORDER BY i.created_at DESC LIMIT 1000",w.id,user.userId,offsetDay(date,-2)),
 rows('SELECT m.*,p.name AS product_name FROM day_meetings m LEFT JOIN products p ON p.id=m.product_id AND p.workspace_id=m.workspace_id WHERE m.workspace_id=? AND m.user_id=? AND m.starts_at>=? AND m.starts_at<? ORDER BY m.starts_at LIMIT 500',w.id,user.userId,offsetDay(date,-31),offsetDay(date,9)),
 rows("SELECT t.*,p.name AS product_name FROM tasks t JOIN runs r ON r.id=t.run_id JOIN products p ON p.id=t.product_id WHERE t.workspace_id=? AND r.kind='live' AND t.status='open' AND NOT EXISTS(SELECT 1 FROM day_items i WHERE i.source_task_id=t.id AND i.workspace_id=t.workspace_id AND i.user_id=?) ORDER BY t.created_at LIMIT 100",w.id,user.userId),
 one("SELECT (SELECT COUNT(*) FROM actions a JOIN runs r ON r.id=a.run_id WHERE a.workspace_id=? AND a.status='pending' AND r.kind='live') AS approvals,(SELECT COUNT(*) FROM tasks t JOIN runs r ON r.id=t.run_id WHERE t.workspace_id=? AND t.status='open' AND r.kind='live') AS tasks",w.id,w.id),
 one("SELECT SUM(status IN ('new','queued','accepted','failed')) AS pending,SUM(kind='booking' AND status IN ('new','queued','failed')) AS bookings,SUM(kind='order' AND status IN ('new','queued','accepted','failed')) AS orders FROM reception_items WHERE workspace_id=?",w.id)
 ]);
 return Response.json({date,timezone,plan:plan||{day:date,timezone,goals:'',issues:'',review_note:'',help_item_ids:'[]',revision:0},history,items,meetings,availableTasks,workspaceCounts:counts,reception,overview:dayOverview(items,meetings,date,timezone),calendarConnected:false,limits:{items:items.length===1000,meetings:meetings.length===500},generatedAt:now()},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return apiError(e);}}
export async function POST(req:Request){try{sameOrigin(req);const {w,user}=await workspace();requireRole(w,['owner','admin','operator']);const b=await readBody(req);const t=now();const ownerArgs=[w.id,user.userId];
 const owned=async(table:string,rid:unknown)=>{if(typeof rid!=='string')fail('Record not found.',404);const r=await one('SELECT * FROM '+table+' WHERE id=? AND workspace_id=? AND user_id=?',rid,...ownerArgs);if(!r)fail('Record not found.',404);return r};
 const checkRevision=(r:any)=>{if(!Number.isInteger(b.revision)||b.revision!==r.revision)fail('This record changed. Refresh and review it before saving.',409)};
 const date=()=>{if(!validDay(b.day))fail('Choose a valid day.');return b.day};
 const pid=async()=>{if(!b.productId)return null;await product(w.id,b.productId);return b.productId};
 if(b.action==='save_plan'){const day=date(),timezone=b.timezone;if(!validZone(timezone))fail('Choose a valid time zone.');if(!Number.isInteger(b.revision)||b.revision<0)fail('Reload the plan before saving.');const help=Array.isArray(b.helpItemIds)?[...new Set(b.helpItemIds)].slice(0,20):[];for(const item of help)await owned('day_items',item);const result=await stmt("INSERT INTO daily_plans(id,workspace_id,user_id,day,timezone,goals,issues,review_note,help_item_ids,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1,?,?) ON CONFLICT(workspace_id,user_id,day) DO UPDATE SET timezone=excluded.timezone,goals=excluded.goals,issues=excluded.issues,review_note=excluded.review_note,help_item_ids=excluded.help_item_ids,revision=daily_plans.revision+1,updated_at=excluded.updated_at WHERE daily_plans.revision=?",id(),...ownerArgs,day,timezone,boundedText(b.goals,4000),boundedText(b.issues,4000),boundedText(b.reviewNote,4000),JSON.stringify(help),t,t,b.revision).run();if(!result.meta.changes)fail('Your daily plan changed elsewhere. Refresh and review it before saving.',409);return Response.json({ok:true});}
 if(b.action==='import_task'){const day=date();const task=await one("SELECT t.* FROM tasks t JOIN runs r ON r.id=t.run_id WHERE t.id=? AND t.workspace_id=? AND r.kind='live' AND t.status='open'",b.taskId,w.id);if(!task)fail('An open live task is required.',404);const existing=await one('SELECT id FROM day_items WHERE source_task_id=? AND workspace_id=? AND user_id=?',task.id,...ownerArgs);if(existing)return Response.json({id:existing.id});const iid=id();await stmt("INSERT OR IGNORE INTO day_items(id,workspace_id,user_id,product_id,source_task_id,title,notes,scheduled_date,due_date,priority,status,blocker,steps,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'normal','planned','',?,1,?,?)",iid,...ownerArgs,task.product_id,task.id,task.title,task.body,day,null,JSON.stringify(startingSteps()),t,t).run();return Response.json({id:(await one('SELECT id FROM day_items WHERE source_task_id=? AND workspace_id=? AND user_id=?',task.id,...ownerArgs))!.id});}
 if(b.action==='save_item'){const title=boundedText(b.title,180);if(!title)fail('Add a task title.');const day=date();if(b.dueDate&&!validDay(b.dueDate))fail('Choose a valid due date.');if(!['high','normal','low'].includes(b.priority))fail('Choose a priority.');const productId=await pid();if(b.id){const r=await owned('day_items',b.id);checkRevision(r);if(r.source_task_id&&productId!==r.product_id)fail('A linked task must stay with its original product.');const result=await stmt('UPDATE day_items SET title=?,notes=?,product_id=?,scheduled_date=?,due_date=?,priority=?,blocker=?,status=CASE WHEN ?!=\'\' THEN \'blocked\' WHEN status=\'blocked\' THEN \'planned\' ELSE status END,revision=revision+1,updated_at=? WHERE id=? AND workspace_id=? AND user_id=? AND revision=?',title,boundedText(b.notes,4000),productId,day,b.dueDate||null,b.priority,boundedText(b.blocker,2000),boundedText(b.blocker,2000),t,b.id,...ownerArgs,b.revision).run();if(!result.meta.changes)fail('This task changed. Refresh and try again.',409);return Response.json({id:b.id});}
 const iid=id();await stmt("INSERT INTO day_items(id,workspace_id,user_id,product_id,title,notes,scheduled_date,due_date,priority,status,blocker,steps,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)",iid,...ownerArgs,productId,title,boundedText(b.notes,4000),day,b.dueDate||null,b.priority,b.blocker?'blocked':'planned',boundedText(b.blocker,2000),JSON.stringify(startingSteps()),t,t).run();return Response.json({id:iid});}
 if(b.action==='item_status'||b.action==='save_steps'){const r=await owned('day_items',b.id);checkRevision(r);if(b.action==='save_steps'){if(!Array.isArray(b.steps)||b.steps.length>20||b.steps.some((s:any)=>!s||typeof s.title!=='string'||!s.title.trim()||s.title.length>300||typeof s.done!=='boolean'))fail('Use up to 20 named steps.');const steps=b.steps.map((s:any,i:number)=>({id:String(i+1),title:s.title.trim(),done:s.done}));const result=await stmt('UPDATE day_items SET steps=?,revision=revision+1,updated_at=? WHERE id=? AND workspace_id=? AND user_id=? AND revision=?',JSON.stringify(steps),t,b.id,...ownerArgs,b.revision).run();if(!result.meta.changes)fail('This task changed. Refresh and try again.',409);return Response.json({ok:true});}
 if(!['planned','in_progress','blocked','completed'].includes(b.status))fail('Choose a valid task status.');const op=id();const statements=[stmt("INSERT INTO audit(id,workspace_id,actor,event,detail,resource_id,created_at) SELECT ?,workspace_id,?,'day.task_status','Updated a personal task status',id,? FROM day_items WHERE id=? AND workspace_id=? AND user_id=? AND revision=?",op,user.email,t,b.id,...ownerArgs,b.revision),stmt("UPDATE day_items SET status=?,blocker=CASE WHEN ?='blocked' THEN ? ELSE '' END,completed_at=?,revision=revision+1,updated_at=? WHERE id=? AND workspace_id=? AND user_id=? AND EXISTS(SELECT 1 FROM audit WHERE id=?)",b.status,b.status,boundedText(b.blocker,2000),b.status==='completed'?t:null,t,b.id,...ownerArgs,op)];
 if(r.source_task_id&&b.status==='completed'&&b.completeSource===true)statements.push(stmt("UPDATE tasks SET status='completed',updated_at=? WHERE id=? AND workspace_id=? AND EXISTS(SELECT 1 FROM audit WHERE id=?)",t,r.source_task_id,w.id,op));
 const result=await db().batch(statements);if(!result[0].meta.changes)fail('This task changed. Refresh and try again.',409);return Response.json({ok:true});}
 if(b.action==='save_meeting'){const title=boundedText(b.title,180);if(!title)fail('Add a meeting title.');if(!validZone(b.timezone))fail('Choose a valid time zone.');if(typeof b.startsAt!=='string'||!/^\d{4}-\d{2}-\d{2}T/.test(b.startsAt)||Number.isNaN(Date.parse(b.startsAt)))fail('Choose a valid meeting time.');const startsAt=new Date(b.startsAt).toISOString();const duration=Number(b.duration);if(!Number.isInteger(duration)||duration<5||duration>720)fail('Choose a duration from 5 to 720 minutes.');if(!['unconfirmed','confirmed','cancelled','completed'].includes(b.status))fail('Choose a meeting status.');const productId=await pid();const values=[title,productId,startsAt,duration,b.timezone,boundedText(b.attendees,1000),b.status,boundedText(b.notes,4000)];if(b.id){const r=await owned('day_meetings',b.id);checkRevision(r);const changed=await stmt('UPDATE day_meetings SET title=?,product_id=?,starts_at=?,duration=?,timezone=?,attendees=?,status=?,notes=?,revision=revision+1,updated_at=? WHERE id=? AND workspace_id=? AND user_id=? AND revision=?',...values,t,b.id,...ownerArgs,b.revision).run();if(!changed.meta.changes)fail('This meeting changed. Refresh and try again.',409);return Response.json({id:b.id});}const mid=id();await stmt('INSERT INTO day_meetings(id,workspace_id,user_id,title,product_id,starts_at,duration,timezone,attendees,status,notes,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,1,?,?)',mid,...ownerArgs,...values,t,t).run();return Response.json({id:mid});}
 if(b.action==='delete_item'||b.action==='delete_meeting'){const table=b.action==='delete_item'?'day_items':'day_meetings';const r=await owned(table,b.id);checkRevision(r);const result=await stmt('DELETE FROM '+table+' WHERE id=? AND workspace_id=? AND user_id=? AND revision=?',b.id,...ownerArgs,b.revision).run();if(!result.meta.changes)fail('This record changed. Refresh and try again.',409);return Response.json({ok:true});}
 fail('Unknown daily planning action.');}catch(e){return apiError(e);}}
