import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { requireModuleEntitlement, requireWritableTenantRole } from "@/modules/platform/module-access";

const scope=z.object({tenantId:z.string().uuid(),tenantProductId:z.string().uuid()});
async function moduleScope(context:any,data:z.infer<typeof scope>,moduleKey:string,write=false){const access=await requireModuleEntitlement(context,{...data,moduleKey});if(write)requireWritableTenantRole(access.role);return access;}

export const listMarketingWorkspace=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"marketing.core");const db=context.supabase as any;const[audiences,campaigns]=await Promise.all([db.from("marketing_audiences").select("*").eq("tenant_id",data.tenantId).eq("tenant_product_id",data.tenantProductId).order("updated_at",{ascending:false}),db.from("marketing_campaigns").select("*").eq("tenant_id",data.tenantId).eq("tenant_product_id",data.tenantProductId).order("updated_at",{ascending:false})]);if(audiences.error)throw new Error(audiences.error.message);if(campaigns.error)throw new Error(campaigns.error.message);return{audiences:audiences.data??[],campaigns:campaigns.data??[]};});

const audienceSchema=scope.extend({id:z.string().uuid().optional(),name:z.string().min(1).max(200),filters:z.array(z.record(z.string(),z.unknown())).max(100).default([]),status:z.enum(["draft","active","archived"]).default("draft")});
export const saveMarketingAudience=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof audienceSchema>)=>audienceSchema.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"marketing.core",true);const db=context.supabase as any;const values={tenant_id:data.tenantId,tenant_product_id:data.tenantProductId,name:data.name,filters:data.filters,status:data.status};const q=data.id?db.from("marketing_audiences").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("marketing_audiences").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Audience could not be saved");return row;});

const campaignSchema=scope.extend({id:z.string().uuid().optional(),name:z.string().min(1).max(240),objective:z.string().min(1).max(1000),audienceId:z.string().uuid().optional().nullable(),channels:z.array(z.enum(["email","sms","whatsapp","push","web","social"])).min(1),creativeBriefId:z.string().uuid().optional().nullable(),startsAt:z.string().datetime().optional().nullable(),endsAt:z.string().datetime().optional().nullable(),status:z.enum(["draft","scheduled","running","paused","completed","cancelled"]).default("draft"),attributionWindowDays:z.number().int().min(0).max(365).optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})});
export const saveMarketingCampaign=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof campaignSchema>)=>campaignSchema.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"marketing.core",true);const db=context.supabase as any;const values={tenant_id:data.tenantId,tenant_product_id:data.tenantProductId,name:data.name,objective:data.objective,audience_id:data.audienceId??null,channels:data.channels,creative_brief_id:data.creativeBriefId??null,starts_at:data.startsAt??null,ends_at:data.endsAt??null,status:data.status,attribution_window_days:data.attributionWindowDays??null,metadata:data.metadata};const q=data.id?db.from("marketing_campaigns").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("marketing_campaigns").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Campaign could not be saved");return row;});

export const listSalesSequences=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"sales.core");const db=context.supabase as any;const{data:rows,error}=await db.from("sales_sequences").select("*").eq("tenant_id",data.tenantId).eq("tenant_product_id",data.tenantProductId).order("updated_at",{ascending:false});if(error)throw new Error(error.message);return rows??[];});

const sequenceSchema=scope.extend({id:z.string().uuid().optional(),name:z.string().min(1).max(200),steps:z.array(z.record(z.string(),z.unknown())).max(100),status:z.enum(["draft","active","paused","archived"]).default("draft"),metadata:z.record(z.string(),z.unknown()).default({})});
export const saveSalesSequence=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof sequenceSchema>)=>sequenceSchema.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"sales.core",true);const db=context.supabase as any;const values={tenant_id:data.tenantId,tenant_product_id:data.tenantProductId,name:data.name,steps:data.steps,status:data.status,metadata:data.metadata};const q=data.id?db.from("sales_sequences").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("sales_sequences").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Sales sequence could not be saved");return row;});

export const listJourneys=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"journeys.core");const db=context.supabase as any;const{data:rows,error}=await db.from("journey_definitions").select("*").eq("tenant_id",data.tenantId).eq("tenant_product_id",data.tenantProductId).order("updated_at",{ascending:false});if(error)throw new Error(error.message);return rows??[];});

const journeySchema=scope.extend({id:z.string().uuid().optional(),name:z.string().min(1).max(200),nodes:z.array(z.record(z.string(),z.unknown())).max(500),edges:z.array(z.record(z.string(),z.unknown())).max(1000),status:z.enum(["draft","active","paused","archived"]).default("draft")});
export const saveJourney=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof journeySchema>)=>journeySchema.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"journeys.core",true);const db=context.supabase as any;const values={tenant_id:data.tenantId,tenant_product_id:data.tenantProductId,name:data.name,nodes:data.nodes,edges:data.edges,status:data.status};const q=data.id?db.from("journey_definitions").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("journey_definitions").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Journey could not be saved");return row;});

export const listFeedbackSurveys=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"feedback.core");const db=context.supabase as any;const{data:rows,error}=await db.from("feedback_surveys").select("*").eq("tenant_id",data.tenantId).eq("tenant_product_id",data.tenantProductId).order("updated_at",{ascending:false});if(error)throw new Error(error.message);return rows??[];});

const surveySchema=scope.extend({id:z.string().uuid().optional(),type:z.enum(["nps","csat","ces","custom"]),name:z.string().min(1).max(200),triggerEvent:z.string().max(160).optional().nullable(),channel:z.enum(["email","sms","whatsapp","web","app"]),status:z.enum(["draft","active","paused","archived"]).default("draft"),config:z.record(z.string(),z.unknown()).default({})});
export const saveFeedbackSurvey=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof surveySchema>)=>surveySchema.parse(input)).handler(async({context,data})=>{await moduleScope(context,data,"feedback.core",true);const db=context.supabase as any;const values={tenant_id:data.tenantId,tenant_product_id:data.tenantProductId,survey_type:data.type,name:data.name,trigger_event:data.triggerEvent??null,channel:data.channel,status:data.status,config:data.config};const q=data.id?db.from("feedback_surveys").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("feedback_surveys").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Survey could not be saved");return row;});