import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
const uuid=z.string().uuid();
const scope=z.object({tenantId:uuid});
export const getGrowthWorkspace=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.infer<typeof scope>)=>scope.parse(i)).handler(async({context,data})=>{const db=context.supabase as any;const rs=await Promise.all([
 db.from("growth_segments").select("*").eq("tenant_id",data.tenantId).order("name"),
 db.from("marketing_campaigns").select("*").eq("tenant_id",data.tenantId).order("created_at",{ascending:false}),
 db.from("customer_journeys").select("*").eq("tenant_id",data.tenantId).order("created_at",{ascending:false}),
 db.from("sales_sequences").select("*").eq("tenant_id",data.tenantId).order("created_at",{ascending:false}),
 db.from("feedback_surveys").select("*").eq("tenant_id",data.tenantId).order("created_at",{ascending:false}),
 db.from("feedback_responses").select("*").eq("tenant_id",data.tenantId).order("created_at",{ascending:false}).limit(500),
 db.from("growth_customer_metrics").select("*,person:crm_people(display_name,email,phone_e164)").eq("tenant_id",data.tenantId).order("revenue_minor",{ascending:false}).limit(500)
 ]);for(const r of rs)if(r.error)throw new Error(r.error.message);return{segments:rs[0].data??[],campaigns:rs[1].data??[],journeys:rs[2].data??[],sequences:rs[3].data??[],surveys:rs[4].data??[],responses:rs[5].data??[],metrics:rs[6].data??[]};});
export const recomputeRfm=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{tenantId:string})=>scope.parse(i)).handler(async({context,data})=>{const r=await(context.supabase as any).rpc("growth_recompute_customer_metrics",{_tenant:data.tenantId});if(r.error)throw new Error(r.error.message);return{customers:r.data as number};});
const segment=scope.extend({name:z.string().min(1).max(160),segmentKey:z.string().regex(/^[a-z0-9-]{1,100}$/),productKey:z.string().max(80).nullish(),rules:z.record(z.string(),z.unknown()).default({})});
export const createSegment=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof segment>)=>segment.parse(i)).handler(async({context,data})=>{const{data:row,error}=await(context.supabase as any).from("growth_segments").insert({tenant_id:data.tenantId,product_key:data.productKey??null,name:data.name,segment_key:data.segmentKey,rules:data.rules,status:"active"}).select("*").single();if(error)throw new Error(error.message);return row;});
const campaign=scope.extend({name:z.string().min(1).max(160),productKey:z.string().max(80).nullish(),channel:z.enum(["whatsapp","sms","email","push","multi"]),segmentId:uuid.nullish(),content:z.record(z.string(),z.unknown()).default({})});
export const createCampaign=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof campaign>)=>campaign.parse(i)).handler(async({context,data})=>{const{data:row,error}=await(context.supabase as any).from("marketing_campaigns").insert({tenant_id:data.tenantId,product_key:data.productKey??null,name:data.name,channel:data.channel,segment_id:data.segmentId??null,content:data.content,status:"draft"}).select("*").single();if(error)throw new Error(error.message);return row;});
const journey=scope.extend({name:z.string().min(1).max(160),productKey:z.string().max(80).nullish(),triggerEvent:z.string().min(3).max(160),definition:z.record(z.string(),z.unknown()).default({})});
export const createJourney=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof journey>)=>journey.parse(i)).handler(async({context,data})=>{const{data:row,error}=await(context.supabase as any).from("customer_journeys").insert({tenant_id:data.tenantId,product_key:data.productKey??null,name:data.name,trigger_event:data.triggerEvent,definition:data.definition,status:"draft"}).select("*").single();if(error)throw new Error(error.message);return row;});
const survey=scope.extend({name:z.string().min(1).max(160),productKey:z.string().max(80).nullish(),surveyType:z.enum(["nps","csat","ces","review"]),triggerEvent:z.string().max(160).nullish()});
export const createFeedbackSurvey=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:z.input<typeof survey>)=>survey.parse(i)).handler(async({context,data})=>{const{data:row,error}=await(context.supabase as any).from("feedback_surveys").insert({tenant_id:data.tenantId,product_key:data.productKey??null,name:data.name,survey_type:data.surveyType,trigger_event:data.triggerEvent??null,status:"active"}).select("*").single();if(error)throw new Error(error.message);return row;});
