/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowPacksRouteImport } from './routes/workflow-packs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWorkflowsRouteImport } from './routes/_authenticated/app.workflows'
import { Route as AuthenticatedAppWhatsappRouteImport } from './routes/_authenticated/app.whatsapp'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppPartnersRouteImport } from './routes/_authenticated/app.partners'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppContactsRouteImport } from './routes/_authenticated/app.contacts'
import { Route as AuthenticatedAppCasesRouteImport } from './routes/_authenticated/app.cases'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppCasesIndexRouteImport } from './routes/_authenticated/app.cases.index'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as AuthenticatedAppCasesCaseIdRouteImport } from './routes/_authenticated/app.cases.$caseId'

const WorkflowPacksRoute = WorkflowPacksRouteImport.update({
  id: '/workflow-packs',
  path: '/workflow-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWorkflowsRoute =
  AuthenticatedAppWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppWhatsappRoute =
  AuthenticatedAppWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPartnersRoute =
  AuthenticatedAppPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContactsRoute =
  AuthenticatedAppContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCasesRoute = AuthenticatedAppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCasesIndexRoute =
  AuthenticatedAppCasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCasesRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppCasesCaseIdRoute =
  AuthenticatedAppCasesCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AuthenticatedAppCasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/datenschutz': typeof DatenschutzRoute
  '/features': typeof FeaturesRoute
  '/impressum': typeof ImpressumRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow-packs': typeof WorkflowPacksRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/partners': typeof AuthenticatedAppPartnersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/app/cases/': typeof AuthenticatedAppCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/datenschutz': typeof DatenschutzRoute
  '/features': typeof FeaturesRoute
  '/impressum': typeof ImpressumRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow-packs': typeof WorkflowPacksRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/partners': typeof AuthenticatedAppPartnersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/app/cases': typeof AuthenticatedAppCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/datenschutz': typeof DatenschutzRoute
  '/features': typeof FeaturesRoute
  '/impressum': typeof ImpressumRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow-packs': typeof WorkflowPacksRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/_authenticated/app/contacts': typeof AuthenticatedAppContactsRoute
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/partners': typeof AuthenticatedAppPartnersRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/_authenticated/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/_authenticated/app/cases/': typeof AuthenticatedAppCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/auth'
    | '/compliance'
    | '/datenschutz'
    | '/features'
    | '/impressum'
    | '/pricing'
    | '/sitemap.xml'
    | '/workflow-packs'
    | '/app'
    | '/app/analytics'
    | '/app/campaigns'
    | '/app/cases'
    | '/app/contacts'
    | '/app/inbox'
    | '/app/partners'
    | '/app/settings'
    | '/app/whatsapp'
    | '/app/workflows'
    | '/app/'
    | '/app/cases/$caseId'
    | '/api/public/whatsapp/webhook'
    | '/app/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/auth'
    | '/compliance'
    | '/datenschutz'
    | '/features'
    | '/impressum'
    | '/pricing'
    | '/sitemap.xml'
    | '/workflow-packs'
    | '/app/analytics'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/inbox'
    | '/app/partners'
    | '/app/settings'
    | '/app/whatsapp'
    | '/app/workflows'
    | '/app'
    | '/app/cases/$caseId'
    | '/api/public/whatsapp/webhook'
    | '/app/cases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agb'
    | '/auth'
    | '/compliance'
    | '/datenschutz'
    | '/features'
    | '/impressum'
    | '/pricing'
    | '/sitemap.xml'
    | '/workflow-packs'
    | '/_authenticated/app'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/cases'
    | '/_authenticated/app/contacts'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/partners'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/whatsapp'
    | '/_authenticated/app/workflows'
    | '/_authenticated/app/'
    | '/_authenticated/app/cases/$caseId'
    | '/api/public/whatsapp/webhook'
    | '/_authenticated/app/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgbRoute: typeof AgbRoute
  AuthRoute: typeof AuthRoute
  ComplianceRoute: typeof ComplianceRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FeaturesRoute: typeof FeaturesRoute
  ImpressumRoute: typeof ImpressumRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkflowPacksRoute: typeof WorkflowPacksRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow-packs': {
      id: '/workflow-packs'
      path: '/workflow-packs'
      fullPath: '/workflow-packs'
      preLoaderRoute: typeof WorkflowPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/workflows': {
      id: '/_authenticated/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AuthenticatedAppWorkflowsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/whatsapp': {
      id: '/_authenticated/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AuthenticatedAppWhatsappRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/partners': {
      id: '/_authenticated/app/partners'
      path: '/partners'
      fullPath: '/app/partners'
      preLoaderRoute: typeof AuthenticatedAppPartnersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts': {
      id: '/_authenticated/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AuthenticatedAppContactsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cases': {
      id: '/_authenticated/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AuthenticatedAppCasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cases/': {
      id: '/_authenticated/app/cases/'
      path: '/'
      fullPath: '/app/cases/'
      preLoaderRoute: typeof AuthenticatedAppCasesIndexRouteImport
      parentRoute: typeof AuthenticatedAppCasesRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/cases/$caseId': {
      id: '/_authenticated/app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/app/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedAppCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedAppCasesRoute
    }
  }
}

interface AuthenticatedAppCasesRouteChildren {
  AuthenticatedAppCasesCaseIdRoute: typeof AuthenticatedAppCasesCaseIdRoute
  AuthenticatedAppCasesIndexRoute: typeof AuthenticatedAppCasesIndexRoute
}

const AuthenticatedAppCasesRouteChildren: AuthenticatedAppCasesRouteChildren = {
  AuthenticatedAppCasesCaseIdRoute: AuthenticatedAppCasesCaseIdRoute,
  AuthenticatedAppCasesIndexRoute: AuthenticatedAppCasesIndexRoute,
}

const AuthenticatedAppCasesRouteWithChildren =
  AuthenticatedAppCasesRoute._addFileChildren(
    AuthenticatedAppCasesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppCasesRoute: typeof AuthenticatedAppCasesRouteWithChildren
  AuthenticatedAppContactsRoute: typeof AuthenticatedAppContactsRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppPartnersRoute: typeof AuthenticatedAppPartnersRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppWhatsappRoute: typeof AuthenticatedAppWhatsappRoute
  AuthenticatedAppWorkflowsRoute: typeof AuthenticatedAppWorkflowsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppCasesRoute: AuthenticatedAppCasesRouteWithChildren,
  AuthenticatedAppContactsRoute: AuthenticatedAppContactsRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppPartnersRoute: AuthenticatedAppPartnersRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppWhatsappRoute: AuthenticatedAppWhatsappRoute,
  AuthenticatedAppWorkflowsRoute: AuthenticatedAppWorkflowsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgbRoute: AgbRoute,
  AuthRoute: AuthRoute,
  ComplianceRoute: ComplianceRoute,
  DatenschutzRoute: DatenschutzRoute,
  FeaturesRoute: FeaturesRoute,
  ImpressumRoute: ImpressumRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkflowPacksRoute: WorkflowPacksRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
