-- Omniqora SaaS Factory: A-to-Z shared capability catalogue, bundles and blueprints.
BEGIN;

INSERT INTO public.omniqora_product_catalogue(
  product_key,name,category,runtime_key,owner_label,sort_order,metadata
) VALUES
  ('motoresq','MotoResQ','generic','motoresq','iTechLounge',10,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('zivvo','Zivvo UK and enabled markets','generic','zivvo','iTechLounge',20,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('bidlumo','Bidlumo','generic','bidlumo','iTechLounge',30,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('amityos','AmityOS','generic','amityos','iTechLounge',40,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('skillfinch','Skillfinch','generic','skillfinch','iTechLounge',50,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('fleetsora','FleetSora','generic','fleetsora','iTechLounge',60,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('eventplanr','EventPlanr UK','generic','eventplanr','iTechLounge',70,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('haccora','Haccora Germany','haccora','haccora','iTechLounge',80,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('craftvaro','Craftvaro','generic','craftvaro','iTechLounge',90,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('kinderstars','KinderStars Germany','generic','kinderstars','iTechLounge',100,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('lawquo','Lawquo / Veris Law','lawquo','lawquo','iTechLounge',110,jsonb_build_object('sourceStatus','metadata-contract-implemented')),
  ('leadlens','LeadLens','generic','leadlens','iTechLounge',120,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('onyngo','OnýnGo','generic','onyngo','iTechLounge',130,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('iq-practice-cloud','IQ Practice Cloud','generic','iq-practice-cloud','iTechLounge',140,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('gabley','Gabley','generic','gabley','iTechLounge',150,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('dokuvera','Dokuvera','generic','dokuvera','iTechLounge',160,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('ilmvero','Ilmvero','generic','ilmvero','iTechLounge',170,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('threeonethree','ThreeOneThree','generic','threeonethree','iTechLounge',180,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('taxcenda','TaxCenda','generic','taxcenda','iTechLounge',190,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('orvilo','Orvilo','generic','orvilo','iTechLounge',200,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('xpertjobs','XpertJobs','generic','xpertjobs','iTechLounge',210,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('taxnuvia','TaxNuvia accountant finder','taxnuvia','taxnuvia','iTechLounge',220,jsonb_build_object('sourceStatus','ranking-contract-implemented')),
  ('zarvane','Zarvane','generic','zarvane','iTechLounge',230,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('zoryn-pay','Zoryn Pay','generic','zoryn-pay','iTechLounge',240,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('zoryn-rewards','Zoryn Rewards','generic','zoryn-rewards','iTechLounge',250,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('affivon','Affivon','generic','affivon','iTechLounge',260,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('cirqiva','Cirqiva','generic','cirqiva','iTechLounge',270,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('commerceops','CommerceOps','generic','commerceops','iTechLounge',280,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('empfangiq','EmpfangIQ','generic','empfangiq','iTechLounge',290,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('gabley-retrofit','Gabley Retrofit','generic','gabley-retrofit','iTechLounge',300,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('insure360','Insure360','generic','insure360','iTechLounge',310,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('konnevia','Konnevia CRM','generic','konnevia','iTechLounge',320,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('lessonahead','LessonAhead UK','generic','lessonahead','iTechLounge',330,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('loungetech-founders','LoungeTech Gründungsportal','generic','loungetech-founders','iTechLounge',340,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('loungetech-training','LoungeTech Training Cloud','generic','loungetech-training','iTechLounge',350,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('marktpass','MarktPass','generic','marktpass','iTechLounge',360,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('premisora','Premisora','generic','premisora','iTechLounge',370,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('auvane-one','Auvane One professional desk','generic','auvane-one','iTechLounge',380,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('recovra','Recovra','generic','recovra','iTechLounge',390,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('regulos','RegulaOS','generic','regulos','iTechLounge',400,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('tenderos','Tendryva','generic','tenderos','iTechLounge',410,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('travel-agency-os','Travel Agency OS','generic','travel-agency-os','iTechLounge',420,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('veyumo','Veyumo','generic','veyumo','iTechLounge',430,jsonb_build_object('sourceStatus','mobile-bridge-source-integrated')),
  ('ahlnikkah','AhlNikkah','generic','ahlnikkah','iTechLounge',440,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('beistandplus','BeistandPlus','generic','beistandplus','iTechLounge',450,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('beratermarkt','BeraterMarkt','generic','beratermarkt','iTechLounge',460,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('construction-planning','AI Construction Planning','generic','construction-planning','iTechLounge',470,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('criclume','Criclume','generic','criclume','iTechLounge',480,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('dearnext','DearNext','generic','dearnext','iTechLounge',490,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('depotmesh','DepotMesh','generic','depotmesh','iTechLounge',500,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('dishbee','Dishbee','generic','dishbee','iTechLounge',510,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('domureva','DOMUREVA','generic','domureva','iTechLounge',520,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('fanzeno','Fanzeno','generic','fanzeno','iTechLounge',530,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('formationgenie','FormationGenie','business-services','formationgenie','iTechLounge',540,jsonb_build_object('sourceStatus','external-runtime')),
  ('gradlume','Gradlume','generic','gradlume','iTechLounge',550,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('hmo-flow','HMO Flow','generic','hmo-flow','iTechLounge',560,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('immoviq','Immoviq','generic','immoviq','iTechLounge',570,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('kalethon-play','Kalethon Play','generic','kalethon-play','iTechLounge',580,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('kiezio','Kiezio','generic','kiezio','iTechLounge',590,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('loungeconnect','LoungeConnect','generic','loungeconnect','iTechLounge',600,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('merqano','Merqano','generic','merqano','iTechLounge',610,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('merqora','Merqora','generic','merqora','iTechLounge',620,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('nearcura','NearCura','generic','nearcura','iTechLounge',630,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('pipkin','Pipkin','generic','pipkin','iTechLounge',640,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('recovarable','Recovarable','generic','recovarable','iTechLounge',650,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('rettio','Rettio','generic','rettio','iTechLounge',660,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('schonova','Schonova','generic','schonova','iTechLounge',670,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('stemcoach','STEMCoach','generic','stemcoach','iTechLounge',680,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('syndryvia','Syndryvia / user spelling Syndrivya — identity to confirm','generic','syndryvia','iTechLounge',690,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('traindirekt','TrainDirekt','generic','traindirekt','iTechLounge',700,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('unipathways','UniPathways','generic','unipathways','iTechLounge',710,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('voxentri','Voxentri','generic','voxentri','iTechLounge',720,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('sparesgrid','SparesGrid','automotive','sparesgrid','iTechLounge',730,jsonb_build_object('sourceStatus','gateway-contract-implemented')),
  ('business360','Omniqora Business360','transformation','business360','iTechLounge',740,jsonb_build_object('sourceStatus','shared-runtime-implemented')),
  ('epos','EPOS intelligence / Cafe1','hospitality','epos','iTechLounge',750,jsonb_build_object('sourceStatus','source-adapter-required')),
  ('courier-broker','Courier Broker OS','logistics','courier-broker','iTechLounge',760,jsonb_build_object('sourceStatus','connect-addon-adapter-implemented')),
  ('autohashi','AutoHashi','automotive','autohashi','iTechLounge',770,jsonb_build_object('sourceStatus','connect-manifest-implemented')),
  ('omniqora','Omniqora Cloud','platform','omniqora','iTechLounge',780,jsonb_build_object('sourceStatus','native')),
  ('kindelo','Kindelo','childcare','kindelo','iTechLounge',790,jsonb_build_object('sourceStatus','external-runtime')),
  ('mealdeck','MealDeck','hospitality','mealdeck','iTechLounge',800,jsonb_build_object('sourceStatus','dishbee-runtime')),
  ('fastremit','FastRemit','remittance','fastremit','iTechLounge',810,jsonb_build_object('sourceStatus','external-runtime')),
  ('all-road-aid','All-Road-Aid','roadside','all-road-aid','iTechLounge',820,jsonb_build_object('sourceStatus','external-runtime')),
  ('omniqora-accounts','Omniqora Accounts','accounting','omniqora-accounts','iTechLounge',830,jsonb_build_object('sourceStatus','external-runtime')),
  ('courier-connect','Courier Connect Hub','logistics','courier-connect','iTechLounge',840,jsonb_build_object('sourceStatus','external-runtime'))
ON CONFLICT(product_key) DO UPDATE SET
  name=excluded.name,category=excluded.category,runtime_key=excluded.runtime_key,
  owner_label=excluded.owner_label,sort_order=excluded.sort_order,
  metadata=public.omniqora_product_catalogue.metadata||excluded.metadata,
  active=true,updated_at=now();

INSERT INTO public.omniqora_service_catalogue(
  service_key,name,description,category,provider_key,runtime_key,service_kind,billing_basis,
  recurring,default_unit_amount_pence,currency,provisioning_key,metadata
) VALUES
  ('omniqora.identity','Omniqora Identity','SSO, MFA, passkeys, magic links, social sign-in and SMS/WhatsApp OTP.','Foundation','omniqora','identity','platform','flat',true,0,'GBP','identity',jsonb_build_object('shared',true)),
  ('omniqora.tenant','Tenant Platform','Organisations, tenants, locations, memberships, RBAC/RLS and configuration.','Foundation','omniqora','tenant','platform','flat',true,0,'GBP','tenant',jsonb_build_object('shared',true)),
  ('omniqora.entitlements','Plans & Entitlements','Products, plans, add-ons, dependency resolution, feature flags and usage controls.','Foundation','omniqora','entitlements','platform','flat',true,0,'GBP','entitlements',jsonb_build_object('shared',true)),
  ('omniqora.audit-security','Audit & Security','Immutable audit trail, approvals, consent, access evidence and security events.','Foundation','omniqora','audit-security','platform','flat',true,0,'GBP','audit-security',jsonb_build_object('shared',true)),
  ('omniqora.data-events','Data & Event Bus','Canonical events, outbox, webhooks, retries, correlation and schema versioning.','Foundation','omniqora','data-events','platform','flat',true,0,'GBP','data-events',jsonb_build_object('shared',true)),
  ('omniqora.api-gateway','API & Connector Gateway','Signed product bridges, scoped APIs, provider adapters, idempotency and quotas.','Foundation','omniqora','api-gateway','platform','flat',true,0,'GBP','api-gateway',jsonb_build_object('shared',true)),
  ('omniqora.documents','Documents & Search','Tenant documents, metadata, secure sharing, retention and search.','Foundation','omniqora','documents','platform','flat',true,0,'GBP','documents',jsonb_build_object('shared',true)),
  ('omniqora.automation','Automation','Reusable triggers, conditions, actions, schedules, approvals and human handoffs.','Automation','omniqora','automation','addon','flat',true,0,'GBP','automation',jsonb_build_object('shared',true)),
  ('omniqora.ai','Omniqora AI','Shared model gateway, copilots, classification, extraction, recommendations and tools.','AI & Knowledge','omniqora','ai','addon','flat',true,0,'GBP','ai',jsonb_build_object('shared',true)),
  ('omniqora.genai','Generative AI','Governed generation for text, reports, correspondence, summaries and structured outputs.','AI & Knowledge','omniqora','genai','addon','flat',true,0,'GBP','genai',jsonb_build_object('shared',true)),
  ('omniqora.agentic-ai','Agentic AI','Tool-using agents, plans, tasks, permissions, budgets, approvals and execution logs.','AI & Knowledge','omniqora','agentic-ai','addon','flat',true,0,'GBP','agentic-ai',jsonb_build_object('shared',true)),
  ('omniqora.ai-governance','AI Governance','Use-case register, risk, approvals, model/agent registry, evaluation, cost and policy controls.','AI & Knowledge','omniqora','ai-governance','addon','flat',true,0,'GBP','ai-governance',jsonb_build_object('shared',true)),
  ('omniqora.knowledge-rag','Knowledge RAG','Evidence-grounded retrieval, citations, tenant knowledge and source-controlled research.','AI & Knowledge','omniqora','knowledge-rag','addon','flat',true,0,'GBP','knowledge-rag',jsonb_build_object('shared',true)),
  ('omniqora.graphrag','GraphRAG','Relationship-aware retrieval and multi-hop reasoning across governed knowledge graphs.','AI & Knowledge','omniqora','graphrag','addon','flat',true,0,'GBP','graphrag',jsonb_build_object('shared',true)),
  ('omniqora.neo4j','Neo4j Knowledge Graph','Optional Neo4j-backed entities, relationships, lineage and graph traversal.','AI & Knowledge','omniqora','neo4j','addon','flat',true,0,'GBP','neo4j',jsonb_build_object('shared',true)),
  ('omniqora.microsoft-rag','Microsoft RAG','Microsoft/Azure RAG profile using Graph, SharePoint/OneDrive, Azure AI Search and governed connectors.','AI & Knowledge','omniqora','microsoft-rag','addon','flat',true,0,'GBP','microsoft-rag',jsonb_build_object('shared',true)),
  ('omniqora.azure-ai-search','Azure AI Search','Hybrid/vector search adapter for enterprise RAG and retrieval.','AI & Knowledge','omniqora','azure-ai-search','addon','flat',true,0,'GBP','azure-ai-search',jsonb_build_object('shared',true)),
  ('omniqora.azure-openai','Azure OpenAI','Enterprise Azure OpenAI model adapter with tenant policy controls.','AI & Knowledge','omniqora','azure-openai','addon','flat',true,0,'GBP','azure-openai',jsonb_build_object('shared',true)),
  ('omniqora.microsoft-graph','Microsoft Graph','Microsoft 365 Graph connector for users, files, email, calendars and approved business context.','AI & Knowledge','omniqora','microsoft-graph','addon','flat',true,0,'GBP','microsoft-graph',jsonb_build_object('shared',true)),
  ('omniqora.sharepoint','SharePoint & OneDrive','Governed SharePoint/OneDrive knowledge and document connector.','AI & Knowledge','omniqora','sharepoint','addon','flat',true,0,'GBP','sharepoint',jsonb_build_object('shared',true)),
  ('omniqora.document-ai','Document AI','OCR/extraction, classification, structured review and evidence capture.','AI & Knowledge','omniqora','document-ai','addon','flat',true,0,'GBP','document-ai',jsonb_build_object('shared',true)),
  ('omniqora.media-ai','Media & Vision AI','Image/document/media analysis with evidence, confidence and human review controls.','AI & Knowledge','omniqora','media-ai','addon','flat',true,0,'GBP','media-ai',jsonb_build_object('shared',true)),
  ('omniqora.warehouse','Central Data Warehouse','Canonical warehouse/events layer for cross-product analytics and governed metrics.','Data & BI','omniqora','warehouse','addon','flat',true,0,'GBP','warehouse',jsonb_build_object('shared',true)),
  ('omniqora.databricks','Databricks','Lakehouse, ML/AI and enterprise data adapter.','Data & BI','omniqora','databricks','addon','flat',true,0,'GBP','databricks',jsonb_build_object('shared',true)),
  ('omniqora.snowflake','Snowflake','Warehouse and governed enterprise data adapter.','Data & BI','omniqora','snowflake','addon','flat',true,0,'GBP','snowflake',jsonb_build_object('shared',true)),
  ('omniqora.microsoft-fabric','Microsoft Fabric','Fabric lakehouse/warehouse integration and semantic-model pipeline.','Data & BI','omniqora','microsoft-fabric','addon','flat',true,0,'GBP','microsoft-fabric',jsonb_build_object('shared',true)),
  ('omniqora.powerbi','Power BI','Tenant dashboards, semantic models, governed KPIs and embedded BI.','Data & BI','omniqora','powerbi','addon','flat',true,0,'GBP','powerbi',jsonb_build_object('shared',true)),
  ('omniqora.analytics','Analytics & BI','Operational analytics, KPI definitions, dashboards and cross-product reporting.','Data & BI','omniqora','analytics','addon','flat',true,0,'GBP','analytics',jsonb_build_object('shared',true)),
  ('omniqora.data-lineage','Data Lineage','Source-to-report lineage, reconciliations, ownership and data quality evidence.','Data & BI','omniqora','data-lineage','addon','flat',true,0,'GBP','data-lineage',jsonb_build_object('shared',true)),
  ('omniqora.customer360','Customer 360','Canonical tenant customer identity and cross-product relationship graph.','CRM & Growth','omniqora','customer360','addon','flat',true,0,'GBP','customer360',jsonb_build_object('shared',true)),
  ('omniqora.crm','Omniqora CRM','Contacts, companies, leads, opportunities, tasks, tickets and interaction timeline.','CRM & Growth','omniqora','crm','addon','flat',true,0,'GBP','crm',jsonb_build_object('shared',true)),
  ('omniqora.sales','Omniqora Sales','Lead lists, sequences, AI outreach, calls, callbacks, meetings and lead scoring.','CRM & Growth','omniqora','sales','addon','flat',true,0,'GBP','sales',jsonb_build_object('shared',true)),
  ('omniqora.journeys','Customer Journeys','Visual trigger-condition-delay-branch-action journeys across channels.','CRM & Growth','omniqora','journeys','addon','flat',true,0,'GBP','journeys',jsonb_build_object('shared',true)),
  ('omniqora.rfm','RFM & Customer Intelligence','RFM, AOV, LTV, churn, engagement, profitability and propensity segments.','CRM & Growth','omniqora','rfm','addon','flat',true,0,'GBP','rfm',jsonb_build_object('shared',true)),
  ('omniqora.feedback','Feedback & Reviews','NPS, CSAT, CES, review requests, recovery workflows and sentiment.','CRM & Growth','omniqora','feedback','addon','flat',true,0,'GBP','feedback',jsonb_build_object('shared',true)),
  ('zoryn.rewards','Zoryn Rewards','Loyalty, points, rewards, tiers and cross-product customer value.','CRM & Growth','omniqora','zoryn-rewards','addon','flat',true,0,'GBP','zoryn-rewards',jsonb_build_object('shared',true)),
  ('omniqora.connect','Omniqora Connect','Shared communications orchestration across WhatsApp, SMS, email, voice and push.','Communications','omniqora','connect','platform','flat',true,0,'GBP','connect',jsonb_build_object('shared',true)),
  ('omniqora.notifications','Notifications','Transactional templates, routing, retries, preferences and delivery receipts.','Communications','omniqora','notifications','addon','flat',true,0,'GBP','notifications',jsonb_build_object('shared',true)),
  ('omniqora.whatsapp','WhatsApp','Multi-number product/tenant WhatsApp Cloud API messaging and workflows.','Communications','omniqora','whatsapp','addon','flat',true,0,'GBP','whatsapp',jsonb_build_object('shared',true)),
  ('omniqora.sms','SMS','Tenant-scoped SMS messaging, templates and fallback routing.','Communications','omniqora','sms','addon','flat',true,0,'GBP','sms',jsonb_build_object('shared',true)),
  ('omniqora.email','Email','Tenant-branded transactional and campaign email.','Communications','omniqora','email','addon','flat',true,0,'GBP','email',jsonb_build_object('shared',true)),
  ('omniqora.voice','Voice','Programmable voice, call routing, AI receptionist, VoIP/SIP and assisted-service workflows.','Communications','omniqora','voice','addon','flat',true,0,'GBP','voice',jsonb_build_object('shared',true)),
  ('omniqora.push','Push Notifications','Web/mobile push notifications and preference routing.','Communications','omniqora','push','addon','flat',true,0,'GBP','push',jsonb_build_object('shared',true)),
  ('omniqora.geo','Omniqora Geo','Geocoding, distance, ETA, routes, optimisation, geofences and territories.','Operations','omniqora','geo','addon','flat',true,0,'GBP','geo',jsonb_build_object('shared',true)),
  ('omniqora.dispatch','Dispatch','Universal job/delivery/field-service dispatch, allocation, SLA and routing.','Operations','omniqora','dispatch','addon','flat',true,0,'GBP','dispatch',jsonb_build_object('shared',true)),
  ('omniqora.fleet','Fleet','Drivers, shifts, vehicles, maintenance, behaviour, utilisation and wallets.','Operations','omniqora','fleet','addon','flat',true,0,'GBP','fleet',jsonb_build_object('shared',true)),
  ('omniqora.agent','Omniqora Agent','Universal driver/courier/recovery/field-agent application capability.','Operations','omniqora','agent','addon','flat',true,0,'GBP','agent',jsonb_build_object('shared',true)),
  ('omniqora.tracking','Customer Tracking','Signed no-login tracking, ETA, status, chat/call-mask, POD and rating.','Operations','omniqora','tracking','addon','flat',true,0,'GBP','tracking',jsonb_build_object('shared',true)),
  ('omniqora.procurement','Procurement Intelligence','Supplier onboarding, sourcing, controls, readiness, spend and contract intelligence.','Operations','omniqora','procurement','addon','flat',true,0,'GBP','procurement',jsonb_build_object('shared',true)),
  ('omniqora.marketplace-core','Marketplace Core','Reusable listings, sellers/providers, matching, availability, checkout and marketplace workflows.','Commerce','omniqora','marketplace-core','addon','flat',true,0,'GBP','marketplace-core',jsonb_build_object('shared',true)),
  ('omniqora.payments','Payments','Payment intents, links, provider abstraction, refunds, payouts and settlement events.','Commerce','omniqora','payments','addon','flat',true,0,'GBP','payments',jsonb_build_object('shared',true)),
  ('omniqora.billing','Billing & Usage','Subscriptions, add-ons, metering, invoices, internal settlement and revenue attribution.','Commerce','omniqora','billing','addon','flat',true,0,'GBP','billing',jsonb_build_object('shared',true)),
  ('omniqora.business360','Business360','Discover, audit, improve and continuously monitor companies, groups, branches and departments.','Audit, M&A & Transformation','omniqora','business360','addon','flat',true,0,'GBP','business360',jsonb_build_object('shared',true)),
  ('omniqora.enterprise-audit','Enterprise Audit','Full-company audit across finance, people, technology, assets, revenue, collections, costs, marketing, operations and controls.','Audit, M&A & Transformation','omniqora','enterprise-audit','addon','flat',true,0,'GBP','enterprise-audit',jsonb_build_object('shared',true)),
  ('omniqora.internal-audit','Internal Audit','Risk-based audit planning, control testing, findings, actions, follow-up and assurance.','Audit, M&A & Transformation','omniqora','internal-audit','addon','flat',true,0,'GBP','internal-audit',jsonb_build_object('shared',true)),
  ('omniqora.external-audit','External Audit','Engagement planning, evidence, materiality, sampling, testing, workpapers, review and reporting.','Audit, M&A & Transformation','omniqora','external-audit','addon','flat',true,0,'GBP','external-audit',jsonb_build_object('shared',true)),
  ('omniqora.audit-workpapers','Audit Workpapers','Structured workpapers, sign-off, review notes, versioning, indexing and evidence links.','Audit, M&A & Transformation','omniqora','audit-workpapers','addon','flat',true,0,'GBP','audit-workpapers',jsonb_build_object('shared',true)),
  ('omniqora.audit-evidence','Audit Evidence','Evidence requests, provenance, completeness, source links, confirmations and chain of custody.','Audit, M&A & Transformation','omniqora','audit-evidence','addon','flat',true,0,'GBP','audit-evidence',jsonb_build_object('shared',true)),
  ('omniqora.audit-risk-controls','Risk & Controls Testing','Risk register, controls, walkthroughs, design/operating effectiveness and deficiencies.','Audit, M&A & Transformation','omniqora','audit-risk-controls','addon','flat',true,0,'GBP','audit-risk-controls',jsonb_build_object('shared',true)),
  ('omniqora.audit-sampling','Audit Sampling','Population definition, statistical/judgemental sampling, test results and projection.','Audit, M&A & Transformation','omniqora','audit-sampling','addon','flat',true,0,'GBP','audit-sampling',jsonb_build_object('shared',true)),
  ('omniqora.audit-reporting','Audit Reporting','Findings, management responses, recommendations, opinions and board/committee reporting.','Audit, M&A & Transformation','omniqora','audit-reporting','addon','flat',true,0,'GBP','audit-reporting',jsonb_build_object('shared',true)),
  ('omniqora.transaction-services','Transaction Services','Transaction workspaces, diligence, deal issues, evidence, decisions and value bridge.','Audit, M&A & Transformation','omniqora','transaction-services','addon','flat',true,0,'GBP','transaction-services',jsonb_build_object('shared',true)),
  ('omniqora.due-diligence','Due Diligence','Financial, operational, technology, commercial, compliance and data due diligence.','Audit, M&A & Transformation','omniqora','due-diligence','addon','flat',true,0,'GBP','due-diligence',jsonb_build_object('shared',true)),
  ('omniqora.qoe','Quality of Earnings','Revenue/EBITDA normalisation, recurring/non-recurring items, working capital and cash/debt analysis.','Audit, M&A & Transformation','omniqora','qoe','addon','flat',true,0,'GBP','qoe',jsonb_build_object('shared',true)),
  ('omniqora.ma','M&A','Buyer/seller/target/NewCo transaction planning, dependencies, synergies and governance.','Audit, M&A & Transformation','omniqora','ma','addon','flat',true,0,'GBP','ma',jsonb_build_object('shared',true)),
  ('omniqora.carveout','Carve-out','Assets, workforce, systems, services, contracts and costs split between retained/separated/shared states.','Audit, M&A & Transformation','omniqora','carveout','addon','flat',true,0,'GBP','carveout',jsonb_build_object('shared',true)),
  ('omniqora.carveout-financials','Carve-out Financials','Standalone P&L/BS/cash-flow, allocations, stranded costs and separation assumptions.','Audit, M&A & Transformation','omniqora','carveout-financials','addon','flat',true,0,'GBP','carveout-financials',jsonb_build_object('shared',true)),
  ('omniqora.tsa','TSA Management','Transition service agreements, owners, SLAs, costs, exit criteria, dependencies and milestones.','Audit, M&A & Transformation','omniqora','tsa','addon','flat',true,0,'GBP','tsa',jsonb_build_object('shared',true)),
  ('omniqora.day1-100','Day 1 & 100-Day Plan','Engagement Day 1 through completion, operational Day 1 and days 2–30/31–60/61–100.','Audit, M&A & Transformation','omniqora','day1-100','addon','flat',true,0,'GBP','day1-100',jsonb_build_object('shared',true)),
  ('omniqora.stranded-costs','Stranded & Shared Costs','Identify, allocate, challenge and remediate retained/shared/stranded costs.','Audit, M&A & Transformation','omniqora','stranded-costs','addon','flat',true,0,'GBP','stranded-costs',jsonb_build_object('shared',true)),
  ('omniqora.separation-planning','Separation Planning','ERP, identity, workplace, cloud, security, software/API, data/BI and vendor separation workstreams.','Audit, M&A & Transformation','omniqora','separation-planning','addon','flat',true,0,'GBP','separation-planning',jsonb_build_object('shared',true)),
  ('omniqora.consolidation','Consolidation & Close','Group consolidation, close, eliminations, reconciliations and reporting controls.','Audit, M&A & Transformation','omniqora','consolidation','addon','flat',true,0,'GBP','consolidation',jsonb_build_object('shared',true)),
  ('omniqora.finance-scenarios','Finance Scenarios','NPV, ROI, payback, cash-flow, sensitivity, savings and transaction scenarios.','Audit, M&A & Transformation','omniqora','finance-scenarios','addon','flat',true,0,'GBP','finance-scenarios',jsonb_build_object('shared',true)),
  ('omniqora.process-mining','Process Mining','Process discovery, bottlenecks, leakage, cycle time and conformance analysis.','Audit, M&A & Transformation','omniqora','process-mining','addon','flat',true,0,'GBP','process-mining',jsonb_build_object('shared',true)),
  ('omniqora.benefits','Benefits Realisation','Benefits ledger, owners, baselines, evidence, verification and realised value.','Audit, M&A & Transformation','omniqora','benefits','addon','flat',true,0,'GBP','benefits',jsonb_build_object('shared',true)),
  ('omniqora.dependency-map','Dependency Mapping','People, systems, vendors, contracts, data, processes and operational dependency graph.','Audit, M&A & Transformation','omniqora','dependency-map','addon','flat',true,0,'GBP','dependency-map',jsonb_build_object('shared',true)),
  ('omniqora.practice-ops','Practice Operations','Clients, engagements, deadlines, requests, e-sign, WIP, fees, tasks, approvals and submissions.','Accounting, Tax & Practice','omniqora','practice-ops','addon','flat',true,0,'GBP','practice-ops',jsonb_build_object('shared',true)),
  ('omniqora.document-intake','Accounting Document Intake','App/scanner/PDF/CSV intake for receipts, invoices, statements and schedules.','Accounting, Tax & Practice','omniqora','document-intake','addon','flat',true,0,'GBP','document-intake',jsonb_build_object('shared',true)),
  ('omniqora.bookkeeping-ai','AI Bookkeeping','Extract/classify transactions, expenses vs capex, confidence and uncertainty queue.','Accounting, Tax & Practice','omniqora','bookkeeping-ai','addon','flat',true,0,'GBP','bookkeeping-ai',jsonb_build_object('shared',true)),
  ('omniqora.ledger','Ledger & Trial Balance','Journals, ledgers, reconciliations, trial balance and period-close controls.','Accounting, Tax & Practice','omniqora','ledger','addon','flat',true,0,'GBP','ledger',jsonb_build_object('shared',true)),
  ('omniqora.asset-register','Fixed Assets','Asset register, depreciation, disposals, capex controls and roll-forwards.','Accounting, Tax & Practice','omniqora','asset-register','addon','flat',true,0,'GBP','asset-register',jsonb_build_object('shared',true)),
  ('omniqora.accounts-production','Accounts Production','Prior-year roll-forward, lead schedules, disclosures, accounts preparation and review.','Accounting, Tax & Practice','omniqora','accounts-production','addon','flat',true,0,'GBP','accounts-production',jsonb_build_object('shared',true)),
  ('omniqora.tax-intelligence','Tax Intelligence','Rules, legislation, guidance, history and case-law research with evidence-backed tax analysis.','Accounting, Tax & Practice','omniqora','tax-intelligence','addon','flat',true,0,'GBP','tax-intelligence',jsonb_build_object('shared',true)),
  ('omniqora.tax-uk','UK Tax Pack','UK tax computations, workflows and filing adapter entitlements.','Accounting, Tax & Practice','omniqora','tax-uk','addon','flat',true,0,'GBP','tax-uk',jsonb_build_object('shared',true)),
  ('omniqora.tax-us','US Tax Pack','US federal/state tax workflows and filing adapter entitlements.','Accounting, Tax & Practice','omniqora','tax-us','addon','flat',true,0,'GBP','tax-us',jsonb_build_object('shared',true)),
  ('omniqora.tax-de','Germany Tax Pack','German tax workflows and filing adapter entitlements.','Accounting, Tax & Practice','omniqora','tax-de','addon','flat',true,0,'GBP','tax-de',jsonb_build_object('shared',true)),
  ('omniqora.rd-tax','R&D Tax & Rebates','R&D incentives, rebates, evidence packs, eligibility and claim workpapers.','Accounting, Tax & Practice','omniqora','rd-tax','addon','flat',true,0,'GBP','rd-tax',jsonb_build_object('shared',true)),
  ('omniqora.payroll','Payroll','Payroll runs, employees, calculations, approvals, filings, journals and payslips.','Accounting, Tax & Practice','omniqora','payroll','addon','flat',true,0,'GBP','payroll',jsonb_build_object('shared',true)),
  ('omniqora.company-secretarial','Company Secretarial','Company formation, PSC/director verification, filings, changes, registers and reminders.','Accounting, Tax & Practice','omniqora','company-secretarial','addon','flat',true,0,'GBP','company-secretarial',jsonb_build_object('shared',true)),
  ('omniqora.client-portal','Practice Client Portal','Client documents, requests, approvals, messages, e-sign and service access.','Accounting, Tax & Practice','omniqora','client-portal','addon','flat',true,0,'GBP','client-portal',jsonb_build_object('shared',true)),
  ('omniqora.wip-billing','Practice WIP & Billing','Time/WIP, fees, quotes, recurring billing and profitability.','Accounting, Tax & Practice','omniqora','wip-billing','addon','flat',true,0,'GBP','wip-billing',jsonb_build_object('shared',true)),
  ('omniqora.compliance-intelligence','Compliance Intelligence','Controls/evidence, policy packs, reviews, approvals and regulatory intelligence.','Compliance','omniqora','compliance-intelligence','addon','flat',true,0,'GBP','compliance-intelligence',jsonb_build_object('shared',true)),
  ('omniqora.rrci','Regulatory, Risk & Compliance Intelligence','Regulatory knowledge, evidence, risk, controls and governed intelligence workflows.','Compliance','omniqora','rrci','addon','flat',true,0,'GBP','rrci',jsonb_build_object('shared',true)),
  ('omniqora.policy-packs','Compliance Policy Packs','Reusable FCA, CQC, Ofsted, ISO, Aramco, NCA, SAMA and other jurisdiction/sector packs.','Compliance','omniqora','policy-packs','addon','flat',true,0,'GBP','policy-packs',jsonb_build_object('shared',true)),
  ('omniqora.monitoring','Continuous Compliance Monitoring','Scheduled controls/evidence checks, expiry monitoring, exceptions and remediation.','Compliance','omniqora','monitoring','addon','flat',true,0,'GBP','monitoring',jsonb_build_object('shared',true)),
  ('omniqora.remediation','Compliance Remediation','Findings, corrective actions, owners, deadlines, evidence and closure assurance.','Compliance','omniqora','remediation','addon','flat',true,0,'GBP','remediation',jsonb_build_object('shared',true)),
  ('omniqora.intelligent-ai-suite','Intelligent AI Suite','AI, GenAI, Agentic AI, RAG, GraphRAG, document intelligence and AI governance in one governed bundle.','Bundles','omniqora','intelligent-ai-suite','bundle','flat',true,0,'GBP','intelligent-ai-suite',jsonb_build_object('shared',true)),
  ('omniqora.data-bi-suite','Enterprise Data & BI Suite','Warehouse, lineage, Microsoft Fabric/Power BI and enterprise data connectors.','Bundles','omniqora','data-bi-suite','bundle','flat',true,0,'GBP','data-bi-suite',jsonb_build_object('shared',true)),
  ('omniqora.omnichannel-growth-suite','Omnichannel Growth Suite','CRM, Customer 360, Connect, WhatsApp, journeys, sales, RFM, feedback and analytics.','Bundles','omniqora','omnichannel-growth-suite','bundle','flat',true,0,'GBP','omnichannel-growth-suite',jsonb_build_object('shared',true)),
  ('omniqora.dispatch-field-suite','Dispatch & Field Ops Suite','Geo, dispatch, fleet, agent application and customer tracking.','Bundles','omniqora','dispatch-field-suite','bundle','flat',true,0,'GBP','dispatch-field-suite',jsonb_build_object('shared',true)),
  ('omniqora.marketplace-suite','Marketplace Suite','Marketplace Core, CRM, payments, communications, analytics and feedback.','Bundles','omniqora','marketplace-suite','bundle','flat',true,0,'GBP','marketplace-suite',jsonb_build_object('shared',true)),
  ('omniqora.full-audit-suite','Full Audit Suite','Complete external/internal/enterprise audit stack with evidence, workpapers, controls, sampling, reporting and AI.','Bundles','omniqora','full-audit-suite','bundle','flat',true,0,'GBP','full-audit-suite',jsonb_build_object('shared',true)),
  ('omniqora.ma-carveout-suite','M&A & Carve-out Suite','Due diligence, QoE, carve-out, TSA, separation, stranded costs, Day 1/100 and value realisation.','Bundles','omniqora','ma-carveout-suite','bundle','flat',true,0,'GBP','ma-carveout-suite',jsonb_build_object('shared',true)),
  ('omniqora.accounting-tax-suite','Accounting & Tax Automation Suite','Document intake through bookkeeping, ledger, assets, accounts, tax, payroll and practice portal.','Bundles','omniqora','accounting-tax-suite','bundle','flat',true,0,'GBP','accounting-tax-suite',jsonb_build_object('shared',true)),
  ('omniqora.compliance-as-a-service','Compliance as a Service','Managed compliance stack with policy packs, monitoring, evidence, audit, remediation, AI/RAG and reporting.','Bundles','omniqora','compliance-as-a-service','bundle','flat',true,0,'GBP','compliance-as-a-service',jsonb_build_object('shared',true))
ON CONFLICT(service_key) DO UPDATE SET
  name=excluded.name,description=excluded.description,category=excluded.category,
  provider_key=excluded.provider_key,runtime_key=excluded.runtime_key,service_kind=excluded.service_kind,
  billing_basis=excluded.billing_basis,recurring=excluded.recurring,
  provisioning_key=excluded.provisioning_key,
  metadata=public.omniqora_service_catalogue.metadata||excluded.metadata,
  active=true,updated_at=now();

INSERT INTO public.omniqora_service_dependencies(service_key,depends_on_service_key,required)
VALUES
  ('omniqora.entitlements','omniqora.tenant',true),
  ('omniqora.audit-security','omniqora.identity',true),
  ('omniqora.data-events','omniqora.tenant',true),
  ('omniqora.api-gateway','omniqora.identity',true),
  ('omniqora.documents','omniqora.identity',true),
  ('omniqora.automation','omniqora.data-events',true),
  ('omniqora.ai','omniqora.identity',true),
  ('omniqora.genai','omniqora.ai',true),
  ('omniqora.agentic-ai','omniqora.ai',true),
  ('omniqora.agentic-ai','omniqora.automation',true),
  ('omniqora.agentic-ai','omniqora.audit-security',true),
  ('omniqora.ai-governance','omniqora.audit-security',true),
  ('omniqora.knowledge-rag','omniqora.documents',true),
  ('omniqora.knowledge-rag','omniqora.ai',true),
  ('omniqora.graphrag','omniqora.knowledge-rag',true),
  ('omniqora.graphrag','omniqora.neo4j',true),
  ('omniqora.microsoft-rag','omniqora.azure-ai-search',true),
  ('omniqora.microsoft-rag','omniqora.microsoft-graph',true),
  ('omniqora.microsoft-rag','omniqora.sharepoint',true),
  ('omniqora.microsoft-rag','omniqora.azure-openai',true),
  ('omniqora.analytics','omniqora.data-events',true),
  ('omniqora.powerbi','omniqora.analytics',true),
  ('omniqora.data-lineage','omniqora.data-events',true),
  ('omniqora.customer360','omniqora.identity',true),
  ('omniqora.crm','omniqora.customer360',true),
  ('omniqora.sales','omniqora.crm',true),
  ('omniqora.sales','omniqora.connect',true),
  ('omniqora.journeys','omniqora.crm',true),
  ('omniqora.journeys','omniqora.connect',true),
  ('omniqora.rfm','omniqora.customer360',true),
  ('omniqora.rfm','omniqora.analytics',true),
  ('omniqora.feedback','omniqora.crm',true),
  ('omniqora.feedback','omniqora.connect',true),
  ('zoryn.rewards','omniqora.customer360',true),
  ('omniqora.connect','omniqora.identity',true),
  ('omniqora.notifications','omniqora.connect',true),
  ('omniqora.whatsapp','omniqora.connect',true),
  ('omniqora.sms','omniqora.connect',true),
  ('omniqora.email','omniqora.connect',true),
  ('omniqora.voice','omniqora.connect',true),
  ('omniqora.push','omniqora.notifications',true),
  ('omniqora.geo','omniqora.identity',true),
  ('omniqora.dispatch','omniqora.geo',true),
  ('omniqora.fleet','omniqora.dispatch',true),
  ('omniqora.agent','omniqora.dispatch',true),
  ('omniqora.tracking','omniqora.geo',true),
  ('omniqora.marketplace-core','omniqora.identity',true),
  ('omniqora.marketplace-core','omniqora.payments',true),
  ('omniqora.payments','omniqora.identity',true),
  ('omniqora.billing','omniqora.entitlements',true),
  ('omniqora.enterprise-audit','omniqora.audit-security',true),
  ('omniqora.internal-audit','omniqora.audit-security',true),
  ('omniqora.external-audit','omniqora.audit-security',true),
  ('omniqora.audit-workpapers','omniqora.documents',true),
  ('omniqora.audit-evidence','omniqora.documents',true),
  ('omniqora.audit-risk-controls','omniqora.audit-security',true),
  ('omniqora.audit-sampling','omniqora.audit-workpapers',true),
  ('omniqora.audit-reporting','omniqora.audit-workpapers',true),
  ('omniqora.transaction-services','omniqora.business360',true),
  ('omniqora.due-diligence','omniqora.transaction-services',true),
  ('omniqora.qoe','omniqora.due-diligence',true),
  ('omniqora.ma','omniqora.transaction-services',true),
  ('omniqora.carveout','omniqora.ma',true),
  ('omniqora.carveout-financials','omniqora.carveout',true),
  ('omniqora.tsa','omniqora.carveout',true),
  ('omniqora.day1-100','omniqora.ma',true),
  ('omniqora.stranded-costs','omniqora.carveout',true),
  ('omniqora.separation-planning','omniqora.carveout',true),
  ('omniqora.dependency-map','omniqora.graphrag',true),
  ('omniqora.process-mining','omniqora.analytics',true),
  ('omniqora.benefits','omniqora.business360',true),
  ('omniqora.practice-ops','omniqora.crm',true),
  ('omniqora.document-intake','omniqora.documents',true),
  ('omniqora.bookkeeping-ai','omniqora.document-intake',true),
  ('omniqora.bookkeeping-ai','omniqora.document-ai',true),
  ('omniqora.ledger','omniqora.bookkeeping-ai',true),
  ('omniqora.asset-register','omniqora.ledger',true),
  ('omniqora.accounts-production','omniqora.ledger',true),
  ('omniqora.tax-intelligence','omniqora.knowledge-rag',true),
  ('omniqora.payroll','omniqora.ledger',true),
  ('omniqora.company-secretarial','omniqora.documents',true),
  ('omniqora.client-portal','omniqora.identity',true),
  ('omniqora.wip-billing','omniqora.practice-ops',true),
  ('omniqora.compliance-intelligence','omniqora.knowledge-rag',true),
  ('omniqora.rrci','omniqora.compliance-intelligence',true),
  ('omniqora.policy-packs','omniqora.compliance-intelligence',true),
  ('omniqora.monitoring','omniqora.compliance-intelligence',true),
  ('omniqora.monitoring','omniqora.automation',true),
  ('omniqora.remediation','omniqora.monitoring',true),
  ('omniqora.intelligent-ai-suite','omniqora.ai',true),
  ('omniqora.intelligent-ai-suite','omniqora.genai',true),
  ('omniqora.intelligent-ai-suite','omniqora.agentic-ai',true),
  ('omniqora.intelligent-ai-suite','omniqora.ai-governance',true),
  ('omniqora.intelligent-ai-suite','omniqora.knowledge-rag',true),
  ('omniqora.intelligent-ai-suite','omniqora.graphrag',true),
  ('omniqora.intelligent-ai-suite','omniqora.document-ai',true),
  ('omniqora.data-bi-suite','omniqora.warehouse',true),
  ('omniqora.data-bi-suite','omniqora.data-lineage',true),
  ('omniqora.data-bi-suite','omniqora.powerbi',true),
  ('omniqora.data-bi-suite','omniqora.microsoft-fabric',true),
  ('omniqora.omnichannel-growth-suite','omniqora.crm',true),
  ('omniqora.omnichannel-growth-suite','omniqora.customer360',true),
  ('omniqora.omnichannel-growth-suite','omniqora.connect',true),
  ('omniqora.omnichannel-growth-suite','omniqora.whatsapp',true),
  ('omniqora.omnichannel-growth-suite','omniqora.journeys',true),
  ('omniqora.omnichannel-growth-suite','omniqora.sales',true),
  ('omniqora.omnichannel-growth-suite','omniqora.rfm',true),
  ('omniqora.omnichannel-growth-suite','omniqora.feedback',true),
  ('omniqora.omnichannel-growth-suite','omniqora.analytics',true),
  ('omniqora.dispatch-field-suite','omniqora.geo',true),
  ('omniqora.dispatch-field-suite','omniqora.dispatch',true),
  ('omniqora.dispatch-field-suite','omniqora.fleet',true),
  ('omniqora.dispatch-field-suite','omniqora.agent',true),
  ('omniqora.dispatch-field-suite','omniqora.tracking',true),
  ('omniqora.marketplace-suite','omniqora.marketplace-core',true),
  ('omniqora.marketplace-suite','omniqora.crm',true),
  ('omniqora.marketplace-suite','omniqora.payments',true),
  ('omniqora.marketplace-suite','omniqora.connect',true),
  ('omniqora.marketplace-suite','omniqora.analytics',true),
  ('omniqora.marketplace-suite','omniqora.feedback',true),
  ('omniqora.full-audit-suite','omniqora.enterprise-audit',true),
  ('omniqora.full-audit-suite','omniqora.internal-audit',true),
  ('omniqora.full-audit-suite','omniqora.external-audit',true),
  ('omniqora.full-audit-suite','omniqora.audit-workpapers',true),
  ('omniqora.full-audit-suite','omniqora.audit-evidence',true),
  ('omniqora.full-audit-suite','omniqora.audit-risk-controls',true),
  ('omniqora.full-audit-suite','omniqora.audit-sampling',true),
  ('omniqora.full-audit-suite','omniqora.audit-reporting',true),
  ('omniqora.full-audit-suite','omniqora.intelligent-ai-suite',true),
  ('omniqora.full-audit-suite','omniqora.powerbi',true),
  ('omniqora.ma-carveout-suite','omniqora.due-diligence',true),
  ('omniqora.ma-carveout-suite','omniqora.qoe',true),
  ('omniqora.ma-carveout-suite','omniqora.ma',true),
  ('omniqora.ma-carveout-suite','omniqora.carveout',true),
  ('omniqora.ma-carveout-suite','omniqora.carveout-financials',true),
  ('omniqora.ma-carveout-suite','omniqora.tsa',true),
  ('omniqora.ma-carveout-suite','omniqora.day1-100',true),
  ('omniqora.ma-carveout-suite','omniqora.stranded-costs',true),
  ('omniqora.ma-carveout-suite','omniqora.separation-planning',true),
  ('omniqora.ma-carveout-suite','omniqora.dependency-map',true),
  ('omniqora.ma-carveout-suite','omniqora.finance-scenarios',true),
  ('omniqora.ma-carveout-suite','omniqora.benefits',true),
  ('omniqora.ma-carveout-suite','omniqora.intelligent-ai-suite',true),
  ('omniqora.ma-carveout-suite','omniqora.data-bi-suite',true),
  ('omniqora.accounting-tax-suite','omniqora.practice-ops',true),
  ('omniqora.accounting-tax-suite','omniqora.document-intake',true),
  ('omniqora.accounting-tax-suite','omniqora.bookkeeping-ai',true),
  ('omniqora.accounting-tax-suite','omniqora.ledger',true),
  ('omniqora.accounting-tax-suite','omniqora.asset-register',true),
  ('omniqora.accounting-tax-suite','omniqora.accounts-production',true),
  ('omniqora.accounting-tax-suite','omniqora.tax-intelligence',true),
  ('omniqora.accounting-tax-suite','omniqora.payroll',true),
  ('omniqora.accounting-tax-suite','omniqora.client-portal',true),
  ('omniqora.accounting-tax-suite','omniqora.wip-billing',true),
  ('omniqora.accounting-tax-suite','omniqora.intelligent-ai-suite',true),
  ('omniqora.compliance-as-a-service','omniqora.compliance-intelligence',true),
  ('omniqora.compliance-as-a-service','omniqora.rrci',true),
  ('omniqora.compliance-as-a-service','omniqora.policy-packs',true),
  ('omniqora.compliance-as-a-service','omniqora.monitoring',true),
  ('omniqora.compliance-as-a-service','omniqora.remediation',true),
  ('omniqora.compliance-as-a-service','omniqora.audit-evidence',true),
  ('omniqora.compliance-as-a-service','omniqora.audit-workpapers',true),
  ('omniqora.compliance-as-a-service','omniqora.audit-risk-controls',true),
  ('omniqora.compliance-as-a-service','omniqora.audit-reporting',true),
  ('omniqora.compliance-as-a-service','omniqora.intelligent-ai-suite',true),
  ('omniqora.compliance-as-a-service','omniqora.powerbi',true)
ON CONFLICT(service_key,depends_on_service_key) DO UPDATE SET required=excluded.required;

INSERT INTO public.omniqora_product_default_services(product_key,service_key,required)
VALUES
  ('omniqora','omniqora.identity',true),
  ('omniqora','omniqora.tenant',true),
  ('omniqora','omniqora.entitlements',true),
  ('omniqora','omniqora.audit-security',true),
  ('omniqora','omniqora.data-events',true),
  ('omniqora','omniqora.api-gateway',true),
  ('omniqora','omniqora.connect',true),
  ('dishbee','omniqora.identity',true),
  ('dishbee','omniqora.customer360',true),
  ('dishbee','omniqora.crm',true),
  ('dishbee','omniqora.connect',true),
  ('dishbee','omniqora.notifications',true),
  ('dishbee','omniqora.payments',true),
  ('dishbee','omniqora.analytics',true),
  ('mealdeck','omniqora.identity',true),
  ('mealdeck','omniqora.customer360',true),
  ('mealdeck','omniqora.crm',true),
  ('mealdeck','omniqora.whatsapp',true),
  ('mealdeck','omniqora.payments',true),
  ('mealdeck','omniqora.dispatch',true),
  ('mealdeck','omniqora.geo',true),
  ('mealdeck','omniqora.analytics',true),
  ('mealdeck','zoryn.rewards',true),
  ('kindelo','omniqora.identity',true),
  ('kindelo','omniqora.crm',true),
  ('kindelo','omniqora.customer360',true),
  ('kindelo','omniqora.connect',true),
  ('kindelo','omniqora.notifications',true),
  ('kindelo','omniqora.payments',true),
  ('kindelo','omniqora.compliance-as-a-service',true),
  ('kinderstars','omniqora.identity',true),
  ('kinderstars','omniqora.crm',true),
  ('kinderstars','omniqora.customer360',true),
  ('kinderstars','omniqora.connect',true),
  ('kinderstars','omniqora.notifications',true),
  ('kinderstars','omniqora.payments',true),
  ('kinderstars','omniqora.compliance-as-a-service',true),
  ('formationgenie','omniqora.identity',true),
  ('formationgenie','omniqora.crm',true),
  ('formationgenie','omniqora.documents',true),
  ('formationgenie','omniqora.document-ai',true),
  ('formationgenie','omniqora.connect',true),
  ('formationgenie','omniqora.company-secretarial',true),
  ('formationgenie','omniqora.compliance-as-a-service',true),
  ('taxnuvia','omniqora.identity',true),
  ('taxnuvia','omniqora.crm',true),
  ('taxnuvia','omniqora.customer360',true),
  ('taxnuvia','omniqora.accounting-tax-suite',true),
  ('taxnuvia','omniqora.compliance-as-a-service',true),
  ('taxcenda','omniqora.identity',true),
  ('taxcenda','omniqora.crm',true),
  ('taxcenda','omniqora.accounting-tax-suite',true),
  ('taxcenda','omniqora.compliance-as-a-service',true),
  ('omniqora-accounts','omniqora.identity',true),
  ('omniqora-accounts','omniqora.crm',true),
  ('omniqora-accounts','omniqora.accounting-tax-suite',true),
  ('omniqora-accounts','omniqora.full-audit-suite',true),
  ('omniqora-accounts','omniqora.compliance-as-a-service',true),
  ('lawquo','omniqora.identity',true),
  ('lawquo','omniqora.crm',true),
  ('lawquo','omniqora.documents',true),
  ('lawquo','omniqora.knowledge-rag',true),
  ('lawquo','omniqora.connect',true),
  ('lawquo','omniqora.compliance-as-a-service',true),
  ('sparesgrid','omniqora.identity',true),
  ('sparesgrid','omniqora.crm',true),
  ('sparesgrid','omniqora.marketplace-suite',true),
  ('sparesgrid','omniqora.connect',true),
  ('courier-connect','omniqora.identity',true),
  ('courier-connect','omniqora.crm',true),
  ('courier-connect','omniqora.dispatch-field-suite',true),
  ('courier-connect','omniqora.connect',true),
  ('courier-connect','omniqora.analytics',true),
  ('courier-broker','omniqora.identity',true),
  ('courier-broker','omniqora.crm',true),
  ('courier-broker','omniqora.dispatch-field-suite',true),
  ('courier-broker','omniqora.connect',true),
  ('courier-broker','omniqora.analytics',true),
  ('all-road-aid','omniqora.identity',true),
  ('all-road-aid','omniqora.crm',true),
  ('all-road-aid','omniqora.dispatch-field-suite',true),
  ('all-road-aid','omniqora.marketplace-core',true),
  ('all-road-aid','omniqora.connect',true),
  ('recovra','omniqora.identity',true),
  ('recovra','omniqora.crm',true),
  ('recovra','omniqora.dispatch-field-suite',true),
  ('recovra','omniqora.marketplace-core',true),
  ('recovra','omniqora.connect',true),
  ('haccora','omniqora.identity',true),
  ('haccora','omniqora.crm',true),
  ('haccora','omniqora.compliance-as-a-service',true),
  ('haccora','omniqora.analytics',true),
  ('fastremit','omniqora.identity',true),
  ('fastremit','omniqora.customer360',true),
  ('fastremit','omniqora.crm',true),
  ('fastremit','omniqora.connect',true),
  ('fastremit','omniqora.payments',true),
  ('fastremit','omniqora.compliance-as-a-service',true),
  ('fastremit','omniqora.analytics',true),
  ('business360','omniqora.identity',true),
  ('business360','omniqora.business360',true),
  ('business360','omniqora.intelligent-ai-suite',true),
  ('business360','omniqora.data-bi-suite',true),
  ('voxentri','omniqora.identity',true),
  ('voxentri','omniqora.crm',true),
  ('voxentri','omniqora.sales',true),
  ('voxentri','omniqora.intelligent-ai-suite',true),
  ('voxentri','omniqora.analytics',true),
  ('autohashi','omniqora.identity',true),
  ('autohashi','omniqora.crm',true),
  ('autohashi','omniqora.marketplace-suite',true),
  ('autohashi','omniqora.analytics',true),
  ('zivvo','omniqora.identity',true),
  ('zivvo','omniqora.crm',true),
  ('zivvo','omniqora.marketplace-suite',true),
  ('zivvo','omniqora.analytics',true),
  ('ahlnikkah','omniqora.identity',true),
  ('ahlnikkah','omniqora.crm',true),
  ('ahlnikkah','omniqora.marketplace-core',true),
  ('ahlnikkah','omniqora.notifications',true),
  ('ahlnikkah','omniqora.payments',true)
ON CONFLICT(product_key,service_key) DO UPDATE SET required=excluded.required;

INSERT INTO public.omniqora_blueprints(
  blueprint_key,name,description,category,country_code,sort_order,defaults
) VALUES
  ('restaurant-hospitality','Restaurant / Café','Hospitality operating tenant with CRM, communications, payments and analytics.','hospitality','GB',10,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('mealdeck-cloud-kitchen','MealDeck Cloud Kitchen','Multi-brand cloud-kitchen / ordering tenant with dispatch and rewards.','hospitality','GB',20,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('kindelo-uk','Kindelo UK Agency','UK childminder agency tenant with communications, payments and managed compliance.','childcare','GB',30,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('kindelo-de','Kindelo Germany','German Kindelo tenant using the same runtime with German localisation.','childcare','DE',40,jsonb_build_object('currency','EUR','timezone','Europe/Berlin')),
  ('accountancy-practice-uk','UK Accountancy & Audit Practice','Practice tenant with AI bookkeeping, accounts, tax, payroll, audit and compliance.','accounting','GB',50,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('accountancy-practice-us','US Accounting & Tax Practice','Practice tenant with US tax pack, intelligent automation and compliance.','accounting','US',60,jsonb_build_object('currency','USD','timezone','America/New_York')),
  ('company-formation-uk','UK Company Formation & Secretarial','FormationGenie with CRM, document AI, Companies House/company-secretarial and compliance.','business-services','GB',70,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('courier-operator','Courier / Field Operations','Courier Connect with Geo, Dispatch, Fleet, Agent and tracking.','logistics','GB',80,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('marketplace','Generic Marketplace','Marketplace Core with CRM, payments, communications, feedback and analytics.','marketplace',null,90,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('compliance-as-a-service','Compliance as a Service','Managed CaaS for internal/external customers with policy packs, monitoring, evidence, audit, remediation, AI/RAG and BI.','compliance',null,100,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('full-audit','Full Company / Financial Audit','Complete enterprise, internal and external audit workspace with evidence, controls, sampling, AI and BI.','audit',null,110,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('ma-carveout','M&A / Carve-out / Separation','Buyer/seller/target/NewCo diligence, QoE, carve-out financials, TSAs, Day 1/100 and separation.','transactions',null,120,jsonb_build_object('currency','GBP','timezone','Europe/London')),
  ('intelligent-ai','Intelligent AI Platform','GenAI, agentic AI, RAG, GraphRAG, Neo4j and governed AI tooling.','ai',null,130,jsonb_build_object('currency','GBP','timezone','Europe/London'))
ON CONFLICT(blueprint_key) DO UPDATE SET
  name=excluded.name,description=excluded.description,category=excluded.category,
  country_code=excluded.country_code,sort_order=excluded.sort_order,
  defaults=excluded.defaults,active=true,updated_at=now();

INSERT INTO public.omniqora_blueprint_products(blueprint_key,product_key,required)
VALUES
  ('restaurant-hospitality','dishbee',true),
  ('mealdeck-cloud-kitchen','dishbee',true),
  ('mealdeck-cloud-kitchen','mealdeck',true),
  ('kindelo-uk','kindelo',true),
  ('kindelo-de','kindelo',true),
  ('accountancy-practice-uk','omniqora-accounts',true),
  ('accountancy-practice-us','omniqora-accounts',true),
  ('company-formation-uk','formationgenie',true),
  ('courier-operator','courier-connect',true),
  ('marketplace','omniqora',true),
  ('compliance-as-a-service','omniqora',true),
  ('full-audit','omniqora',true),
  ('ma-carveout','business360',true),
  ('intelligent-ai','omniqora',true)
ON CONFLICT(blueprint_key,product_key) DO UPDATE SET required=excluded.required;

INSERT INTO public.omniqora_blueprint_services(blueprint_key,service_key,required)
VALUES
  ('restaurant-hospitality','omniqora.omnichannel-growth-suite',true),
  ('mealdeck-cloud-kitchen','omniqora.omnichannel-growth-suite',true),
  ('mealdeck-cloud-kitchen','omniqora.dispatch-field-suite',true),
  ('kindelo-uk','omniqora.compliance-as-a-service',true),
  ('kindelo-de','omniqora.compliance-as-a-service',true),
  ('accountancy-practice-uk','omniqora.accounting-tax-suite',true),
  ('accountancy-practice-uk','omniqora.full-audit-suite',true),
  ('accountancy-practice-uk','omniqora.compliance-as-a-service',true),
  ('accountancy-practice-us','omniqora.accounting-tax-suite',true),
  ('accountancy-practice-us','omniqora.tax-us',true),
  ('accountancy-practice-us','omniqora.compliance-as-a-service',true),
  ('company-formation-uk','omniqora.company-secretarial',true),
  ('company-formation-uk','omniqora.compliance-as-a-service',true),
  ('courier-operator','omniqora.dispatch-field-suite',true),
  ('marketplace','omniqora.marketplace-suite',true),
  ('compliance-as-a-service','omniqora.compliance-as-a-service',true),
  ('full-audit','omniqora.full-audit-suite',true),
  ('ma-carveout','omniqora.ma-carveout-suite',true),
  ('intelligent-ai','omniqora.intelligent-ai-suite',true),
  ('intelligent-ai','omniqora.data-bi-suite',true)
ON CONFLICT(blueprint_key,service_key) DO UPDATE SET required=excluded.required;

-- Existing Omniqora workspaces become Omniqora product tenants without creating a second tenant record.
INSERT INTO public.omniqora_tenant_products(tenant_id,product_key,status,activated_at)
SELECT t.id,'omniqora','active',t.created_at
FROM public.tenants t
ON CONFLICT(tenant_id,product_key) DO NOTHING;

-- Existing RRCI entitlements are reflected in the new universal service model.
INSERT INTO public.omniqora_tenant_services(
  tenant_id,service_key,status,quantity,unit_amount_pence,config,activated_at,cancelled_at
)
SELECT e.tenant_id,'omniqora.rrci',
  CASE e.status WHEN 'cancelled' THEN 'cancelled' WHEN 'suspended' THEN 'suspended' ELSE 'active' END,
  1,0,jsonb_build_object('legacyBillingReference',e.billing_reference,'validUntil',e.valid_until),
  CASE WHEN e.status IN ('trial','active') THEN e.updated_at ELSE null END,
  CASE WHEN e.status='cancelled' THEN e.updated_at ELSE null END
FROM public.addon_entitlements e
WHERE e.addon='rrci'
ON CONFLICT(tenant_id,service_key) DO UPDATE SET
  status=excluded.status,config=public.omniqora_tenant_services.config||excluded.config,
  updated_at=now();

COMMIT;
