import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { requireModuleEntitlement, requireWritableTenantRole } from "@/modules/platform/module-access";

const scope=z.object({tenantId:z.string().uuid(),tenantProductId:z.string().uuid(),productKey:z.string().min(1).max(80)});

export const getAnalyticsMetrics=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>&{metricKeys?:string[]})=>scope.extend({metricKeys:z.array(z.string().max(160)).max(100).optional()}).parse(input)).handler(async({context,data})=>{await requireModuleEntitlement(context,{tenantId:data.tenantId,tenantProductId:data.tenantProductId,moduleKey:"analytics.core"});const db=context.supabase as any;let q=db.from("analytics_metric_points").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("period_start",{ascending:false}).limit(5000);if(data.metricKeys?.length)q=q.in("metric_key",data.metricKeys);const{data:rows,error}=await q;if(error)throw new Error(error.message);return rows??[];});

export const getFinancialWorkspace=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof scope>)=>scope.parse(input)).handler(async({context,data})=>{await requireModuleEntitlement(context,{tenantId:data.tenantId,tenantProductId:data.tenantProductId,moduleKey:"financials.core"});const db=context.supabase as any;const[actuals,budgets,forecasts,benefits]=await Promise.all([db.from("financial_actuals").select("*").eq("tenant_id",data.tenantId).eq("product_key",data.productKey).order("period_start",{ascending:false}).limit(2000),db.from("financial_budgets").select("*").eq("tenant_id",data.tenantId).order("period_start",{ascending:false}).limit(1000),db.from("financial_forecasts").select("*").eq("tenant_id",data.tenantId).order("period_start",{ascending:false}).limit(1000),db.from("financial_benefits").select("*").eq("tenant_id",data.tenantId).order("updated_at",{ascending:false}).limit(1000)]);for(const r of[actuals,budgets,forecasts,benefits])if(r.error)throw new Error(r.error.message);return{actuals:actuals.data??[],budgets:budgets.data??[],forecasts:forecasts.data??[],benefits:benefits.data??[]};});

const budgetSchema=scope.extend({id:z.string().uuid().optional(),locationId:z.string().uuid().optional().nullable(),periodStart:z.string().date(),periodEnd:z.string().date(),category:z.string().min(1).max(160),amountMinor:z.number().int(),currency:z.string().regex(/^[A-Z]{3}$/),ownerUserId:z.string().uuid().optional().nullable()});
export const saveFinancialBudget=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof budgetSchema>)=>budgetSchema.parse(input)).handler(async({context,data})=>{const access=await requireModuleEntitlement(context,{tenantId:data.tenantId,tenantProductId:data.tenantProductId,moduleKey:"financials.core"});requireWritableTenantRole(access.role);const db=context.supabase as any;const values={tenant_id:data.tenantId,product_key:data.productKey,location_id:data.locationId??null,period_start:data.periodStart,period_end:data.periodEnd,category:data.category,amount_minor:data.amountMinor,currency:data.currency,owner_user_id:data.ownerUserId??context.userId};const q=data.id?db.from("financial_budgets").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("financial_budgets").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Budget could not be saved");return row;});

const forecastSchema=scope.extend({id:z.string().uuid().optional(),locationId:z.string().uuid().optional().nullable(),periodStart:z.string().date(),periodEnd:z.string().date(),category:z.string().min(1).max(160),amountMinor:z.number().int(),currency:z.string().regex(/^[A-Z]{3}$/),basis:z.enum(["manual","run_rate","model","scenario"]),assumptions:z.array(z.string().max(1000)).max(100).default([]),modelRunId:z.string().max(200).optional().nullable()});
export const saveFinancialForecast=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:z.input<typeof forecastSchema>)=>forecastSchema.parse(input)).handler(async({context,data})=>{const access=await requireModuleEntitlement(context,{tenantId:data.tenantId,tenantProductId:data.tenantProductId,moduleKey:"financials.core"});requireWritableTenantRole(access.role);const db=context.supabase as any;const values={tenant_id:data.tenantId,product_key:data.productKey,location_id:data.locationId??null,period_start:data.periodStart,period_end:data.periodEnd,category:data.category,amount_minor:data.amountMinor,currency:data.currency,basis:data.basis,assumptions:data.assumptions,model_run_id:data.modelRunId??null};const q=data.id?db.from("financial_forecasts").update(values).eq("id",data.id).eq("tenant_id",data.tenantId):db.from("financial_forecasts").insert(values);const{data:row,error}=await q.select("*").single();if(error||!row)throw new Error(error?.message??"Forecast could not be saved");return row;});