"""Fictional company intake. Example assumptions are not business forecasts."""


def seed_planning(engine, actor, project):
    records = []
    def add(kind, **row):
        records.append({"kind": kind, "record": row, "expected_revision": 0})
    for cid, name, role in [("seller", "Northstar Seller (fictional)", "seller"), ("newco", "Northstar NewCo (fictional)", "newco")]:
        add("company", id=cid, name=name, company_role=role, sector="Business services", countries=["United Kingdom", "United Arab Emirates"], owner="Programme sponsor", evidence_ref="urn:fictional:perimeter")
    add("business_service", id="pay-employees", name="Pay employees accurately and on time", company_id="newco", owner="People operations", criticality="critical", day_one_required=True, acceptance_criteria="Parallel payroll reconciles and payment authority is independently verified", evidence_ref="urn:fictional:payroll")
    for aid, name, stream in [("asset-identity", "Identity tenant", "identity"), ("asset-erp", "ERP environment", "enterprise")]:
        add("asset", id=aid, name=name, company_id="seller", asset_type="technology", quantity=1, owner="Technology lead", criticality="critical", day_one_required=True, disposition="separate", target_company_id="newco", transferability="unknown", workstream_id=stream, system_id="identity" if stream == "identity" else "erp", evidence_ref="urn:fictional:architecture")
    add("asset_dependency", id="erp-needs-identity", source="asset-erp", target="asset-identity", reviewed=True, evidence_ref="urn:fictional:architecture")
    add("workforce", id="operations-team", name="Business operations team", company_id="seller", owner="People lead", headcount=10, fte="8.5", skills=["Payroll", "Service support", "Finance operations"], key_dependencies="Two team leads cover payroll approvals", target_company_id="newco", transition_approach="HR validates proposed coverage, required consultation and training before any employment decision", evidence_ref="urn:fictional:workforce")
    for cid, company, state, amount, frequency in [("current-run", "seller", "current", "25000", "monthly"), ("target-run", "newco", "target", "16000", "monthly"), ("separation-cost", "newco", "transition", "100000", "one_off"), ("tsa-cost", "newco", "transition", "18000", "monthly")]:
        add("cost_item", id=cid, name=cid.replace("-", " "), company_id=company, cost_key=cid, cost_state=state, cost_category="tsa" if cid == "tsa-cost" else "technology", amount=amount, currency="GBP", frequency=frequency, owner="Finance lead", basis="estimated", evidence_ref="urn:fictional:cost-assumptions", **({"duration_months": "3"} if cid == "tsa-cost" else {}))
    add("objective", id="application-rationalisation", name="Review application rationalisation opportunity", company_id="newco", owner="Technology lead", metric="Applications in agreed comparable scope", baseline="10", target="8", unit="applications", direction="decrease", moscow="should", target_date="2027-01-08", evidence_ref="urn:fictional:investment-thesis")
    add("delivery_mandate", id="embedded-delivery", name="Embedded technical delivery (fictional)", company_id="newco", owner="Delivery director", delivery_model="sub_contract", client="Northstar sponsor (fictional)", prime_adviser="Lead advisory firm (fictional)", delivery_partner="Technical delivery partner (fictional)", branding="co_branded", display_brand="Northstar Transformation", workstream_ids=["enterprise", "identity", "cloud", "security", "integration", "data"], decision_rights="Lead adviser owns SMO decisions; client approves spend and cutover; partner owns agreed technical delivery", reporting_cadence="Weekly workstream pack and daily cutover reporting", acceptance_criteria="Business owners accept evidence against agreed milestones", commercial_ref="urn:fictional:statement-of-work")
    add("tdd_finding", id="shared-identity", name="Seller identity dependency", company_id="seller", owner="Technology lead", severity="high", finding_status="open", business_impact="Day 1 access depends on seller support and licence rights", recommendation="Confirm TSA scope and consent; rehearse independent access before exit", cost_item_ids=["separation-cost", "tsa-cost"], evidence_ref="urn:fictional:diligence")
    add("tsa_obligation", id="identity-services", name="Seller identity services", company_id="newco", owner="Workplace lead", tsa_id="tsa-identity", provider_company_id="seller", recipient_company_id="newco", asset_ids=["asset-identity"], service_scope="Directory support and agreed authentication services", service_levels="Define support hours, availability measurement and incident response in the agreement", charging_basis="GBP 18,000 monthly, subject to negotiated terms", responsibilities="Seller operates shared service; buyer owns target identity and acceptance", exit_roadmap="Confirm rights, build target tenant, test users and recovery, reconcile permissions, approve exit", consent_status="negotiating", evidence_ref="urn:fictional:tsa-draft")
    add("decision", id="target-operating-model", name="Proposed standalone operating model", company_id="newco", owner="Programme sponsor", decision_date="2026-09-16", decision_status="proposed", rationale="Separate identity and finance while preserving service continuity", alternatives="Extend shared service or replace selected applications", evidence_ref="urn:fictional:options")
    add("planning_scope", id="northstar-plan", name="Northstar company separation plan", deal_type="carve_out", company_ids=["seller", "newco"], target_company_id="newco", owner="Programme director", start_date="2026-09-16", day_one_date="2026-10-01", horizon_days=100, constraints="Protect payroll and finance close. Review all company, workforce, contract and country-specific requirements.", requirements_ref="urn:fictional:scope-review", inventory_complete=False, workforce_complete=False, costs_complete=False, transition_budget="180000")
    for record in records:
        engine.upsert(actor, project, record)
    return records
